### ISSUE TITLE
Add authentication option to DoPost?

### ISSUE THREAD

**Issue by jregovic** [bosun-monitor/bosun#1002]
I'd like to post notifications to Zenoss, but to do so requires cookie based authentication.

Would this be better off as a separate notification, or extending the current post action?

**Comment by elementai** [comment]
As a quick workaround one can configure small reverse proxy like this, e.g. HAProxy : 
```
listen zenoss-proxy
  bind 127.0.0.1:8080
  reqadd Authorization:\ Basic\ Blahblah....blah===
  server name ip ..
```

**Comment by elementai** [comment]
For nginx
```
server {
  listen                127.0.0.1:8080;

  server_name           name.example.com;

  proxy_connect_timeout 2s;

  location / {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_pass https://_zenoss_balancer;
    proxy_set_header 'Authorization' 'Basic Blahblahblah';
  }
}

**Comment by kylebrandt** [comment]
Adding headers will be part of https://github.com/bosun-monitor/bosun/pull/2135 so will be fixed in that
