### ISSUE TITLE
Notification chain is not executed

### ISSUE THREAD

**Issue by lukaspustina** [bosun-monitor/bosun#1004]
Hi all,

we're running 785bf4e896ae4209f9edd5827b16e18448cde3b5 and I just introduced slack based notification into our Bosun configuration. Unfortunately, the next action is not executed as expected after a timeout of 15 min -- in case of a warning -- or immediately -- in case of a critical event. Below is my current configuration. Is this a bug or is there an error in my config?

```
notification default {
  email = infrastructure-hosting-team@XXXX
  next = default
  timeout = 6h
}

notification slack.warn {
  post = https://hooks.slack.com/services/XXXX
  body = payload={"username": "Bosun Cluster B", "channel": "#alerts-clusterb", "text": {{.|json}}, "icon_url": "https://raw.githubusercontent.com/bosun-monitor/bosun/master/cmd/bosun/web/static/img/tsaf-logo-mark.png"}
  next = default
  timeout = 15m
}

notification slack.crit {
  post = https://hooks.slack.com/services/XXXX
  body = payload={"username": "Bosun Cluster B", "channel": "#alerts-clusterb", "text": {{.|json}}, "icon_url": "https://raw.githubusercontent.com/bosun-monitor/bosun/master/cmd/bosun/web/static/img/tsaf-logo-mark.png"}
  next = default
}
```

Thanks in advance,
cheers,
Lukas

**Comment by mjibson** [comment]
You didn't acknowledge the alert within that 15 minutes?

**Comment by lukaspustina** [comment]
Nope, I didn't. 
I also tried is using different timeouts; even one minute without success.

**Comment by lukaspustina** [comment]
I updated to 0.2.0 and still observe the same behavior. Any ideas?

**Comment by mjibson** [comment]
Here's how to debug this:

1. Add `print = true` to all of the notifications.
1. Set the timeout to something small like `5s`.
1. Make a simple alert that always triggers: `crit = 1`, that is also hooked up to one of those notifications.
1. Watch the log entries produced to see what it's doing.

That will help determine what is the part that isn't working.

**Comment by lemkepf** [comment]
From my experience the chain breaks with something with the body generation: 

This kept the chain working: 

notification hipchat {
    next = email
    #post = http://api.hipchat.com/v2/room/xx/notification?auth_token=xx
    #:body = {"color": "red", "notify": true, "message_format": "text", "message": {{.|json}}}
    #contentType = application/json
    timeout = 5s
    print = true
}

this didn't: 
notification hipchat {
    next = email
    #post = http://api.hipchat.com/v2/room/xx/notification?auth_token=xx
    body = {"color": "red", "notify": true, "message_format": "text", "message": {{.|json}}}
    contentType = application/json
    timeout = 5s
    print = true
}

**Comment by lukaspustina** [comment]
Sorry guys for not coming back to you earlier.

I'm using `bosun version 0.3.0 (9386abc03b9d074e42dbbe5eb5944ee88ca641f6) built 2015-07-13T15:17:11Z`

@mjibson I added `print = true` to all notifications and could see the the alarm's subject getting logged. Unfortunately, there doesn't seem to be a deterministic behavior for alarm chains.

The following example worked exactly the first time the alarm became active, both notification were executed:
```
notification test.email.warn {
  print = true
  email = lukas.pustina@XXX
}

notification test.slack.warn {
  print = true
  post = https://hooks.slack.com/services/XXXX
  body = payload={"username": "Bosun Cluster B", "channel": "#alerts-clusterb", "text": {{.|json}}, "icon_url": "https://raw.githubusercontent.com/bosun-monitor/bosun/master/cmd/bosun/web/static/img/tsaf-logo-mark.png"}
  next = test.email.warn
  timeout = 5s
}

alert test.slack.notification {
  template = default.woGraph
  warnNotification = test.slack.warn

  warn = 0

  $name = TEST: Slack alarm chain
  $description = Just for testing
  $steps = Make it work
}
```

I couldn't make the chain work again. Even the slack notification wasn't executed reliably every time the alarm become active.

I reduced the notification to email only:

```
notification escalate {
  print = true
  email = infrastructure-alert@XXX
  next = escalate
  timeout = 1d
}

notification default {
  print = true
  email = infrastructure-alert-cluster-b@xxxx
  next = escalate
  timeout = 5s
}
```

This chain didn't worked even once, but at least the first E-Mail (`default`) was sent reliably every time the alarm became active.

Currently, I settled on using the E-Mail integration of slack andd sending E-Mails in `default` to two E-Mail address -- mailing list and slack.

I'm happy to try any other debugging you guys might think could help to analyse the problem.

**Comment by kylebrandt** [comment]
I believe this is fixed now
