### ISSUE TITLE
Problem configuring scollector to monitor processes

### ISSUE THREAD

**Issue by IzakMarais** [bosun-monitor/bosun#1007]
I haven't managed to get scollector to monitor generic processes as the docs claim it can.  

My scollector.conf (running on bosun+opentsdb host):
```
host = http://localhost:8070

[[Process]]
  Command = "redis-server *:6379"
  Name = "redis-main"
[[Process]]
  Command = "redis-server *:6380"
  Name = "redis-slave"
```

Note that the process syntax is a direct copy and paste of the [latest docs ](https://godoc.org/bosun.org/cmd/scollector).
I am also using the latest scollector available for download:
```
# ./scollector-linux-amd64 --version
scollector version 20150515173231 (9adbcee922cb30c89d7158ba033e05862d47c79e)
```
Trying to use this config file gives an error:
```
./scollector-linux-amd64 -d
2015/05/29 13:11:47 error: main.go:86: expected = in /data/scollector/scollector.conf:3
2015/05/29 13:11:47 fatal: main.go:145: unknown key in /data/scollector/scollector.conf:4
```

Do I have a syntax error here? 

Also, the docs are not very clear here: 

* is the '*' in the example matching anything (like a bash cmd prompt), or was that the actual command used (sorry if this is a dumb question, I have never used redis)? 
* Also, it mentions that "Args" is a valid key; what would the value be if a process has more than one arg?
* Could you perhaps give an example of how I would monitor a specific java program, e.g. Hbase-master. It's command line looks like: 
```
/usr/bin/java -Dproc_master -XX:OnOutOfMemoryError=kill -9 %p -Xmx6000m -XX:+UseConcMarkSweepGC -Dhbase.log.dir=/var/log/hbase -Dhbase.log.file=hbase-hbase-master-bd0004.log -Dhbase.home.dir=/usr/lib/hbase -Dhbase.id.str=hbase -Dhbase.root.logger=INFO,RFA -Djava.library.path=/usr/lib/hadoop/lib/native -Dhbase.security.logger=INFO,RFAS org.apache.hadoop.hbase.master.HMaster start
```

**Comment by mjibson** [comment]
We are currently in a transition state. The docs are ahead of the latest release. If you compile scollector from source it should work. We will update the website with a new release soon.

**Comment by kylebrandt** [comment]
aka we screwed up. We haven't gone through many breaking changes yet so we
are not very good at it yet. Breaking changes will be versioned and
smoother going forward.

**Comment by IzakMarais** [comment]
> We are currently in a transition state
> aka we screwed up...

That's OK, no harm done. 

> Breaking changes will be versioned and smoother going forward.

Glad to hear it.

~~However, I would be very grateful for some help getting this feature to work (I had tried and failed previously with the old syntax as well). I have now compiled from the latests source and I don't see the error messages any more. However, I still don't see any output from `./scollector -d | grep <process name>`~~

Maybe this is just my stupidity, but for some reason I assumed that the monitored process' name will be part of the metric name. Perhaps you could just mention in the docs that these stats are logged under _linux.proc.*_ with the process name in the _name_ tag? I see now it makes sense, but I wouldn't want others to also waste time based on wrong assumption.

Will you let me know when an official version is available for download? For now I am using my compiled version. Thanks!

**Comment by mjibson** [comment]
New binaries are up: https://github.com/bosun-monitor/bosun/releases/tag/0.1.0

**Comment by IzakMarais** [comment]
Thanks! I am closing this issue.
