### ISSUE TITLE
Proxy support for post notifications?

### ISSUE THREAD

**Issue by ukn** [bosun-monitor/bosun#1008]
Hi,
I'd like to use post notifications over HTTP proxy.
Any plans to support it?

**Comment by elementai** [comment]
It probably already works out-of-the-box, have you tried running Bosun with HTTP_PROXY environment variable defined ?
Like
```
HTTP_PROXY="http://proxyIp:proxyPort" ./bosun -c=...
```

**Comment by ukn** [comment]
My question should not be even here as it works just like you described. Thanks

This was a case of a misconfigured test environment(s).

**Comment by ukn** [comment]
I might have closed this one too quickly as I can't make it work.

I have this in my conf file:
```javascript
notification json {
  post = https://event.alarmservice.com/raise_alarm.json
  body = {"event": "alarm", "description": "Bosun test json", "details": {{.|json}}, "service_key": "xxx"}
  contentType = "application/json"
}
```
With https_proxy it still tries to connect directly to https://event.alarmservice.com (it resolves to AWS instance), bosun connection attempt:
```bash
bosun     12654    root    7u     IPv4              36331      0t0        TCP my_host:36540->ec2-111.111.111.111.compute.amazonaws.com:https (SYN_SENT)

```
and it's timing out:
```bash
bosun[12654]: 2015/06/02 16:19:41 Post https://event.alarmservice.com/raise_alarm.json: net/http: request canceled while waiting for connection
```
Same https_proxy variable is recognized correctly by curl:
```bash
$ HTTPS_PROXY="http://myproxy.net:80" curl https://event.alarmservice.com/raise_alarm.json -d '{"event_type": "trigger", "description": "Bosun test API", "details": "my test", "service_key": "xxx"}' -H 'contentType = "application/json"'
{"status":"success"}

**Comment by mjibson** [comment]
I've opened a PR to try to add proxy-from-environment support to bosun. Could you try it out?

https://github.com/bosun-monitor/bosun/pull/1028

**Comment by ukn** [comment]
Works like a charm. Thank you.
