### ISSUE TITLE
Expanding large groups on the dashboard should probably load in multiple "pages"

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1031]
The host.down alert is displayed on the dashboard in one large group with 222 members for our production environment. When you expand this group it tries to load the data for all 222 members, which takes a few minutes. Might be better to support some sort of paging, where it will load the first 25 members, then you have to click to load the next 25 or have another option to load all members.

We've often seen that interacting with these large groups can cause issues (like errors in haproxy) or other side effects, so defaulting to only loading 25 alerts when expanding the group may help prevent problems.

Screenshot from devtools showing all the api calls when expanding the group:

![image](https://cloud.githubusercontent.com/assets/304401/7946016/82510aba-0931-11e5-944b-507b6bdd9eb7.png)

**Comment by kylebrandt** [comment]
This also prevents me from being able to close alerts.
