### ISSUE TITLE
'send notification' of multiple ACK/CLOSE is not informative

### ISSUE THREAD

**Issue by ayashjorden** [bosun-monitor/bosun#1045]
Hi,
When ACK/CLOSE multiple alerts, and the 'send notification' is checked(enabled), the sent message is '<USER_NAME> Closed 10 Alerts.'.

Suggested is to add a json checkbox that will format the 'send notification' message with: user_name, alert array, timestamp and maybe other relevant fields.

Also, plain text message should include the alerts in context.

Thanks,
Yarden

**Comment by kylebrandt** [comment]
Seems like we did this at some point:

![image](https://cloud.githubusercontent.com/assets/1692624/16357486/01cc077e-3ac6-11e6-859a-61bc34472224.png)
