### ISSUE TITLE
Actions will fail if you are performing them on many alerts

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1053]
Just like the https://github.com/bosun-monitor/bosun/issues/1033 , actions will fail if you are performing them on X alerts.

**Comment by captncraig** [comment]
The counter-argument here is that emails have action links. You can't get an email client to execute a post. If we are having proxy issues with long urls, perhaps we should reconfigure proxy. Or maybe make the action endpoint accept either, since the web ui is the only place we close multi.

**Comment by kylebrandt** [comment]
"Or maybe make the action endpoint accept either, since the web ui is the only place we close multi."

I think that is what we should do (or something like this). We can configure the proxy, but people are going to have issues around this and it will keep coming up again and again.

**Comment by captncraig** [comment]
On further inspection, they do use post: https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/web/static/js/action.ts#L29

**Comment by mjibson** [comment]
The action endpoint can only use POST because it needs JSON data in the body. The title of this issue is wrong. I'm changing it to be the bug instead of the assumed solution.

**Comment by kylebrandt** [comment]
When I looked at the long string I thought it was a GET request. I believe what I was actually seeing is all the get parameters for the Referer header. So the result is the same, the header ends up being unreasonably large.

That is my hypothesis anyways

**Comment by kylebrandt** [comment]
Called this a bug, even though it is really just the result of it being behind a proxy. Basically "doesn't work" even if it isn't exactly bosun's fault
