### ISSUE TITLE
scollector new version not starting in windows 

### ISSUE THREAD

**Issue by skhprabu** [bosun-monitor/bosun#1054]
I'm kind of stuck with this for few hours now. So wanted to check if this is an issue or I'm doing something wrong.
I'm trying to upgrade to the recent scollector version. The previous scollector working version is scollector version 20150311224711 (7dc91ad5902bb9316c75321d07268221f64ce3b3)

Current scollector Version : scollector version 0.1.0 (7a4ff145315ab52276f440b2624d2676fee8d096) Built 01 Jun 15 20:49 UTC
OS : Windows Server 2012 R2

I've changed my conf file format to the new toml format. Here is the extract of my scollector.conf/scollector.toml. I've this in the default location. When I start the scollector as a windows service, i see this error in the event log

"fatal:main.go:236: invalid host : no host specified"

Host = "http://tsdbhost:8070"

FullHost = false

ColDir = ""

Hostname = ""

DisableSelf = false

Freq = 20

Filter = ["c_diskspace_windows", "c_physical_disk_windows", "c_cpu_windows", "c_cpu_info_windows", "c_simple_mem_windows", "c_windows_memory", "c_windows_pagefile", "c_network_windows", "c_network_team_windows", "c_network_windows_tcp", "c_windows_process_total", "c_windows_processess", "c_system_windows", "c_dotnet_memory", "c_dotnet_loading"]

KeepalivedCommunity = ""

[[ProcessDotNet]]

  Name = ".*"

**Comment by gbrayut** [comment]
The file should be called scollector.toml now instead of scollector.conf. If you want to use the .conf filename you will need to start the service using something like: `...\scollector.exe -conf .\scollector.conf`

Also be aware that toml doesn't like spaces between headers and values, so you should use
```
[[ProcessDotNet]]
  Name = ".*"
```
