### ISSUE TITLE
Missing Avatar on https://hub.docker.com/account/organizations/stackexchange/ profile

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1072]
Someone that is an owner on the docker registry organization should update the profile to use the https://github.com/stackexchange logo

**Comment by mjibson** [comment]
We need a gravatar account for this. I'm not aware if we have one.

**Comment by gbrayut** [comment]
sysadmin-team @ so .com is now a gravatar account using the SE logo

**Comment by mjibson** [comment]
Done.
