### ISSUE TITLE
Custom down sample window / function does not work in template graphs

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1104]
Using `q("sum:600s-avg:traffic.haproxy.server_tr_max{server=ny-service0*}", "1h", "")` in a template graph produces the same graph as if the 600s-avg was omitted, so it appears that template graphs do not support custom down samples. The expression produces the desired result when used on the expression page.

**Comment by gbrayut** [comment]
I think this needs to be addressed sooner than later now that we have added a bunch of graphs to the footer. It takes significantly longer to run a test or process an alert due to all the data points displayed on the graphs. They should use custom downsampling to make them cleaner and prevent overloading the graph rendering library, but as of right now the graph command does not respect the custom downsample settings.

**Comment by kylebrandt** [comment]
It would be nice to have this regardless, but do you have example of this being slow? I didn't find that when setting the time in the config page to ensure that I was hitting TSDB cache. There will be the automatic downsampling so the number of data points should be sane.

Also as a work around we could use the window() function, but that can generate a lot of tsdb queries depending on what you are doing.

**Comment by gbrayut** [comment]
try adding `macro = host.based.contacts` to the **traffic.processing.service.down** alert and compare the testing duration for a single iteration.

I've update the generic.graph template to check for osCPU before including the footer, so the above steps can show the difference between one graph and lots of graphs.

**Comment by gbrayut** [comment]
Also custom downsampling would let us significantly cut the number of data points in the graph since many of those stats work fine using 10m or larger down sample windows. The assumption is that with less data points the alert/graphs would take much less time to render.

**Comment by kylebrandt** [comment]
I tried cutting the time down for everything so there wasn't a lot of
datapoints, but it is still slow (Roughly 9 seconds, even setting the time
to ensure cache hitting). So I'm not really sure why it is slow, need more
stepping in miniprofiler I think. Maybe we can see what Craig thinks on
Monday
