### ISSUE TITLE
quickstart: template prints error not warning expression

### ISSUE THREAD

**Issue by ecki** [bosun-monitor/bosun#1109]
With the test case in the quickstart guide the resulting sample email output prints the error expression even when only a warning was triggered. It looks like the input data has that problem already (or the template does not work hard enough to pick the right rule)

**Comment by kylebrandt** [comment]
@ecki Can you explain this a bit more. i.e. show the section of the quickstart guide you mean, and show the resulting error?

**Comment by kylebrandt** [comment]
Closing due to lack of details.
