### ISSUE TITLE
Unable to Clear Silences on New Silence Page

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1150]
![image](https://cloud.githubusercontent.com/assets/1692624/8607041/7623bede-264d-11e5-99fa-6992fcae07e6.png)

**Comment by acesaro** [comment]
I'm running into this as well.  Is there any workaround?

**Comment by kylebrandt** [comment]
@cedw93 you on master?

**Comment by kylebrandt** [comment]
Fixed in master according to cedw93 via chat
