### ISSUE TITLE
Indexing existing metrics and tagk/tagv pairs 

### ISSUE THREAD

**Issue by mxk1235** [bosun-monitor/bosun#1158]
I was wondering what the plan is for bosun to discover metrics that were not routed through bosun to OpenTSDB.  In our setup, we have all services talk directly to a large opentsdb cluster for insertion of metrics.  By now, there are thousands of metrics and tagk/tagv strings.  Can bosun automatically or manually pull those from OpenTSDB and index them?

thanks in advance.

**Comment by kylebrandt** [comment]
There is no plan to do this at the moment. If you start relaying data through bosun it will start to populate. Our assumption is that it is okay to be missing old information from Bosun's knowledge. This in a way is similar to OpenTSDB's behavior of not returning results if they don't exist in the time span.

If you just don't want to relay all data through a single bosun process, we do have a seperate relay process that can be used. That basically just duplicates the traffic and sends it to OpenTSDB and Bosun. The process is more reliable than bosun itself since it is so simple (This is why we created it}. It is in `cmd/tsdbrelay`.

Bosun also keeps track of relational information (This metric has these tag keys, and these tag keys have these values, etc). OpenTSDB doesn't do this by default, so we can't really just replay the information from the OpenTSDB tag table since it doesn't store relational information.

**Comment by mxk1235** [comment]
I think that's a reasonable stance, but still presents a barrier for us, since most of our services use the opentsdb telnet interface.  I think my current preferred idea is to issue a separate /api/index to bosun for tagk/tagv values that i care about.   

However, i think bosun would still benefit from indexing the metric names.  Can you offer any thoughts on that as a compromise solution?

**Comment by kylebrandt** [comment]
You can but unless it is simple I don't think we will have time to act on
it without a PR.

Our collector (scollector) takes the telnet format on the command line and
formats it to JSON. You also get queueing. If that doesn't help it might be
trivial to make scollector run in a mode where it also takes those messages
via a network socket and proxies them. Maybe that would help?

My first guess at implementing a an indexer would be to create an api route
that expects no data points and just metric tag sets. I would then see if I
can use OpenTSDBs scan cmdline utility to get the ids from the tsdb table
to feed that new route (translating the keys back to the metric tag sets).
If not I would try to do the same thing but with hbase directly. One way or
another you would have to scan the tsdb table to know the relational
information.

**Comment by kylebrandt** [comment]
When it comes to just the metric names I think that would be problematic.
We would have two behaviors (some metrics know what tags belong, others
don't) and that would get messy fast

**Comment by mxk1235** [comment]
Thanks, I have no problem working on a PR, but looking for guidance to start.  two questions:

1) i thought /api/index already exists.  http://bosun.org/api.html#apiindex  is there any reason why it would not be appropriate?  As long as i have a corresponding call to bosun to index what i just inserted into opentsdb (because i bypass bosun), it would be my client keeping the data synced.

2) does bosun also passthrough graphite data, or does it discover metric names from graphite in some other way?

**Comment by captncraig** [comment]
1. /api/index should be sufficient. It expects a set of gzipped/json encoded data points. If you can get them in that format and call /index, it will accept them. 

Possibly an external indexer/opentsdb scraper app could look for metrics and tags and call that endpoint.

2. I believe graphite queries do not get the benefit of the search and indexing functionality in bosun. It can run alerts and evaluate expressions, but I think the graph page is less useful. Most users I know of use grafana for graphing from graphite.

**Comment by mxk1235** [comment]
We also use grafana for dashboarding and such, but evaluating Bosun for actually doing alerting.  Is that possible?   

I've configured graphiteHost in bosun.conf, but i can't seem to run a query against it.  It's almost as if Bosun assumes it's an opentsdb metric.  how does bosun figure out whether to query Graphite or TSDB?

**Comment by captncraig** [comment]
There is a seperate query function for graphite.http://bosun.org/expressions.html#graphite-query-functions

**Comment by kylebrandt** [comment]
@captncraig @mxk1235 The reason I was thinking a different route is that I believe /api/index expects datapoints (values) whereas the only information needed if you were scanning the tsdb table would metric+tagset. I guess you put in 0,0 values or something but that seems a bit messy. 

I haven't checked the implementation though, maybe it doesn't need a time value pair already...

**Comment by psadhu** [comment]
we are looking to build alerting on exisiting tsdb.  It  would be good to see this feature in Bosun.
