### ISSUE TITLE
Bosun hard-codes the set of aggregators

### ISSUE THREAD

**Issue by mxk1235** [bosun-monitor/bosun#1165]
Opentsdb 2.0+ introduces some new aggregators, and the list of them is exposed via /api/aggregators endpoint ( http://opentsdb.net/docs/build/html/api_http/aggregators.html ).  Bosun should call that in order to populate the lists here,

https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/web/static/js/graph.ts#L156

and here,

https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/web/static/js/bosun.js#L1634

I started on a PR, but realized that those are web assets that talk to the bosun server, which first needs an endpoint to proxy the request to tsdb.

**Comment by kylebrandt** [comment]
I thought about doing that at first but decided it wasn't worth the complexity and that hardcoding it was better.

I think 2.2 is the first time aggregators have been added in years. I would rather make this a hard coded list in Bosun so we don't have a dependency or wait on getting that list. We be good to centralize that in Bosun though.

**Comment by mxk1235** [comment]
you are right, new aggregators are in 2.2.  however, if you hard-code, that introduces an incompatibility, as the same code in bosun really only works with either pre-2.2 and 2.2+.  (as an aside, 2.2 also removed the currently hard-coded "minmax" aggregator, and introduced "mimmax" and "mimmin").  

i've implemented a similar change in grafana, which is purely browser assets, and it doesn't wait for a response.  it uses a hard-coded default (pre-2.2) and overwrites it when opentsdb responds with the list.   https://github.com/grafana/grafana/pull/1646/files

**Comment by kylebrandt** [comment]
What about Bosun detecting the version on startup, and then doing everything within Bosun based on the version?

**Comment by captncraig** [comment]
Well it doesn't really introduce incompatibilities. If you use an aggregator not supported by your install of tsdb, you will get an error. Nobody that is working will break.

**Comment by mxk1235** [comment]
i think if Bosun detects the version on startup, it could also pull down the list of aggregators on startup.
