### ISSUE TITLE
How to customize the external collectors and enable it

### ISSUE THREAD

**Issue by LeeKui** [bosun-monitor/bosun#1175]
Hello, bosun runs in docker container, on the client side. test [collector](https://github.com/OpenTSDB/tcollector/blob/master/collectors/0/mongo.py) is in the directory /scollector/collectors/0/, and config parameter is included in /scollector/scollector.toml: ColDir = "/scollector/collectors/". However, the customized metric is not present in http://localhost:8070/items. Did I miss something?

**Comment by kylebrandt** [comment]
Sorry we missed this request for help. Closing because of the age, but request reopen if still a problem.
