### ISSUE TITLE
Error when trying to get package

### ISSUE THREAD

**Issue by Johnathon332** [bosun-monitor/bosun#1177]
Tried to get the package as explained in the documentation "go get bosun.org/cmd/scollector" but got this error "package net/http/cookiejar: unrecognized import path "net/http/cookiejar"  I am trying to install this on a raspberry pi model B+.  Also does scollector allow sending data remotely? for example via the OpenTSDB HTTP api?

**Comment by Dieterbe** [comment]
what go version do you use? perhaps it's too old

**Comment by captncraig** [comment]
You can also download pre-built binaries for the pi on our releases page.

**Comment by Johnathon332** [comment]
I tried running the binaries and got this 

./scollecter-linux-armv6
-bash: ./scollecter-linux-armv6: No such file or directory

Not sure if I am using the right commands as I am rather new to linux.  Do you know how to check what version of GO I have on linux?

**Comment by captncraig** [comment]
`go version`

**Comment by Johnathon332** [comment]
@Dieterbe  I think you are right in saying my go version is too old.  It says go version go1.0.2 I went on the go site to see if there was an ARM version but doesn't seem to be?

**Comment by captncraig** [comment]
Yeah. 1.0.2 is really old. Honestly, you should probably go with the pre-built binaries for pi. It looks like maybe you didn't download it properly, or were not in the proper directory when you ran it.

If you really wanna run go on the pi, there are some binary distributions at http://dave.cheney.net/unofficial-arm-tarballs

**Comment by Johnathon332** [comment]
I'll redownload the prebuilt binary for pi and try run it again

**Comment by Johnathon332** [comment]
@captncraig so I tried to redownload and tried to run it again, got permission denied even though I am the only user on the pi.  I tried to do it with the sudo and that still came back with the same error.  I then tried with sudo su and sudo su - in which I got the same thing.  I did a chmod +x after and tried to re run it, got a Text file busy error.

**Comment by kylebrandt** [comment]
Text file busy generally means the file is still being downloaded.

Also are we sure the prebuilt version is the right arm version?

**Comment by Johnathon332** [comment]
@kylebrandt I checked my arm version by using cat /proc/cpuinfo and it says ARMv6 so I believe so

**Comment by kylebrandt** [comment]
Not sure where this left off but closing due to age. Reopen if needed
