### ISSUE TITLE
"Shouldn't be here" error upon query

### ISSUE THREAD

**Issue by k-bx** [bosun-monitor/bosun#1180]
My metric `linux.net.sockets.used` for one of hosts is shown fine for 3h-long data, but when I choose 4h interval I get an error:

```
opentsdb: {"start":"4h-ago","queries":[{"aggregator":"sum","metric":"linux.net.sockets.used","rateOptions":{},"tags":{"host":"app3"}}]}: Shouldn't be here
```

What is the meaning of this?

Thank you.

**Comment by kylebrandt** [comment]
Haven't seen this one in a long time. IIRC it is what OpenTSDB returns when you query something that had duplicated datapoints (Same tagset, Same Timestamp, *different values*.

If this is the case, you have two options: Ensure there are no duplicates (you will only find out at query time, not write time) or enable tsd.storage.fix_duplicates in the OpenTSDB config.

If it is something else it is an error returned by OpenTSDB, so you that would be the place for further troubleshooting / bug filing.

**Comment by k-bx** [comment]
Thanks, closing for now then, will reopen if I'll see the error again and these won't help.

**Comment by k-bx** [comment]
@kylebrandt I think 2 instances of scollector were running on a problematic host
