### ISSUE TITLE
Question: load-balancing / failover

### ISSUE THREAD

**Issue by mxk1235** [bosun-monitor/bosun#1183]
I am planning on running Bosun on multiple machines for redundancy/scale/etc...  As of right now, my understanding is that each machine would execute its own checks and alerts, but it will probably result in a double email.

Is there a correct or recommended to do this?
thanks in advance!

**Comment by kylebrandt** [comment]
We don't really have anything planned yet but this is coming up for us soon
at Stack. The main thing we would need to do is sync state between the two
instances. My recommended workaround for the time being would have opentsdb
relay send index information to both instances. Run the back up instance
with -n (no checks) and you won't get email. When you need to failover you
could clear all active alerts on the standby, and then restart it without
-n.

Not ideal but should be functional for manual or scripted failover until we
have some way to sync state. make sense?

**Comment by mxk1235** [comment]
Yes it does.  We have roughly sketched out a similar primary/secondary infrastructure.

A followup question, is it possible for bosun instances to use a shared database service for state?  I realize that bosun right now uses an in-memory database, but perhaps that sort of failover is also possible.

**Comment by captncraig** [comment]
We have discussed potentially using a redis model since there is also an in-memory implementation of redis. That could potentially allow check coordination across multiple bosun hosts, but that is not really too close on our radar at present.

**Comment by kylebrandt** [comment]
This library caught my interest for that http://ledisdb.com/

**Comment by mxk1235** [comment]
I see.  Did you think about supporting multiple backends, perhaps through an abstraction?  If storage is more simply a key-value store, it could really benefit from connecting to either redis, ledis, boltdb, etc.

**Comment by mxk1235** [comment]
actually, i see that https://github.com/siddontang/ledisdb can in fact use boltdb as a backend.  that could be perfect.

**Comment by kylebrandt** [comment]
Closing this for now as a "question" since closing this won't delete the discussion.
