### ISSUE TITLE
[Question]no Elasticsearch node available when querying Logstash

### ISSUE THREAD

**Issue by cedw93** [bosun-monitor/bosun#1186]
I have 3 docker containers running each park for the ELK stack in its own container and a fourth docker container running the bosun image. 

I have been able to submit data to Logstash and view the submitted logs in the Kibana dashboard so all seems to be configured correctly.

In my Bosun config i have the following:

    logstashElasticHosts = localhost:5000

where local host is the docker ip, as they both run docker image, I also tried

    logstashElasticHosts = localhost:9200

However with both the above configurations I get the following error:

     no Elasticsearch node available

when executing:

     lscount("logstash", "", "", "5m", "2d", "")

I also tried removing `localhost` and substituting it for my public docker ip but the problem persists.

I looked at [#871](https://github.com/bosun-monitor/bosun/issues/871) but that didn't really help. I also tried looking at the documentation but it didn't really help with configuration.

    docker ps 

produces

    CONTAINER ID        IMAGE                    COMMAND                CREATED             STATUS                      PORTS                                            NAMES
    2a4121c9d26e        ehazlett/kibana          "nginx -g 'daemon of   18 hours ago        Up 36 minutes       0.0.0.0:80->80/tcp, 443/tcp                      clever_bardeen      
    a70d5fba5430        ehazlett/logstash        "/opt/logstash/bin/l   18 hours ago        Up 37 minutes       0.0.0.0:5000->5000/tcp, 0.0.0.0:5000->5000/udp   reverent_pike       
    a39310af839e        ehazlett/elasticsearch   "/opt/elasticsearch/   18 hours ago        Up 37 minutes       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   es                  
    409551d6cb08        stackexchange/bosun      "/usr/bin/supervisor   41 hours ago        Up 5 minutes        4242/tcp, 0.0.0.0:8070->8070/tcp                 trusting_pike      

Can anybody explain what i am doing wrong? first time using Bosun with the ELK stack

Edit: example JSON from one entry in the Kibana dashboard, data is sent from a simple java application:

    {
      "_index": "logstash-2015.07.22",
      "_type": "monitoring",
      "_id": "lBkTLwPmSHCW2QUiwMTYXQ",
      "_score": null,
      "_source": {
        "@timestamp": "2015-07-22T10:40:19.607Z",
        "@version": 1,
        "message": "This is an error message",
        "logger_name": "Test",
        "thread_name": "pool-1-thread-1",
        "level": "ERROR",
        "level_value": 40000,
        "HOSTNAME": "RICMID12033a.local",
        "host": "192.168.59.3:56656",
        "type": "monitoring"
      },
      "sort": [
        1437561619607,
        1437561619607
      ]
    }

**Comment by ermeaney** [comment]
I got rid of that error by this:
logstashElasticHosts = http://localhost:9200

**Comment by Andre12c** [comment]
Hi everyone, I have the same problem when quering elasticsearch from bosun

logstashElasticHosts =http://192.168.99.100:9200
lscount("logs_all_AEZ-2016-02-06", "", "", "2m", "3d", "2d")

Json document example:

{
	"_index" : "logs_all_AEZ-2016-02-06",
	"_type" : "logs",
	"_id" : "AVPqNbnLDqJMfK6wffhg",
	"_score" : 1,
	"_source" : {
		"application_Name" : "ASD",
		"loglevel" : "PANTH",
		"composant" : "ELP",
		"hostname" : "pol",
		"esType" : "logs",
		"timestamp" : "1459923282809",
		"type_source" : "syslog_pli",
		"Severity" : "0",
		"esIndex" : "logs_all_AEZ",
		"Facility" : "5698",
		"instance" : "WDFOADP27PAO",
		"datetime" : "2016-04-06 08:14:42,809",
		"logfile" : "WQDERTGLOG"
	}
}

error: no elastic indices available during this time range, index[allpaologs_all_wdi], start/end [2016.04.10|2016.04.12] 

I also can't use escount function (expr: non existent function escount ) 

elasticsearch version:1.7.2

**Comment by kcech** [comment]
In regard to "no elastic indices available", I had this problem too. After looking to https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/expr/logstash.go#L136 I placed a slash "/" at the end of the index name and the error went away.

Bosun expects logstash format  indexRoot+”-“, “YYYY.MM.DD”
escount available since Elasticsearch 2

**Comment by kylebrandt** [comment]
ls* funcs deprecated, new es gives you more control over index names.
