### ISSUE TITLE
new vertx lib for bosun

### ISSUE THREAD

**Issue by jtruelove** [bosun-monitor/bosun#1200]
I created a small lib for vert.x & bosun here -> https://github.com/cyngn/vertx-bosun I'm not sure if you have a distro list or anything to make people aware. Let me know if you have any feedback or requests related to it.

**Comment by gbrayut** [comment]
Thanks! We don't have a distro list, just the [bosun slack chat room](http://bosun.slack.com). Nice work on the library. 

A good next step would be adding metadata support (gauge vs counter, units, and description) and long term making it easy to create aggregated metrics (see the bosun.collect.post.*_* metrics created by the [collect package](https://github.com/bosun-monitor/bosun/tree/master/collect) or the more advanced [BosunReporter.NET library](https://github.com/bretcope/BosunReporter.NET) used by our .NET web apps)

**Comment by jtruelove** [comment]
Cool, the meta data stuff would be easy to add. Do you have a place in your docs where you link to libs or anything? I can submit a pull request if so to let people know about it.

**Comment by gbrayut** [comment]
Not yet but that sounds like a good idea! We'll find a place to put details about libraries and I'll update this issue once is is ready for additions.

**Comment by jtruelove** [comment]
Sounds great! Just let me know.

**Comment by gbrayut** [comment]
This is now included in the Libraries and Collectors section of http://bosun.org/resources

**Comment by nickman** [comment]
Thanks......
