### ISSUE TITLE
Need a way to force delete Alert Instances

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1208]
Normally you can't close an active alert, because it will just come right back (with the exception of an error state).

Currently we have one stuck on our dashboard that resulted from a panic, so it seems there always might be the possibility of stuck alerts. We should be striving to prevent whatever caused them, but we need some sort of remediation route.

**Comment by captncraig** [comment]
Added some time ago. Force close and purge actions.
