### ISSUE TITLE
Cannot draw graph when datapoints are undefined

### ISSUE THREAD

**Issue by garrettheel** [bosun-monitor/bosun#1211]
If any groups do not contain data then a JS error occurs when trying to draw a graph:

```
TypeError: Cannot read property 'Data' of undefined
...
at draw (bosun.js:1300)
...
```

This is because there are `undefined` items in `scope.data`.

**Comment by kylebrandt** [comment]
What time series database are you using? What is the expression?

**Comment by GarrettHeel** [comment]
It's using a graphite expression: `graphite("redis.*.connected_clients", "5m", "", "..host")` where some of the values matching the `*` have no data.

**Comment by kylebrandt** [comment]
@Dieterbe Can you advise here?
