### ISSUE TITLE
querying documents from ES to be shown as text in notifications?

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#1212]
ability to query for numbers about matching docs in ES is nice and all, but i also would like to show some matching docs in notifications.

use case: our log entries go into ES, they have different log levels. such as warn/crit/error/info, etc.
we want to do alerts on "number or errors has gone up" but it would be nice to be able to put in notifications stuff like:
1. a list of distinct error messages seen amongst all errors, along with their counts in the last 10min.
2. an overview of which hosts are erroring and how many errors each
3. last error seen per host

**Comment by kylebrandt** [comment]
I don't have distinct, but look at the .LSQuery template func that already
exists ;-) then see if what improvement you need

**Comment by Dieterbe** [comment]
oh neat

**Comment by kylebrandt** [comment]
@Dieterbe Going to close this for now. Reopen or open a separate issue if LSQuery isn't enough to complete your mission.
