### ISSUE TITLE
New runtime metrics in go 1.5 release

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1219]
I was checking the commits for the [go 1.5 beta 3 change log](https://github.com/golang/go/compare/cc8f544...d3ffc97) and noticed this one https://github.com/golang/go/commit/23e4744c07f78151a4e9fa5187b84ed26fe3628b which is a new runtime metric we probably want to add to collect. There may be others, so we can track them here.

**Comment by captncraig** [comment]
Added some basic stats in a recent change.
