### ISSUE TITLE
JSON External Documentation Format is not Documented

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1225]
http://godoc.org/bosun.org/cmd/scollector doesn't talk about how they can output json now

**Comment by kylebrandt** [comment]
The PR that needs to be documented https://github.com/bosun-monitor/bosun/commit/fced1642fd260bf6afa8cba169d84c60f2e23e92

**Comment by gbrayut** [comment]
I'll add this to the resources PR today, but for now the structs used in JSON are [opentsdb.DataPoint](https://github.com/bosun-monitor/bosun/blob/master/opentsdb/tsdb.go#L62) for metric data and [metadata.Metasend](https://github.com/bosun-monitor/bosun/blob/master/metadata/metadata.go#L212) for metadata. You send a stream of serialized JSON data over stdout, so when you run the program it should produce something like below. It starts with Metadata (only needed once, scollector will re-send as needed) and then starts sending metrics. You can also see the 4th line is a log message which was sent to stderror not stdout.

```
{"Metric":"exceptional.exceptions.count","Name":"rate","Value":"counter"}
{"Metric":"exceptional.exceptions.count","Name":"unit","Value":"errors"}
{"Metric":"exceptional.exceptions.count","Name":"desc","Value":"The number of exceptions thrown per second by applications and machines. Data is queried from multiple sources. See status instances for details on exceptions."}
2015/08/05 15:32:00 lookup OR-SQL03: no such host
{"metric":"exceptional.exceptions.count","timestamp":1438788720,"value":0,"tags":{"application":"AdServer","machine":"ny-web03","source":"NY_Status"}}
{"metric":"exceptional.exceptions.count","timestamp":1438788720,"value":2,"tags":{"application":"AdServer","machine":"ny-web04","source":"NY_Status"}}
{"metric":"exceptional.exceptions.count","timestamp":1438788720,"value":1,"tags":{"application":"AdServer","machine":"ny-web06","source":"NY_Status"}}
```

**Comment by gbrayut** [comment]
Update docs now at http://bosun.org/scollector/external-collectors
