### ISSUE TITLE
Bosun: y axis label on Graph tab has a ; at the begining

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1226]
![image](https://cloud.githubusercontent.com/assets/304401/9014741/7d62fb8e-3781-11e5-95e7-6fcc2d82a4f1.png)

I checked the Elastic Cluster alerts and the y axis label on those graphs looks fine, so this is just on the Graph tab.

**Comment by kylebrandt** [comment]
Is this multiple queries? My guess is I did a string join on the units, and one of the metrics doesn't have a unit...

**Comment by gbrayut** [comment]
doh... yep. I had two series. one with a unit and one without. so it was <blank>; seconds
