### ISSUE TITLE
bosun logstash elastic query needs better timeout

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1227]
our alerts based on lscount queries may be causing issues with unknowns due to very long check runs. Details at http://goo.gl/4AatCY

Disabling those in our config for now, will renable after a better timeout is implemented.

**Comment by kylebrandt** [comment]
Thinking we are better off doing this at a high level, so it doesn't just apply to logstash.

**Comment by gbrayut** [comment]
From the log:
```
Jul 26 03:40:34 ny-bosun01 bosun[12657]: 2015/07/26 03:40:34 linux.oom_killer{}: template: linux.oom_killer:4:23: executing "linux.oom_killer" at <.LSQuery>: error calling LSQuery: no Elasticsearch node available
```
