### ISSUE TITLE
Better home page and doc page explaining what Bosun is

### ISSUE THREAD

**Issue by oliverjanik** [bosun-monitor/bosun#1230]
I arrived to the homepage via golang mailing list and being a newbie to monitoring (besides AWS CloudWatch) I don't quite understand what this project is all about and why would I use it instead of the alternatives.

Also I know it's lame, but the frondpage could use some examples and screenshots.

**Comment by kylebrandt** [comment]
I'd rather have a cleaner front page. We do have screenshots and examples on the site. Currently bosun is target at a more advanced monitoring audience, so if someone is look for a quick and easy monitoring system, Bosun is probably a bad fit.

Raintank is making open source SaaS that uses bosun to some degree, but for now I'd rather keep its overall design the way it is.
