### ISSUE TITLE
Modular backends

### ISSUE THREAD

**Issue by lcoulet** [bosun-monitor/bosun#1236]
After raising  #1235 (which was about KairosDB), a little bit more code inspection confirmed that the backends are all pretty much hardcoded.
It would be nice to have a well defined interface for the Bosoun backends, so each backend supported by Bosuncan be implemented as a separate plugin or module and registered as so in the configuration file.

I think this would be an enabled for additional backends (like KairosDB but also influxDB or whatever) and to decouple responsibilities. IMO, this would also lead to a much more maintenable system at the end.

**Comment by Dieterbe** [comment]
+1

fyi i wrote the first additional backend, which was graphite.
it wasn't too bad (all in all was about 2 days).  IIRC the main challenges are in:
* config system is hardcoded to support certain backends
* function mappings (GraphiteQuery, `q()` etc. see cmd/bosun/expr/funcs.go) are globally defined
* a bunch of the structs and functions take fixed args for the supported backends
* (also it's assumed that you can have at most 1 graphite, at most 1 opentsdb, etc. this is probably fine but worth noting)

**Comment by kylebrandt** [comment]
I don't see us changing to a plugin model for backends in the near future so closing this. Not that I think it is a bad long term idea, but in the short term would rather focus on our current set of backends.
