### ISSUE TITLE
[Question]How to query Logstash based on contents of the message

### ISSUE THREAD

**Issue by cedw93** [bosun-monitor/bosun#1238]
The documentation surrounding the Logstash querying is quite vague and there isn't really any examples of how to achieve this. 

If I have an entry (or entries) in the form of:
```
{
  "_index": "logstash-2015.08.04",
  "_type": "java",
  "_id": "fK-U4k0xToegQ5VQqzuydA",
  "_score": null,
  "_source": {
    "message": "{\"@timestamp\":\"2015-08-04T17:21:52.876+01:00\",\"@version\":1,\"message\":\"This is an error message\",\"logger_name\":\"Test\",\"thread_name\":\"pool-1-thread-1\",\"level\":\"ERROR\",\"level_value\":40000,\"HOSTNAME\":\"RICMID12033a.local\"}",
    "@version": "1",
    "@timestamp": "2015-08-04T16:21:52.879Z",
    "host": "xxxxxxxxxxxx,
    "type": "java"
  },
  "sort": [
    1438705312879,
    1438705312879
  ]
}
```

How do I query based on the contents of the `message` field, currently I am counting the number of entires a second which are of `type java` using:

```
lscount("logstash", "", "_type:java", "1m", "5m", "")
```

If possible id like to also specify a type and the contents of the message I wish to filter for example:

This is in `pseudo-code`

```
lscount("logstash", "", "_type:java && message contains level:ERROR", "1m", "5m", "")
```

Is there a good tutorial? The docs only seem to list what each parameter does, not how to explicitly use them in certain scenarios, which i think would be a very good addition to the docs.

**Comment by lukaspustina** [comment]
For the query try `_type: java AND message: ERROR`.

AFAIK there is currently no support for quoting in in `lscount()` and `lsquery()` so there is no way you can express "level:ERROR", because that reads like a field named "level" and the content "ERROR".

**Comment by cedw93** [comment]
So currently there is no way to combine the type and the content of the message field? My syntax maybe wrong but is the a correct way to do so? If not for now I guess I could specify different typings rather than extract the contents of the message although this is far less maintainable.

**Comment by cedw93** [comment]
Closed accidentally. Sorry.

**Comment by gbrayut** [comment]
You can use a , to combine two searches like `field:regex,field:regex`. Here are some examples of our lscount based alerts:

```
$indexRoot = logstash
$keyString = logsource
$filterString = message:.*error.*,message:.*scollector.*
$error_rate = avg(lscount("$indexRoot","$keyString", "$filterString" , "1m", "10m", ""))
warn = $error_rate > 0

$q = avg(lscount("logstash-it", "@source_host", "eventlog_id:1376","10m","1h",""))
crit = $q > 0

crit = avg(lscount("logstash","logsource","message:.*oom-killer.*", "1m", "10m", ""))
```

**Comment by cedw93** [comment]
Thank you very much! I assumed there was a built in way to handle multiple search terms.
