### ISSUE TITLE
Alerting on backend problems

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1239]
It'd be good if Bosun could generate an alert whenever one of the backends is not accessible for whetever reason.

One possible implementation is to provide special status variables for each backend, which could then be used in alerting rules. These variables could then be updated whenever a query is made to that backend.

@captncraig thinks it may be better to separate error handling from the usual alerting workflow, like the unknowns handling

Any thoughts?

**Comment by kylebrandt** [comment]
Calling this a dup of https://github.com/bosun-monitor/bosun/issues/766
