### ISSUE TITLE
SNMP Collected metrics don't follow os.xx conventin of other metrics

### ISSUE THREAD

**Issue by GABeech** [bosun-monitor/bosun#1241]
Metrics that are not collected via SNMP are stored in two places. `type.something.metric` and `os.something.metric` with SNMP collected metrics they are only stored in `os.something.metric`

For example, as windows CPU metric would live in `win.cpu` and `os.cpu`. 

A CPU metric collected via SNMP does not work this way. 

For example a Cisco switch CPU metric only lives in `os.cpu` not also in `cisco.cpu`.

**Comment by kylebrandt** [comment]
This was becuase they were gauges and os.cpu was a counter, a while back I added some functionality to scollector to turn gauges into counters, so this is fixed.
