### ISSUE TITLE
FYI Bosun and go-metrics

### ISSUE THREAD

**Issue by rbucker** [bosun-monitor/bosun#1244]
I had been trying to get [go-metrics](https://github.com/rcrowley/go-metrics) to work for a few hours.  Ultimately I posted an issue only to be told that they are forking the exporters. And as I read and reread the OpenTSDB code I realized that to did not support Bosun and the current OpenTSDB was socketed and not http+JSON. It seeme obvious to me that Bosun and go-metrics should work out of the box but I do not run that project.

Any, by way of announcement here is my code for exporting from go-metrics to bosun. [go-metrics-bosun](https://bitbucket.org/oneoffcode/go-metrics-bosun)

**Comment by kylebrandt** [comment]
I don't understand what you mean by the following:

"And as I read and reread the OpenTSDB code I realized that to did not support Bosun and the current OpenTSDB was socketed and not http+JSON"

Bosun takes HTTP/JSON as input for metric datapoints, and it takes it in the same format as OpenTSDB does...

As an aside, we also support metadata for those metrics, which is a different endpoint

**Comment by rbucker** [comment]
There are several notes but this is the most [recent](http://opentsdb.net/docs/build/html/user_guide/writing.html) that I found: 

"There are currently three main methods to get data into OpenTSDB: Telnet API, HTTP API and batch import from a file. Alternatively you can use a tool that provides OpenTSDB support, or if you're extremely adventurous, use the Java library."

However, looking at the Bosun documentation they refer to the `/api/put` URL meaning that they are supporting the HTTP API only. "Ew. Perhaps you might open a ticket with bosun requesting implementation of the telnet put service. Should be simple enough." [739](https://github.com/bosun-monitor/bosun/issues/739)

**Comment by rbucker** [comment]
Just to make one clarification.  I'm using the docker container version of Bosun.  It appears that they baked OpenTSDB into the container. (I wish they had not but oh well). Since the `docker run` command only exposes ports 4242 and 8070 you have to make due unless there is another port for the telnet payload. I know I do not know enough and I don't want to at this point. Maybe later.

**Comment by kylebrandt** [comment]
Ya, we don't support the telnet interface. The only exception is for
external collectors via scollector which print to stdout and scollector
reads and relays, but even with that JSON is the prefered method.

**Comment by rbucker** [comment]
anyway, I implemented it so now no one else has to.

**Comment by dimamedvedev** [comment]
Cool, thanks, although it seems that your repository isn't public. Am I wrong?

**Comment by rbucker** [comment]
Sorry. I have corrected that.
