### ISSUE TITLE
Bosun: /api/tagk to get all current tags across all metrics (also support basic filtering)

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1245]
We were trying to find if a current tag is used, but the API doesn't have a route to return all tags. We could use the /api/metric route to get all metrics and then call /api/tagk/{metric} but it would be better if there was a /api/tagk route that returned a list of all metrics and tags.

/api/metadata/get has the information, but also includes other metadata which makes it an expensive call. The /api/tagk route could use the same format but just exclude the extra data:

[{"Metric":"os.disk.fs.space_used","Tags":{"disk":"/opt/gitlab"}},{"Metric":"web.comment.edited","Tags":{"host":"ny-web04","role":"coreqa","site":"datascience.stackexchange.com"}},{"Metric":"elastic.indices.suggest.current","Tags":{"cluster":"StackExchangeNetwork","index_name":"careers-full-cv-candidate-search-635643440065754201"}}]

The /api/metadata/get route is also close to what we would need when you provide a query string, but ?tagk=tagname doesn't work by itself (error: "unpaired tagk/tagv") or allow globs. The ability to request /api/tagk?tagk=tagname to find all metrics using a specific tag would be very helpful.

**Comment by kylebrandt** [comment]
I'm not entirely clear on the expected result. Do you want a list of all tag keys, all tag values, or all tagk/tagv pairs?

**Comment by gbrayut** [comment]
The goal would be to find where and how the site tag is used. Values would be nice, but just knowing where a tag is used is difficult right now without pulling down the entire thing via /api/metadata/get.

**Comment by kylebrandt** [comment]
Ya, that is crazy slow due to the number of requests required. I think a route that returns all metrics and their associated tag keys makes sense. From there you can expand the values in additional requests, since the number of values is potentially quite large, whereas the metrics and their available keys will be big but I think at least sane.
