### ISSUE TITLE
Improve Error history

### ISSUE THREAD

**Issue by IzakMarais** [bosun-monitor/bosun#1261]
I have the following alert error that keeps popping up on my dashboard
![image](https://cloud.githubusercontent.com/assets/8266640/9349171/135727ea-4642-11e5-905a-e5740af2720b.png)
I closed it yesterday, but this morning it is back. However, there are some strange things about it:
* _1n-ago_ : what does this mean?
* _Full History_ : looking at the history it seems like it has been active continually for more than a month: 
![image](https://cloud.githubusercontent.com/assets/8266640/9349222/03ea2d38-4643-11e5-8bb5-eef1c566dea6.png)
* We did have backend instability problems a month ago, but these have been sorted out. Looking at the data for the last 24h, I see none of the usual error indications. From these dashboards one can see: 
  * no [HBase NSREs](https://snapshot.raintank.io/dashboard/snapshot/jBTCdN0x3F1afWi9Bddkf0Q6lwuHpYkd), 
  * [Number op OpenTSDB connections](https://snapshot.raintank.io/dashboard/snapshot/ZByvl4aBf7Tdx1z6WcT1AmG6v1z2X4Sk) seems reasonable
  * [Bosun's open file descriptors and go routine](https://snapshot.raintank.io/dashboard/snapshot/qkISBaLo48HXYdTsvVgJGWdMWHViRHxT) count look stable 
* Testing the alert in the rule Editor works fine. 

How can I debug this further?
We are using Bosun 0.1.

**Comment by IzakMarais** [comment]
OK, so the error is likely correct in indicating back-end instability.

All that could be improved is the history. In stead of showing a single event (and a continually active error state), it would be useful to actually see each occurence of the error in the Full History.

**Comment by captncraig** [comment]
@IzakMarais We totally reworked errors in #1301. It should be easier to debug and see individual failures. Let me know if you have continued suggestions or problems.

**Comment by IzakMarais** [comment]
Thanks, the new errors view is a big improvement.
