### ISSUE TITLE
Repeating "unknown" status on windows machines

### ISSUE THREAD

**Issue by rajder** [bosun-monitor/bosun#1262]
I'm getting "unknown" for many of my windows machines in randomly occurring 5-30 minute intervals. It seems that WMI related processes are spiking CPU usage during this unknown interval. Anyone else observing similar problems? BR /Anders

**Comment by gbrayut** [comment]
What version of Powershell is the system using? Please paste the output of $PSVersionTable from a Powershell prompt here. Also are you using Desired State Configuration by chance?

**Comment by rajder** [comment]
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

I have not configured or used DSC directly, I am not aware of any software on our servers that interact with DSC.

Have you observed similar issues?

**Comment by gbrayut** [comment]
We saw some issues with DSC on one of the Powershell 5.0 previews causing WMI queries to stall on a few systems. How many CPU cores do these systems have? We've seen CPU spikes on single or dual core VMs, but even then they usually are short and less than 10%.

Another thing to check is if it is just the WMI metrics or if ALL metrics go unknown. You can compare the graphs for os.cpu (based on WMI) and something like scollector.collect.sent (based on an internal counter) to see if it is just WMI metrics or all metrics. 

There are also a bunch of metrics in the scollector.* area that can help find issues (GC stats, post size/duration/errors, collector duration/errors) so digging through those might help narrow down the issue.

**Comment by rajder** [comment]
Thanks for the tips, here are some findings:
The os.cpu (and others) have long unknown periods, scollector stats do not have unknown periods.
The machines with problems have at least 8 cores and are physical machines not VMs.
This graphs bellow is of data from one of the most problematic machines:
![wmi-issues](https://cloud.githubusercontent.com/assets/3704611/9626362/5e129e74-515d-11e5-9e65-a0cf7c80728b.png)

There are tons of threads about WMI performance issues with many suggested causes and solutions, I have not found why my machines are having issues yet. The only common pattern I have found yet is that the issues get worse when the load increase, and this only applies to windows machines and the WMI-collectors.

Thank you for the help this far, I will report back if I find the actual cause of the problems.
