### ISSUE TITLE
Expression links from graph page should always be relative time

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#127]
Even though the time fields in the graph page might be absolute time. The expression link should convert that to relative time since our query functions only support relative time. Or we could let our query functions support absolute time. I think I like the latter

**Comment by gbrayut** [comment]
This still occurs in bosun. On http://goo.gl/2oLCP0 clicking expression when the graph is set for either Absolute or Relative time generates an "time: invalid duration" error.

**Comment by kylebrandt** [comment]
I find myself wishing we just supported absolute time. It is useless in alerting but useful for when trying to do "expression graphs"

**Comment by mjibson** [comment]
It is trivial to convert absolute times to a format our existing expressions can already handle. Set the end time to the second timestamp, send an empty "" for end duration, set start duration to the diff of the two timestamps. No need to rethink how we do expressions, this is just a few lines of javascript. I'll do it.

**Comment by kylebrandt** [comment]
Needs to set the time on the expr page as well so the time doesn't shift
when sharing links, but other than that sounds like it solves my immediate
the issues
