### ISSUE TITLE
Are -t and -c flags no longer supported by scollector?

### ISSUE THREAD

**Issue by kebarcla** [bosun-monitor/bosun#1276]
Hello,

I just upgraded to go 1.5 & the latest bosun and scollector. 
scollector no longer recognizes the -t and -c flags, which I used to use as:

scollector -conf="scollector.conf" -c="/usr/local/tcollector/collectors" -t=cluster=production

Do we need to specify these in some sort of conf file now?

Thanks
Ken

**Comment by captncraig** [comment]
Those are now availible via config file only. See docs at http://godoc.org/bosun.org/cmd/scollector

Namely you want the `ColDir` and `Tags` Keys.
