### ISSUE TITLE
Specifying https Host url to a receiver with self-sign certificate

### ISSUE THREAD

**Issue by rodionos** [bosun-monitor/bosun#1277]
Greetings, is it possible to configure scollector to connect to a receiving server running on a self-signed certificate? 

    Host = "https://user:password@hostname:8443/"

**Comment by gbrayut** [comment]
The Host value is parsed into a URL using https://github.com/bosun-monitor/bosun/blob/b79f6313a00cfdff5e3394dd76bce5c68709147c/cmd/scollector/main.go#L291 which should support https, credentials, and ports just fine. 

The user:password part of the URL is used for basic authentication, which is not supported directly by Bosun but can be setup using a frontend load balancer like Haproxy or nginx. The frontend would handle the authentication and SSL termination (which is also not supported directly by Bosun) and then forward the traffic to Bosun.

As for self-signed certificates, scollector doesn't do any certificate management, so the cert would need to already be added as a trusted root on the local system. You can test that the SSL and basic authentication are working using something like `curl -U user:password https://hostname:8443`. Once that test works scollector should work using the URL in your example.

If it works using curl but scollector still cannot connect, please post any error messages found in the scollector logs here and we will try and help troubleshoot.

**Comment by rodionos** [comment]
Thank you.
