### ISSUE TITLE
Rename Squlech to Filter

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1278]
Other options might be setFilter , since it filters out tagsets from *all* expressions in the alert definition. Squelch isn't a very intuitive name, so might be worth the break change.

Thoughts, other naming ideas?

**Comment by bretcope** [comment]
`exclude` or `inputFilter` would be other options.

**Comment by kylebrandt** [comment]
Decided not to care and stick with squelch
