### ISSUE TITLE
graphiteband does not work with nonNegativeDerivative

### ISSUE THREAD

**Issue by mklynx** [bosun-monitor/bosun#1284]
Good morning

I just did some testing and found the following issue.
This query works okay 

"graphiteBand("sol.web.gLogCredMgtAPI.metrics._._.*.OK.calls.count", "5m", "7d", ".....host.service",2)"

Also this works 

"graphite("nonNegativeDerivative(sol.web.gLogCredMgtAPI.metrics._._.*.OK.calls.count)", "5m", "", ".....host.service")" 

But when i try to do a nonNegativeDerivative in the graphiteBand it gives Nothing back not even Zero or NULL.

graphiteBand("nonNegativeDerivative(sol.web.gLogCredMgtAPI.metrics._._.*.OK.calls.count)", "5m", "7d", ".....host.service",2)

I have tested this with different queries and they all react the same as soon as there is a "nonNegativeDerivative" in there they fail in the graphiteBand. If i use the graphite option and check a week ago it works. So the data is there.

please check this out and if you can fix it.
Marcel Koert

**Comment by Dieterbe** [comment]
did you read http://bosun.org/expressions#graphite-query-functions, specifically the part that describes how the target strings must look like?

**Comment by mklynx** [comment]
Yes i have looked at that and nothing in that explanation say's that the nonNegativeDerivative should not work. Especially when the  graphite/GraphiteQuery call works fine.

**Comment by johnewing1** [comment]
Have you tried wrapping that graphite call in alias() so the series name has no non a-z characters in it?
