### ISSUE TITLE
lscount returns count per second ignoring bucketDuration param

### ISSUE THREAD

**Issue by alexander-chervony** [bosun-monitor/bosun#1285]
Lscount documentation: "The values of the series will be the count of log entries in 5 second buckets over the last 10 minutes." 
But it returns rather count per second (maybe average count per second for bucketDuration)
My test expression:
lscount("prod", "level", "level:error", "30s", "15m", "")

**Comment by prein** [comment]
Same here. What it does is, for example, when setting bucket to 10m it looks that it will fetch counts from particular moments in time, every 10 minutes instead of sums of counts in between those moments.

**Comment by kylebrandt** [comment]
Probably an old version? Used to be that way and it was changed.

**Comment by prein** [comment]
bosun version 0.5.0-alpha-dev (191a2410063a4ba1163ae922d86550fc3e58f36f) built 2015-11-11T16:14:12Z

**Comment by kylebrandt** [comment]
In 5.0 ls\* funcs are being deprecated in favor of the es\* functions. But those are designed to work with ES 2.0 and above. Are you at current elastic yet?

**Comment by prein** [comment]
Unfortunately we're not running ES >= 2.0 yet. We are in the upgrade preparations phase but not yet there, so I wanted to play with Bosun using the old ES and ls* functions.
