### ISSUE TITLE
cmd/scollector: disk_linux filter pseudo filesystems

### ISSUE THREAD

**Issue by dimamedvedev** [bosun-monitor/bosun#1286]
There's a function https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/disk_linux.go#L175 that calls `df -lP --block-size 1`. Is anyone interested in reporting e.g. `/run` or `/dev/shm` space stats? I have a problem with Kubernetes mounting
```
tmpfs           498M  8.0K  497M   1% /var/lib/kubelet/pods/dfcc215d-4d7d-11e5-9396-04016828c001/volumes/kubernetes.io~secret/default-token-zmjhm
```
that will  eventually pollute OpenTSDB tags. I can compile a comprehensive list of pseudo FSes or make that filter list configurable.

**Comment by kylebrandt** [comment]
Ya, it is annoying and makes the cardinality worse on something that already has a lot of tags. I'd be happy to see a PR that filters those out.
