### ISSUE TITLE
When readonly mode is specified a wrong Host header is used to query opentsdb 

### ISSUE THREAD

**Issue by davidone** [bosun-monitor/bosun#1299]
When flagReadonly is specified a relay is created to drop all /api/put actions.
This relay is listening on 127.0.0.1:random_unprivileged_port so the entire chain is:
bosun -> relay -> opentsdb (the one specified in bosun.conf config file).
Bosun passes the correct Host header when he queries the relay but when the request (i.e. /api/query) reached the opentsdb, the Host header reports the relay IP:port (i.e. Host; 127.0.0.1:57218).
This breaks things if there is a reverse proxy in front of the opentsdb checking from valid Host headers.

**Comment by gbrayut** [comment]
I believe @captncraig was looking into this issue. He posted a question to the https://groups.google.com/d/msg/golang-nuts/GxXAnc4yNQQ/iWWW2yL92yIJ Golang-nuts mailing list a few days ago but is out this week for a family matter.
