### ISSUE TITLE
Bosun API Endpoint can't handle tag values containing "/"

### ISSUE THREAD

**Issue by IzakMarais** [bosun-monitor/bosun#1305]
The Bosun API endpoint
`/api/metric/{tagk}/{tagv}`
can't handle tag values that contain the forward-slash "/". 

The "/" _is_ supported by OpenTSDB  and is a natural way to describe tag values that refer to file handles. 

I have also tried encoding the tagv by replacing "/" with %2F, to no avail.

**Comment by theunsa** [comment]
Hi, any update on this issue? Seem to have been dormant for a while so are there any simple workarounds besides replacing "/" characters in the tag value field?
