### ISSUE TITLE
Bosun Panic

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1310]
This happened in Stack's CO instance:
```
2015/09/10 16:49:20 info: alertRunner.go:56: runHistory on host.down took 56.218652ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4d0729]

goroutine 344 [running]:
os.(*Process).signal(0x0, 0x7f78ad77c078, 0xc82000e220, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:40 +0x39
os.(*Process).Signal(0x0, 0x7f78ad77c078, 0xc82000e220, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:51 +0x41
os.(*Process).kill(0x0, 0x0, 0x0)
        /usr/local/go/src/os/exec_posix.go:53 +0x45
os.(*Process).Kill(0x0, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:36 +0x2d
bosun.org/util.Command(0x2540be400, 0x0, 0x0, 0xdea150, 0x2, 0xc84777aac0, 0x4, 0x4, 0x0, 0x0, ...)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/util/command.go:53 +0x5a3
bosun.org/util.ReadCommandTimeout(0x2540be400, 0xc9ab235b20, 0x0, 0x0, 0xdea150, 0x2, 0xc84777aac0, 0x4, 0x4, 0x0, ...)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/util/command.go:69 +0xa0
bosun.org/util.ReadCommand(0xc9ab235b20, 0xdea150, 0x2, 0xc84777aac0, 0x4, 0x4, 0x0, 0x0)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/util/command.go:63 +0x8a
bosun.org/metadata.metaLinuxIfaces.func1(0x3, 0x5dc, 0xc976a9a090, 0x3, 0xc9fbd8886c, 0x6, 0x1794, 0x13, 0xc85d837080)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/metadata_linux.go:88 +0x2dd
bosun.org/metadata.metaIfaces(0xf910d0)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/ifaces.go:28 +0xa48
bosun.org/metadata.metaLinuxIfaces()
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/metadata_linux.go:89 +0x23
bosun.org/metadata.collectMetadata()
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/metadata.go:196 +0x88
created by bosun.org/metadata.Init
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/metadata.go:186 +0xc1
```

**Comment by kylebrandt** [comment]
Another one:

2015/09/14 12:47:55 info: check.go:428: check alert exceptions.internal.chat start
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4d0729]

goroutine 282 [running]:
os.(*Process).signal(0x0, 0x7fda65ad8078, 0xc82000e210, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:40 +0x39
os.(*Process).Signal(0x0, 0x7fda65ad8078, 0xc82000e210, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:51 +0x41
bosun.org/util.Command(0x2540be400, 0x0, 0x0, 0xdeb190, 0x2, 0xc903e63000, 0x4, 0x4, 0x0, 0x0, ...)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/util/command.go:50 +0x55b
bosun.org/util.ReadCommandTimeout(0x2540be400, 0xcb3dd59b20, 0x0, 0x0, 0xdeb190, 0x2, 0xc903e63000, 0x4, 0x4, 0x0, ...)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/util/command.go:69 +0xa0
bosun.org/util.ReadCommand(0xcb3dd59b20, 0xdeb190, 0x2, 0xc903e63000, 0x4, 0x4, 0x0, 0x0)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/util/command.go:63 +0x8a
bosun.org/metadata.metaLinuxIfaces.func1(0x4, 0x5dc, 0xca4f787020, 0x3, 0xca07ca4c58, 0x6, 0x13a8, 0x13, 0xc9c8f146c0)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/metadata_linux.go:88 +0x2dd
bosun.org/metadata.metaIfaces(0xf92258)
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/ifaces.go:28 +0xa48
bosun.org/metadata.metaLinuxIfaces()
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/metadata_linux.go:89 +0x23
bosun.org/metadata.collectMetadata()
        /home/teamcity/buildAgent/work/73e1f84984469e15/src/bosun.org/metadata/metadata.go:196 +0x88
created by bosun.org/metadata.Init

**Comment by dimamedvedev** [comment]
Dunnon if it's connected, but we experience following panics constantly on current master https://gist.github.com/dimamedvedev/d0776af1397732332bf5

**Comment by captncraig** [comment]
Fairly certain all of these have been addressed. If they happen again, feel free to reopen.
