### ISSUE TITLE
tsdbrelay occasionally sending non-gzipped content with gzip headers

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1312]
The following request was sent from tsdbrelay to a local opentsdb instance. The metrics were forwarded from a remote tsdbrelay instance.

(request truncated for clarity)
```
POST /api/put HTTP/1.1
Host: co-bosun:80
User-Agent: Go 1.1 package http
Content-Length: 799
Accept-Encoding: gzip
Content-Encoding: gzip
Content-Type: application/json
X-Forwarded-For: 10.8.0.231
X-Relayed-From: ny-tsdb03.ds.stackexchange.com

[{"value":30980,"timestamp":1441914070,"tags":{"host":"ny-web02","role":"careers","tier":"prod"}
```

As you can see, the request is setting a content-encoding of gzip, but it is sending plaintext data.

**Comment by gbrayut** [comment]
This should be fixed now, and we haven't seen this for a few weeks so I am closing it.
