### ISSUE TITLE
Alerting doesn't send emails to all hosts in warning/critical state

### ISSUE THREAD

**Issue by AnanthRavi** [bosun-monitor/bosun#1321]
I'm having an issue where Bosun is not sending alerts for all the hosts that are in warning/critical state. I'm using Graphite as the backend for this. 

My alert looks like this

```
alert db.cpu.high {
    template = cpu
    $d = graphite("servers.test.DB*.cpu.cpu0.idle)", "5m", "", "..host.metric.core.type")
    $q = avg($d)
    warn = $q < 10
    crit = $q <= 2
    critNotification = email
    warnNotification = email
}
```

 Say 4 hosts are in warning state, the email gets sent only for the first host.

**Comment by gbrayut** [comment]
I haven't worked with the graphite backend yet (I'll try and set it up tomorrow for testing) but when debugging notifications it often is helpful to use the `print = true` option to have it add print statements to the logs. See https://github.com/bosun-monitor/bosun/issues/1004 for  more details.

Also in the email you receive what does it show for the alert key? Is there just one host listed in the key or does it not have any host (indicating it is a global alert not per host scoped alert).

**Comment by AnanthRavi** [comment]
The log has the entry for the first host only, I used the print = true option on the notification and also decreased the timeout to 5s, didn't help. It would be great if you guys could look into this. Thanks

**Comment by AnanthRavi** [comment]
Any updates on this?

**Comment by gbrayut** [comment]
I was able to get a graphite instance setup and send some test metrics using:

```
docker run -d --name graphite --restart=always -p 81:80 -p 2003:2003 -p 8125:8125/udp hopsoft/graphite-statsd

#Send random numbers to statsd for server1
while true; do   echo -n "example.statsd.counter.server1:$(((RANDOM % 10) + 1))|c" | nc -w 1 -u bosun 8125; done
#Send random numbers to statsd for server2
while true; do   echo -n "example.statsd.counter.server2:$(((RANDOM % 10) + 1))|c" | nc -w 1 -u bosun 8125; done
```

Then use the following bosun config file for testing:

```
tsdbHost = gbcentos7:4242
influxHost = gbcentos7:8086
graphiteHost = gbcentos7:81
smtpHost = gbcentos7:25
emailFrom = bosun@localhost
httpListen = :80
timeAndDate = 202,75,179,136
stateFile = /home/gbray/go/src/bosun.org/cmd/bosun.state
checkFrequency = 1m

notification default {
    email = gbray@localhost
}

#Templates omitted
alert test{
    template = generic.graph
    $metric = graphite("stats.example.statsd.counter.*", "1h","", "....host")
    $generic_graph = $metric
    $q = last($metric)
    crit = $q > 4
    critNotification = default
}
```

Once I saved the config file and restarted bosun I could see the alert check running every minute and that it relayed the alert for both hosts

```
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 enabling syslog
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: bolt.go:118: RestoreState
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: bolt.go:231: RestoreState done in 139.061077ms
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: check.go:428: check alert test start
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: web.go:120: bosun web listening on: :80
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: web.go:121: tsdb host: gbcentos7:4242
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: check.go:449: check alert test done (38.617225ms): 2 crits, 0 warns, 0 unevaluated, 0 unknown
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: alertRunner.go:56: runHistory on test took 210.261299ms
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: notify.go:104: relayed alert test{host=server2} to [gbray@localhost] sucessfully
Sep 18 14:25:59 gbcentos7 bosun: 2015/09/18 14:25:59 info: notify.go:104: relayed alert test{host=server1} to [gbray@localhost] sucessfully
```

and the local postfix server delivered the mail to the user:

```
[root@gbcentos7 gbray]# mail
Heirloom Mail version 12.5 7/5/10.  Type ? for help.
"/var/spool/mail/gbray": 2 messages 1 unread
    1 bosun@localhost  Fri Sep 18 14:25 453/31113 "critical: test: 4.60 on server2"
>U  2 bosun@localhost  Fri Sep 18 14:25 501/34756 "critical: test: 5.70 on server1"
& delete 1
& delete 2
& quit
```

The alerts also showed on the dashboard

![image](https://cloud.githubusercontent.com/assets/304401/9970376/02272e88-5e12-11e5-89c9-f5d86a1e4165.png)

so best I can tell it is working as expected. Please note that if you are using the Rule Editor page to test sending mail it will only send one alert instance for the currently rendered template. You can change which instance is used via the template group:

![image](https://cloud.githubusercontent.com/assets/304401/9970503/bd02136c-5e12-11e5-8ee0-c905ca0f4e9a.png)

**Comment by AnanthRavi** [comment]
Thanks @gbrayut! Looks like I was trying to do this with the Rule editor which is why I was getting alerts only for the first host.
