### ISSUE TITLE
SVG generating bug

### ISSUE THREAD

**Issue by dduuch** [bosun-monitor/bosun#1325]
Hello.

I've noticed a problem with my Bosun (**0.3.0-dev**) during getting API request. I need to get a graph in SVG format to put it on my site, but it seems that Bosun creates a damaged file in API request.

My steps were:

1. Get a query to draw a proper graph:
```
filter(100 - q("sum:os.mem.percent_free{host=*}", "1h", ""), limit(sort(avg(q("sum:os.mem.percent_free{host=*}", "1h", "")), "asc"), 10))
```

2. Encode it in Base64 to insert the result in API egraph result:
```
ZmlsdGVyKDEwMCAtIHEoInN1bTpvcy5tZW0ucGVyY2VudF9mcmVle2hvc3Q9Kn0iLCAiMWgiLCAiIiksIGxpbWl0KHNvcnQoYXZnKHEoInN1bTpvcy5tZW0ucGVyY2VudF9mcmVle2hvc3Q9Kn0iLCAiMWgiLCAiIikpLCAiYXNjIiksIDEwKSk=
```

3. Make an API request to Bosun to the the graph:
```
http://10.0.0.1:69/api/egraph/ZmlsdGVyKDEwMCAtIHEoInN1bTpvcy5tZW0ucGVyY2VudF9mcmVle2hvc3Q9Kn0iLCAiMWgiLCAiIiksIGxpbWl0KHNvcnQoYXZnKHEoInN1bTpvcy5tZW0ucGVyY2VudF9mcmVle2hvc3Q9Kn0iLCAiMWgiLCAiIikpLCAiYXNjIiksIDEwKSk=.svg
```

The result is:
```
XML Parsing Error: no element found
Location: http://10.0.0.1:69/api/egraph/ZmlsdGVyKDEwMCAtIHEoInN1bTpvcy5tZW0ucGVyY2VudF9mcmVle2hvc3Q9Kn0iLCAiMWgiLCAiIiksIGxpbWl0KHNvcnQoYXZnKHEoInN1bTpvcy5tZW0ucGVyY2VudF9mcmVle2hvc3Q9Kn0iLCAiMWgiLCAiIikpLCAiYXNjIiksIDEwKSk=.svg
Line Number 13312, Column 1:
```

After examining the SVG file (dowloaded by wget) the source seems to have </svg> element missing at the end of the file. Now my question is where the problem lies? Bosun, OpenTSDB not ending its query or maybe SVGo crashes during making a SVG file?

**Comment by gbrayut** [comment]
Looks like we are missing a call to [end the svg object](https://github.com/bosun-monitor/bosun/blob/2454db52018ff3d34c84b5f0e9544c77dc96b096/_third_party/github.com/ajstarks/svgo/svg.go#L127) in [sched/chart.go ExprSVG](https://github.com/bosun-monitor/bosun/blob/2454db52018ff3d34c84b5f0e9544c77dc96b096/cmd/bosun/sched/chart.go#L50)

The only other place we use svg.new is [web/chart.go](https://github.com/bosun-monitor/bosun/blob/6f67e1e966795fdde7f65612c23869d1319cbf9e/cmd/bosun/web/chart.go#L159)

I'll create a PR to fix this. Good find!
