### ISSUE TITLE
filter(...) should also accept numberSet for first argument

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1327]
Right now filter only accepts a seriesSet for the first argument. I have alerts were I want to filter the results but cannot because they are numberSets instead of seriesSet. Filter really operates on a tag level, so we should add  filter(numberSet, numberSet) to the available functions.

example:

```
//Get all systems using a version of scollector older than 20150916205517
$version = max(q("max:scollector.version{os=windows,host=*}", "2w",""))
sort(filter($version, ($version < 20150916205517)),"asc")
//does not work because $version is a numberSet and filter requires seriesSet as the first argument

//This works, but is a bit verbose
$version = max(q("max:scollector.version{os=windows,host=*}", "2w",""))
sort(max(filter(q("max:scollector.version{os=windows,host=*}", "2w",""), ($version < 20150916205517))),"asc")
```

**Comment by kylebrandt** [comment]
What is your end goal with this? Generally it would just be `q("max:scollector.version{os=windows,host=*}", "2w","") < 20150916205517)` and you get 0 / 1 to indicate true or false.

**Comment by gbrayut** [comment]
That is hard to read on a page with 100+ results. I want to print a list of systems using an older version of scollector. Filter would do exactly what I want if it accepted numberSet instead of seriesSet. Considering the filter is done on the tags and not the set values I see no reason why it shouldnt support that.

**Comment by kylebrandt** [comment]
The expression language is not polymorphic, so this would involve reworking the expression language. This sounds like a use case for "reports", since what you want is a filtered view (like you could do in a template). Except that it is perhaps ad hoc.

We could also maybe add a "hide false" option for the expression results.

**Comment by gbrayut** [comment]
I thought we already had functions that worked on both types of sets, but I think I was remembering the scalar -> numberSets promotion stuff. This isn't a pressing need since there is a workaround in this case, but I think having a filter that works on numberSets would make for cleaner alerts (see examples above) even if it is a different function like filterNumberSet().

Right now I often end up with complex expressions or complicated "if and eq .. eq ..." statements in templates because we are missing what seem to be simple functions (or have mismatched types like this example). I am trying to start filing these as issues for tracking, as if we can add a few functions to simplify common expressions it will make things easier to read.

**Comment by gbrayut** [comment]
It may just be my SQL background, but even the shortest version of that expression I can currently create looks very non-intuitive when compared to the first example above:
```
$version = q("max:scollector.version{os=windows,host=*}", "2w","")
sort(max(filter($version, (max($version) < 20150916205517))),"asc")
```

**Comment by kylebrandt** [comment]
Why is it better to have it in the expression language instead of as a template function? filter is particular for limiting series for graphing. It generally wouldn't be good to use in alert defs I don't think because one would likely end up with unjoined groups.

**Comment by gbrayut** [comment]
I get more control using expressions and they can be used in more places. I'd love both, since you are right that often expressions are more generalized, but if I only get one I'd usually rather have a clean expression and minimal template than do a lot of data manipulations using the go/bosun templates.

In this case I was using the expression page for reporting, and a hide false button would also have worked. But the point is having it as an expression solves all of those cases, and potential future ones like grafana sourcing directly from bosun.
