### ISSUE TITLE
Graphite query with basic auth

### ISSUE THREAD

**Issue by eMerzh** [bosun-monitor/bosun#1349]
i've set up bosun with 
 graphiteHost to smth like "https://user:pass@myhost/render" 
but it seems to still have a 401.... 

my logs says 
```graphite RequestError (https://myhost/render?format=json&from=1443166442): Get failed: 401 Authorization Required```

it seems that somewhere it drop the auth part.

**Comment by vgatto** [comment]
This still doesn't work for me.  The pull request looks like it only copies the user from the parsed url and not the password.
