### ISSUE TITLE
Logstash plugin doesn't support alternate date formats

### ISSUE THREAD

**Issue by aodj** [bosun-monitor/bosun#1354]
The Logstash plugin can only support dates in the format [YYYY.MM.dd](https://github.com/bosun-monitor/bosun/blob/f7a0673f3e5edc9e2176c6b9b2c8ef52a009951d/cmd/bosun/expr/logstash.go#L145) (ie: period separated values) which means, if you've got indexes that are separated with hyphens (for example: YYYY-MM-dd) the only way to access them is using the trailing slash approach

**Comment by kylebrandt** [comment]
I wouldn't want an additional argument to the function, but it could be a conf setting to change the delimiter.

**Comment by aodj** [comment]
In my particular case, I've got some ElasticSearch indexes that are period separated, and others that are separated with a hyphen.

**Comment by kylebrandt** [comment]
You could make a config option that takes a map such that the base name is pared with different delimiters.

**Comment by kylebrandt** [comment]
Also, curious why you have mixed date formats? Are you using products that are outside of your control? Having a consistent format would seem desirable.

**Comment by aodj** [comment]
An unfortunate result of having different people setting up different systems.
