### ISSUE TITLE
"notification post" body is missing

### ISSUE THREAD

**Issue by madshall** [bosun-monitor/bosun#1355]
I'd like the template's `body` to be posted elsewhere via HTTP POST request. The post request works by itself, however template's `subject` is sent instead of or along with `body`. When I remove body from the template and set subject to '``{{.Alert.Vars.measurement}}.alerts,name={{.Alert.Name}},server={{.Group.server}},warning={{.Eval .Alert.Vars.isWarn}},critical={{.Eval .Alert.Vars.isCrit}},warnVal={{.Alert.Vars.warnValue}},critVal={{.Alert.Vars.critValue}} value={{.Eval .Alert.Vars.average}} {{.Last.Time.Unix}}000``' everything looks great, except the Bosun UI where alerts' names are replaced with all that post data.

```
notification post {
	post = http://localhost:8086/write?db=sam&precision=ms
	print = true
}

template postdata {
	body = {{.Alert.Vars.measurement}}.alerts,name={{.Alert.Name}},server={{.Group.server}},warning={{.Eval .Alert.Vars.isWarn}},critical={{.Eval .Alert.Vars.isCrit}},warnVal={{.Alert.Vars.warnValue}},critVal={{.Alert.Vars.critValue}} value={{.Eval .Alert.Vars.average}} {{.Last.Time.Unix}}000
	subject = Alert!!!
}
```

**Comment by ayashjorden** [comment]
@madshall looks like #1096 ?
:)

**Comment by kylebrandt** [comment]
closing as dupe
