### ISSUE TITLE
Scollector: ms.GCCPUFraction undefined fatal error

### ISSUE THREAD

**Issue by evgeny-potapov** [bosun-monitor/bosun#1360]
When running chef-client after adding recipe 'scollector' I get an error which is the following:

```
/usr/local/go/bin/go get -v bosun.org/cmd/scollector # called by recipe
bosun.org/collect
# bosun.org/collect
/opt/go/src/bosun.org/collect/collect.go:151: ms.GCCPUFraction undefined (type runtime.MemStats has no field or method GCCPUFraction)
```
So installation failed.
When I remove the call ms.GCCPUFraction with everything is ok, but this change is difficult to automate.

OS: Ubuntu 14.04, RHEL 6.4.

**Comment by gbrayut** [comment]
Building scollector requires that you have go 1.5 installed. That error usually means you are using an older version of go.
