### ISSUE TITLE
Error in expression page when defining var

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1363]
![image](https://cloud.githubusercontent.com/assets/218431/10226715/9f8e8fc4-6815-11e5-912a-0a86201bb578.png)

**Comment by captncraig** [comment]
The last line of your input is always interpreted as a standalone expression. A single variable declaration is not a valid input. Perhaps it should give a more sensible message here. 

adding $netbytes below your declaration should let it work

**Comment by alienth** [comment]
@kylebrandt  asked to leave this open, as it is more of a usability / error message clarity issue.
