### ISSUE TITLE
MySQL collector

### ISSUE THREAD

**Issue by krutaw** [bosun-monitor/bosun#1371]
Perhaps I'm just missing it, but has anyone put any thought into creating a MySQL collector to collect performance statistics?

**Comment by vitorboschi** [comment]
There is no such collector for scollector yet, however it's fully compatible with tcollector external collector scheme, so you can use [the one](https://github.com/OpenTSDB/tcollector/blob/master/collectors/0/mysql.py) from scollector until someone integrates it.

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/pull/1391

**Comment by tdinucci** [comment]
See comments in linked PR - this wasn't considered a good idea
