### ISSUE TITLE
[Windows] [64-bit] scollector not running external scripts

### ISSUE THREAD

**Issue by Stolson** [bosun-monitor/bosun#1373]
Scollector is not running external scripts with the Windows 64-bit build. Go's os/exec pacakge changed a bit, and instead of collecting the stdout and err with Pipewriter, should use:

stdout, err := cmd.Output()

Not sure how this affects the Linux build (if at all), but wanted to bring this to attention. Currently get the error "%1 is not a valid Win32 application" error on debug mode for each Python/Powershell script.

**Comment by HuiyingLi** [comment]
Scollector under windows appears only to run '.exe' files and ignores things like python scripts that could be run through an interpreter.

**Comment by captncraig** [comment]
Almost, it actually takes a list of extensions from the PATHEXT envrionment variable which by default is `.COM;.EXE;.BAT;.CMD`. You could make a batch script, or else add your extension to that variable.

See http://environmentvariables.org/PathExt

**Comment by SteveOlson05** [comment]
That bug occurs with scripts that are enabled by the PATHEXT environment variable, especially Python and Powershell scripts. I'm wondering if it's trying to run them as a 32-bit command (even though my Python installation and scollector are 64-bit?)
