### ISSUE TITLE
Delay in data

### ISSUE THREAD

**Issue by krutaw** [bosun-monitor/bosun#1384]
I could be completely missing something, but there appears to be a 20-30 minute delay in data being available within Bosun (and OpenTSDB for that matter.) Did I miss a configuration setting somewhere?

**Comment by gbrayut** [comment]
Might be related to time zones. Bosun and scollector assume UTC for everything.

Otherwise you will need to look at the scollector/bosun logs and the scollector.* / bosun.* metrics to see what is happening.
