### ISSUE TITLE
Question about Scollector channels being passed to each collector

### ISSUE THREAD

**Issue by MichaelS11** [bosun-monitor/bosun#1385]
In the collectors.go under Run, there is ch and quit passed to every collector:

ch := make(chan *opentsdb.DataPoint)
quit := make(chan struct{})
....
go c.Run(ch, quit)

instead of passing it to each collector, would it be alright to have something like the below in collectors.go?

var CollectorVars struct {
	dpChan                chan *opentsdb.DataPoint
	quit                  chan make(chan struct{})
}

Or is there a reason it should be passed to each one?

**Comment by captncraig** [comment]
What problem does it create? The purpose of the quit chan is so that when scollector receives an interrupt, collectors can finish gracefully and scollector can flush its remaining datapoints to the db. There are only a few collectors that implement the Run method, as most of them rely on IntervalColelctor. 

Certainly your solution would work, but I don't see the point in making a parameter struct for only two parameters. What problem are you hoping to solve? A quit channel is a fairly common pattern in go programs.

**Comment by MichaelS11** [comment]
Most of it coding style and preferences. If you prefer not to have the struct, that is all good.

The main question was is there a reason why it has to be passed around instead of making a common variable? If there was not a reason for passing it around, seems like it might be "nice" to have a common variable. Less passing around the same variable. No big deal either way, just was curious.

**Comment by captncraig** [comment]
Basically, the collectors package is really big, and without a good way to parcel it up into smaller packages, I want to be careful about how many items we add to the package scope. If you feel there are improvements to be made I'm happy to look at a pr.

**Comment by MichaelS11** [comment]
@captncraig 

The idea for talking about it here instead of putting in a pull request is that it would take some work to make the change. Not reason to do all that work if it was not something you wanted.

**Comment by captncraig** [comment]
gotcha. The other reason I like it as an explicit argument, is that anybody who implements a new collector is forced to consider graceful shutdown. Making them write out an argument at least makes it cross their mind that a quit can be triggered externally. 

Again, almost all of the built in collectors use IntervalCollector, who is really the only one who needs to know about the quit stuff.

**Comment by MichaelS11** [comment]
Ok, sounds good :)
