### ISSUE TITLE
Reduce Grouping on the Dashboard

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1387]
Currently the dashboard groups alerts based on alert name, state, tagsets etc. This grouping can be helpful if this a big group of alerts, but often it nests important alerts a level deep on the dashboard which makes them more likely to be missed.

Short of rethinking the dashboard, I think we should have a grouping threshold for alerts. That way alerts don't get grouped unless the groups has at least N members. This way we still get some protection against alert bursts, but we don't rely on the feature, and are still encouraged to scope alerts to an accurate tagset / group.

**Comment by captncraig** [comment]
Complete.
