### ISSUE TITLE
Can someone share dev.conf for bosun and let me know its location.

### ISSUE THREAD

**Issue by RamyaBineesh** [bosun-monitor/bosun#1395]
Getting following error when trying to start bosun in my system.

./w.sh 
(RE)STARTING BOSUN
2015/10/09 15:33:09 fatal: main.go:88: open dev.conf: no such file or directory
exit status 1

**Comment by gbrayut** [comment]
There is an example file at https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/dev.sample.conf but you will need to edit the host and port sections and then save it as dev.conf in the cmd/bosun folder
