### ISSUE TITLE
Unable to start bosun with w.sh

### ISSUE THREAD

**Issue by RamyaBineesh** [bosun-monitor/bosun#1396]
We are getting following error when trying to start bosun with w.sh.
Can someone help to resolve the issue?

$./bosun-master/cmd/bosun/w.sh 
(RE)STARTING BOSUN
2015/10/13 16:19:18 info: bolt.go:136: RestoreState
2015/10/13 16:19:18 error: bolt.go:147: notifications unknown bucket: bindata
2015/10/13 16:19:18 error: bolt.go:150: silence unknown bucket: bindata
2015/10/13 16:19:18 error: bolt.go:153: incidents unknown bucket: bindata
2015/10/13 16:19:18 error: bolt.go:156: errors unknown bucket: bindata
2015/10/13 16:19:18 error: bolt.go:167: status unknown bucket: bindata
2015/10/13 16:19:18 info: bolt.go:227: RestoreState done in 151.7µs
2015/10/13 16:19:18 info: web.go:61: using local web assets
2015/10/13 16:19:18 info: check.go:486: check alert example.opentsdb.cpu.lookup start
2015/10/13 16:19:18 info: notify.go:96: quiet mode prevented 0 notifications
2015/10/13 16:19:18 info: check.go:486: check alert example.opentsdb.os.high.cpu start
2015/10/13 16:19:18 info: web.go:124: bosun web listening on: :8070
2015/10/13 16:19:18 info: web.go:125: tsdb host: localhost:4242
2015/10/13 16:19:18 info: check.go:510: check alert example.opentsdb.cpu.lookup done (2.035402ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2015/10/13 16:19:18 info: alertRunner.go:56: runHistory on example.opentsdb.cpu.lookup took 2.762µs
2015/10/13 16:19:18 fatal: main.go:192: too many open files

**Comment by kylebrandt** [comment]
Sorry looks like we missed this one. I'm assuming the issue is to old now, but reopen if we can still be of help.

Apologies,
Kyle
