### ISSUE TITLE
Error: no metadata for sum:<metric key>: cannot use auto rate

### ISSUE THREAD

**Issue by digrich** [bosun-monitor/bosun#1397]
I have recently started using bosun and relaying OpenTSDB metrics through bosun but getting the following error for all non Scollector metrics.

"no metadata for sum:<metric key>: cannot use auto rate", while accessing the graph on browser.

How to add metadata for custom metrics?  I am posting the same data as I was submitting to OpenTSDB before bosun.

**Comment by kylebrandt** [comment]
This is done via `/api/metadata/put` which is documented in http://bosun.org/api.html#metadata

You can also just manually select if it is a gauge or a counter in the graph UI's "Series Type" field.

**Comment by digrich** [comment]
Thanks @kylebrandt
