### ISSUE TITLE
scollector on windows 2008 32bit keeps outputing this message:

### ISSUE THREAD

**Issue by samahee** [bosun-monitor/bosun#1400]
2015/10/19 21:49:45 error: queue.go:102: json: error calling MarshalJSON for type *opentsdb.DataPoint: cleaning key : clean result is empty
2015/10/19 21:49:45 info: queue.go:121: restored 6, sleeping 5s
2015/10/19 21:49:50 error: queue.go:102: json: error calling MarshalJSON for type *opentsdb.DataPoint: cleaning key : clean result is empty
2015/10/19 21:49:50 info: queue.go:121: restored 6, sleeping 5s
2015/10/19 21:49:55 error: queue.go:102: json: error calling MarshalJSON for type *opentsdb.DataPoint: cleaning key : clean result is empty
2015/10/19 21:49:55 info: queue.go:121: restored 33, sleeping 5s
2015/10/19 21:50:00 error: queue.go:102: json: error calling MarshalJSON for type *opentsdb.DataPoint: cleaning key : clean result is empty
2015/10/19 21:50:00 info: queue.go:121: restored 472, sleeping 5s
2015/10/19 21:50:05 error: queue.go:102: json: error calling MarshalJSON for type *opentsdb.DataPoint: cleaning key : clean result is empty
2015/10/19 21:50:05 info: queue.go:121: restored 500, sleeping 5s

**Comment by samahee** [comment]
and cpu100% hit!

**Comment by captncraig** [comment]
This happens when either a tag key or tag value consist only of non-valid opentsdb characters. That message is entirely unhelpful isn't it. Some extra debugging information in that log would certainly help narrow down which collector is causing it.

**Comment by kylebrandt** [comment]
clean was improved for better error reporting
