### ISSUE TITLE
cant get slack invite

### ISSUE THREAD

**Issue by dprime** [bosun-monitor/bosun#1401]
Hi,

The auto invite for the slack chatroom does not appear to be working. I'm trying to troubleshoot a complex query and there's no one to talk to :(

http://bosun.org/slackInvite  is the invite url

This might not be the perfect place to raise this but since there does not seem any other way to contact the bosun team except via the slack channel, this will have to do.

**Comment by captncraig** [comment]
I sent you an invite by hand. Looks like maybe something broke with the undocumented slack apis that was relying on. Looking into it.
