### ISSUE TITLE
Multiple backends of the same type?

### ISSUE THREAD

**Issue by aodj** [bosun-monitor/bosun#1404]
Is it possible to have multiple instances of the same type of backends? for example multiple InfluxDB backends or multiple ElasticSearch backends? I ask because I'm trying to pull in data from two separate instances but simply creating a duplicate key results in a config error:
`fatal: main.go:88: conf: bosun.config:2:0: at <influxHost = xx.xx.x...>: duplicate key: influxHost`

**Comment by Dieterbe** [comment]
currently not possible, but would be nice to have for sure.
we need to rethink the backends to be more pluggable/modular anyway.

**Comment by captncraig** [comment]
Would you want to use multiple sources within the same alert, or just on the same bosun host? 

Initial thoughts are that we would add "named" datasources. Perhaps

```
influxHost = xx.xx.xx.xx #default
influxHost[db2] = yy.yy.yy.yy
#or maybe
influxHost = [db2]yy.yy.yy.yy
```

I don't like any of that syntax super much, but that is the idea.

For expressions, there may need to be overloaded functions that take the datasource. 

```
influxHost("db2","mydb","query","","")
#or maybe in influx's case we could reuse the database field:
influx("db2:mydb","query","","")
```

just a few thoughts. I like the idea, but it would take a bit of thought and effort.

**Comment by aodj** [comment]
I'm not entirely sure; Grafana allows you to define any number of data sources and then you just choose them from the drop down, or choose `-- Mixed --` and specify them in each query in turn.

**Comment by lpalm** [comment]
+1
For our use case, being able to set a per-alert influxHost (defaulting to the global if unspecified) would be sufficient. Per query as proposed by captncraig might be more flexible/useful in the long run, though.

**Comment by kylebrandt** [comment]
I'm interested in more user stories about why there are multiple time series database engines of the same type in their setups tied to the same bosun instance.

Problems with support multiple:
 - Function signatures all change, so a pretty big breaking change
 - An extra argument has been added to the function, that from what I have gathered so far is rarely needed.

**Comment by lpalm** [comment]
We collect high volumes of data from data centers all over the world. We'd like to monitor them all. It would be impractical to ship the entirety of that data to a centralized database for many reasons:
- We'd like to not have a SPoF
- Links between remote regions may have limited bandwidth
- We'd like to keep that data local for other processing anyway

In theory we could run Bosun next to every database, but that adds a maintenance burden for N extra Bosun instances, as well as needing N configuration files and the infrastructure to push these files and restart the correct Bosun on updates.

If signature changes are unwanted, perhaps we could just let users reset the host variable and any expressions below it will use the latest assigned host?

**Comment by kylebrandt** [comment]
Sounds like a pretty solid use case to me - thanks for that. With influx I like:

influx("db2:mydb","query","","")

The same thing could be done with elastic. Not sure with Graphite and OpenTSDB. Maybe we should just change influx for now to solve lpalms problem, since we already specify the DB on those anyways, just make host:db

**Comment by vitorboschi** [comment]
> Function signatures all change, so a pretty big breaking change
> An extra argument has been added to the function, that from what I have gathered so far is rarely needed.

A good solution for both would be to improve the language and add support for optional parameters

**Comment by kylebrandt** [comment]
Optional Parameters being an improvement is debatable, and also would be quite an investment to implement. Do we use keywords, or do optional things go at the end? Or at they assumed positional unless keywords are specified etc.

I don't think the return is there since most params are usually needed, a lot of work to do, and if we use keywords things get long fast.

**Comment by vitorboschi** [comment]
I was thinking in optional parameters only at the end here, and there are at least 2 cases in which an optional parameter would help:
- this case (defaults to the first server?)
- end date on several functions (defaults to empty string)

I can't comment on the work needed to get this working and I agree it's something that should get a low priority in Bosun, but it's a way to avoid breaking compatibility when adding support for multiple backends of the same type

**Comment by Dieterbe** [comment]
how about all query functions get a new arg (let's say at pos 0) denoting the datasource (each datasource always being explicitly named, like "my_influx_in_us-east" or whatever). but you could give your datasource a key consisting of 1 character if you wanted to, maybe call it "d". to make it less annoying for people who only have 1 datasource.
we could write a script that auto converts your bosun config by adding a new argument value to denote the datasource by name, for people upgrading.  seems simpler than trying to accomodate the transition with code complexity in bosun itself.

**Comment by kylebrandt** [comment]
Regardless of any syntax, I'm trying to picture what alerts look like in this case? Generally we have something like a single alert for say cpu utilization that applies to all hosts. Would you duplicate the alerts for different sites? 

Having a clearer picture of what it will look like I think will help figure out the right way to do this.

Another more complicated option that I'm thinking about is just having queries sent to N backends, and then the response merged into a single result. This would assume no data conflicts. 

Another thing to consider with having a model like this is that the time series dbs is that you will lose DB level operations across datacenters.

**Comment by Dieterbe** [comment]
> that you will lose DB level operations across datacenters

What do you mean with this?

**Comment by Dieterbe** [comment]
> Would you duplicate the alerts for different sites? 

potentially, maybe could also specify a pattern like `opentsdb-*` and it would query all your datasources that have a prefix `opentsdb-`

**Comment by lpalm** [comment]
As a datapoint, we have use cases for both approaches - running the same alert/query over many influx backends, and having different alerts on different backends. Some sort of a glob/loop for the duplicated alerts as mentioned by Dieterbe would be great to avoid copying/pasting dozens of alerts.

**Comment by gbrayut** [comment]
> We'd like to not have a SPoF
> Links between remote regions may have limited bandwidth
> We'd like to keep that data local for other processing anyway

My concern is the three arguments you have for not centralizing the data also apply to not centralizing bosun. We run a separate bosun instance in our DR site specifically so that we still have access to it when the primary is offline. We do replicate the data to both DCs, mainly so we can unify the alerts and have a full backup if the primary is lost.

Not saying we shouldn't support multiple backends, but I'm not convinced it would be the best approach.

**Comment by captncraig** [comment]
One thing I could see is not for DR purposes, but if they have a sharded data architecture. If different application teams all have their own tsdb instance, and the network has another, etc..

Then each particular alert may need to pull from a different data source. But each query knows exactly which one it needs.

**Comment by kylebrandt** [comment]
I was considering that as well, but they are two different user stories
really. That is more about multi-tenancy - which people are interested in.
We should be careful not to conflate the two even if they have overlapping
features for implementation.

**Comment by kylebrandt** [comment]
Quick rough thought on how we might do this:

You can declare multiple backends with an alias to them. As soon as you do, the signature of all query funcs related to that backend gets a new prepended argument that is the backend.

This means different people's config's will have different signatures for the same function, but the signature is still hardcoded - it just depends on the "mode". People with multiple backends get to use them and would have to name them anyways. People without multiple backends don't have the extra text.

I'm not sure I'm wild about this idea myself, but wanted to capture it while it popped into my head.

**Comment by gbrayut** [comment]
More options we thru out in SRE chat (just for tracking, not something we plan on implementing any time soon):

q[instance2]("whatever"...

q("instanceName$realquery")?

a TSQL like "using xyz" syntax might also work, maybe in a functional form using("xyz", q(...))

I kind of like the q("instanceName$realquery") option where we extend the OpenTSDB query syntax and prepend the backend alias. It would be great if there was a "canonical" way to do that (supported by OpenTSDB itself). We should also see what the vNext changes are for supporting InfluxDB like functions.

**Comment by kylebrandt** [comment]
I'm also kind of fun of the using idea, I just don't know how we would do it. Since things are evaluated inside to the outside, using would be strange because it alters the behavior of the function that is enclosed within it.

The bracket syntax is also interesting, I like that you could omit it to have a default. That will require changes in both the lexer and the parser.

**Comment by Dieterbe** [comment]
the using form is also a bit too verbose IMHO. the `[]` could work but really it's just a workaround for allowing 1 optional argument.  let's hope we don't run into another use case for optional args, what will we do then? `q{foobar}[instance](fixed, args)` ?
For graphite at least it would be nice to be able to optionally specify a "max points to return" (in graphite this is a separate arg to be passed, next to the query). i suppose we could also patch the query format and so `query:maxpoints` in accordance with opentsdb but that just looks a bit weird.
not sure if anyone can think of other things we may want optional arguments for?

**Comment by kylebrandt** [comment]
Optional args would have to be positional at the end (unless we want to go down the keyword pythony path), and then what if you want vargs at the end of something that takes different backends? So I don't think it is as straight forward as supporting optional args.

I'm not against optional args, just not sure we want to have to add another argument (optional or not) to every query func since they won't mix with vargs well that I can see right now.

So with the [foo]func idea I don't see it as a workaround to avoid supporting optional args, but rather something specific to query functions that would be common to all of them.

**Comment by kylebrandt** [comment]
I'm not familiar with the graphite use case you mention. But another option is always to have additional functions that take that extra param when you want it. I guess it depends on the frequency of use.

**Comment by pradeepbbl** [comment]
We want this feature to support multiple elasticsearch clusters, So we will be doing code changes to https://github.com/bosun-monitor/bosun/pull/1947

**Comment by kylebrandt** [comment]
@pradeepbbl what are you thinking as far as what the user facing functions will look like?

**Comment by pradeepbbl** [comment]
@kylebrandt we are thinking creating a map of ElasticConf.Hosts example mentioned below

[ElasticConf]
	[ElasticConf.Hosts]
            default = "http://ny-lselastic01.example.com:9200"
            host01  = "http://ny-lselastic02.example.com:9200"

and by default set the endpoint to `default` host and create a new function in expr/elastic.go which will set host depend on user config something like e.g

alert bosun_error {
    $instance = esinstance("host01")
    $index = esindices("@timestamp", "*-bosun-logs-*")
    $filter = esand(esquery("alert_state", "Null"), esregexp("msg_text", ".*error\\:.*"))
    crit = max(escount($instance, $index, "msg_text", $filter, "1h", "30m", "")) > 3
}

let us know your thoughts

**Comment by kylebrandt** [comment]
@pradeepbbl I think I'd like to see a new syntax outside of the function arguments. 

```
[host01]escount("foo")
```

Reasons:

- Doesn't break existing function signatures
- Can be universal for all TSDB providers (i.e. influx, opentsdb, etc)

**Comment by kylebrandt** [comment]
Also note that the host server will need to become part of the cache key for queries. I made the mistake of not taking that into account when support for multiple indices was added. If you don't identical requests to different servers will be considered the same.

**Comment by kylebrandt** [comment]
so https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/expr/parse/parse.go#L248 

```
Func -> name "(" param {"," param} ")"
```

would be something like

```
Func -> name "(" param {"," param} ")" | "[" prefix "]" name "(" param {"," param} ")"
```

**Comment by pradeepbbl** [comment]
27852aa
