### ISSUE TITLE
Network Graph on Host item Page mislabeled

### ISSUE THREAD

**Issue by GABeech** [bosun-monitor/bosun#1410]
The network graph on host item pages are mislabeled. They are labeled as **bits** per second, when the metric is **bytes** per second.

See attached screenshot.
![bosun_bit_byte](https://cloud.githubusercontent.com/assets/945425/10643692/2f41e800-77f2-11e5-8283-292819929166.png)

**Comment by kylebrandt** [comment]
There is a transformation that turns it to bits, but then the metric label
looks others. I used to have the label just say the direction. So
regression to fix there.

**Comment by GABeech** [comment]
We should not be doing a transform that is not possible to do on the other graphing areas. Either everything in the system should be in **bytes** or everything in the system should be in **bits** we need to pick one and stick with it, otherwise you cause confusion when transitioning between different parts of the interface. 

Since currently there is no way to transform on the graphing page, or no way to do it easily we should just use **bytes** everywhere to avoid confusion.
