### ISSUE TITLE
Installable package

### ISSUE THREAD

**Issue by floyd-may** [bosun-monitor/bosun#1411]
It would be fantastic if there were an installable package (my interest would be a .deb package) with init.d scripts set up so that I can install, configure, and run bosun on vanilla Ubuntu (e.g.) without needing to set up something like [supervisor](http://supervisord.org/) to ensure that bosun is running.

**Comment by gbrayut** [comment]
At this time we plan on leaving packaging up to the end users, but if you find or create packages we would be happy to provide links to them from the http://bosun.org/resources page or download pages.

**Comment by syndicut** [comment]
Just in case you are interested - I build a quick and dirty debian source package, which can be used to build binary packages - https://github.com/syndicut/bosun-deb. In fact, I tried to build it from go source, but failed, so I decided just to use prebuilded binaries, which are downloaded at build time from github.

**Comment by syndicut** [comment]
https://github.com/syndicut/bosun-deb/releases/tag/0.4.0%2B42187e2 - setup a travis CI build for packages
