### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by krutaw** [bosun-monitor/bosun#1423]
The documentation site is down.

**Comment by captncraig** [comment]
http://bosun.org/ works for me. Maybe its up again? Were you trying a different url?

**Comment by vitorboschi** [comment]
Working fine here, however I've seen some issues yesterday. The page was being served with an alert from cloudfare saying that the website was down, but they were serving a mirror 'till the site was back up.

**Comment by gbrayut** [comment]
Github was having some issues: https://status.github.com/messages

**Comment by gbrayut** [comment]
Ah... do you mean https://godoc.org/bosun.org/cmd/scollector

That probably is broken due to the github/canonical import issue @captncraig was working on.

**Comment by krutaw** [comment]
Yeah, sorry, I should have been more precise.  Yes, it's the scollector documentation site that is down.

**Comment by gbrayut** [comment]
This should be fixed now
