### ISSUE TITLE
Cannot clear silences

### ISSUE THREAD

**Issue by cedw93** [bosun-monitor/bosun#1424]
When attempting to clear silences from the list of active silences the following error is thrown:

```
json: cannot unmarshal number into Go value of type string
```

Example of silence screen, click clear -> ok

![screen shot 2015-10-27 at 16 52 59](https://cloud.githubusercontent.com/assets/5663935/10766547/fb2d993c-7ccf-11e5-91e2-b4e3e4ad395e.png)

error message in bosun

![screenshot 2015-10-27 16 54 52](https://cloud.githubusercontent.com/assets/5663935/10766533/e722712e-7ccf-11e5-9d0d-ebd30eff7d12.png)

payload:

![screen shot 2015-10-27 at 17 25 09](https://cloud.githubusercontent.com/assets/5663935/10766568/123c3a3e-7cd0-11e5-84bf-39137da38d37.png)

Some more request data:

![screenshot 2015-10-27 17 28 59](https://cloud.githubusercontent.com/assets/5663935/10766615/3d9ae09a-7cd0-11e5-9811-43f8c32e77b8.png)

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/issues/1150
