### ISSUE TITLE
Route /api/templates returns 404

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1427]
As the title says. Tested in 0.4.0

**Comment by captncraig** [comment]
This route was removed in April with commit 6fc1bfc074eb03cb5bfe760c55a1d03a5a639065. It has been superseded by `/api/config` which returns the raw config text. This was all a part of the big rule/config page reworking. Is it still in the docs somewhere?

**Comment by vitorboschi** [comment]
yes, it is in http://bosun.org/api

**Comment by tdinucci** [comment]
This looks to have been done
