### ISSUE TITLE
LSQuery/LSQueryAll functions are not sorted and have no option to do so

### ISSUE THREAD

**Issue by awesensepaul** [bosun-monitor/bosun#1428]
The `@timestamp` field is already hard-coded in the query building for the user-specified time range. Seems reasonable to add an option to sort by `@timestamp` field by default, or (ideally) sort by a user-specified field.

**Comment by awesensepaul** [comment]
Any response to this?

**Comment by awesensepaul** [comment]
Still seeing this behaviour with the new `ESQuery` / `ESQueryAll`. Still frustrating and unintuitive. Any response to this?

**Comment by kylebrandt** [comment]
Can you show the ESQuery you are using? The esdaily function returns an "indexer": ` esdaily (timeField string, indexRoot string, layout string) ESIndexer`. So you should be able to set the timeField to anything.

**Comment by awesensepaul** [comment]
Certainly:
```
macro log_based_alert_macro {
  # skip the bosun dashboard
  log = true
  # only send log alerts this often
  maxLogFrequency = 1h
  # never go unknown (no way to 'close'?)
  ignoreUnknown = true

  template = generic_alert_template

  $index = esls("rsyslog")
  crit = max(escount($index, "host,unit", $crit_query, "5m", "5m", "")) > 0
  warn = max(escount($index, "host,unit", $warn_query, "5m", "5m", "")) > 0

  critNotification = $notification_list
  warnNotification = $notification_list
}
alert all_errors {
  $crit_query = esand(esquery("severity", "err"), esquery("message", '''<snip>''))
  $warn_query = esand(esquery("severity", "warning"), esquery("message", '''<snip>'''))

  $notification_list = alerts_slack,alerts_email

  macro = log_based_alert_macro
}
```
and in the template:
```
<snip>
    {{ $index := (.Eval .Alert.Vars.index) }}
    {{ $filter_err := (.Eval .Alert.Vars.crit_query) }}
    {{ range $v := .ESQuery $index $filter_err "5m" "0m" 25 }}
      {{ $timestampStr := index $v "@timestamp" }}
      {{ $timestampNoTZ := replace $timestampStr "+00:00" "" -1 }}
      {{ $timestamp := replace $timestampNoTZ "T" " " -1 }}
      <tr>
        <td>{{ $timestamp }}</td>
        <td>{{ $v.unit }}</td>
        <td>{{ $v.severity }}</td>
        <td class="{{ $v.severity }}">{{ $v.message }}</td>
      </tr>
    {{ end }}
<snip>
```

Hope this helps! (please ask if you'd like more, or if you'd like to know what got `<snip>`'d.

**Comment by awesensepaul** [comment]
I do get the expected limit of 25 results returned from the correct index, but the result rows themselves (when iterated) are in what seems like a random order.

**Comment by kylebrandt** [comment]
Right, so you are currently using esls for the index at `$index = esls("rsyslog")`:

> ### esls(indexRoot string) ESIndexer
> esls is a shortcut for `esdaily("@timestamp", indexRoot+"-", "2006.01.02")` and is for the default daily format that logstash creates.

So instead you can use:

> ### esdaily (timeField string, indexRoot string, layout string) ESIndexer
> 
> esdaily is for elastic indexes that have a date name for each day. Based on the timeframe of the enclosing es function (i.e. esstat and escount) to generate which indexes should be included in the query. It gets all indexes and won't include indices that don't exist. The layout specifer uses's [Go's time specification format](https://golang.org/pkg/time/#Parse). The timeField is the name of the field in elastic that contains timestamps for the documents.

**Comment by kylebrandt** [comment]
Oh, I see. This isn't about which field, but rather sorting in the template. I misunderstood.

**Comment by awesensepaul** [comment]
Yup that's correct. The indexes look good, it always uses the right one. I think a sort clause needs to be added to the underlying ES query(?), but I'm not sure where to make that modification.

For us, if we have multiple lines (e.g. a stacktrace) they end up all out-of-order (and this happens over several seconds, not just a limit of the millisecond resolution that ES uses for timestamps.)

**Comment by kylebrandt** [comment]
Okay I will think on that. Currently the ESQuery functions are returning a slice of interface. Ideally that could just be passed to a sort filter in the template. 

But no generics, so will need to figure out how to do that. Since normally in Go you would make different sortable types.

**Comment by awesensepaul** [comment]
In fact, I would actually prefer a sort in Go (vs in the underlying ES query) since ES only sorts with millisecond precision even though our timestamps have microsecond resolution.

I think in our case, all our fields come out as strings and lexicographical sorting would be fine. But I understand that a generic sort would be useful in templates for other reasons.
