### ISSUE TITLE
Alert and Group details in the post notification.

### ISSUE THREAD

**Issue by digrich** [bosun-monitor/bosun#1429]
I am trying to get Alert and Group details within post notification to send out more information about the alert to some other external service. Is their any way to get these details? Though template subject to available but it won't be having complete Alert details.

**Comment by nhproject** [comment]
+10

For now, In HTTP POST we can only use {{. | json}} and it takes the subject of the template.
It will be great for a lot of us to be able to use specific values like we do in the template. For example - {{.Group.host}}.
