### ISSUE TITLE
Allow incidents to be closed/marked as invalid

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1446]
By allowing the operators to mark an incident as invalid, it becomes easier for the sysadmins to detect/improve rules that generates lots of false positives.
This information should be saved in the state file (possibly also included in some new bosun self metric) so that it could be displayed in the alert testing tool.

**Comment by gbrayut** [comment]
I think this could also be solved with annotations, which are available in [opentsdb](https://github.com/bosun-monitor/bosun/issues/852) and other back ends like Elastic Search / Influx and even have some plumbing in place for use with Grafana. Right now I often use the bosun.alert metrics to help track down noisy alerts that need tuning. That combined with the rendered templates in my Gmail are usually all I need.

+1 on the idea, but it might be better to start with annotations that can be applied more broadly to include things like outages or maintenance windows.

**Comment by vitorboschi** [comment]
yes, I guess annotations would be a good fit for that kind of data too

**Comment by kylebrandt** [comment]
Work on annotations is currently in progress, teaser:

![createannotation](https://cloud.githubusercontent.com/assets/1692624/13055965/522af93e-d3e0-11e5-8e8a-f64bbedc196a.gif)
