### ISSUE TITLE
Can't Escape Regexes in Logstash Query

### ISSUE THREAD

**Issue by DanKans** [bosun-monitor/bosun#1456]
Hi, 

I would like to get an information about all response codes that are different than 200.
Currently I'm using "lscount" method as described, for each response code (example for 500):
lscount("logstash", "_type:access-log,", "response:500", "1m", "15m", "")

Creating directly ES query I can use "must_not" or "query": "_type:access-log  AND NOT response:200" to get information about response codes that are different than 200. 
I've noticed that it's not possible to use "query" as an argument in lscount method.

Please advise me, what options do I have.
Thank in advance!

**Comment by kylebrandt** [comment]
After the : is a ES style regex. I don't have the time to look up the exact
syntax right now, but I imagine you might be able to do something like
`[1345]00`

**Comment by DanKans** [comment]
Thanks for replay. It might be something:[300 TO 600] syntax. Unfortunately it won't work with Bosun plugin: 
```
SearchParseException[[logstash-2015.11.16][18]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"aggregations":{"g__type":{"aggregations":{"ts":{"date_histogram":{"field":"@timestamp","interval":"1m","min_doc_count":0}}},"terms":{"field":"_type","size":0}}},"query":{"filtered":{"filter":{"and":{"filters":[{"regexp":{"_type":"access-log"}},{"regexp":{"response":"[500 TO 510]"}}]}},"query":{"range":{"@timestamp":{"from":"2015-11-16T16:28:55.320405221Z","include_lower":true,"include_upper":true,"to":"2015-11-16T16:43:55.320405221Z"}}}}},"size":0}]]]; nested: NumberFormatException[For input string: "[500 TO 510]"]; }
```
It is because it uses regexp in filters:
```filters":[{"regexp":{"_type":"access-log"}},{"regexp":{"response":"[500 TO 510]"}}]}}```

Normally using for example kibana it creates:
```    "query": {
        "bool": {
          "should": [
            {
              "query_string": {
                "query": "_type:logs-access AND response:[300 TO 510]"
              }
            }
          ]
        }
      },```
I think I will go in this way and try to create some regexp to cover this case.
Thanks!

**Comment by kylebrandt** [comment]
I think this is a problem with escaping. The `[]` need to be escaped according to allowed characters in: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html. 

Triple single quotes `lscount("haproxy", '''ResponseCode:\[234\].*''', "", "15m", "15m", "")` results in:

![image](https://cloud.githubusercontent.com/assets/1692624/11222264/89410192-8d37-11e5-903a-32c133e51b5d.png)

Single Double Quotes:

![image](https://cloud.githubusercontent.com/assets/1692624/11222298/af1b3c16-8d37-11e5-82c8-5681793c5486.png)

Single Double Quotes with Double Escape:
 
`lscount("haproxy", "ResponseCode:\\[234\\].*", "", "15m", "15m", "")`

![image](https://cloud.githubusercontent.com/assets/1692624/11222381/0d4be434-8d38-11e5-8058-1741af10d5e4.png)

So it seems like there is no way to escape the string - maybe a problem in our lexer, json encoding, or the interaction between the two?

**Comment by captncraig** [comment]
Looks like the config parser correctly escapes `"\\["` to `\[`, but when encoded to json, it gets "re-escaped" to `\\[` again. A bit tricky to fix.

**Comment by DanKans** [comment]
Closing due to:

https://docs.influxdata.com/influxdb/v0.13/troubleshooting/frequently_encountered_issues/#single-quoting-and-double-quoting-in-queries

http://bosun.org/expressions#notes
