### ISSUE TITLE
More than 2 emails sent in the same Incident Id

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1460]
Sometimes Bosun is sending more emails than it should (ie. 1 for warning and 1 for critical) when the alert rule is flapping.
This doesn't seem to happen every time, but it is quite frequent.

I'm using Bosun 0.4.0 with opentsdb 2.2

**Comment by vitorboschi** [comment]
This is one of the examples:
![image](https://cloud.githubusercontent.com/assets/71193/11146189/235f2990-89f3-11e5-93ba-251e65142858.png)

![image](https://cloud.githubusercontent.com/assets/71193/11146194/3e011fe2-89f3-11e5-9976-61f45abfda95.png)

**Comment by captncraig** [comment]
How many emails did you get total? I would expect 2.

**Comment by vitorboschi** [comment]
A lot of them. Right now I've got 4 entries in the Ack list for this incident

**Comment by captncraig** [comment]
I have figured out how to reproduce this behaviour. It is all my fault. I have made #1471 to clarify a lot of these rules and to fix them. Please comment there if you think those definitions are inadequate.
