### ISSUE TITLE
Integration With OpsGenie

### ISSUE THREAD

**Issue by nhproject** [bosun-monitor/bosun#1463]
Hi

I'm using Bosun and sending alerts to OpsGenie using the HTTP Post method.
It works fine, but the integration is not full. One example is that Acknowledgements are not recognised by Bosun and it continues to resend the alerts.

Is there a future plan to implement an integration with this platform?

Nitz

**Comment by captncraig** [comment]
I've never used opsgenie. How do their acknowledgements work? You should be able to craft a post for acknowledgement that bosun will accept, but whether or not you can do that is another question. What specifically can we do to make it easier for you?

**Comment by captncraig** [comment]
Or do you mean that bosun's acks don't notify opsgenie? That template is not modifiable, but it could be.

**Comment by nhproject** [comment]
I meant that bosun is not recognizing OpsGenie Acks.
There are two aspects, actually:
1. Alerts are being sent from Bosun to OpsGenie, but when someone acknowledges an alert in OpsGenie - nothing happens.
2. I tried to add the {{.Ack}} field to the notification. The URL is ok and I'm getting the Bosun's web interface (the ack page) , but when I press Submit - I'm getting the an error: "cannot acknowledge closed alert". Of course no one closes this alert, so why this message is shown?

If the template can be modified it will be really good. Which modifications will be possible?

**Comment by kylebrandt** [comment]
Closing this as there are no integration plans at the moment. However, you might find the following new resource helpful https://github.com/TrentScholl/opsgenie-bosun
