### ISSUE TITLE
Customised time windows do not stick when triggering image

### ISSUE THREAD

**Issue by mhenderson-so** [bosun-monitor/bosun#1465]
When you are querying Bosun for data in the expression editor, with a customised time window, you will see the correct data shown underneath the query, but the image will show the data from _now_, not the provided window

For example, in the expression editor, you might set a date/time of `2015-11-16 00:00:00` and query:

```
lscount("logstash", "somevalue", "", "1m", "15m", "")
```

or

```
q("sum:rate{counter,,1}:dns.query.queries{host=*}", "1h", "")
```

And in the preview data below the form you will get the correct data. But if you click the "image" link, you will see the data for _right now_, not the `2015-11-16 00:00:00` start date specified.

It looks like the `?now=1447708010` parameter on the end of the generated URL is not respecting the time provided.

**Comment by tdinucci** [comment]
Seems OK now
