### ISSUE TITLE
errors in log while scollector monitoring rabbitmq

### ISSUE THREAD

**Issue by bizhao** [bosun-monitor/bosun#1467]
in /var/log/syslog, it says:
Nov 17 08:01:12 messagequeue01 scollector[16235]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode

RabbitMQ version: 3.4.3

**Comment by dimamedvedev** [comment]
Could you please show config snippet regarding RabbitMQ ?

**Comment by bizhao** [comment]
viouser@messagequeue01:/var/lib/rabbitmq/mnesia/rabbit@messagequeue01$ more cluster_nodes.config 
{[rabbit@messagequeue01,rabbit@messagequeue02],[rabbit@messagequeue01,rabbit@messagequeue02]}.

viouser@messagequeue01:/var/lib/rabbitmq/mnesia/rabbit@messagequeue01$ more /etc/rabbitmq/rabbitmq-env.conf 
# Defaults to rabbit. This can be useful if you want to run more than one node
# per machine - RABBITMQ_NODENAME should be unique per erlang-node-and-machine
# combination. See the clustering on a single machine guide for details:
# http://www.rabbitmq.com/clustering.html#single-machine
#NODENAME=rabbit

# By default RabbitMQ will bind to all interfaces, on IPv4 and IPv6 if
# available. Set this if you only want to bind to one network interface or#
# address family.
#NODE_IP_ADDRESS=127.0.0.1

# Defaults to 5672.
#NODE_PORT=5672

viouser@messagequeue01:/var/lib/rabbitmq/mnesia/rabbit@messagequeue01$ more /etc/rabbitmq/enabled_plugins   
[rabbitmq_management].


Anything else do you need?

**Comment by dimamedvedev** [comment]
Yeah, sorry for not being clear enough, I need
* your scollector config
* RabbitMQ `/api/nodes` endpoint output, e.g. `curl http://localhost:15672/api/nodes` , you'll need rabbitmq-management plugin enabled

**Comment by bizhao** [comment]
I just found the original issue is due to the incorrect username/password of rabbitmq.

Now the rabbitmq metrics are gathered successfully.
However in /var/log/syslog, there are still error messages like:
Nov 23 06:07:40 messagequeue01 scollector[26848]: info: main.go:187: OpenTSDB host: http://10.111.106.16:4242
Nov 23 06:07:45 messagequeue01 scollector[26848]: error: metadata.go:241: bad metadata return: 400 Bad Request
Nov 23 06:07:55 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_overview: Error: invalid RabbitMQ node name, can not split ''
Nov 23 06:07:55 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:07:55 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue
Nov 23 06:08:10 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:08:10 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_overview: Error: invalid RabbitMQ node name, can not split ''
Nov 23 06:08:10 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue
Nov 23 06:08:25 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:08:25 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue
Nov 23 06:08:25 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_overview: Error: invalid RabbitMQ node name, can not split ''
Nov 23 06:08:40 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:08:40 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue
Nov 23 06:08:40 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_overview: Error: invalid RabbitMQ node name, can not split ''
Nov 23 06:08:55 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:08:55 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue
Nov 23 06:08:55 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_overview: Error: invalid RabbitMQ node name, can not split ''
Nov 23 06:09:10 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue
Nov 23 06:09:10 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_overview: Error: invalid RabbitMQ node name, can not split ''
Nov 23 06:09:10 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:09:25 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue
Nov 23 06:09:25 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:09:25 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_overview: Error: invalid RabbitMQ node name, can not split ''
Nov 23 06:09:40 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_nodes: json: cannot unmarshal object into Go value of type []collectors.rmqNode
Nov 23 06:09:40 messagequeue01 scollector[26848]: error: interval.go:62: bosun.org/cmd/scollector/collectors.c_rabbitmq_queues: json: cannot unmarshal object into Go value of type []collectors.rmqQueue

Not sure if has other impacts or not..

Attached nodes.txt as the output of http://localhost:15672/api/nodes
[nodes.txt](https://github.com/bosun-monitor/bosun/files/41312/nodes.txt)

**Comment by dimamedvedev** [comment]
Was a vacation, sorry for a long response, I think I'll submit a PR this week. Different RabbitMQ use different formats for stats output unfortunately.

**Comment by kylebrandt** [comment]
@dimamedvedev Did this every get fixed or get a PR?

**Comment by dschneller** [comment]
This just happened to me, too, and it took me a moment to understand what's going on.

What it boils down to is what is said in this sentence from the documentation:

> RabbitMQ (array of table, keys are URL): RabbitMQ hosts to poll. Regardless of config the collector will automatically poll management plugin on http://guest:guest@127.0.0.1:15672/ .

This is what causes the errors in the log every time the collector interval passes, _if_ your RabbitMQ does _not_ allow logins for `guest:guest`. In that case, Rabbit helpfully returns HTTP status 401 with a body of
```
 {"error":"not_authorised","reason":"Login failed"}
```
Because it is not an error, this JSON is passed into the parser, leading to the errors in the log.

Looking closely at the log, it even says what is causing the failure, but that only makes sense when looking at the code:

https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/rabbitmq.go#L29-L33

Took me a moment to realize it, because I already had a `[[RabbitMQ]]` section in my config file, specifying a URL with correct credentials.

The fix might be as simple can removing the default URL altogether, make the config entry mandatory, or -- probably better -- to only use them when no specific URL has been set.
For bonus points, the 401 response might be used to construct a more helpful error message ;)
