### ISSUE TITLE
Changing .Last.Status 

### ISSUE THREAD

**Issue by nhproject** [bosun-monitor/bosun#1468]
Hi,

Is it possible to change this parameter in the template section?
Meaning - if the event state is critical (=3), is it possible to assign it a new state (for example, 2 / warning) ?

10x!

Nitz

**Comment by captncraig** [comment]
Why do you need to do this? What are you actually trying to accomplish?

**Comment by nhproject** [comment]
Because I'm using crit for both warning/critical values, and warn as a trigger for normal values.
and in the template I want to split to two possible options - values that are actually crit will remain as is, and for values that are actually should be warn - I want to set their state to warn.

Alternatively, will you add another state parameter ? for example, norm for normal values?

**Comment by captncraig** [comment]
Sorry, templates are absolutely not supposed to modify the underlying data. The state should be a direct result of evaluating crit/warn expressions. 

I'm not sure what you are trying to accomplish with "warn as a trigger for normal values". Are you trying to get notifications on normal values?

**Comment by nhproject** [comment]
Kind of. I'm trying to notify on "Back to normal state". We should know when we resolve a problem :smile:

**Comment by nhproject** [comment]
Adding "norm" variable (like "warn" or "crit") will be awesome

**Comment by captncraig** [comment]
Well that is horrible abuse of the notification system to accomplish that. We have discussed various options around this kind of thing, and there are some varying philosophical positions there. #333 is still open and is the most likely to resolve your issue, you can comment there and maybe we can prioritize it after our next release.

**Comment by nhproject** [comment]
It's an horrible abuse, that's right.
But for now I don't see another option to implement my needs - One should know when a problem is resolved. That's why I used this "anti-alert" way of work.
It's not something out of the ordinary - If you are familiar with monitoring systems like Sensu - when a problem is fixed you get a notification about it.
So maybe adding a variable such as "norm" is not right, but maybe using the history is the way. If changing from "warning"/"critical" to "normal" is recognized - that's the trigger for it.
