### ISSUE TITLE
Logstash query function's filter string wildcard matching works only with numeric types

### ISSUE THREAD

**Issue by pmcameron** [bosun-monitor/bosun#1474]
Hi, 

I am trying to use the "star character *" for wildcard matching in the filter string of a logstash query function and it seems to only work on numeric fields. 

For example:
lscount("logstash-index","servername","id:3*","1m","4h","")
works and queries all logs having id starting with 3 (the id field only contains numeric characters)

and  lscount("logstash-index","servername","host:ca_prod*","1m","46h","") works as "ca_prod" is a host

BUT  lscount("logstash-index","servername","host:ca*","1m","46h","")  returns no results even though there are multiple hosts starting with the substring "ca" including "ca_prod"

why am I getting no results with the filter string "host:ca*" ?

Thanks in advance!

**Comment by kylebrandt** [comment]
Those functions don't use wildcard querying, but rather they use elastic's regex query type. Note those happened to be anchored by default. so `a*` means zero or more `s`s IIRC.

**Comment by pmcameron** [comment]
Thank you for your fast reply!
