### ISSUE TITLE
Retrieve time stamp from data point 

### ISSUE THREAD

**Issue by pmcameron** [bosun-monitor/bosun#1478]
Hi, 
I am using the logstash query functions to alert me about execution times for queries against my database. For my crit field i have something like:
max(lsstat("logstash-querysrv", "", "env:prod", "querytime", "max", "1m", "1h", "")) > 10000

which works great, but this only tells me that there was a querytime above 10000 in the 1 hour period, it would be very helpful to get the time value of the data point that made the crit field trigger so i could search for the issue much easier. I feel like there is a template variable to get the time value of a timeseries data point but i cant find one.
Is this possible ?

Thanks in advance!

**Comment by kylebrandt** [comment]
If all you care about is Max query time, why not lower the time period it
queries to narrow it down more?

Also, you can use the Graph and GraphAll template functions to get a
visualization.

Finally, you can iterate over the datapoints of an .EvalAll that returns a
seriesSet, although don't have an example of that handy. You can look at
the Bosun code for the structure that EvalAll returns when it is a
seriesSet, or just do some printing in the template to explore it.

**Comment by pmcameron** [comment]
Thanks Kyle
