### ISSUE TITLE
[scollector] Add scollector binary for arm64 on official website

### ISSUE THREAD

**Issue by PierreZ** [bosun-monitor/bosun#1480]
Hi!

On your official [website](http://bosun.org/scollector/), you are providing binary for different versions of ARM. Could you also add binary for ARMv8 (also known as AArch64, or arm64 in [Go 1.5](https://github.com/golang/go/wiki/GoArm))?

**Comment by captncraig** [comment]
sure. its a one line change to the build script. Out of curiosity, what will you be running it on?
