### ISSUE TITLE
Can we schedule the silence rule to trigger daily or weekly?

### ISSUE THREAD

**Issue by digrich** [bosun-monitor/bosun#1492]
I am trying to define silence rule to suppress all alerts on Saturday and Sunday during our maintenance window and also daily at specific time when our customers re-connect.

Is their a way to achieve this?

**Comment by Dieterbe** [comment]
sounds like a job for a crontab + http://bosun.org/api

**Comment by digrich** [comment]
I believe, this would be a very common case to silence any alert rule on specific day/time every week/day/hour and to have that support within silence rule itself would be great. 

It could be like defining the start date and time to the existing start date field and to have a separate field for 'recurrence period' where we can define some thing like 1h/1d/1w/1m.

**Comment by vaibhav376** [comment]
+1
