### ISSUE TITLE
New behavior of wildcard in 2.2 silently breaks alerts

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1495]
Previously bosun would let you use both * and | in the match criteria for tags. The new 2.2 default will silently not return any data if you specify a `name=optiona|any*|optionb` or any other combination of | and *. Kyle already filed an issue with https://github.com/OpenTSDB/opentsdb/issues/650 but if it is not fixed upstream before releasing the next version we should return an error for any tag criteria that include a * and | but are not using the regexp() filter. Otherwise we will silently break existing alerts (we had multiple broken in our config for the last week or so)

**Comment by manolama** [comment]
Hmm, 2.2 *should* treat these as literals in the same way 2.1 did, e.g. it would match ``name=optiona || name=any* || name=optionb`` but not match ``name=anysomthing`` since TSDB didn't support wildcards previously. Did Boson do post-filtering when a wildcard was given?

**Comment by kylebrandt** [comment]
Yes, Bosun did its own wildcard expansion when there was an asterisk. So it
is the ability to mix or and wildcard.

**Comment by kylebrandt** [comment]
With #1710 it made me think of another workaround (I haven't tried it yet though, and it was really meant for this):

```
$a = q("min:ping.timeout{dst_host=iwildcard(foo*)" ....)
$b = q("min:ping.timeout{dst_host=iwildcard(bar*)" ....)
$c = merge($a, $b)
```

Merge is meant for graphing and not alerting, but this may work. I've pinged them on the opentsdb issue, maybe it can get added to 2.3.

**Comment by kylebrandt** [comment]
In terms of the Milestone, we need to make the config error out on the condition so alerts do not silently break.

**Comment by captncraig** [comment]
Documented in 0.5.0 release notes draft I have seen form kyle. Closing.
