### ISSUE TITLE
Thresholds or mappings for unknown alerts

### ISSUE THREAD

**Issue by timurb** [bosun-monitor/bosun#1498]
It would be nice if we could specify thresholds for unknown alerts like such:
* produce alert when the unknown is there for N checks
* produce alert only when there are simultaneously more/less than N unknown alerts for a single metric/tag combination (host)/for the whole set of data

Also there could be use of mapping certain unknown alerts to different messages
* for example, when no data is received for metrics with tag `dc=foo` produce alert "Connectivity with DC foo is lost"
* this would naturally require some alerts only to be displayed on the dashboard and some to be sent out via e-mail/HTTP action

**Comment by kylebrandt** [comment]
You can set an unknown duration for individual alerts using the keyword unknown. You can also have alerts depend on other alerts (uses the subset tag matching like booleans). Both are in the configuration documentation on bosun.org.

**Comment by timurb** [comment]
Could you please send a link?
I could find only reference to `unknownTemplate` (which should solve my first part of the question) but no other references for `unknown`.

**Comment by kylebrandt** [comment]
Under http://bosun.org/configuration#alert

**Comment by timurb** [comment]
Right. Somehow I've missed that or was looking to different page.

Then the only point in my original feature request left would be supressing unknown alerts for less than specified number of unknowns.
I'm not that confident now that I really need that given all the rest of my points are available :-)

I'll come back here after I've checked how unknown templates and dependencies for them work. 
If you more feel like closing this ticket -- that's fine for me.

**Comment by kylebrandt** [comment]
@timurb One major caveat is that the rule testing page doesn't support dependencies currently :-/ It won't error, but there is no way to test what them without deploying them to a test bosun instance or to prod.

**Comment by captncraig** [comment]
Not entirely accurate. It evaluates static expressions in the rule page, but the `alert` function won't look for unknown or unevaluated dependency alerts.
