### ISSUE TITLE
Lookups and InfluxDB

### ISSUE THREAD

**Issue by nhproject** [bosun-monitor/bosun#1503]
Hi,

Is it possible to use lookups when using InfluxDB as my database?
If so, then how should I do it?

I'm getting "0 crits, 0 warns, 0 unevaluated, 0 unknown" when using the lookup.

Nitz

**Comment by kylebrandt** [comment]
Considering this a dupe of https://github.com/bosun-monitor/bosun/issues/1035 , needs to be changed not to use search if possible.
