### ISSUE TITLE
Elasticsearch collector crashing scollector

### ISSUE THREAD

**Issue by floyd-may** [bosun-monitor/bosun#1510]
(Using 0.4.0 release)

I added elasticsearch to my Ubuntu 14 machine and discovered that scollector started crashing pretty frequently (every minute or so). Contents of stderr:

```
panic: interface conversion: interface is nil, not float64

goroutine 34 [running]:
bosun.org/cmd/scollector/collectors.c_elasticsearch(0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/bosun.org/cmd/scollector/collectors/elasticsearch.go:162 +0x2b56
bosun.org/cmd/scollector/collectors.(*IntervalCollector).Run(0xc820013440, 0xc820019140)
        /go/src/bosun.org/cmd/scollector/collectors/interval.go:58 +0x11c
created by bosun.org/cmd/scollector/collectors.Run
        /go/src/bosun.org/cmd/scollector/collectors/collectors.go:145 +0x105

goroutine 1 [select (no cases)]:
main.main()
        /go/src/bosun.org/cmd/scollector/main.go:221 +0x226f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

Is there a way to disable this collector temporarily until the problem is sorted out?

**Comment by kylebrandt** [comment]
Is this v2 Elastic? If that is the case then you can just build scollector from master and it should be fixed.

**Comment by floyd-may** [comment]
Yes, v2. I'm not in a great position to build from source; does the 0.5.0 release have the fix in it?

**Comment by kylebrandt** [comment]
Is linux 64 bit the only thing you need a binary for?

**Comment by floyd-may** [comment]
yup.

**Comment by floyd-may** [comment]
Somewhat-related question: reason I noticed is because I stopped getting hbase garbage collection stats. With this collector bringing down the entire process, it puts collection of other stats in jeopardy. Is there a fix for that in the works as well, i.e. trap errors per-collector so they don't bring down stat collection for other collectors?

**Comment by kylebrandt** [comment]
That seems like it good be a good idea. Make a new issue for it please, we
could maybe wrap the interval collectors in a defer panic

**Comment by floyd-may** [comment]
Is this a duplicate of another issue? If not, would it be inappropriate to ask that this stay open until there's a release available with ES2 support? The [latest release I'm seeing is from Nov 3](https://github.com/bosun-monitor/bosun/releases). Thanks!

**Comment by kylebrandt** [comment]
It will get included in the next release when redis is finished (very close), so keeping this open doesn't really help us in a way that I can see

**Comment by floyd-may** [comment]
Can you point me to a different issue I can subscribe to so that I get an email when it closes that should (roughly) correspond with that next GA release?

**Comment by kylebrandt** [comment]
Hmm.. maybe subscribe to
https://github.com/bosun-monitor/bosun/releases.atom ?
