### ISSUE TITLE
Error trap collectors to prevent crashing the entire process

### ISSUE THREAD

**Issue by floyd-may** [bosun-monitor/bosun#1511]
(spun off from #1510)

I noticed that a crashing elasticsearch collector was crashing the entire scollector process because I stopped getting hbase garbage collection stats.

If a collector can bring down the entire process, it puts collection of other stats in jeopardy. Is it possible to trap errors per-collector so they don't bring down stat collection for other collectors?

**Comment by christoffbotha** [comment]
+1 I also experienced this crash after I upgraded to elasticsearch 2. I know version 2 is not supported yet but we need a way to trap individual collector panics like this so they do not kill scollector.
