### ISSUE TITLE
Invalid class error from scollector

### ISSUE THREAD

**Issue by floyd-may** [bosun-monitor/bosun#1516]
Getting this error in the event log from scollector:

```
error: interval.go:62: bosun.org/cmd/scollector/collectors.c_windows_processes: Exception occurred. (Invalid class )
```

scollector 0.4.0
Windows Server 2008 32 bit

**Comment by floyd-may** [comment]
This was an issue with the WMI providers on the windows machine getting hosed up.

**Comment by gbrayut** [comment]
Sorry... I had meant to respond and had a draft written but it slipped my mind. These often are transient errors that a reboot usually will fix. Has happened on about 3 out of 300 systems. You may also see the following errors in the event log:

Event Log Error: The WMI Performance Adapter service terminated with the following error: Unspecified error
Log Name: System
Source: Service Control Manager
Event ID: 7023

Last time I saw that I also noticed the WMI Performance Adapter service was starting and stopping every few seconds. I set the service to disabled for about 60s and then set it back to manual and it seemed to start working again.

If all else fails you can try using instructions at http://blogs.technet.com/b/askperf/archive/2014/08/11/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class.aspx to rebuild WMI counters. We have had one system that was corrupt enough we had to reinstall the OS.
