### ISSUE TITLE
Connecting to OrientDB using Go Lang

### ISSUE THREAD

**Issue by githubusersan** [bosun-monitor/bosun#1521]
Hi Team,
I am trying to connect to Orient DB using Go Lang.
I am trying to use orientgo package but not able to connect to DB and query it.
Please let me know the steps to achieve it or any pointers would be of great help.

Thanks,
Santosh

**Comment by captncraig** [comment]
I don't think orientdb has any real relevance to bosun. It is a graph database, while we are concerned mostly with time series data. 

Looking at their website, there doesn't appear to be any Go drivers. You would likely need to implement an interface using their [http api](http://orientdb.com/docs/last/OrientDB-REST.html). This should be fairly straightforward in go, but we probably can't offer much assistance. 

Good luck!
