### ISSUE TITLE
Logstash queries use regexp, which doesn't work well on unanalyzed fields

### ISSUE THREAD

**Issue by sysadmin1139** [bosun-monitor/bosun#1525]
It looks like the logstash functions use the [regexp](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html) query to look for information. This provides regex over tokenized fields, and does so very quickly.

What it doesn't do, is search on unanalyzed fields in any way that is meaningful. Our Kibana seems to use [query_string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) quite extensively. For certain fields like `[message]`, this allows building dashboards for any random text.

Our hope was to be able to take the ability to create dashboards in Kibana and write Bosun alerts. Due to the different queries being used, our data visibility is much reduced in Bosun.

---
Would it be possible to create a new config option, maybe `logstashQueryType`, to indicate the type of query to be used for the `lsstat()` and `lscount()` functions? Keep the default as `regexp` to not break existing installations, and allow full-text query types?

**Comment by kylebrandt** [comment]
"What it doesn't do, is search on unanalyzed fields in any way that is meaningful." -- Can you expand on why that is?

**Comment by sysadmin1139** [comment]
Here are two example elasticsearch queries.

```json
{
	"size": 1,
	"query": {
		"regexp": {
			"message": "SQLERROR"
		}
	}
}
```
And the query_string version of it:
```json
{
	"size": 1,
	"query": {
		"query_string": {
			"query": "SQLSTATE",
			"default_field": "message"
		}
	}
}
```
The regexp version of this returns no documents.  The query_string version of that returns 5569.

I admit, our [message] field is set `not_analyzed` which is likely an incorrect assumption, but it also seems Logstash did that to itself.

**Comment by kylebrandt** [comment]
Elastic Regexes are anchored by default, so it as if you regex was `^SQLERROR$`. 
not analyzed should mean that the field is raw IIRC, which regexes should be useful with.

**Comment by kylebrandt** [comment]
I anticipate having to rework the lsquery funcs to for 2.0 support in the next couple weeks, so now isn't a bad time for changes, but need to fully understand the need.

**Comment by sysadmin1139** [comment]
The issue is that `regexp` does its regex magic on the terms, not the full text of the field:

>  The "term queries" in that first sentence means that Elasticsearch will apply the regexp to the terms produced by the tokenizer for that field, and not to the original text of the field.

So if a field is not analyzed, there are no terms for it to search against. The full-text search functions will work on the full text of a field. The `query_string` function [does have a regular expression feature](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_regular_expressions), which is what our Kibana is using.

That said, tokenizing makes things a lot faster for searching at the cost of CPU at ingestion time and overall index size.

**Comment by kylebrandt** [comment]
I'm currently thinking about adding a new return type that is a elastic filter. That filter could then become type of parameter for generating tag keys as well as filtering.  This would make it more powerful since we could add filters over time, and allow more breathing room for mistakes in those functions by localizing the breakage.
