### ISSUE TITLE
Adding comments to already acknowledged incidents

### ISSUE THREAD

**Issue by timurb** [bosun-monitor/bosun#1532]
Sometimes you acknowledge alert and then need to add some comment to the log.

It would be nice if we could add comments to already acknowledged incidents.

**Comment by captncraig** [comment]
We've had this idea before too. Would essentially be an additional action type you could perform. And a little bit of ui on the incidents page.

**Comment by kylebrandt** [comment]
closing as dupe of https://github.com/bosun-monitor/bosun/issues/1767 (this one was first, but already referenced the other one in the PR that adds this feature).
