### ISSUE TITLE
JSON encode post body

### ISSUE THREAD

**Issue by deanefrati** [bosun-monitor/bosun#1533]
following PR https://github.com/bosun-monitor/bosun/pull/1101 and the  discussion with @captncraig @ayashjorden and I would like to discuss an enhancement of changing the way a post body is encoded from HTML to JSON

**Comment by ayashjorden** [comment]
Hi @deanefrati ,
The initial intent of the template body is to be sent as an email message, hence the HTML encoding.

Can you elaborate on the benefits of JSON encoding of the template's body other than removing the HTML tags wrapping it?

Maybe we should have json_template and email_template (and probably others down the road). but this will add complexity that we need to consider.

Finally, I think that the discussion should answer "How Bosun can better its outbound API integration?"

**Comment by deanefrati** [comment]
sure. like you mentioned the goal is to better Bosun's outbound integration with other tools. The reason i think encoding the body as json v.s just stripping the html would be better is that it's likely that whichever tool you want to integrate with can speak JSON in some form or the other and if we just strip the html you'll probably need to convert the plain text message bosun will now send to json (or some other serialized text) on the consumer side to actually process it. While this may be an option it will add some serialization work on the consumer side v.s enabling the consumer to just process the event. I think sending the event in a structured way from the get go will save users the time trying to parse it on the consumer side and will end up making integrations easier.

**Comment by kylebrandt** [comment]
Will be fixed in https://github.com/bosun-monitor/bosun/pull/2135
