### ISSUE TITLE
Allow alerting for missing data

### ISSUE THREAD

**Issue by lpalm** [bosun-monitor/bosun#1534]
When making an Influx query that returns no results (i.e. the server collecting that data crashed), there's seemingly no way to make it alert. I was told I could set ignoreUnknown=true but this doesn't seem to work when "backtesting" in the rule editor, so there's no easy way to check it works besides stopping the server producing this data (which we cannot do easily). 
Ideally we'd be able to at least see those "unknown" alerts when testing it on the rule editor and see periods with no data on the timeline view.

**Comment by lpalm** [comment]
This may be related to https://github.com/bosun-monitor/bosun/issues/1498

**Comment by kylebrandt** [comment]
You want the opposite ignoreUnknown (don't set it at all). Unknown alerts trigger when a tagset "disappears". The rule page will only detect the test range starts before the tagset was absent.
