### ISSUE TITLE
Query links generated in expression results don't set tags correctly

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1535]
When running an expression that spits out a number of links to graphs, the displayed link contains a 'host=blah' query, yet the resulting graph page does not match on host. Perhaps this broke with the recent query language changes?

@kylebrandt

**Comment by kylebrandt** [comment]
Not entirely sure what this is. Can you provide more info / screenshots?

**Comment by alienth** [comment]
Bottom link here:
![screenshot](https://cloud.githubusercontent.com/assets/218431/13064581/c377b01c-d400-11e5-9e12-d86a798fa6b6.png)

Clicking on that link takes you here:
![screenshot](https://cloud.githubusercontent.com/assets/218431/13064601/dcb1bca8-d400-11e5-947c-d41e7c3e2d38.png)



Note that the 'host' field is blank, despite the host being specified on the expression page.
