### ISSUE TITLE
Add button to fire one-off alert checks to clear alerts

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1550]
Would like a button to recheck an alert that I know to be resolved. Cases where I need this are when an alert is currently active, but I've fixed it. Right now I just have to remember to go back to the dashboard and clear it after it goes inactive, but most of the time I don't remember to do so, and when I do it interrupts other work.

In terms of implementation, was thinking we could just fire a new goroutine to run the collector one-time only.

**Comment by captncraig** [comment]
this seems a use case for the "deferred close" feature kyle wants. Something like "If this goes normal in the next n minutes, close it."

**Comment by alienth** [comment]
That doesn't serve my purposes, actually. There are cases where I'm not certain an alert will go clear, so 'deferred close' doesn't do what I need. I need the check to run again to ensure all is well, and I don't want to wait minutes for that to happen.
