### ISSUE TITLE
Event notification

### ISSUE THREAD

**Issue by JozoVilcek** [bosun-monitor/bosun#1553]
I want to set up a rule, which repeatedly gets checked and sends out an informative notification about it. For example, number of new warnings logged by applications via `lscount` with a link to kibana for review. This does not necessarily requires acknowledge, silence, close. Lets say it is a digest what happened during some time window, invites you to check out logs, graphs, something else, and maybe some precise alerts will get cooked from what is observed.

A have tried to use `alert` with `warn` and `ignoreUnknown`. However, if event occur in each time window, next notifications gets suspended until event is acknowledged and closed. Even this I can not do, because I `can not close active alert`.

Is there a way to do what I want with Bosun? Or, should I walk a different path?

**Comment by vitorboschi** [comment]
I guess what you want can be acomplished by adding log = true in the alert rule, as said in the docs:
> log: setting log = true will make the alert behave as a “log alert”. It will never show up on the dashboard, but will execute notifications every check interval where the status is abnormal.

**Comment by JozoVilcek** [comment]
Yes. That will do it. Word `log` slipped my sight. Have to be more thoroughgoing.
Thanks!

**Comment by JozoVilcek** [comment]
After adding `log = true` I observe strange behavior in links generated for lookup to kibana. Some time ranges are off. I use, as an alert `now` time this variable `{{.Last.Time.UTC}}`

**Comment by kylebrandt** [comment]
Closing this for now since we are replacing these functions with the `es*` funcs. If it exists in those comment and will reopen.
