### ISSUE TITLE
scollector: too many open files

### ISSUE THREAD

**Issue by bcandrea** [bosun-monitor/bosun#1557]
scollector seems to leak socket connections when left running for several days (>60). The issue becomes apparent when looking at syslog, and noticing that the process stops recording metrics:

    $ tail /var/log/syslog
    ...
    scollector[3666]: error: queue.go:84: Post http://localhost:9107/api/put: dial tcp 127.0.0.1:9107: socket: too many open files

The output of `lsof` shows sockets open:

    $ sudo lsof -p 3666
    ...
    scollecto 3666 scollector 1018u  sock                0,7      0t0 9458743 can't identify protocol
    scollecto 3666 scollector 1019u  sock                0,7      0t0 9814562 can't identify protocol
    scollecto 3666 scollector 1020u  sock                0,7      0t0 9824249 can't identify protocol
    scollecto 3666 scollector 1021u  sock                0,7      0t0 9832600 can't identify protocol
    scollecto 3666 scollector 1022u  sock                0,7      0t0 9976212 can't identify protocol
    scollecto 3666 scollector 1023u  sock                0,7      0t0 9849449 can't identify protocol

This points to similar issues, e.g. http://stackoverflow.com/questions/7911840/seeing-too-many-lsof-cant-identify-protocol, where sockets were left half-open.

My setup uses `scollector` in conjunction with `prometheus-scollector` to export metrics to a Prometheus server.

**Comment by captncraig** [comment]
Our system runs pretty flat:
<img width="1101" alt="screen shot 2016-01-11 at 8 10 32 am" src="https://cloud.githubusercontent.com/assets/192540/12237221/dbd05a24-b83a-11e5-9ca3-4c6e5ab1406c.png">

Are you monitoring scollector with the process collector? Either some collector we don't run is leaking fds, or maybe prometheus-scollector is. Do you have a graph of file descriptors?

**Comment by bcandrea** [comment]
Thanks for the quick reply. My configuration is very basic (I just start the daemon with a host option), so the only other process involved is `prometheus-scollector`. I'm not monitoring the scollector process unfortunately, but I will add it (along with prometheus-scollector) to the configuration and see if I can find out which one is keeping the socket open. From what I can see there is no correlation with anything else than uptime (systems up for more than a month typically show this behaviour).

**Comment by bcandrea** [comment]
I finally got to the bottom of the issue. After looking at the number of file descriptors reported by the process monitor, I noticed a regular pattern:

<img width="1428" alt="scollector_num_fds_1" src="https://cloud.githubusercontent.com/assets/127672/12466323/a574a3c0-bfcb-11e5-9234-11c8ff480416.png">

An hourly increase of the number of open FDs pointed me to the metadata upload, which happens every hour. After some digging I noticed that the latest version doesn't include #1476, that adds a `r.Body.Close()` after the POST. Apart from memory/goroutine leak, leaving the reader open was keeping alive the connection with the server.

After recompiling from 855eb85 and running the collector again I got a much better result:

<img width="1423" alt="scollector_num_fds_2" src="https://cloud.githubusercontent.com/assets/127672/12466329/ab554dd0-bfcb-11e5-93a1-8e50a9b4de31.png">

I had quite some fun investigating the issue by using scollector to monitor itself. Great job, this is an awesome tool. Looking forward to the next stable release to come out.

**Comment by gbrayut** [comment]
Nice work! We are close to finishing the move of data from bolt to redis and will be releasing a new version once that is ready. Until then we will keep in mind there may be a fd leak in scollector.

**Comment by digrich** [comment]
I am using 0.5.0-alpha release and encountered this issue where each scollector ends up opening 100 of socket connections to OpenTSDB. Over the period, OpenTSDB ends up having thousands of established connections from hundreds of scollectors. Can we have next version of alpha release with this fix?

**Comment by kylebrandt** [comment]
@digrich See if it is fixed in https://github.com/bosun-monitor/bosun/releases/tag/0.5.0-rc1 ?

**Comment by digrich** [comment]
@kylebrandt It is fixed with the latest release. Thanks for the quick release and response.  Let me say, scollector with bosun and grafana is coming up very well in our company.
