### ISSUE TITLE
Odd results for scollector.collect.post.errors

### ISSUE THREAD

**Issue by floyd-may** [bosun-monitor/bosun#1558]
The metric description for scollector.collect.post.error reads:

> Counter of errors received when sending a batch to the server.

However, when I graph it as a counter, I get numbers that don't appear to be numeric counts. Values are significantly less than one:

![image](https://cloud.githubusercontent.com/assets/1608756/12265482/db905ab4-b902-11e5-9607-4e021facb969.png)

I would expect that those spikes would have tops that are at least 1.0. What am I missing?

**Comment by kylebrandt** [comment]
With counter OpenTSDB is giving you a per second rate. So if it collects
every 15 sec, a there was one event during that buckets, the per second
rate will be 1/15. Query as gauge to see raw count

**Comment by floyd-may** [comment]
If I query as a gauge, I get an ever-ascending graph, which is what I would expect for a counter incorrectly graphed as a gauge:

![image](https://cloud.githubusercontent.com/assets/1608756/12265956/e40c8fac-b905-11e5-9a62-0244c7f3e3bc.png)

So I presume where the blue circles are indicate where a single error occurred. However, I have no idea what happened at the question mark - this part is really strange to me.

Is the per-second calculation purely an OpenTSDB thing, or can it be controlled by how the metrics are configured? There are a number of counter metrics where I would prefer to see the actual totals, not n-per-second rates. For instance, `iis.bytes`. There are plenty of cases where I'm more interested in knowing how many bytes transferred across the wire than how fast the data rate is.

**Comment by kylebrandt** [comment]
I would assume the question mark is a restart? When things are restarted,
counters reset back to zero.

Bosun's metric metadata says if things are a Gauge or Counter (that is what
Auto uses in the graph view) - you can override what the metadata says it
is by manually setting the Series Type.

As far as the rates unit (per second, per minute etc) OpenTSDB only
supports per second currently. I have requested options on this:
https://groups.google.com/forum/#!searchin/opentsdb/per$20second/opentsdb/FduybJGjNgo/pJ8gwyeKAwAJ

**Comment by floyd-may** [comment]
> you can override what the metadata says it is by manually setting the Series Type.

How would one go about doing that?

**Comment by kylebrandt** [comment]
I just meant the drop down in the graph UI. In general the series type (gauge/counter) is hard coded into scollectors code. So if you changed the metadata, scollector would just change it back.

The graph page in bosun is more meant for ad hoc work. If you want long term displays I would suggest Grafana. You can graph and table bosun expressions: https://github.com/grafana/grafana-plugins/tree/master/datasources/bosun

**Comment by floyd-may** [comment]
Sure, I understand that. I've got a bunch of dashboards set up in Grafana; I love it =)

I guess I'm more confused by the relationship between the metric type and aggregator not giving me an option to get the raw totals instead of n-per-second. Is there a clever way to get that data using a bosun expression? If so, I may get the bosun datasource plugin wired into my Grafana server.

**Comment by kylebrandt** [comment]
If you look on the graph page, it shows the expression generated at the
bottom. So if you query it as a gauge, you will see what expression for a
gauge vs counter looks like. Bosun's metadata doesn't change the way
expressions behave, it will just generate a different expression on the
graph page when using auto. So all auto really does is pick counter vs
gauge for you based on the metadata in the graph view.

You can then use this expression in grafrana with the bosun data source. Or
you can use OpenTSDB grafana backend and query it without the rate option.

**Comment by floyd-may** [comment]
I think what I'm looking for is more along the lines of your feature request with the OpenTSDB folks, where I'd like to (optionally) query a given metric as a count of "events" as opposed to events per second. Thanks for your help!

**Comment by kylebrandt** [comment]
You can kind of hack that using the bosun window() query func in the
meantime.

**Comment by kylebrandt** [comment]
Closing since this depends on OpenTSDB
