### ISSUE TITLE
Allow searching through alert history

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1559]
Currently there's no easy way to check all alerts that ocurred in a given timespan. A view displaying incidents history and a way to filter by date/time, tags and/or alert would be really useful

**Comment by azhurbilo** [comment]
+1

**Comment by acesaro** [comment]
We've solved this by POSTing the events to another log aggregation tool and then report using that.  This allows us to use different tools for what they're best at instead of bloating tools with additional functionality.

**Comment by kylebrandt** [comment]
@acesaro Did you do this by changing Bosun's code to do this for all (or some part) of notifications, or did you do this via notifications in Bosun's configuration?

**Comment by acesaro** [comment]
Hi @kylebrandt , I didn't change any Bosun code to achieve this.  It's simply an entry in a chain of `notification` entries that does an HTTP POST to the log aggregation system's ingestion endpoint.  We use Splunk in this case, but could be easily achieved with any similar system that exposes an HTTP ingestion endpoint.

The capability of HTTP POSTs in Bosun makes this nice and simple. :)  Thanks again for your hard work on this very useful tool!
