### ISSUE TITLE
public Bosun repository

### ISSUE THREAD

**Issue by d10v** [bosun-monitor/bosun#1563]
It's much easier to install packages from repositories, especially when using automation tools. There are already convenient options for this (e.g. packagecloud.io), setting this up shouldn't be hard. I could do this too obviously, but it's much better if repo is controlled by StackExchange. Another option is using Travis to push packages, I haven't succeeded doing that though. Any thoughts?

**Comment by Dieterbe** [comment]
Circleci is nice too

**Comment by thenewwazoo** [comment]
Because Go binaries are monolithic, I've found packaging per se to be unnecessary. Instead of:
```
  - name: install bosun
    apt: name=bosun state=installed
```
I can simply do
```
  - name: install bosun
    get_url: url=https://github.com/bosun-monitor/bosun/releases/... dest=/usr/local/bin/bosun
```

I'm not opposed to the idea, but I've already had good success to date.
