### ISSUE TITLE
scollector: Not generating syslog or not sending data

### ISSUE THREAD

**Issue by mokshpooja** [bosun-monitor/bosun#1572]
Hi Guys,
I have a vagrant + docker container setup. There are a total of 7 docker containers running-
- 6 docker containers have different services/application with 1 container having scollector installation (installed via dockerfile such as- `FROM golang
  ADD . /go/src/main 
  RUN go get bosun.org/cmd/scollector` 
- the 7th container has Bosun server (on localhost:8070, installation from docker registry)

`scollector -h "http://localhost:8070"

```
2016/02/03 00:44:11 error: log_unix.go:10: Unix syslog delivery error
2016/02/03 00:44:11 error: main.go:247: stat /scollector: no such file or directory
2016/02/03 00:44:11 info: main.go:195: OpenTSDB host: http://localhost:8070
2016/02/03 00:44:11 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 00:44:11 error: queue.go:105: Post http://localhost:8070/api/put: dial tcp [::1]:8070: getsockopt: connection refused
2016/02/03 00:44:11 info: queue.go:124: restored 39, sleeping 5s
2016/02/03 00:44:16 error: queue.go:105: Post http://localhost:8070/api/put: dial tcp [::1]:8070: getsockopt: connection refused
2016/02/03 00:44:16 info: queue.go:124: restored 500, sleeping 5s
2016/02/03 00:44:21 error: queue.go:105: Post http://localhost:8070/api/put: dial tcp [::1]:8070: getsockopt: connection refused
2016/02/03 00:44:21 info: queue.go:124: restored 500, sleeping 5s
2016/02/03 00:44:26 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 00:44:27 error: queue.go:105: Post http://localhost:8070/api/put: dial tcp [::1]:8070: getsockopt: connection refused
2016/02/03 00:44:27 info: queue.go:124: restored 500, sleeping 5s
^C2016/02/03 00:44:31 error: metadata.go:244: Post http://localhost:8070/api/metadata/put: dial tcp [::1]:8070: getsockopt: connection refused
2016/02/03 00:44:31 error: queue.go:105: Post http://localhost:8070/api/put: dial tcp [::1]:8070: getsockopt: connection refused
```

`
I see 3 possible errors
- No syslog been generated,
- Syslog not being found
- Access between the containers might be failing 

I can see some metrics on the bosun web interface which are basically from the the host on the 7th container but not from other containers. Could somebody help me to understand what am I doing wrong?

**Comment by kylebrandt** [comment]
`scollector -h "http://localhost:8070"`. - That seems like you telling scollector to send it data to localhost, which would only make sense within the container that has bosun.

`main.go:247: stat /scollector: no such file or directory` is interesting. That error is called from scollector trying to call stat on itself. Not sure why that would error, maybe a container thing?

```
	prog := os.Args[0]
	p, err := filepath.Abs(prog)
	if err != nil {
		return "", err
	}
	fi, err := os.Stat(p)
```

Is what I think throws the error.

I'm guessing syslog might be a container thing as well. 

When I've run scollector in containers, I've done the following when bosun is running on my host machine (and docker is a boot2docker image on OS X):

```
GOOS=linux go build && docker run -i -t -v ~/src/bosun.org/cmd/scollector:/scollector centos /scollector/scollector -h 192.168.64.1:8070
```

So I am using the centos image. But I don't current have a lot of docker knowledge.

**Comment by PeterGrace** [comment]
So that I can understand the issue better, you are attempting to log data from scollector in the 6 docker containers, to the 7th docker container running bosun.  You're attempting to do so by running `scollector -h http://localhost:8070` in each container?

This would be incorrect because that localhost entry would refer to the docker instance you're currently running in.  If you started the 7th container with argument `-p 8070:8070` then you'll want to run `scollector -h http://<actual-ip-of-your-host-machine>:8070`

However, there's a trick you can do in docker called Linking.  If you link your 6 docker containers to the bosun container by adding `--link <name_of_your_bosun_container>:bosun`, you'll then be able to call `scollector -h http://bosun:8070` and it should work without needing to worry about ephemeral ip addresses or trying to hairpin at your host system.

For more info on linking, check out [this blog post.](http://rominirani.com/2015/07/31/docker-tutorial-series-part-8-linking-containers/)

**Comment by mokshpooja** [comment]
@kylebrandt and @PeterGrace Thanks for the quick response guys. 
Some Clarification- 
- All 7 containers are running inside the same vm and share the same ip but different ports.
- I am trying to collect metrics from the 6 containers through scollector and send over to the 7th container running bosun server.

Just to be sure I change the host from "localhost:8070" to "bosun_server_ip:8070" and still the same errors. 

Any other ideas you guys might have? Also is there a way to see the location and the log files being generated by scollector?

**Comment by mokshpooja** [comment]
@kylebrandt  and @PeterGrace  After adding the container linking here is the error.

` scollector -h bosun:8070
2016/02/03 18:30:11 error: log_unix.go:10: Unix syslog delivery error
2016/02/03 18:30:11 info: main.go:195: OpenTSDB host: http://bosun:8070
2016/02/03 18:30:11 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 18:30:26 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 18:30:41 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 18:30:56 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 18:31:11 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 18:31:26 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2016/02/03 18:31:41 error: interval.go:62: c_systemd: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
`

My concern is that the logs are not being generated by scollector. Is there a way to check this? also the location of the logs?

**Comment by kylebrandt** [comment]
So logs would be the same as stderr I think. I'm guess maybe your container lacks a syslog daemon? Did you try running it in the centos container?

**Comment by mokshpooja** [comment]
@kylebrandt I have a debian container and cannot change to centos because of the applications i have running in my containers.
The logging is working in the 7th container, so my question is what sort of a syslog daemon is consisted in the bosun docker image (since the bosun server installation on the 7th container is from bosun docker image)?

**Comment by mokshpooja** [comment]
@kylebrandt @PeterGrace The linking actually worked but today I am getting this error-
`error: log_unix.go:10: Unix syslog delivery error
2016/02/16 13:24:07 info: main.go:195: OpenTSDB host: http://bosun:8070
2016/02/16 13:24:07 fatal: main.go:220: MaxQueueLen must be >= 500 (BatchSize)
`
Any idea how to fix it?

**Comment by kylebrandt** [comment]
I think that was a bug that got fixed just last night: https://github.com/bosun-monitor/bosun/commit/8b7df5a0ba94ff63d53a95577bcf2c72d083d411

So rebuild scollector?

**Comment by mokshpooja** [comment]
rebuild works!
