### ISSUE TITLE
computations is empty at the time of notification rendering 

### ISSUE THREAD

**Issue by zhenghouzz** [bosun-monitor/bosun#1582]
```
version: bosun version 0.5.0-alpha-dev
git hash: 02dcb890dba931dfc1608f944613dc5be8a7a904
```

I have the following template section to include the computation in the email notification. However, it is always empty. However, the web 'rule editor' page can successfully render the computation formulas. Based on the slack chat with @gbrayut, the last time the computation showing up in his email is from 4/30/2015.

`template computation {
    body = '<p><strong>Computation</strong>

```
<table>
    {{range .Computations}}
        <tr><td><a href="{{$.Expr .Text}}">{{.Text}}</a></td><td>{{.Value}}</td></tr>
    {{end}}
</table>'
```

}`

**Comment by angadsingh** [comment]
Same here. Facing the same issue

**Comment by hamo** [comment]
Same here. empty computations.

**Comment by amitkumar912** [comment]
I'm seeing this issue happen to me too.
Using version 0.5.0.

Any idea on when this will make it in?
