### ISSUE TITLE
Thresholds depending on a running process

### ISSUE THREAD

**Issue by ahaeusge** [bosun-monitor/bosun#1585]
I want to create an alarm with different thresholds depending a process is running or not. I already configured scollector as described in http://bosun.org/scollector/process-monitoring and get data points while the process is running. While the process is not running I get no data points. No data points equals the process is down (or there is a problem with the scollector (configuration)).

**Question:** Is there a cookbook how can I create an alarm with different thresholds depending a process is running or not? Is there a query that if no data points are available then do something?

Below a part of the Bosun Alarm I created so far. However this one is failing if the process is down and no data points are available. Still it might be helpful to understand my questions.

**Comment by ahaeusge** [comment]
```
alert linux.disk.ios_in_progress.too.high {
  macro = alert.default
  
  $resilvering_check = ungroup(last(q("sum:rate:linux.proc.uptime{name=checkarray}", "5m", "")))
  $resilvering_not_running = $resilvering_check < 0

  $q = q("sum:5m-sum:linux.disk.ios_in_progress{dev=*,host=*,hosttype=*}", "10m", "")
  $metric = last($q)
  warn = ($resilvering_not_running && $metric > lookup("linux.disk.ios_in_progress.too.high_normal", "warn")) || $metric > lookup("linux.disk.ios_in_progress.too.high_resilvering", "warn")
  crit = ($resilvering_not_running && $metric > lookup("linux.disk.ios_in_progress.too.high_normal", "crit")) || $metric > lookup("linux.disk.ios_in_progress.too.high_resilvering", "crit")

  $name = xxx
  $description = xxx
  $steps = xxx
}
```

**Comment by gbrayut** [comment]
are they adhoc processes or do they use some kind of init system like systemd/initd/runit. We currently have linux.systemd.unit.activestate and os.service.running metrics as part of undocumented systemd support from https://github.com/bosun-monitor/bosun/pull/1374

There also was a PR for initd/runit support that hasn't been merged (probably needs refactor) https://github.com/bosun-monitor/bosun/pull/1161

or you can add IncludeCount = true to your Proccess settings like so https://github.com/bosun-monitor/bosun/issues/1539 to get linux.proc.count which would be 0 when the process isn't running

**Comment by ahaeusge** [comment]
Hi Greg. Thank you for this very fast answer!!! Great!!
>are they adhoc processes or do they use some kind of init system like systemd/initd/runit.

The process I want to check is the mdadm checkarray which is started monthly by cron. While this process is running I want to set higher thresholds for `linux.disk.ios_in_progress` than while the process is not running.

>or you can add IncludeCount = true to your Proccess settings like so #1539 to get linux.proc.count which would be 0 when the process isn't running. Except for GitHub, is there another place online availble for everybody where this option is documented?

This sounds like what I am looking for. I will try it tomorrow.

Wow. Awesome tool and awesome support!!!
