### ISSUE TITLE
Influx query parser can't handle hyphens

### ISSUE THREAD

**Issue by sysadmin1139** [bosun-monitor/bosun#1587]
This expression should work, given a correct amount of escaping:

    influx("graphite", "select sum(value) from df-root_df_complex-free where env='prod' and node='web'", "2h", "1m", "1m")

The query as it hits the Influx server is logged as:

    SELECT sum(value) FROM "graphite"."default".df WHERE time >= '2016-02-10T22:58:24.288593858Z' AND time <= '2016-02-11T00:57:24.288593858Z' GROUP BY time(1m) fill(none)

Clearly, something is happening around the dash in the measurement name, and the string is getting truncated. Quoting that string gives a parse failure (`expected identifier`), attempting to backslash-escape the hyphen gives `unquoting error, invalid syntax`. Attempting to back-slash escape quotes around the whole string also yields `unquoting error, invalid syntax`. I don't know how to get it to deliver the whole string.

**Comment by kylebrandt** [comment]
Perhaps related to https://github.com/bosun-monitor/bosun/issues/1456

**Comment by kylebrandt** [comment]
Also did you try triple double quotes? `""" foo """`, that was added as part of influx

**Comment by sysadmin1139** [comment]
I saw mention of 'triple quotes' in the Bosun documentation, but wasn't
sure what that was. Single and double quotes I know, but triple?
Triple-double, that's a new one. Will try that.

**Comment by kylebrandt** [comment]
Idea came from python:
https://docs.python.org/3.2/tutorial/introduction.html#strings

Trouble is that backticks were taken by the configuration language.

**Comment by sysadmin1139** [comment]
Enclosing the errant measurement in `"""` gives me `unexpected "\"\"" in func` now. Wrapping the whole clause in triples gives me `unexpected "\"SELECT su"... in func`

Cueing off of `unexpected invalid start of string, must use double qutoes or triple single quotes in input `, I tried wrapping the select statement in triple-single-quotes. This works, but it behaves exactly like double-quotes, in that the query is truncated after `df`.

**Comment by sysadmin1139** [comment]
Any chance this has been dealt with in the new release?

**Comment by sysadmin1139** [comment]
This is still a problem with the 0.5.0 release binary.

```
influx("graphite", "select count(value) from df-mnt-enc_df_complex-free", "2d", "1m", "1h")
```

Gives me this in the Influx logs:

    [query] 2016/06/22 16:45:58 SELECT count(value) FROM graphite."default".df WHERE time >= '2016-06-20T16:45:58.579042151Z' AND time <= '2016-06-22T16:44:58.579042151Z' GROUP BY time(1h) fill(none)

This data is coming from collectd, maybe there is something in there to specify alternate delimiters.

**Comment by kylebrandt** [comment]
Hmmm.. I wonder if updating the vendored influx libs would fix this, don't have an influx test env setup currently myself, anyone willing to try this?

**Comment by gunnaraasen** [comment]
@sysadmin1139 Can you try adding double quotes around the measurement name? E.g.

```
influx("graphite", "select sum(value) from \"df-root_df_complex-free\" where env='prod' and node='web'", "2h", "1m", "1m")
```

**Comment by kylebrandt** [comment]
Or maybe:

`influx("graphite", '''select sum(value) from "df-root_df_complex-free" where env='prod' and node='web' ''', "2h", "1m", "1m")`

**Comment by sysadmin1139** [comment]
That last combination of quotes seems to do the trick.

    [query] 2016/06/25 03:25:43 SELECT sum(value) FROM graphite."default"."df-root_df_complex-free" WHERE env = 'prod' AND node = 'web' AND time >= '2016-06-25T01:25:43.44806831Z' AND time <= '2016-06-25T03:24:43.44806831Z' GROUP BY time(1m) fill(none)

This is going to have to be a docfix internally. And no one will ever get it right. But at least I'll know.

**Comment by kylebrandt** [comment]
I added a note the other day to the docs http://bosun.org/expressions#notes
and an example shows quoting a metric with a period. Happy to add more
there, any suggestions?

**Comment by kylebrandt** [comment]
We can link to
https://docs.influxdata.com/influxdb/v0.13/troubleshooting/frequently_encountered_issues/#single-quoting-and-double-quoting-in-queries
, maybe that would help
