### ISSUE TITLE
changing lookup for active alert leaves it in active state forever

### ISSUE THREAD

**Issue by timurb** [bosun-monitor/bosun#1595]
I have a rule that send alert based on some lookup function:

```
lookup Req_Threshold {
    entry env=preprod {
            RATE=10
        }
    entry env=prod {
            RATE=100
        }
    entry env=* {
            RATE=10
        }
}
```

I've modified it to include one more tag so that it looks now as following:

```
lookup Req_Threshold {
    entry env=preprod,source=* {
            RATE=10
        }
    entry env=prod,source=foo {
            RATE=50
        }
    entry env=prod,source=* {
            RATE=100
        }
    entry env=*,source=* {
            RATE=10
        }
}
```

This made bosun to create alerts for `env=prod`, `env=preprod` (without `source` tags).
The alerts didn't go away even though an alert condition became normal -- rate went above threshold.

After I rolled back the change in config Bosun started to create alerts for `env=prod,source=foo`, `env=prod,source=bar` (a few dozens of such alerts, for all combinations of `env` and `source`) and they remain in active state even after condition became normal.

**Comment by kylebrandt** [comment]
When you say the alerts didn't go away, does that mean they were still on the dashboard, or they were still on the dashboard *and* active? (had the (!) icon)
