### ISSUE TITLE
bosun: alert is being triggered false positive

### ISSUE THREAD

**Issue by ahaeusge** [bosun-monitor/bosun#1597]
We are using Bosun (bosun version 0.3.0 (9386abc03b9d074e42dbbe5eb5944ee88ca641f6) built 2015-07-13T15:17:11Z) and we are getting false positive alerts.

This is the alert block which we have now for a long time:
```
alert vm.counts.deviate {
  macro = alert.crit_only

  $osCount = last(q("avg:openstack.vm.count{service=openstack}", "6m", "1m"))
  $qemuCount = last(q("sum:os.process.count{process=qemu,service=openstack}", "6m", "1m"))
  crit = $osCount != $qemuCount

  $name = xx
  $description = xxx
  $steps = xx
}
```

Since yesterday a lot of false positive alert come even both expressions are delivering the same results.

I checked the expressions of `q("avg:openstack.vm.count{service=openstack}", "10h", "1m")` and `last(q("sum:os.process.count{process=qemu,service=openstack}", "10h", "1m")` and the results for both expressions are always `23` which is expected. And `last(q("avg:openstack.vm.count{service=openstack}", "6m", "1m")) != last(q("sum:os.process.count{process=qemu,service=openstack}", "6m", "1m"))` always delivers `0`. I did this for many dates.

But why is this alert being triggered? It can take up to one minute until all nodes have deliverd their data for metric `os.process.count`, because of this we use start duration 6m and endDuration 1m. 

If an alert is being triggered because not all nodes delivered their data (or instances are down) then I can understand this alert, when I can see this also in the results of the expressions.

When using **no** end duration then I can see that the result is **less** than `23`. The expressions within the alert definition is using a end duration of 1m and using this I always get `23`.

# Result of `$osCount`
<img width="890" alt="expression_1" src="https://cloud.githubusercontent.com/assets/16099134/13073259/efe6a4b2-d49d-11e5-9fe7-2c669cb64509.png">

# Result of `$qemuCount`
<img width="947" alt="expression_2" src="https://cloud.githubusercontent.com/assets/16099134/13073294/2c0a44a8-d49e-11e5-846f-efd0edfd7dde.png">

# Result of `$qemuCount` without end duration
<img width="943" alt="expression_no_downsample" src="https://cloud.githubusercontent.com/assets/16099134/13073310/4069a7f4-d49e-11e5-9ab3-e438c040c16f.png">

# Result of `$qemuCount` again with end duration of 1 minute
<img width="947" alt="expression_1m_downsample" src="https://cloud.githubusercontent.com/assets/16099134/13073338/7338142c-d49e-11e5-860a-a36b46ffcf5e.png">

Update: I wrongly used before downsampling but actually mean end duration as described in http://bosun.org/expressions#qquery-string-startduration-string-endduration-string-seriesset

**Comment by kylebrandt** [comment]
If you captured the value of the variables in the template (either via compultations are Eval) that might help see what Bosun sees the data evaluated as when it triggers. This is a pretty old version, so possible whatever this was fixed

**Comment by ahaeusge** [comment]
If possible I would like to delete this issue. We had for one day a "strange" behavior with false positive alarms and then it stopped. I still wonder about the root cause. As this cannot be reproduced I will never know. In the end Bosun is and was working fine as expected. Sorry for the noise!
