### ISSUE TITLE
Question- What is the difference between bosun.conf and dev.conf? 

### ISSUE THREAD

**Issue by mokshpooja** [bosun-monitor/bosun#1600]
Background- Running the docker image of bosun in its container and feeding data from scollectors from different containers

**Comment by kylebrandt** [comment]
Can you reference the two files you are referring to?

**Comment by mokshpooja** [comment]
Sure.. To my understanding, 
- For making the alarms persistent- one needs to create/update bosun.conf with the alarms (this contains the same content from the rule editor). Than restart bosun server.
`tsdbHost = :4242
smtpHost = smtp.gmail.com:587
emailFrom = BosunDockerSetup@gmail.com
httpListen = :8070
timeAndDate = 202,75,179,136
stateFile = /data/bosun.state
ledisDir = ../ledis_data
checkFrequency = 1m

notification default {
	email = moksh.pooja@gmail.com
	print = true
}

template test {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Name: {{.Alert.Name}}
	<hr>
	<p><strong>Computation</strong>
	<table>
		{{range .Computations}}
			<tr><td><a href="{{$.Expr .Text}}">{{.Text}}</a></td><td>{{.Value}}</td></tr>
		{{end}}
	</table>`
}

alert test {
    template = test
	$metric = q("sum:rate{counter,,1}:os.cpu{host=*}", "1h", "")
	$avg_metric = avg($metric)
	crit = $avg_metric < 5 || $avg_metric > 8
	warn = $avg_metric < 2 || $avg_metric > 10
}
`
When I do this I get this error `could not open syslog: Unix syslog delivery error
2016/02/18 09:51:20 fatal: main.go:88: open dev.conf: no such file or directory`
on doing a bit of searching i found (https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/dev.sample.conf), the content is the same as bosun.conf and it is unclear where to locate dev.conf since cmd folder doesn exist in the docker image installation

**Comment by mokshpooja** [comment]
Observation- When there are no changes made to /data/bosun.conf
`root@c506a1b59f1d:/# ls -la
total 100
drwxr-xr-x  60 root root 4096 Feb 18 12:25 .
drwxr-xr-x  60 root root 4096 Feb 18 12:25 ..
-rwxr-xr-x   1 root root    0 Feb 18 12:24 .dockerenv
-rwxr-xr-x   1 root root    0 Feb 18 12:24 .dockerinit
drwxr-xr-x   2 root root 4096 Nov  9 20:53 bin
drwxr-xr-x   2 root root 4096 May  4  2015 boot
drwxr-xr-x   2 root root 4096 Nov 11 16:14 bosun
drwxr-xr-x   2 root root 4096 Feb 18 12:24 data
drwxr-xr-x   5 root root  360 Feb 18 12:24 dev
drwxr-xr-x  57 root root 4096 Feb 18 12:24 etc
drwxr-xr-x   5 root root 4096 Feb 18 12:24 hbase
drwxr-xr-x   2 root root 4096 May  4  2015 home
drwxr-xr-x   4 root root 4096 Feb 18 12:24 ledis_data
drwxr-xr-x   8 root root 4096 Jun 22  2012 lib
drwxr-xr-x   2 root root 4096 Nov  9 20:52 lib64
drwxr-xr-x   2 root root 4096 Nov  9 20:51 media
drwxr-xr-x   2 root root 4096 May  4  2015 mnt
drwxr-xr-x   2 root root 4096 Nov  9 20:51 opt
dr-xr-xr-x 138 root root    0 Feb 18 12:24 proc
drwx------   2 root root 4096 Nov  9 20:51 root
drwxr-xr-x   5 root root 4096 Feb 18 12:24 run
drwxr-xr-x   2 root root 4096 Nov  9 20:53 sbin
drwxr-xr-x   2 root root 4096 Nov 11 16:14 scollector
drwxr-xr-x   2 root root 4096 Jun 10  2012 selinux
drwxr-xr-x   2 root root 4096 Nov  9 20:51 srv
dr-xr-xr-x  13 root root    0 Feb 18 12:24 sys
drwxrwxrwt   7 root root 4096 Feb 18 12:25 tmp
drwxr-xr-x  10 root root 4096 Feb 18 12:25 tsdb
drwxr-xr-x  20 root root 4096 Feb 18 12:24 usr
drwxr-xr-x  18 root root 4096 Feb 18 12:24 var
root@c506a1b59f1d:/# cd data
root@c506a1b59f1d:/data# ls-la
bash: ls-la: command not found
root@c506a1b59f1d:/data# ls -la
total 28
**drwxr-xr-x  2 root root  4096 Feb 18 12:24 .
drwxr-xr-x 60 root root  4096 Feb 18 12:25 ..
-rw-r--r--  1 root root    56 Nov  2 22:32 bosun.conf
-rw-------  1 root root 32768 Feb 18 12:24 bosun.state**
`
After updating bosun.conf and restarting the server, /data/-

`root@c3240bc5f400:/# cd /data
root@c3240bc5f400:/data# ls -la
total 12
drwxr-xr-x  2 root root 4096 Feb 18 10:30 .
drwxr-xr-x 59 root root 4096 Feb 18 12:29 ..
-rwxrwxrwx  1 root root  789 Feb 18 10:24 bosun.conf
`
bosun.conf does not exist

**Comment by mokshpooja** [comment]
So I am trying to understand-
1. What the content of bosun.conf and dev.conf should be
2. What should be the location of these files shouls be
3. Why do bosun.state disappear after bosun.conf is updated

**Comment by kylebrandt** [comment]
Hmm... you are running in docker?

**Comment by mokshpooja** [comment]
yes I am.. right now I have no clue how to fix this

**Comment by PeterGrace** [comment]
@mokshpooja - 

1. Are you using the `stackexchange/bosun` image from the docker registry?
2. Can you specify how you're starting the container?  If you're using docker-compose, please provide the yaml config file.  If you're running in straight docker, please give me the command line you've used to start the container.
3. Are you mounting the /data folder on your local host?
4. Have you made changes to /etc/supervisor/conf.d inside the docker container?

**Comment by mokshpooja** [comment]
@PeterGrace 
1. Yes I am using stackexchange/bosun
2. I am using docker-compose.yml-
`bosun:
  build: ./bosun
  ports:
   - "8070:8070"
   - "4242:4242"
   - "8070:8070/tcp"
  expose:
   - "8070"
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"`

3. In my setup I am using vagrant, which spawns the docker containers (7 containers talking to each other) through docker-compose.yml. Bosun server is 1 f 7 docker containers, thus yes /data folder in mounted inside the docker container inside vagrant machine (vm)
4. No changes on /etc/supervisor/conf.d

**Comment by PeterGrace** [comment]
@mokshpooja I believe your docker-compose file may be wrong, because the `build` imperative indicates you are making a docker image from your local source tree.  Here's what I have for a docker-compose.yml file for a bosun test:

```
bosun:
  restart: always
  image: stackexchange/bosun
  ports:
    - "8070:8070"
```
