### ISSUE TITLE
Question- Does bosun come with its inbuilt smtp server? or is there any that is a suggested configuration?

### ISSUE THREAD

**Issue by mokshpooja** [bosun-monitor/bosun#1601]

**Comment by vitorboschi** [comment]
No. In order to make Bosun capable of sending alert mails, you have to set the smtpHost, smtpUsername and smtpPassword diretives in bosun.conf. For more info, look at http://bosun.org/configuration

**Comment by mokshpooja** [comment]
Thanks @vitorboschi !
SO If I wanted to setup bosun with my admin gmail SMTP server I just need to add- 
`smtpHost = smtp.gmail.com:587
emailFrom = adminEmail@gmail.com
smtpUsername= adminEmail@gmail.com
smtpPassword= *password_removed*`
Is there anything else that I need to do, like install any packages or open any output/going smtp ports since I am running this inside a docker container?
