### ISSUE TITLE
Automatically Close Normal Alerts

### ISSUE THREAD

**Issue by rohitpmore** [bosun-monitor/bosun#1607]
Hi,
  I have a peculiar requirement, where I would like to close alerts automatically when they go back to Normal state. I am quite happy with the rest of the Alert Life Cycle. How should it affect the overall Bosun performance?

**Comment by kylebrandt** [comment]
Bosun doesn't have that feature. You could do it via the api. I don't really think it would impact performance, but you might get a lot of alert noise.

Perhaps the `log` alert directive might do what you want? That basically bypasses the entire alert cycle, and just triggers when the condition is true every nth check)

**Comment by rohitpmore** [comment]
"Log" alerts are not that useful, since I want to handle other Alert events such as Ack. 
What I did was tweak some of code, so that whenever alert goes to "Normal" state, close the incident in same way the "unknown" alerts are closed when "ignoreUnknown = true". 
That code changes seems to be working for me for now :)

Thanks.

**Comment by knowroozi** [comment]
FWIW i added this as a configuration on the alert for a use-case we needed at our company. If the key is set inside the alert config, the issue will automatically close and notify if it returns to the normal state.

https://github.com/knowroozi/bosun/commit/c0e09081d3f45574c237fe278f18a971edbe91d4

I can submit a PR if this is desired to be included to the project

**Comment by rohitpmore** [comment]
After fishing in alerts for quite a while, we realized it is not such a great idea to automatically close normal alerts. 😆 
Thanks.

**Comment by earwin** [comment]
@knowroozi your patches fail sometimes:
```
2016/08/30 17:00:53 info: check.go:529: check alert servers_packet_loss start
2016/08/30 17:00:53 info: check.go:553: check alert servers_packet_loss done (25.717244ms): 3 crits, 2 warns, 0 unevaluated, 0 unknown
2016/08/30 17:00:54 info: search.go:207: Backing up last data to redis
2016/08/30 17:01:03 info: alertRunner.go:55: runHistory on servers_packet_loss took 10.13331037s
2016/08/30 17:01:53 info: check.go:529: check alert servers_packet_loss start
2016/08/30 17:01:53 info: check.go:553: check alert servers_packet_loss done (23.790258ms): 3 crits, 1 warns, 0 unevaluated, 0 unknown
2016/08/30 17:02:00 info: check.go:249: auto close servers_packet_loss{instance=[REDACTED]} because returned to normal
2016/08/30 17:02:00 error: check.go:252: cannot close active alert
2016/08/30 17:02:03 info: alertRunner.go:55: runHistory on servers_packet_loss took 10.205952693s
```
I've not investigated in full yet, but have a feeling this has something to do with notification chain that is still active for that alert.
