### ISSUE TITLE
'Invalid command param' when testing alerts

### ISSUE THREAD

**Issue by cedw93** [bosun-monitor/bosun#1613]
**Images are as links, sorry.**

When using the latest master (cloned today 23rd Feb) I get the following error when testing alerts from the rule editor page:

[Error message in bosun ui](http://imgur.com/9aWmXqJ)

Using the following Config:

```
tsdbHost = localhost:4242
stateFile = bosun.state

notification level1_alert {
        post = http://localhost:8090/notify-endpoints
        body = {"subject": {{.|json}},"html":"This is a level 1 alert"}
        contentType = application/json
        print = true
        next = level1_alert
        timeout = 20m
}

template sbx_rs {
    subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
    body = `<p>Name: {{.Alert.Name}}
    <p>Tags:
    <table>
        {{range $k, $v := .Group}}
            <tr><td>{{$k}}</td><td>{{$v}}</td></tr>
        {{end}}
    </table>`
}

alert primary.count {
    template = sbx_rs
    critNotification = level1_alert
    $min = min(q("sum:primary.count{host=*}", "1h", ""))
    crit = $min < 1
}
```

And has the following request:

[JS console error](http://i.imgur.com/h4OfExV.png)
[Request Headers](http://i.imgur.com/hg6OaXA.png)
[Request params and body](http://i.imgur.com/mXROJk1.png)

**Comment by kylebrandt** [comment]
Hmmm.. The stateFile is no longer used since the new version is on Redis. What if you remove that and restart? 

Either way though I can't currently replicate this, the test works okay for me (except I changed the metric in $min for one that exists on my system) in our prod setup :-/

**Comment by cedw93** [comment]
I removed the state file and the same error persists, running go version go1.5.1 linux/amd64 on AWS EC2 instance, have you tested on amazon linux before?
