### ISSUE TITLE
Not sending email notification

### ISSUE THREAD

**Issue by mokshpooja** [bosun-monitor/bosun#1618]
Hi guys,
I have a simple config file with simple crit and warn alarms (notification on dashboard and email). I do get notifications/alarms on the dashboard when critNotification and warnNotification is true but do not get an email on my gmail account.

Can someone help me figure out what might be wrong?

Here is my config file-
`tsdbHost = localhost:4242
smtpHost = stmp.gmail.com:587
emailFrom = _adminmail_@gmail.com
smtpUsername=  _adminmail_@gmail.com
smtpPassword= _password_
httpListen = :8070
timeAndDate = 202,75,179,136
stateFile = /data/bosun.state
# ledisDir = ../ledis_data

checkFrequency = 1m

notification notif2 {
    email = "recipient"@gmail.com
    next = notif2 
    print = true
}

template test {
    subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
    body = `<p>Name: {{.Alert.Name}}
    <p>Tags:
    <table>
        {{range $k, $v := .Group}}
            <tr><td>{{$k}}</td><td>{{$v}}</td></tr>
        {{end}}
    </table>`
}

alert test {
    template = test
    critNotification = notif2
    $metric = q("sum:rate:os.cpu{host=*}", "1h", "")
    $avg_metric = avg($metric)
    crit = $avg_metric < 7.2 || $avg_metric > 8
}

template test.cpu-low {
    subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
    body = `<p>Name: {{.Alert.Name}}
    <p>Tags:
    <table>
        {{range $k, $v := .Group}}
            <tr><td>{{$k}}</td><td>{{$v}}</td></tr>
        {{end}}
    </table>`
}

alert test.cpu-low {
    template = test.cpu-low
        warnNotification = notif2
    $metric = q("sum:rate:os.cpu{host=*}", "1h", "")
    $avg_metric = avg($metric)
    warn = $avg_metric < 2 || $avg_metric > 10
}
`

Here are the info and error msgs on the terminal-
`info: web.go:125: tsdb host: localhost:4242
2016/02/24 13:02:07 info: check.go:520: check alert test start
2016/02/24 13:02:07 info: check.go:520: check alert test.cpu-low start
2016/02/24 13:02:08 error: funcs.go:880: Error on tsdb query 1: opentsdb: {"start":1456315327,"end":1456318927,"queries":[{"agg           regator":"sum","metric":"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'host'
2016/02/24 13:02:08 error: funcs.go:880: Error on tsdb query 1: opentsdb: {"start":1456315327,"end":1456318927,"queries":[{"agg           regator":"sum","metric":"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'host'
2016/02/24 13:02:08 error: funcs.go:880: Error on tsdb query 2: opentsdb: {"start":1456315327,"end":1456318927,"queries":[{"agg           regator":"sum","metric":"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'host'
2016/02/24 13:02:08 error: funcs.go:880: Error on tsdb query 2: opentsdb: {"start":1456315327,"end":1456318927,"queries":[{"agg           regator":"sum","metric":"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'host'
2016/02/24 13:02:08 error: check.go:612: opentsdb: {"start":1456315327,"end":1456318927,"queries":[{"aggregator":"sum","metric"           :"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'host'
2016/02/24 13:02:08 error: check.go:537: Error checking alert test.cpu-low: opentsdb: {"start":1456315327,"end":1456318927,"que           ries":[{"aggregator":"sum","metric":"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'hos           t'
2016/02/24 13:02:08 info: check.go:544: check alert test.cpu-low done (657.014062ms): 0 crits, 0 warns, 0 unevaluated, 0 unknow           n
2016/02/24 13:02:08 info: alertRunner.go:56: runHistory on test.cpu-low took 71.951µs
2016/02/24 13:02:08 error: check.go:612: opentsdb: {"start":1456315327,"end":1456318927,"queries":[{"aggregator":"sum","metric"           :"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'host'
2016/02/24 13:02:08 error: check.go:537: Error checking alert test: opentsdb: {"start":1456315327,"end":1456318927,"queries":[{           "aggregator":"sum","metric":"os.cpu","rate":true,"rateOptions":{},"tags":{"host":"*"}}]}: No such name for 'tagk': 'host'
2016/02/24 13:02:08 info: check.go:544: check alert test done (673.818711ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2016/02/24 13:02:08 info: alertRunner.go:56: runHistory on test took 141.893µs
2016/02/24 13:03:07 info: check.go:520: check alert test.cpu-low start
2016/02/24 13:03:07 info: check.go:520: check alert test start
2016/02/24 13:03:07 info: check.go:544: check alert test.cpu-low done (190.966417ms): 0 crits, 3 warns, 0 unevaluated, 0 unknown
2016/02/24 13:03:07 info: check.go:544: check alert test done (184.91297ms): 3 crits, 0 warns, 0 unevaluated, 0 unknown
2016/02/24 13:03:07 info: alertRunner.go:56: runHistory on test.cpu-low took 7.683187ms
2016/02/24 13:03:07 info: notify.go:44: warning: test.cpu-low on 8756d7213d7a
2016/02/24 13:03:07 info: alertRunner.go:56: runHistory on test took 11.07618ms
2016/02/24 13:03:07 info: notify.go:44: critical: test on 8756d7213d7a
2016/02/24 13:03:07 info: notify.go:44: warning: test.cpu-low on ee4b7cbbe068
2016/02/24 13:03:07 info: notify.go:44: critical: test on ee4b7cbbe068
2016/02/24 13:03:07 info: notify.go:44: warning: test.cpu-low on 1d6aa2f30c7a
2016/02/24 13:03:07 info: notify.go:44: critical: test on 1d6aa2f30c7a
2016/02/24 13:04:07 info: search.go:199: Backing up last data to redis
2016/02/24 13:04:07 info: notify.go:122: Batching and sending unknown notifications
**2016/02/24 13:04:07 info: notify.go:152: Done sending unknown notifications**
`

**Comment by westsouthnight** [comment]
I have some situation, please help. Test from GUI works, but alerts not received.
