### ISSUE TITLE
Scollector on centos 6 filling logs with c_systemd

### ISSUE THREAD

**Issue by cleonte** [bosun-monitor/bosun#1623]
Hi,

i'm running your collector on centos 6 and it fills syslog with this

 error: interval.go:62: c_systemd: The name org.freedesktop.systemd1 was not provided by any .service files

any idea how can i make it stop?

Cheers

**Comment by gbrayut** [comment]
just pushed a fix. You can build from master or wait for the next release for a new binary

**Comment by cleonte** [comment]
Hi Again,

i have this collector version/opt/scollector/scollector --version
scollector version 0.5.0-rc3 (e69b9e71ad635705370b74000730d3e1a09e6e1d) built 2016-05-16T16:35:48

and now get this message again in syslog:

error: interval.go:62: c_systemd: The name org.freedesktop.systemd1 was not provided by any .service files

any idea?

Cheers

**Comment by cleonte** [comment]
Sorry,

please disregard, was running and old version

Cheers
