### ISSUE TITLE
Closing annotation modal popup in graph page causes the page to scroll to the bottom

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1625]
Repro steps:

1. Load a graph with annotations.
2. Click on the annotation to open the modal.
3. Close the modal popup.

The browser will scroll to the bottom of the page.

**Comment by kylebrandt** [comment]
Happens in FF, not chrome. Noticeable when you do something=* and get a lot series.

**Comment by kylebrandt** [comment]
@alienth Can you try that branch to verify the fix. I was able to replicate it in FF on Mac, and it seems to be fixed:

![image](https://cloud.githubusercontent.com/assets/1692624/13464921/3cf129a2-e061-11e5-8af2-d8c7f8645368.png)
