### ISSUE TITLE
Docker image with volumes

### ISSUE THREAD

**Issue by cleonte** [bosun-monitor/bosun#1626]
Hi Bosun Team,

i'm just trying bosun and think its pretty cool! One question, do you have a docker image that exports volumes? would be cool to persist data across container reboots 

Cheers

**Comment by PeterGrace** [comment]
As the [Dockerfile](https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/docker/run/Dockerfile) here shows, there are currently no VOLUME statements to export the data directories at this time.  The docker image started out as a "try it out before you invest a lot of time in hbase on a product you find didn't meet your needs."

That being said, if we were to edit the container image to be smart about the /data and /hbase/hbase/... data folders, we could conceivably export them, thereby allowing state to remain.  It'd take a couple changes though, including writing some shell scripting and amending the Dockerfile.

**Comment by cleonte** [comment]
Think that would be a good idea, that won't mean that the docker image would be used for 'production' just that the state will remain in case the container crashes

and will be useful for small small deployments

Cheers

**Comment by bigkraig** [comment]
@cleonte you can always start the old container again, you don't need to 'docker run' it every time.

**Comment by cleonte** [comment]
yeah, no

ended up doing something else

using this https://github.com/PeterGrace/opentsdb-docker - this one knows volumes for opentsdb and i ran bosun from systemd connected to that opentsdb instance, easier to play with than bosun docker image

Cheers

**Comment by lukaspustina** [comment]
@cleonte You could try this https://gist.github.com/lukaspustina/a04f66461c72f8adc92f6283c1c4c6a0. We use use this in production (almost like this). It bases on @PeterGrace opentsdb Docker Image and a second one that has a recent bosun release (0.5.0-rc2).
