### ISSUE TITLE
Proposal: End Darwin Support for Scollector

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1631]
We added darwin support because when we first started to develop scollector the devs were on mac, os it was handy for early testing.

I personally find it useless, does anyone actually depend on darwin support that uses scollector?

**Comment by jareksm** [comment]
It's not really necessary, but I do use OSX and Linux for coding/testing.

Now that I'm more familiar with scollector's internals, I was thinking more about rewriting it in a more golang idiomatic way. Use more structures/methods/interfaces/goroutines/channels.

Try to make it faster and easier to reread or stream metrics. Also doing things this way should make it easier to add deduplication. I'm still thinking about the overall design.
