### ISSUE TITLE
Unable to query bosun after running for a minute

### ISSUE THREAD

**Issue by VictoriaD** [bosun-monitor/bosun#1649]
I have installed Hbase, opentsdb and bosun on a machine running Centos7.
I can see the bosun website fine, but any query I try to run from the graph page is giving some error.
I've put the bosun output into a log file, and there are 2 kinds of errors that pop up. Sometime it's too many open files:

> 2016/03/04 11:10:23 error: queue.go:102: Post http://localhost:8070/api/put: dial tcp 127.0.0.1:8070: socket: too many open files

Sometimes it's just a timeout.

> 2016/03/04 11:14:06 error: queue.go:102: Post http://localhost:8070/api/put: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Sometimes restarting seems to help, other times not so much. The longest I've had bosun running without these errors is a day.

**Comment by kylebrandt** [comment]
What version of Bosun / scollector?

**Comment by VictoriaD** [comment]
I’m currently using the latest version of the binaries downloaded from here:
https://github.com/bosun-monitor/bosun/releases/download/0.5.0-alpha/bosun-linux-amd64

**Comment by kylebrandt** [comment]
Can you try the more recent RC1 and see if the problems continue?
https://github.com/bosun-monitor/bosun/releases/tag/0.5.0-rc1

**Comment by VictoriaD** [comment]
This is still giving the timeout errors:
2016/03/04 14:45:17 error: check.go:605: Post http://localhost:4242/api/query: net/http: request canceled
2016/03/04 14:45:17 error: check.go:530: Error checking alert disk.is.almost.full: Post http://localhost:4242/api/query: net/http: request canceled

***
Please consider the environment before printing this e-mail or any attachments.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. If you have received this message in error, please notify us and remove it from your system.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of  UK Mail Group Plc or any of its subsidiaries.
UK Mail Group Plc is registered and incorporated in England.
Registered Office: Express House, 120 Buckingham Avenue, Slough, SL1 4LZ, United Kingdom.
Registered Company No.: 02800218

**Comment by kylebrandt** [comment]
Sounds like maybe something is using too many files, in Linux connections are files. Can you check the file limits and current number of files used for bosun, opentsdb, and hbase related processes?

**Comment by VictoriaD** [comment]
OK, how do I do that? I don’t know what commands to use.

***
Please consider the environment before printing this e-mail or any attachments.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. If you have received this message in error, please notify us and remove it from your system.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of  UK Mail Group Plc or any of its subsidiaries.
UK Mail Group Plc is registered and incorporated in England.
Registered Office: Express House, 120 Buckingham Avenue, Slough, SL1 4LZ, United Kingdom.
Registered Company No.: 02800218

**Comment by kylebrandt** [comment]
```
[root@co-tsdb01 ~]# grep 'open files' /proc/$(pidof bosun)/limits
Max open files            65536                65536                files
[root@co-tsdb01 ~]# ls -l /proc/$(pidof bosun)/fd/ | wc -l
412
```
etc...

**Comment by kylebrandt** [comment]
Oh, and maybe just go to the opentsdb web interface (usually on port 4242) and see if you have any query issues there. You can also see OpenTSDB's logs in that interface.

**Comment by VictoriaD** [comment]
This is the result I got from the bosun process:
[root@bosun-test ~]# grep 'open files' /proc/15371/limits
Max open files            1024                 4096                 files
[root@bosun-test ~]# ls -l /proc/15371/fd/ | wc -l
157

I don’t know specifically which processes are for opentsdb and hbase, but I think they are labelled java. These are the results from my 2 java processes:

[root@bosun-test ~]# grep 'open files' /proc/11048/limits
Max open files            4096                 4096                 files
[root@bosun-test ~]# ls -l /proc/11048/fd/ | wc -l
240
[root@bosun-test ~]# grep 'open files' /proc/11102/limits
Max open files            65535                65535                files
[root@bosun-test ~]# ls -l /proc/11102/fd/ | wc -l
3465

The web page for opentsdb just gave “Error The requested URL could not be retrieved”. Do I need to open the port for this?


***
Please consider the environment before printing this e-mail or any attachments.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. If you have received this message in error, please notify us and remove it from your system.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of  UK Mail Group Plc or any of its subsidiaries.
UK Mail Group Plc is registered and incorporated in England.
Registered Office: Express House, 120 Buckingham Avenue, Slough, SL1 4LZ, United Kingdom.
Registered Company No.: 02800218

**Comment by VictoriaD** [comment]
I opened port 4242 on that machine, and am trying to get to it through firefox, but just getting a spinning wheel at the moment. But not the error message like before.

***
Please consider the environment before printing this e-mail or any attachments.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. If you have received this message in error, please notify us and remove it from your system.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of  UK Mail Group Plc or any of its subsidiaries.
UK Mail Group Plc is registered and incorporated in England.
Registered Office: Express House, 120 Buckingham Avenue, Slough, SL1 4LZ, United Kingdom.
Registered Company No.: 02800218

**Comment by kylebrandt** [comment]
Opentsdb log files? In /var/log/opentsdb/ in my setup.

What sort of resources does this machine have, and how many things are sending it to it (to get a rough idea of load)?

**Comment by kylebrandt** [comment]
We use cloudera manager to setup hbase. That can help show if there are problems on the hbase side of things ( documented our setup the other day at http://kbrandt.com/post/bosun_arch/ )

**Comment by VictoriaD** [comment]
This is the result of top:
top - 15:29:18 up 7 days,  1:02,  1 user,  load average: 0.00, 0.01, 0.05
Tasks:  95 total,   2 running,  93 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.7 us,  0.3 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  1884512 total,   658552 free,   551428 used,   674532 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  1049824 avail Mem

And I’ve got 13 scollectors pointing at it from elsewhere. They are each sending about 50 metrics, once a minute.

I’ve found my opentsdb log files in the same place you suggested.
The error one has a time stamp from last week on it. The out one has stuff from yesterday, but mostly marked [INFO]. The only error seems to be this, which doesn’t seem relevant:
11:44:25,848 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@28:27 - no applicable action for [appender-ref], current ElementPath  is [[configuration][appender-ref]]


***
Please consider the environment before printing this e-mail or any attachments.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. If you have received this message in error, please notify us and remove it from your system.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of  UK Mail Group Plc or any of its subsidiaries.
UK Mail Group Plc is registered and incorporated in England.
Registered Office: Express House, 120 Buckingham Avenue, Slough, SL1 4LZ, United Kingdom.
Registered Company No.: 02800218

**Comment by VictoriaD** [comment]
Thanks for making that available! I will take the time to read it through. It may be that InfluxDB is a better option for me than Hbase – I haven’t used Hbase before, and have no on site knowledge to tap into either!

Is it easy to set up and get Influx going with Bosun? Does it replace both OpenTSDB and Hbase, or just Hbase?


***
Please consider the environment before printing this e-mail or any attachments.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. If you have received this message in error, please notify us and remove it from your system.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of  UK Mail Group Plc or any of its subsidiaries.
UK Mail Group Plc is registered and incorporated in England.
Registered Office: Express House, 120 Buckingham Avenue, Slough, SL1 4LZ, United Kingdom.
Registered Company No.: 02800218

**Comment by kylebrandt** [comment]
Are you open to joining our chat, http://bosun.org/slackInvite , might help to get some additional input, and a fair amount of back and forth here for troubleshooting.

Logback is the Java mechanism for logging with opentsdb. If it is throwing an error, maybe it can get it's logs anywhere else without configuration.

InfluxDB would be a replacement for both OpenTSDB and HBase. Basically bosun queries stuff for time series, InfluxDB is another time series database option.

**Comment by VictoriaD** [comment]
I’ve joined the general channel just now

***
Please consider the environment before printing this e-mail or any attachments.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. If you have received this message in error, please notify us and remove it from your system.
Any views or opinions expressed are solely those of the author and do not necessarily represent those of  UK Mail Group Plc or any of its subsidiaries.
UK Mail Group Plc is registered and incorporated in England.
Registered Office: Express House, 120 Buckingham Avenue, Slough, SL1 4LZ, United Kingdom.
Registered Company No.: 02800218
