### ISSUE TITLE
Data Queueing when TSDB is offline

### ISSUE THREAD

**Issue by NickCraver** [bosun-monitor/bosun#166]
*V2 Feature Request*

Bosun should queue data itself when OpenTSDB is down. If not for everything, then at least for agents that *aren't* scollector it should take the data and queue it up for later insert.

This allows much more flexibility when performing maintenance on the TSDB nodes/cluster and user scripts that aren't scollector to just not care about of handle the collector's backend status.

The queue should also probably have a configurable memory cap if that's doable.

**Comment by kylebrandt** [comment]
This is something we decided to leave up to client libraries so the memory is distributed. This also makes them more robust since data gets queued if Bosun or OpenTSDB is down, and not just if OpenTSDB is down.
