### ISSUE TITLE
Provisions for Best Effort fast alerting.

### ISSUE THREAD

**Issue by CheRuisiBesares** [bosun-monitor/bosun#1664]
Hi all.

I have been trying to use Bosun to do some "best effort" fast detection but im having some problems getting it to work for our use case. A little background for anyone interested: We currently have 30+ edge locations around the world. We collect data about the functionality of these different edge data centers in a few different ways. We use tcollector to collect metrics at the edges and several external systems to collect metrics from various locations. Various network conditions that are outside of our control (something like a peering partner / transit provider cable is cut etc ) make it very difficult to talk declaratively about when metrics will make it into tsdb. All of our systems attempt to get the metrics back to one of our core facilities in a "best effort" fashion. By all reasonable standards these would probably be considered bad metrics. Our strategy here is to essentially have enough observers that one of the systems will make it back home and provide us something actionable that we can alert on.

The problems that we have been encountering is that when we write our alerts we don't want to say the average over the last "5m" we want to say the average over the last available 5m window. Obviously we could pair this with some kind of since alert that looks back over a longer period and determines if the metric stream has just been dead for too long which is probably actionable. So we would like something like `last` but with the ability to return a Series Set. So ideally we would love to do something like

```
alert example {
   macro = needed_parts
   $last_point = last_seen(q("unreliable_metric_a","20m",""))
   $last_avalible_series_set = q("unreliable_metric_a","5m",$last_point)
   crit = avg($last_avalible_series_set) > $some_numer
}
```

The important function here would be last_seen. It lets us know when the last data point was put in the set and returns a string. That way we can do math on the last available series. I have tried changing the query to start looking back at 10m something like:

```
alert example {
   macro = needed_parts
   $last_avalible_series_set = q("unreliable_metric_a","5m","10m")
   crit = avg($last_avalible_series_set) > $some_numer
}
```

The issue here is that in best case we have a 10 minute delay. Which is the threshold we needed to ensure that the alert didn't go unknown. In our use case one node can lag for up to 10 minutes in any one  metric and that isn't an unknown or alert worth state but all of our other nodes that are giving data right up to the last minute have a 10 minute delay which isn't great. 

Using a combination of ignoreUnkown and the `band` function we have been able to get some of the alerts working the way we want but it hasn't been very easy. As I mentioned above for anyone host we would like to have any number of these alerts for a single edge location and eventually combined them into something more sane that says if some % of the unreliable metrics are reporting failure alert. 

Anyway im wondering an im doing this correctly or if there is something fundamental im missing in my use of Bosun?

**Comment by kylebrandt** [comment]
Related is another thing someone is trying to do https://github.com/bosun-monitor/bosun/issues/1656 - they are related in that having duration math would possibly be helpful.

**Comment by kylebrandt** [comment]
I wonder if a weighted average that favors more recent observations might be good here.

**Comment by CheRuisiBesares** [comment]
That would definitely be an interesting addition to the bosun arsenal. It doesn't open up all the other built in functions but it would probably be interesting for the above example.

**Comment by kylebrandt** [comment]
Seems like it might be ill suited to the task, [from R docs](http://www.inside-r.org/packages/cran/TTR/docs/GD)

> Warning
> Some indicators (e.g. EMA, DEMA, EVWMA, etc.) are calculated using the indicators' own previous values, and are therefore unstable in the short-term. As the indicator receives more data, its output becomes more stable. See example below.
