### ISSUE TITLE
cmd/scollector: MSSQL Express instances should not be monitored

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1678]
Currently if you have a SQL Express instance you will probably get the following error message:

error: interval.go:64: bosun.org/cmd/scollector/collectors.c_mssql: sql_windows.go:265: Exception occurred. (Invalid class )

It detects the instance but the Win32_PerfRawData_MSSQLSERVER_SQLServerDatabases (default instance) or 
Win32_PerfRawData_MSSQL<NAMEDINSTANCE>_MSSQL<NAMEDINSTANCE>Databases (named sql instace) WMI classes don't exist. 

Currently the only filtering we do is exclude disabled instances or Windows Internal Database instances (services named like MSSQL$MICROSOFT##WID), but we should also find a way to exclude express instances. [This](http://stackoverflow.com/questions/16709536/how-to-know-the-version-and-edition-of-sql-server-through-registry-search) seems to indicate there should be some registry keys we can use to detect express edition.

The MDT default install includes an named express instance (service name MSSQL$ADK see co-wds01 at Stack Exchange) which we can use for testing.

**Comment by joodies** [comment]
Hi,  how can i skip this error? scollector can not work, keep showing this error.

**Comment by gbrayut** [comment]
Sorry... I haven't found a good way to detect/exclude SQL Express yet.

As mentioned at https://godoc.org/bosun.org/cmd/scollector you can add -f="*,-mssql" when starting scollector to exclude the sql collector. If you are using Scollector as a Windows Service installed at c:\Program Files\scollector you can use the following PowerShell script to edit the command line:

Set-ItemProperty hklm:\SYSTEM\CurrentControlSet\Services\scollector -Name ImagePath -Value '"c:\Program Files\scollector\scollector.exe" -f="*,-mssql"'

**Comment by joodies** [comment]
Thanks, that helped ATM.
