### ISSUE TITLE
Metric tags applied erroneously when performing subsequent graph lookups

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1679]
When changing the 'metric' field on the graph page from one metric to another, any tags searched for on the first metric will apply to the second metric, even if the second metric has no such tag. This will result in 'no results' for the second metric if it does not have that tag.

To repro:

1. Graph some metric that has a number of tags. Fill in a value for one of those tags.
1. From the same view, change the 'metric' field to another metric which does not share the specified tag from above. Query this new metric.
1. The resulting graph will always have new results, as the query is still searching for that old tag, despite the tag disappearing from the form page. This can be verified by looking at the generated query at the bottom of the page.

**Comment by alienth** [comment]
I've hit this several times without realizing it and it caused me much confusion. I suspect it is an easy trap to fall in. Would be nice for the form to discard searching for tags which don't apply to any subsequent metric search, or at least keep that form field displayed so the user can manually wipe it out.

**Comment by gbrayut** [comment]
This is a real pain point. Any time you change metrics on the graph page you are likely to get no results due to the extra tags (you have to open a new graph tab to work around it). Not sure when the bug was introduced (must have been recently) but causing a lot of pain when troubleshooting issues. @kylebrandt @captncraig please look at this when you have time.

**Comment by kylebrandt** [comment]
Guess of the top of my head is that I broke it in
https://github.com/bosun-monitor/bosun/commit/e8d299e18fb578d34eca37d5214c243206be5812
, not able to verify right now though

**Comment by kylebrandt** [comment]
If you find out that is it, feel free to revert the commit and I'll fix it
when I get back.
