### ISSUE TITLE
Add bosun alarm rules???

### ISSUE THREAD

**Issue by msqiao** [bosun-monitor/bosun#1680]
hello:
    I want to ask, how to through the Java language to add the corresponding alarm rules and amendments, alarm information query and view of Valles long HTTP API does not find the answers I need. Thank you who can help me to explain, thank you.

**Comment by captncraig** [comment]
I'm not clear what you are looking for. Are you looking for a way to add rules to a bosun instance. We store rules and alerts in a config file you can edit and restart bosun.

**Comment by msqiao** [comment]
Thank you for your answer, I am sorry I may not describe the problem clearly, I would like to ask is whether the bosun provides the API can add alarm rules and query alarm events?

**Comment by kylebrandt** [comment]
Bosun does not provide a way to add rules via an API. It is all in the config file, and the process needs to restart to pick up changes in that file.

Open alerts can be queried via `http://bosun/api/alerts`

**Comment by msqiao** [comment]
thank you for your answer

**Comment by msqiao** [comment]
Bosun through what kind of way can be restarted?
