### ISSUE TITLE
Scollector: Add support to configure polling interval at the collector level. 

### ISSUE THREAD

**Issue by digrich** [bosun-monitor/bosun#1681]
It's good to have support in some way to override the default/global frequency interval at the individual collector level. We have seen the cases, where we don't want to collect the metrics from all collectors at the same frequency interval.

**Comment by gbrayut** [comment]
Adding some notes from http://bosun.slack.com

We likely won't implement this feature anytime soon, but would be happy to discuss implementation strategy and review a pull request (here or in slack room)

**Comment by digrich** [comment]
@kylebrandt It seems, you did changes for this enhancement. Is this feature supported now?

**Comment by gbrayut** [comment]
I don't think https://github.com/bosun-monitor/bosun/pull/1736 was ever merged into master as it was still pending documentation

**Comment by digrich** [comment]
Any plan, by when this would be merged?

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/pull/1736#issuecomment-223645558 is still true if you want to test it out and see if actually works, I just wrote the code that I thought would do it, but haven't had time to test.

**Comment by digrich** [comment]
Thanks @kylebrandt, I will test it. Will FreqOverride be defined as Array of tables with CollectorName as key and Freq as Value in the configuration file?
