### ISSUE TITLE
Alert condition validation 

### ISSUE THREAD

**Issue by pavanshetty05** [bosun-monitor/bosun#1683]
Every time mail is generating . As per our understanding mail should generate only if this crit =  $metric <= 0 condition satisfy . Will you please let us know what is wrong in the alert ? expecting quick response from your side .

tsdbHost = ***********:4242
smtpHost = *********:25
emailFrom = bosun@*****.com

notification mails {
email = pavanshetty05@***********
next = mails
timeout = 2s
}

template test {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Name: {{.Alert.Name}}
	<p>Time: {{.Time}}
	<p>Tags:
	<table>
		{{range $k, $v := .Group}}
			<tr><td>{{$k}}</td><td>{{$v}}</td></tr>
		{{end}}
	</table>`
}

alert cpu.usage.alert {
	template = test
	$metric = nv(avg(q("min:rate:proc.uptime.now{host=*}", "1h", "")),-1)
	crit =  $metric <= 0
	critNotification=mails
   	
}

**Comment by dimamedvedev** [comment]
You have a notification that will continuously send mails every 2 seconds. When you test alert on historical data, does it become "crit" every time? And if yes, what data points does your expression evaluates to?

**Comment by kylebrandt** [comment]
Once the alert triggers (Goes to non-normal) it will send emails every 2 seconds until someone acknowledges it as per the following section in your config:

```
next = mails
timeout = 2s
```
