### ISSUE TITLE
Support for multiple graphite servers in config

### ISSUE THREAD

**Issue by angadsingh** [bosun-monitor/bosun#1694]
Currently bosun only supports querying a single graphite server. We have servers in 4 different colos submitting metrics to 4 different graphite clusters, and the only solution currently is to run 4 instances of bosun each pointing to one of the clusters, with the same rules. Bosun simply queries the graphite cluster , and then evaluates the alert expressions and as such doesn't do much processing, so can scale for all clusters in a single instance.

**Comment by avi-ram** [comment]
Looks like this issue is closely related to #1404
