### ISSUE TITLE
Allow changing the ledisBindAddr port

### ISSUE THREAD

**Issue by angadsingh** [bosun-monitor/bosun#1695]
https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/conf/conf.go#L365

This is currently hardcoded:
`LedisBindAddr:    "127.0.0.1:9565"`

Thus one cannot run multiple bosun processes on the same machine. Running multiple bosun daemons is necessary to query multiple `graphiteHost`'s (https://github.com/bosun-monitor/bosun/issues/1694)

**Comment by captncraig** [comment]
I believe this was added with https://github.com/bosun-monitor/bosun/commit/b142ea10e56f866e85c4f9ee2b54c6d244582e19. Just set `ledisBindAddr = localhost:4444` or whatever.

**Comment by angadsingh** [comment]
ledisBindAddr does not work
