### ISSUE TITLE
windows scollector error

### ISSUE THREAD

**Issue by chsword** [bosun-monitor/bosun#1699]
I got a error in Windows Event .

```
error: queue.go:105: json: error calling MarshalJSON for type *opentsdb.DataPoint: cleaning tags for metric sntp.stratum: cleaning value  for tag remote: clean result is empty
```

There is this error in windows 2008 r2 / windows 2012 r2 .
And 386 / amd64 both has error.

**Comment by neulf** [comment]
The same to u.

**Comment by simnv** [comment]
Is your Windows by any chance is not in english locale?

scollector can't parse w32time /querysntp result if it is not in english.

**Comment by chsword** [comment]
yes Chinese-Simplified

**Comment by noblehng** [comment]
I had play with codepage to force w32tm to output english with not much luck.

So for now, I just disable the Windows TIme service or disable the sntp collector.

**Comment by StianOvrevage** [comment]
How do you disable the sntp collector?

**Comment by kylebrandt** [comment]
Need `*` first to match all, then subtract the sntp collector, i.e.

`PS C:\Users\kbrandt> & 'C:\Program Files\scollector\scollector.exe' -f "*,-sntp" -l`

**Comment by StianOvrevage** [comment]
Great, thanks. Also, when adding to scollector.toml, the right format looks to be:

    Filter = ["*,-sntp"]

in the main section.
