### ISSUE TITLE
How to add metrics???

### ISSUE THREAD

**Issue by msqiao** [bosun-monitor/bosun#1703]
How to add metrics? Can allow scollector to collect the data of the newly added metrics? How to combine bosun and opentsdb?

**Comment by dimamedvedev** [comment]
Could you elaborate on that, please? 

If you mean custom metrics then read scollector's docs on `LocalListener` collector, enable it, and send metrics to it via opentsdb http protocol.

from scollector's doc.go
```
LocalListener (string): local_listener will listen for HTTP request and forward
the request to the configured OpenTSDB host while adding defined tags to
metrics.

        LocalListener = "localhost:4242"
```
