### ISSUE TITLE
Bosun api Documentation

### ISSUE THREAD

**Issue by Andre12c** [bosun-monitor/bosun#1705]
I just want to retrieve all the results and computations of a bosun query using api/expr, here is my request:
http://192.168.99.100:8070/api/expr?q=q(%22sum%3Aos.disk.fs.percent_free%22%2C%20%221h%22%2C%20%22%22)
i always get the folowing error:
expr: unexpected EOF in input ???

**Comment by kylebrandt** [comment]
At some point we broke GET requests to that route. Noticed that late last week.

Should work fine as a POST request:

```
curl 'http://bosun/api/expr' -d 'q("sum:rate{counter,,1}:os.cpu{host=ny-web*}", "1m", "")'
```

The API needs some love. Making it proper rest and giving it documentation is on my mind for .6. The next .5RC should be this week.
