### ISSUE TITLE
[Bug] Broken query when using openTSDB 2.2 mode

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1710]
Some queries get broken when using the 2.2 mode, for example:

`min:ping.timeout{dst_host=foo*|bar*}`

this gets converted to

`min:ping.timeout{dst_host=iwildcard(foo*|bar*)}`

which is invalid. The only solution I can think so far is to let Bosun expand the * like in 2.1, so that the query would become:
`min:ping.timeout{dst_host=literal_or(foo1|foo2|bar1|bar2)}`

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/issues/1495
