### ISSUE TITLE
first mail notification delay +/- 10 minutes

### ISSUE THREAD

**Issue by cosmicja** [bosun-monitor/bosun#1711]
I configured the following alert to notify me when a windows service stops running. I start receiving the mail notification +/- 10 minutes after the occurence. After the occurence I receive mails every minute as expected.

How and when the alerts are triggered ?

I post here the example code:

tsdbHost = 10.10.10.10:4242
smtpHost = 10.10.10.11:25
emailFrom = bosun@mail.com
stateFile = /data/bosun.state

template tmp_ServiceWindows {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Name: {{.Alert.Name}}
	
	Service stopped
	<p>Tags:
	<table>
		{{range $k, $v := .Group}}
			<tr><td>{{$k}}</td><td>{{$v}}</td></tr>
		{{end}}
	</table>`
}

notification notifMail  {
	email = test@domain.com
	next = notifMail
	timeout = 1m
}

alert TargetService {
	template = tmp_ServiceWindows
	$avgServiceMonaCrit = min(q("sum:os.service.running{host=myServer,name=TargetService}", "1m", ""))
	
    crit = $avgServiceMonaCrit < 1
   
    critNotification = notifMail
}

**Comment by kylebrandt** [comment]
The alert will run every 5 minutes by default. Look at http://bosun.org/configuration for the `checkFrequency` and `defaultRunEvery` configuration directives.
