### ISSUE TITLE
[Feature Request] Add optional headers to notification config

### ISSUE THREAD

**Issue by petemyron** [bosun-monitor/bosun#1717]
It would be good to be able to pass arbitrary headers when setting up notifications in the config. In my case, I'm connecting to an SMSC API and need to pass in some Basic Auth:

```
# post to SMSC proxy for text messaging
notification sms{
    post = "https://some.box.com/api/sms/1/outbound/tel:+5555/requests/"
    body = { "outboundSMSMessageRequest": { "senderAddress": "tel:+5555", "outboundSMSTextMessage": { "message": {{.|json}} }, "address": [ "tel:+1234567890" ], "receiptRequest":{} } }
    contentType = "application/json"
    # add zero or more headers
    headers = { "Authorization": "Basic jkflsdjlfdsjfjslfjskfjs=", "Accept": "application/json", "Cache-Control": "no-cache" }
}
```

**Comment by kylebrandt** [comment]
Will be fixed in https://github.com/bosun-monitor/bosun/pull/2135

**Comment by datto-aparrill** [comment]
@kylebrandt Can you clarify how #2135 implements this? I don't see anything in that PR or in the documentation on how to set headers besides the content-type header.
