### ISSUE TITLE
Bosun  with elasticsearch as backend storage not working

### ISSUE THREAD

**Issue by vinayakbhadage** [bosun-monitor/bosun#1720]
Hi, 
I have following dev.conf for bosun-windows-amd64.exe for latest release.

```
logstashElasticHosts=http://blueduck:9200
smtpHost = host:[port]
emailFrom = bosun@example.org
httpListen = :8070
timeAndDate = 202,75,179,136
stateFile = ../bosun.state
ledisDir = ../ledis_data
checkFrequency = 5m

notification default {
	email = john@example.org
	print = true
}
```

And doing following api call which result in 404  server error.

```
POST http://127.0.0.1:8070/api/put HTTP/1.1
Host: 127.0.0.1:8070
Connection: keep-alive
Content-Length: 495
Cache-Control: no-cache
Origin: chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6

[{
	"metric": "hello.world",
	"timestamp": 1461752702,
	"value": 1234,
	"tags": {
		"name": "vinayak",
		"desi": "tech"
	}
}, {
	"metric": "hello.world",
	"timestamp": 1461752717,
	"value": 123,
	"tags": {
		"name": "vinayak",
		"desi": "tech"
	}
}, {
	"metric": "hello.world",
	"timestamp": 1461752732,
	"value": 12,
	"tags": {
		"name": "vinayak",
		"desi": "tech"
	}
}, {
	"metric": "hello.world",
	"timestamp": 1461752747,
	"value": 34,
	"tags": {
		"name": "vinayak",
		"desi": "tech"
	}
}]

```

Even tried with bosun docker container .. it is giving 500 internal server error for same request.

I want to use bosun api to send the time series data from an application and want to use Elasticsearch as backend storage for bosun.

Please help me to configure it.

Thanks & regards,
Vinayak

**Comment by dimamedvedev** [comment]
You can only query ES in Bosun, to use `/api/put` you must configure OpenTSDB instance.

**Comment by 21stio** [comment]
@dimamedvedev Hey, can you provide some more details on how to setup ES with Bosun please?

**Comment by dimamedvedev** [comment]
@21stio Basically you set ES-related config options in bosun.conf as described here http://bosun.org/configuration#backends and after that you can run functions in "Expression"as described here http://bosun.org/expressions#logstash-query-functions-deprecated or here http://bosun.org/expressions#elastic-query-functions depending on what ES version you use.
