### ISSUE TITLE
Ability to get alert vars in notification, and/or specify per-notification templates

### ISSUE THREAD

**Issue by angadsingh** [bosun-monitor/bosun#1726]
Currently its hardcoded, that notification POST body (HTTP notifications) only has access to the subject of the rendered notification template (or I believe the body if useBody = true). This is too limited, and is causing us to create too many redundant notification definitions.

E.g. one for each pagerduty service (if only the service_key changes, but we copy/paste the entire notification definition:

```
notification x-team-pagerduty {
  post = https://events.pagerduty.com/generic/2010-04-15/create_event.json
  contentType = application/json
  next = x-team-pagerduty
  timeout = 30m
  runOnActions = false
  print = true
  body = `{
      "service_key": "safasdfasfda12412asfs",
      "incident_key": {{.|json}},
      "event_type": "trigger",
      "description": {{.|json}},
      "client": "Bosun",
      "client_url": "http://bosun.corp.company.com:8070"
    }`
}

notification y-team-pagerduty {
  post = https://events.pagerduty.com/generic/2010-04-15/create_event.json
  contentType = application/json
  next = x-team-pagerduty
  timeout = 30m
  runOnActions = false
  print = true
  body = `{
      "service_key": "safasdfasfda12412asfs",
      "incident_key": {{.|json}},
      "event_type": "trigger",
      "description": {{.|json}},
      "client": "Bosun",
      "client_url": "http://bosun.corp.company.com:8070"
    }`
}

#you get the idea
```

It gets worse, for example, when we need to send events to graphite. We need to send the alert name as a tag of the event, so that bosun alerts can be displayed on top of grafana/graphite graphs of their respective components:

```
notification graphite-event-tag-team-x-component-y {
  post = http://hb4101.grid.lhr1.inmobi.com/events/
  contentType = application/json
  next = graphite-event-tag-team-x-component-y
  timeout = 30m
  runOnActions = true
  print = true
  body = `{
      "what": {{.|json}},
      "tags": "bosun,team-x,component-x"
    }`
}

notification graphite-event-tag-team-x-component-z {
  post = http://hb4101.grid.lhr1.inmobi.com/events/
  contentType = application/json
  next = graphite-event-tag-team-x-component-z
  timeout = 30m
  runOnActions = true
  print = true
  body = `{
      "what": {{.|json}},
      "tags": "bosun,team-x,component-z"
    }`
}
```

We have 50+ of the above and its a huge mess. Would be great to have the entire `.Alerts.<var>` scope available to be used in the POST body.

Either that.. or

(1) have different template types for different notifications - for "email", the template fields would be "subject" and "body", for "post", templates would have "payload" and "headers". Each notification type requires different fields, and the current structure just overloads the subject/body fields for everything.
(2) make it possible to pass in the "template" used for a notification, as an argument - example:

```
alert component.x.lag.too.high {
    macro = alertdefaults

    $notes = Sample alert, does this, that
    $query = '''aliasByNode(transformNull(sumSeriesWithWildcards(x.*.y-*.z.*.*.a.*.b.c ,4)),1,2,4,6)'''
    $metrictags = "a.b.c.d"
    $metric = graphite($query, "15m", "10m", $metrictags)
    $q = avg($metric)

    warn = $q > lookupSeries($metric,"x_lag_thresholds","warnValue")
    crit = $q >= lookupSeries($metric,"x_lag_thresholds","critValue")

    warnNotification = graphite-event(graphite-event-template-1)
    critNotification = pagerduty(pagerduty-template-1),slack(slack-template-1)
}
```

**Comment by mkuzmin** [comment]
Related issue: https://github.com/bosun-monitor/bosun/issues/689

**Comment by kylebrandt** [comment]
Is the type for an event in pagerduty well defined or can you have custom
fields?

It seems like 90% of the struggle with Json post is using it with
pagerduty. If I made a pagerduty notification type I could also integrate
ack and close actions in Bosun to do the same to their corresponding
pagerduty endpoints.

Any thoughts on this? Wouldn't help your graphite issue or generic posting,
but the concreteness of it might be easier to deliver, thoughts?

**Comment by mkuzmin** [comment]
I have no experience with PagerDuty, but even if its format is fixed, there are also OpsGenie, Slack, and others.
Maybe hardcoded templates will work, but we'll need a list we could extend by PRs.

**Comment by krutaw** [comment]
The problem with having something specific for PagerDuty is that there's so many other uses for the post functionality.  For instance, auto-correction of incidents by sending enough information to Hubot, perhaps creation of issues in a ticketing system like JIRA, sending notifications to a chat system such as HipChat / Cisco Jabber and I'm sure there are lots of other use-cases out there.

Wouldn't it be better to make the entire .Alerts.vars line of variables available to notifications?

**Comment by angadsingh** [comment]
having hardcoded templates for each alert management backend makes no sense at all. bosun config syntax is powerful enough to allow creating generic templates which can solve this problem.

**Comment by amgorb** [comment]
+1 for this, it was a pity that template block is email-only right now.

**Comment by kylebrandt** [comment]
Will be fixed with https://github.com/bosun-monitor/bosun/pull/2135

**Comment by angadsingh** [comment]
Thanks @kylebrandt. The solution in #2135 makes sense.
