### ISSUE TITLE
Set UserAgent in Scollector

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1729]
In Bosun we set the UserAgent to Bosun/Version at

https://github.com/bosun-monitor/bosun/blob/c5de6525d157409de0e4013f6a58da1790d51192/cmd/bosun/main.go#L50

We should do the same for Scollector to help identify HTTP requests coming from Scollector

**Comment by kylebrandt** [comment]
When we do this we should also allow the user to append to the UA, so external pollers can identify the org doing the polling if desired.
