### ISSUE TITLE
How to use Series Operations?

### ISSUE THREAD

**Issue by WangFenjin** [bosun-monitor/bosun#1730]
Hi Team,

For the doc:

> If you combine two seriesSets with an operator (i.e. q(..) + q(..)), then operations are applied for each point in the series if there is a corresponding datapoint on the right hand side (RH). A corresponding datapoint is one which has the same timestamp (and normal group subset rules apply). If there is no corresponding datapoint on the left side, then the datapoint is dropped. This is a new feature as of 0.5.0.

So I'm wondering where can I test this feature? I try to put the expression
> q("sum:rate{counter,,1}:web.nginx.feed.503", "1h", "")+q("sum:rate{counter,,1}:web.nginx.feed.499", "1h", "")

in the `Expression` tab of bosun web, but it says 

> expr: parse: type error in q("sum:rate{counter,,1}:web.nginx.feed.503", "1h", "") + q("sum:rate{counter,,1}:web.nginx.feed.499", "1h", ""): at least one side must be a number

Thanks for your great work!

**Comment by dimamedvedev** [comment]
First, make sure you are using 0.5.0 or greater version.

**Comment by kylebrandt** [comment]
Actually only on master currently I think

**Comment by WangFenjin** [comment]
Thanks! I build the master branch and it worked!

Will resolve this issue.
