### ISSUE TITLE
Query elasticsearch weekly / monthly index

### ISSUE THREAD

**Issue by JozoVilcek** [bosun-monitor/bosun#1738]
How do I query time rotated elasticsearch indexes different than daily? E.g. weekly index.

**Comment by kylebrandt** [comment]
Do you need both right now, or just one or the other (daily vs weekly)?

**Comment by JozoVilcek** [comment]
I would use a weekly index. I do not have use for monthly right now.

**Comment by kylebrandt** [comment]
@JozoVilcek I don't have any weekly indexes, can you test the above commit and see if it works for you and then let me know?

Thanks,
Kyle

**Comment by JozoVilcek** [comment]
@kylebrandt No, does not work well for me. I am getting more results for the query then I should be. It seems like query is hitting all indices matching time slice ... regardless date-time layout, regardless indexRoot.
Executed `esweekly("@timestamp", "metrics-", "2006", 0)` and got data even from `esls("logstash")`

**Comment by kylebrandt** [comment]
@JozoVilcek Can you try again? I fixed some things - also 2006 probably isn't correct, can you show me some example index names?

**Comment by kylebrandt** [comment]
Basically this was supposed to err if there were no indices matching your request, but when I refactored for this I accidently shadowed (effectively) ignored that error.

**Comment by JozoVilcek** [comment]
Yep, now I am getting error complaining about zero matched es indices. I am unable to find how to specify a correct go time layout for this. Index names looks like `metrics-hdfs-2016.20` as current week of the year is `20`.

**Comment by kylebrandt** [comment]
Ugh, I thought go could parse iso weeks, apparently not... will figure out what to do.. sigh

**Comment by JozoVilcek** [comment]
Ha! I am happy it is not just me being blind. OK, I will sit tight. Thanks!

**Comment by kylebrandt** [comment]
Okay, try again with `esisoweekly("@timestamp", "metrics-hdfs-", "2006.52")` .... note the func name change and prefix change

**Comment by kylebrandt** [comment]
Also, considering adding a function that just takes the timestamp field and the prefix, and queries all indexes regardless of date as a failback :P 

Maybe that isn't even that expensive.

**Comment by JozoVilcek** [comment]
Great! `esisoweekly` forks fine for me. Thanks!

**Comment by calh** [comment]
How can I get monthly indexes to work?  I've been trying something like:

```
esdaily("@timestamp", "logstash-", "2006.01")
```

But the error message seems to indicate it's still using the daily string.

**Comment by grafanouille** [comment]
Hi @kylebrandt ,

I've got my logs in weekly indexes, so I can't currently query and alert on them. Could you please merge #1741 into master ?

Thanks a lot !
