### ISSUE TITLE
Reduction over tag value

### ISSUE THREAD

**Issue by JozoVilcek** [bosun-monitor/bosun#1747]
I need to do a reduction for a specific tag value (sum, min, max, avg), so function(s) should take `SeriesSet` and spit out again a `SeriesSet`. E.g. lets assume I am watching a disk usage. When I query my elasticsearch data source, I choose date historgam aggregation `MAX`. So the series set looks like:

```
cluster=A,disk=D1,host=H1
cluster=A,disk=D2,host=H1
cluster=A,disk=D1,host=H2
cluster=A,disk=D2,host=H2
```

But, I want total disk usage per host in specific cluster, so I would like to do something like 
`reduce(seriesSet, 'disk', 'sum')` to produce:

```
cluster=A,host=H1
cluster=A,host=H2
```

Can I do this with bosun series functions or elasticseach datasource functions?

**Comment by kylebrandt** [comment]
The key is the `t` (transpose func) http://bosun.org/expressions#tnumberset-group-string-seriesset

Slightly different order of operations that what you describe. It works out to

1) Use estat to get a max histogram aggregation. 
2) Reduce to number to set with last (pick the last value for each cluster,disk,host
3) Turn that into a new seriesSet with t grouping by cluster,host.
4) Sum those values. 

```
$minute = 15
$bucketSize = "${minute}m"
$index = esdaily("@timestamp", "logstash-", "2006.01.02")
$keyField = "cluster,disk,host"
$filter = esall()
$q = esstat($index, $keyField, $filter, $bucketSize, ....)
sum(t(last($q), "cluster,host"))
```

**Comment by JozoVilcek** [comment]
Yep, this works. But I have problem with `last()` part. What are my options If I want also visualize trend over time?

**Comment by JozoVilcek** [comment]
@kylebrandt Can this be done or does it require implementation of a new function?

**Comment by kylebrandt** [comment]
You're hurting my brain... so I think we need to

1. Max aggregate cluster,disk,host over time
2. Sum aggregate over the above result by cluster,host 

That should probably all be done in elastic if you want to view it over time. I think this is a new function, or I messed up the design and esstat should be nestable. But not sure yet.

The next step for me would be to get some elastic query examples of this behavior. If you hit alt-p in the Bosun UI, it will bring up miniprofiler. You can then view the elastic queries that are currently being generated. Is figuring out what the elastic query should be something you have the skill/time to figure out by chance?

Once I see what the elastic queries look like, can try to think of a func signature and implementation.

**Comment by kylebrandt** [comment]
Or I could attempt to write transpose func that works on series sets maybe... but I think the elastic option is probably best for performance so not as much information has to be sucked into Bosun's memory.

**Comment by JozoVilcek** [comment]
I agree that aggregation is better to be done in elasticseach. I can not say I have the skill, but I will do my best to do a homework and come back to you with working elastic json query example

**Comment by JozoVilcek** [comment]
So, I have bad news. After failed experiments, I have asked on elasticsearch forum and stackoverflow. 
https://discuss.elastic.co/t/pipeline-aggregation-combining-multiple-buckets/
http://stackoverflow.com/questions/37522341/es-pipeline-aggregation-combining-multiple-buckets
No answer yet there. 

Right now, I asked question on elasticsearch IRC and the reply is, this is not posible to do with elasticseach. Application have to combine those timeseries data. Can bosun have such feature?

**Comment by Dieterbe** [comment]
FWIW this is a lot like graphite's api, it has a gazzilion functions to aggregate series together in a series-wise fashion (e.g. resulting in one or more output series). there's go implementations already for all of them but of course it's not tag based, so not very useful i guess.

**Comment by kylebrandt** [comment]
@JozoVilcek I believe elastic can do do a query like this. I think you would just need to build the ES query with the aggregations nested correctly.

Working on other things, but will play with this when I can.
