### ISSUE TITLE
How to get alarm information？？？

### ISSUE THREAD

**Issue by msqiao** [bosun-monitor/bosun#1749]
1, bosun is able to add alarm strategy through the API Bosun? Or by what way to modify and add strategies???
2, bosun generated alarm event information how to get???

**Comment by dimamedvedev** [comment]
1) currently the only way to change Bosun configuration is to edit it's config file
2) use https://bosun.org/api#apialertsfilterfilter

**Comment by msqiao** [comment]
Get alarm information through the https://bosun.org/api#apialertsfilterfilter, but the back of the filterfilter I do not understand how to filter, can you give an example? Thank you!

**Comment by msqiao** [comment]
If I use the Java language to modify the bosun configuration file, then through the SSH to modify and then have to restart bosun is it? Thank you for taking the time to answer my questions, thank you very much!

**Comment by efficks** [comment]
up.
I do not understand how to filter, can you give an example?
