### ISSUE TITLE
Alert continues to notify after being Acked and resolved

### ISSUE THREAD

**Issue by busukajw** [bosun-monitor/bosun#1750]
Occasionally(at least once a day) after Acknowledging and Closing an Alert, we will continue to receive notifications for the alert. These notifications are not viewable via the bosun web interface, however  purging the alert via the API stops the notifications.

I am running bosun-0.5.0rc2 with a redis backend, and I am using graphite as the TSDB.

**Comment by dgryski** [comment]
Seems like dup of https://github.com/bosun-monitor/bosun/issues/1690 ?

**Comment by busukajw** [comment]
Yes just seen this.  Will upgrade and test.  If I am wrong will reopen
