### ISSUE TITLE
number variables from alert are typed string and cannot be used in templates with lt/gt/eq ?

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#1759]
IIRC I spoke about this with Matt Jibson years ago, and although I couldn't find the ticket, I think it has always been an unresolved issue

basically when you have something like this in your template `  {{else if lt $v.Value $.Alert.Vars.b }}` you're bound to get `error calling lt: incompatible types for comparison`
no matter whether you define `$b` as 60 or 60.0, v.Value is a number obtained from `streak()`, printf says the type is expr.Number, whereas $b has type string.

notably if you replace `$.Alert.Vars.b` with 60.0 it works fine

**Comment by kylebrandt** [comment]
I think you need to wrap `$b` in Eval:

```
template test {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `{{ lt (.Eval .Alert.Vars.q) (.Eval .Alert.Vars.threshold) }}`
}

alert test {
	template = test
	$q = avg(q("avg:rate:os.cpu{host=*bosun*}", "5m", ""))
	$threshold = 1
	crit = avg(q("avg:rate:os.cpu{host=*bosun*}", "5m", "")) > $threshold
}
```

**Comment by Dieterbe** [comment]
you're right! that makes it work, and it doesn't even matter if declared as 60 or 60.0
both work.
