### ISSUE TITLE
Elasticsearch help

### ISSUE THREAD

**Issue by atlante77** [bosun-monitor/bosun#1763]
Hello guys !

i'm trying to use elasticsearch with bosun but it doesn't work ...

In my elasticsearch i did this : 
```
curl -XPUT 'http://localhost:9200/bosun/data/2' -d'{
    "cpu": 92
}'

```

but i don't know how i can check my cpu item with bosun : 

```
tsdbHost = localhost:4242
stateFile = /data/bosun.state
elasticHosts = xx.xx.xx.xx:9200

template test {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Name: {{.Alert.Name}}
	<p>Tags:
	<table>
		{{range $k, $v := .Group}}
			<tr><td>{{$k}}</td><td>{{$v}}</td></tr>
		{{end}}
	</table>`
}

alert elastic {
  template = test
  $index = esdaily("@timestamp", "bosun", "2016.01.02")
  #esdaily (timeField string, indexRoot string, layout string) 

  crit = max(esstat($index, {} , esall(),????; "1m","5m", "5m", "" ???)) > 0
  
  #esstat(indexRoot ESIndexer, keyString string, filter ESQuery, field string, rStat string, bucketDuration string, startDuration string, endDuration string)
}

```

Thanks in advance.

reagards,

Atlante

**Comment by kylebrandt** [comment]
escount is for counting the number of documents. estat is for accessing
numerical values in a document (i.e. cpu: 92). The document will also need
a timestamp field. In your put I don't see that field (unless elastic adds
the automatically?).

**Comment by atlante77** [comment]
Hello Kylebrandt,

Thank you for your help.
I'm using elasticsearch 2.3 and i tried to add the field timestamp like this : 

```
 curl -XPUT 'http://localhost:9200/bosun/data/3?timestamp=2016-06-02' -d'{
    "cpu": 92
}'
{"_index":"bosun","_type":"data","_id":"3","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}
```
But in the official documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html) they write :

> Deprecated in 2.0.0-beta2.
> The _timestamp field is deprecated. Instead, use a normal date field and set its value explicitly.

So someone could show me the best way do test elasticsearch with bosun ?
I don't understand what i have tu set in esstat resquest.

I just want to take the CPU value with timestamp...

Thanks in advance

**Comment by atlante77** [comment]
Or can i add the timestamp like this ?
```

curl -XPUT 'http://localhost:9200/bosun/data/2' -d '{
    "cpu": 92,
"@timestamp" : "02062016"
}'
```

**Comment by atlante77** [comment]
Ok, i removed and recreate new index with @timestamp field and i put manually my data :

```
curl -XPOST 'http://localhost:9200/bosun/data/' -d '{
    "cpu": 92,
	"@timestamp" : "2016-06-03"
}'
```

In bosun :

```
alert elastic {
  template = test
  $minute = 60
  $bucketSize = "${minute}m"
  $index = esdaily("@timestamp", "bosun", "2016-06-03")
  #esdaily (timeField string, indexRoot string, layout string) 
  $keyField = "@timestamp,cpu"
  $filter = esall()
  $q = esstat($index, $keyField, $filter, "data", "max", $bucketSize, "2d","" )
  #esstat(indexRoot , keyString , filter , field , rStat , bucketDuration , startDuration , endDuration ) 
  
 
  crit = max($q) > 0
  
}
```

But it's not working :
`no elastic indices available during this time range, index[bosun], start/end [2016.06.01|2016.06.03]`

Someone can help me ?

regards,

**Comment by kylebrandt** [comment]
Since your index is just "bosun" you want esindicies("@timestamp", "bosun")
as your index function
<http://bosun.org/expressions#elastic-index-functions>

**Comment by atlante77** [comment]
Thanks for your answer but another problem with your modification :
`conf: Test Config:62:2: at <crit = max($q) > 0>: expr: non existent function esindicies`

In the same time could you confirm that my esstat request is good to peek all "cpu" value in bosun/data ?

Because i success it directly in the termianl :
`curl -XGET 'http://localhost:9200/_search?q=@timestamp:2016-06-03'`

**Comment by kylebrandt** [comment]
Should be esindices - spelling error, fixing docs

**Comment by atlante77** [comment]
Yeah, thank you !
it works better now, i just change data to cpu :

```
alert elastic {
  template = test
  $minute = 60
  $bucketSize = "${minute}m"
  $index = esindices("@timestamp", "bosun")
  #esdaily (timeField string, indexRoot string, layout string) 
  $keyField = "@timestamp,cpu"
  $filter = esall()
  $q = esstat($index, $keyField, $filter, "cpu", "max", $bucketSize, "2d","" )
  #esstat(indexRoot , keyString , filter , field , rStat , bucketDuration , startDuration , endDuration ) 
  crit = (max($q) > 0)
  
}
```

Thanks for the fix in your documentation :)
Have a nice day !
