### ISSUE TITLE
Bosun self metrics zeroed

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1766]
Many Bosun self metrics are storing only zeros:
- bosun.alerts.active_status
- bosun.alerts.acknowledgement_status_by_notification
- bosun.alerts.last_abnormal_severity

there are probably other metrics doing this as well.

Checking my data history I can see that they were all working in the past and stopped working at the first half of April, so it may be related to the redis stuff

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/sched/check.go#L373
