### ISSUE TITLE
Elasticsearch collector unmarshalling error

### ISSUE THREAD

**Issue by neilfordyce** [bosun-monitor/bosun#1769]
The Elasticsearch collector consistently fails under the linux-386 build due to a JSON unmarshalling error.

```
elasticsearch: json: cannot unmarshal number 1464880941331 into Go value of type int
```

I believe this occurs as a result of using the int type where int64 is required.  E.g. The timestamp fields returned by the elastic _nodes/_local/stats endpoint are too large to fit into 32 bits allowed by [the interface timestamp](https://github.com/bosun-monitor/bosun/blob/d057439bcf93b99d185129294d75ccf4503e43d9/cmd/scollector/collectors/elasticsearch.go#L477) in 32-bit builds.

scollector version: 0.5.0rc3
elastic version: 2.2.0

**Comment by StianOvrevage** [comment]
Same-ish error:

    error: interval.go:64: elasticsearch: json: cannot unmarshal string into Go value of type []string

scollector version 0.5.0-rc4
elastic version 5.0.0-rc1

**Comment by WangHouLing** [comment]
same error:
```
error: interval.go:64: elasticsearch: json: cannot unmarshal string into Go value of type []string
```
scollector version 0.5.0
elastic version 5.0.1
Have you got any good solutions to the problem?Please help me. @StianOvrevage @neilfordyce

**Comment by StianOvrevage** [comment]
I don't recall finding a solution to this, sorry.

**Comment by neilfordyce** [comment]
I am unsure of the cause, but that looks different to issue I experienced.  My issue did not occur in scollector-linux-amd64 v0.5.0 with elastic v2.2.0, so I would hazard a guess it's related to compatibility with Elastic 5.

**Comment by WangHouLing** [comment]
Thanks for your replay!
