### ISSUE TITLE
band functions set ignoreunjoined which cannot be controlled by end user and leads to NaN's

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#1774]
original discussion: https://bosun.slack.com/archives/general/p1465389219000241

in an alert like https://gist.github.com/anonymous/9478adf8147c3899ce7c64755ccfe97c
where $now and $past are queries for the same data, but different times, often tagsets exist only in $now and not in $past, e.g. for newly created series that only have recent data.
so $cluster_frac and warn and crit become NaN for those particular tagsets.

i also tried `nv($val,0)` but the NaN just seems to "come through"

from slack

```

kylebrandt
10:09 AM @dieter: Have an idea, not sure what to do about it yet though
10:10
cmd/bosun/expr/graphite.go:101 sets ignore unjoined, and when that is set, the NaN substition that takes place at cmd/bosun/expr/expr.go:~425 is not done
10:11
So it looks like we automagically drop things that don’t have past when joined with Band
10:11
OpenTSDB’s band does the same thing
```

see rest of discussion on slack. but it looks like basically band functions should use ignoreunjoined internally, but then unset that flag when their data will be used with other terms/factors, so that it's up to users to achieve the desired behavior. don't-ignore should be the default behavior everywhere probably, and should be able to override it ad-hoc

**Comment by kylebrandt** [comment]
So want to get this right this time. Band is used to get a sample of history. So we get

```HistoricalSet Operator CurrentSet```

Things that can happen that would cause join errors if we have no special "flags" and assuming the join within history all works:

1. An item can be missing from the historical set but be in the current set
2. An item can be in the historical set but not in the current set

For case 1:
  a) Could be a new item was introduced
  b) Less likely, but could be an item that was out during all of the historical period

For Case 2:
 a) Something was decommissioned
 b) Something has disappeared, and it wasn't supposed to.

**Comment by kylebrandt** [comment]
1a - Story, the current behavior where new things by default are ignored if there is no history is not an acceptable default IMO since it can result in not getting alert one would expect to get without knowing this pitfall.

**Comment by kylebrandt** [comment]
Note: lookupSeries also seems to set this flag:

```
	lookupSeries := func(e *expr.State, T miniprofiler.Timer, series *expr.Results, lookup, key string) (results *expr.Results, err error) {
		results = new(expr.Results)
		results.IgnoreUnjoined = true
...
```

**Comment by kylebrandt** [comment]
Note (all in `cmd/bosun/expr/expr.go`): 
 * The short circuiting happens in `operate(op string, a, b float64) (r float64)`.
 * `union` is where the joining of items in a set happens, as well as NaN substitution when ignoreUnjoined and ignoreOtherUnjoined are **not** set: ```// union returns the combination of a and b where one is a subset of the other.
func (e *State) union(a, b *Results, expression string) []*Union```
 * `walkBinary` calls `union` then calls `operate`. Since union is called is before operate, operate is unable to short circuit because the items have already been dropped before operate can short circuit them.

**Comment by kylebrandt** [comment]
Looks like it was probably added to fix https://github.com/bosun-monitor/bosun/issues/177 and we never marked it

**Comment by kylebrandt** [comment]
Had a thought, although I think I don't like it.

We could make this a non-breaking change by allowing `unjoinedOk = false` in the alert configuration. Or logic is then to cancel the automatic inclusion of `unjoinedOk` with band functions if the user has set it to false.

Why I am wary of this:
 1. I sort of regret the unjoinedOk behavior magically happening when you use band. Even though this may often be what the user may want, they should make the choice, and the documentation should just recommend considering this parameter with the usage of the functions and explain why. 
 2. Currently we don't have anything where you set it to "false" like that. They are really just on/off flags, and this makes it a more complicated state.

So I think I might rather eat the breaking change then having a flag that sometimes gets enabled by default depending on the functions used in the expression.

**Comment by kylebrandt** [comment]
Also, FWIW I bet Matt suggested this was a bad idea and I didn't listen :-/
