### ISSUE TITLE
Elasticsearch collection Freq

### ISSUE THREAD

**Issue by iainangusneil** [bosun-monitor/bosun#1776]
In version:  0.5.0-rc3
Elastic collector didn't acknowledge 5 minute default frequency and would run every 10 seconds or so causing elastic performance degradation. 

On a 30 node (2 core, 8gb) cluster consuming 1.1TB a day with ~400 indices. The elasticsearch collector causes large cpu spikes during metric collection resulting in performance issues and possibly skews system metrics at the time of collection. Setting Freq param helped performance but it still spikes during collection.

**Comment by kylebrandt** [comment]
ES Version?

**Comment by iainangusneil** [comment]
ES version: 2.2.0
