### ISSUE TITLE
Metrics from external script does not appear in Bosun

### ISSUE THREAD

**Issue by bamboolanit** [bosun-monitor/bosun#1787]
I have a Bosun server with hostname server01 and monitored host with hostname machine01.
At machine01 deployed scollector with config:
`Host = "http://server01:8070"
ColDir = "/opt/scollector/scripts"
Hostname = "machine01"`
And custom bash script at $ColDir/10/scrtipt.sh:
`echo service.healt $(date +%s) 0 application=app01`
And custom bash script at $ColDir/10/script2.sh:
`echo {\"metric\":\"service02.health\"\,\"timestamp\":$(date +%s)\,\"value\":\"0"\,\"tags\":{\"application\":\"app02\"}}`
After saving both scripts scollector was restarted, but metrics **service.healt** and **service02.health** does not appear in Bosun.
Maybe I do something wrong?

**Comment by vitorboschi** [comment]
looks right to me. Do the scripts have execution permission (+x)?Are both scripts

**Comment by bamboolanit** [comment]
yes
`-rwxr-xr-x 1 root root 345 Jun 15 16:27 script.sh
-rwxr-xr-x 1 root root 173 Jun 15 17:04 script2.sh`

**Comment by RaghavendraP** [comment]
Hi,

Is the issue fixed? I am also facing similar issue. Through echo inside a for loop I want to post metrics data to OpenTSDB using scollector. When I run the scollector binary directly from the terminal the metrics are being sent to OpenTSDB but when I run the scollector as a service its not sending the metrics. I don't know what I am doing wrong.

My script:
#!/bin/bash
format=" metrics.name %d %d host=%s table=%s\n"
var=$(hadoop fs -du hdfs:/hbase/data/)
read -ra arr -d '' <<<"$var"
len=${#arr[@]}
for (( a=0; a<$len;a++))
do
        b=$((a++));
        export unixtimestamp=$(date +%s)
        table=$(echo  ${arr[$a]} | grep -o '\w*$')
        echo $(printf "$format" $unixtimestamp ${arr[$b]} "`echo $HOSTNAME`" $table);
done

I have given full execution (+x) permission on the script.

**Comment by bamboolanit** [comment]
No, this issue not fixed :(

**Comment by RaghavendraP** [comment]
I fixed my issue. I was calling hadoop binary inside my metric collection script and scollector is unable to locate that binary after giving specific path now my scollector service is sending metrics to OpentTSDB.

You could check following things:
1. in Linux, the scollector will send logs to /var/log/syslog. So, take a look at them once if there is any error while executing the custom metric script.
2. If its still failing you might want to write logic to put metrics within the custom script as below.
sleeptime=15
while:
do 
echo put "" | nc -w 15 tsdbhost tsdbport #in my case
sleep $sleeptime
done
In this case, keep the directory name as **0** as mentioned in the doc.

> Use a directory named 0 for any executables or scripts that will run continuously and create output on their own schedule

I don't know whether this logic is correct or not but it works.
