### ISSUE TITLE
MetricFilters doesn't filter out external collector metrics.

### ISSUE THREAD

**Issue by digrich** [bosun-monitor/bosun#1797]
It seems metric filters in scollector are not working for metrics published by external collectors. Though if I try to filter out the complete external collector using Filter key, it works but filtering out individual metrics using MetricFilters key doesn't work.

**Comment by gbrayut** [comment]
I think the filtering is done as part of the collector code, which isn't executed for external collectors. I'll take a look at it when I have some time, hopefully next week.

**Comment by digrich** [comment]
Thanks @gbrayut. We are writing external collectors in different languages to get the metrics from different sources and want to use scollector as a container and to leverage on its core features as much as possible like batching, internal buffering, filters etc instead of building them outside.

**Comment by kylebrandt** [comment]
Possibly related https://github.com/bosun-monitor/bosun/issues/597

**Comment by PouuleT** [comment]
@gbrayut the filtering is done in AddTS (which is used for almost everything except external collectors), I don't know why external collectors are pushed directly in the channel of openstsdb.DataPoint
Quick fix would be to add a check 
```
if skipMetric(dp.Metric) {
    continue
}
```
just before the lines
https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/program.go#L153
and
https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/program.go#L167

Real fix would be to understand why Add or AddTS is not used here

**Comment by digrich** [comment]
Is any priority decided for this issue?
