### ISSUE TITLE
Non-active alerts doesn't have "Active" field in JSON API

### ISSUE THREAD

**Issue by Civil** [bosun-monitor/bosun#1805]
request to /api/alerts have '"Active": true' in json if it's ongoing alert, but if it's healed, you don't have "Active" field at all.

From API's point of view, I think it's more common practive to have '"Active": false' in that case.

**Comment by kylebrandt** [comment]
Agreed, disappearing fields in API is not something we want. I think we are getting close to wanting an APIv2 that is just better.

Right the API does an `omitempty`  in `sched.go`, so in theory it would just mean deleting that line, but also need to make sure that doesn't impact the any UI stuff that might define false as "Missing".

All active means though is that that CurrentStatus is nor "normal":

```
func (s *IncidentState) IsActive() bool {
	return s.CurrentStatus > StNormal
}
```

So in the meantime you can replicate that in your endpoint by checking that the CurrentStatus field does not equal normal.

The Grafana plugin uses /api/incidents/open instead, you might check that to see if it is more what you are after, it doesn't group or include the body
