### ISSUE TITLE
[Feature Request] notifications on close event should be sent via different sources

### ISSUE THREAD

**Issue by Civil** [bosun-monitor/bosun#1806]
In case of alerts that uses some external API (e.x. SMS or something like PagerDuty) you'll receive notification again. In case of PagerDuty-like service it's not what you actually want, cause it'll create a new alert for recovery.

Sometimes it's useful to have different API endpoint for recoveries or different set of sources for recovery notifications.

**Comment by gbrayut** [comment]
You can use [runOnActions = false](http://stackoverflow.com/documentation/bosun/612/notifications#t=20160810220601220489&a=remarks) in the notification definition to prevent the close/ack/note actions from triggering that notification. This is recommended as part of the [PagerDuty example notification](http://stackoverflow.com/documentation/bosun/612/notifications/8595/pagerduty-notifications#t=20160810220601220489).
