### ISSUE TITLE
confusing unknown alert(Bosun 0.5.0)

### ISSUE THREAD

**Issue by batmanWjw** [bosun-monitor/bosun#1809]
Here is the situation..
I add an simple alert showing below
```
tsdbHost = localhost:4242
stateFile = /usr/share/bosun/bosun.state
redisHost = localhost:6379
redisDb = 1
checkFrequency = 10s
........
alert bf285adc-aa29-487c-9357-6d5c47812b44 {
    template = default_post
    runEvery = 1
    $metriccpu = q("avg:cpu.idle.percent{host=d9722ec9-31b0-4ac1-b735-b96a64907814}", "30s", "")
    $avgcpu = avg($metriccpu)
    crit = $avgcpu <= 0
    critNotification = default_post
}
```
It's all work fine, no alert. Then I turn down the host, and modify the alert to bind other host, and restart bosun
```
tsdbHost = localhost:4242
stateFile = /usr/share/bosun/bosun.state
redisHost = localhost:6379
redisDb = 1
checkFrequency = 10s
........
alert bf285adc-aa29-487c-9357-6d5c47812b44 {
    template = default_post
    runEvery = 1
    $metriccpu = q("avg:cpu.idle.percent{host=4bc6d114-9826-4ce9-af5d-3facb3b96255}", "30s", "")
    $avgcpu = avg($metriccpu)
    crit = $avgcpu <= 0
    critNotification = default_post
}
```
The dashboard appear an unknown alert for the host which I just have deleted.

**Comment by kylebrandt** [comment]
When decommissioning a host you can add a silence with autoforget checked, and when it goes unknown it should auto close.

Or, you if you don't care about unknowns alerts (data disappearing for an alert), you can just set the ignoreUnknown alert directive on the alert. This is generally what you would do in an environment where your hosts are short lived.
