### ISSUE TITLE
Indicate graph drag timeframe better

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#181]
When you click+drag on the graph page, the time ranges update. It is not obvious that the query button needs to be hit again. On laptops, you have probably scrolled past them and can't tell they've changed. Do something (popup tooltip, scroll so the time range boxes are in view and highlight the query button) to indicate this.

**Comment by kylebrandt** [comment]
Don't feel the need for this, and it is old. Can be reopened if someone cares.
