### ISSUE TITLE
Scollector why some time point data is not obtained?

### ISSUE THREAD

**Issue by msqiao** [bosun-monitor/bosun#1811]
hi,all:
    I have two questions:
       1, I use scollector to collect data, found in the query time point of the data, according to the frequency of scollector acquisition, found that there is no time point data.
       2, I use is scollector, bosun, opentsdb, through opentsdbAPI acquisition data, found that the current point in time before a period of time will be no data, do not know what is the reason, opentsdb is not to obtain the data of frequency and scollector is the same as it? If this is the reason, how to set the opentsdb to get the frequency of the data it?

**Comment by msqiao** [comment]
Who can help me to answer it,thank you

**Comment by msqiao** [comment]
These two questions puzzled me for a long time, which good hearted person to help me

**Comment by kylebrandt** [comment]
@msqiao Apologies but having trouble following you (English is hard :-/ ). Maybe if you add some screenshots or expressions I might be able to better understand your question.
