### ISSUE TITLE
Bosun not sending mails 

### ISSUE THREAD

**Issue by YerisAntonio** [bosun-monitor/bosun#1815]
Hi!

Getting a error while trying to send mail notifications
`
2016/07/07 17:45:23 error: notify.go:111: failed to send alert uptime{host=9f2156745317} to [ymadrigal@mydomain.com] EOF
`

 The configuration file looks like:

> `smtpUsername = bosun@mydomain.com
> smtpPassword = mypassword
> smtpHost = mail.mymailserver.com:465
> emailFrom = bosun@mydomain.com
> 
> template isup {
>         subject = {{.Last.Status}}: {{.Alert.Name}} Good thing Bosun is Up! /  {{ .Eval .Alert.Vars.up }} seconds uptime
>         body = `<p> Bosun is up
>         <p>Tags:
> `
> }
> 
> notification mail {
>         print = true
>         email = ymadrigal@mydomain.com
> }
> 
> alert uptime {
>     #runEvery = 60
>     log = true
>         template = isup
>         #crit = avg(q("sum:os.system.uptime{host=literal_or(9f2156745317)}", "1h", ""))
>         $up = avg(q("sum:os.system.uptime{host=literal_or(9f2156745317)}", "1h", ""))
>         crit = $up > 3600
>         critNotification = mail
> }

I am using the docker image

what could be wrong

**Comment by YerisAntonio** [comment]
Tried a standalone installation, got the same error.

**Comment by YerisAntonio** [comment]
Now it is working!, I had to use port 25, usually we use 465, but apparently ssl/tls security in the server wont work, however there are not logs related to that issue in my bosun.

**Comment by wjk1982** [comment]
nice +1
