### ISSUE TITLE
Some graphite functions are not working with bosun

### ISSUE THREAD

**Issue by liorchaga** [bosun-monitor/bosun#1825]
some functions (like sumSeries, divideSeries) are not working in version 0.5.0 (tried also rc3, and same result).
It produces ParseError.
For example:

sumSeries(nonNegativeDerivative(system.production.domain.server.*.myService.someMetric.timer.count))

It used to work in rc1.

**Comment by kylebrandt** [comment]
Can you show the full expression so I can see the context?

**Comment by liorchaga** [comment]
Thanks Kyle,

Basically we just tried:
graphite("sumSeries(nonNegativeDerivative(<metric>))", "1h", "", "")
where <metric> is just some metric namespace that shows the count of some codahale timer.

**Comment by kylebrandt** [comment]
Could it have anything to do with the new tag restrcitions?, see 0.5 release notes https://github.com/bosun-monitor/bosun/releases

**Comment by liorchaga** [comment]
I don't think so... except for a-z, A-Z, digits, underscores and wildcards, there are no other characters in the expression.
