### ISSUE TITLE
ss/tls mail connections not working

### ISSUE THREAD

**Issue by YerisAntonio** [bosun-monitor/bosun#1844]
Hi!

We have an issue with bosun notifications, we moved from none tls/ssl connection to a tls/ssl connection and every time bosun tries to send a notification it fails with error:

2016/08/01 15:37:35 error: notify.go:111: failed to send alert Test{} to [username@mydomain.com] crypto/tls: use of closed connection

smtpUsername = webmaster@mydomain.com
smtpPassword = somepass
smtpHost = smtp.office365.com:25
emailFrom = bosun@mydomain.com

**Comment by wjk1982** [comment]
telnet smtp.office365.com 25 
can't connected
SSL/TLS protocol cannot be used for bosun
change config as follows 
smtpHost = smtp.qq.com:25
smtpUsername = 271000035@qq.com
smtpPassword = *********
emailFrom = 271000035@qq.com

**Comment by YerisAntonio** [comment]
I tried that mate, did not work, even port 25, it needs TLS, so I ended up configuring a server relay with postfix.
