### ISSUE TITLE
Using scollector to send to influxdb directly

### ISSUE THREAD

**Issue by R-Sommer** [bosun-monitor/bosun#1846]
Hi,

I've read somewhere in the internet (and couldn't find it again) that scollector is able to send data directly to influxdb. However, I cannot get it work means I always get: Status of collector run. 1=Error, 0=Success.

BTW: with -p debug looks like "error: metadata.go:256: Post http://localhost:0/api/metadata/put: dial tcp [::1]:0: getsockopt: connection refused". Port 0 is wrong of course. Is this a display error?

--- my scollector.toml (username and password are replaced here): ---
Host = "http://username:password@localhost:8086/"

[[Vsphere]]
  Host = "192.168.53.21"
  User = "username"
  Password = "password"
------------x------------------------------------------------------------------

So, is this a layer 8 issue or is scollector not able to send data directly to influxdb?

Thanks,
Roland

**Comment by kylebrandt** [comment]
8086 is Influx's native format. scollector sends metrics in OpenTSDB
format. So in Influx's config you need to enable the OpenTSDB listener.

**Comment by kylebrandt** [comment]
-p is "print only mode". It sets the host to localhost:0 to make sure
nothing gets sent. Perhaps that should disable metadata as well. -d makes
it so metadata is printed as well.

**Comment by R-Sommer** [comment]
Thanks for you help. Now I'm able to send metrics from linux to influxdb. Trying to get metrics from an vSphere host still doesn't work.

I'm using scollector-linux-amd64
scollector version 0.5.0 (00772aee8c27482893f885bbdbb10e26f75d7fd0) built 2016-06-21T18:18:45Z
and -l does not report any kind of vsphere. Is that ok? Do I miss something?

**Comment by gbrayut** [comment]
per https://godoc.org/bosun.org/cmd/scollector you have to add settings to the .toml file so it knows where to poll vsphere. Example:

```
[[Vsphere]]
  Host = "vsphere01"
  User = "vuser"
  Password = "pass"
```

**Comment by R-Sommer** [comment]
@gbrayut That's is exactly what I've done, but it does not work: Status of collector run. 1=Error, 0=Success.

However, I've done some more tests and it's works if I configure the vCenter Server instead of ESXi host.
