### ISSUE TITLE
expr returns error if some of the expression have no results

### ISSUE THREAD

**Issue by WangFenjin** [bosun-monitor/bosun#1863]
Hi,

If I add or divide some metrics, the result may be error if one of the expression have no value.

For example, if most of my time my server only return 503 error, and there are no 500, this query can't work. Could we improve this and just ignore the metrics (such as set to 0) in this case?
`
(q("sum:rate{counter,,1}:web.nginx.app.500", "1h", "") + 
 q("sum:rate{counter,,1}:web.nginx.app.503", "1h", ""))
/ q("sum:rate{counter,,1}:web.nginx.app.200", "1h", "")`

Thanks.

**Comment by kylebrandt** [comment]
The seriesset operations are pretty limited.  If you reduce each query first, you can then short circuit to avoid a divide by zero. For example:

```
$five = avg(q("sum:rate{counter,,1}:haproxy.frontend.hrsp{}{status_code=5xx}", "1h", ""))
$two = avg(q("sum:rate{counter,,1}:haproxy.frontend.hrsp{}{status_code=2xx}", "1h", ""))
#$two = 0
$two && $five / $two  > .0001
```

Except for visualization, it is recommended to reduce earlier in the expression.

However, with series operations, things are dropped from the left side if there is no corresponding timestamp in the right side.  You can mix this with the dropbool function to avoid divide by zero:

```
$five = q("sum:rate{counter,,1}:haproxy.frontend.hrsp{}{status_code=5xx}", "1h", "")
$two = q("sum:rate{counter,,1}:haproxy.frontend.hrsp{}{status_code=2xx}", "1h", "")

$two / dropbool($five, ($five > 0))
```

**Comment by kylebrandt** [comment]
I've added a draft of avoiding div by zero on so documentation so this information is findable to others: http://stackoverflow.com/documentation/bosun/drafts/69984
