### ISSUE TITLE
Missing alarm status in API

### ISSUE THREAD

**Issue by efficks** [bosun-monitor/bosun#1865]
I'm using bosun with shinken monitoring system. To do that, i've create a script that check the API status for each alarm to report the status to shinken.
I start the system for the first time, with every systems with optimal values so, all alarm are in normal status.
When calling the api with URL /api/status?ak=cpu{host=<hostname>} I get HTTP 500 error with the message

> unknown alert key: cpu{host=WK-PICC-00}

It seems Bosun is not aware of the alarm state when everithing is OK and no systems report it's alarm at least one time.

It should be possible to get the alart status of every alarm even if it was never reported bad.

[Edit]
By looking at the code in web.go, it seems the status API only looks in the incident database. So if no incidents ever reported for an host, ho alert will be available.
I suggess, to add a mecanism to put the alarm state normal if no incident was reported.

Thanks

**Comment by efficks** [comment]
Up?

**Comment by efficks** [comment]
Up?

**Comment by kylebrandt** [comment]
I think Up is really relative to gravity - where is the gravity?

One could also ask:

Down?

Sideways?

And be left wondering where one fits in a seemingly infinite realm....

Or perhaps you meant something else that what I am pondering? I suggest a
complete sentence ;-)

Hugs.

**Comment by kylebrandt** [comment]
More seriously I do think I get what you are saying. I'm currently making notes on things for refactoring the incident and notification workflows into proper state machines. I think this idea is good and I expect it will be part of that refactor that can hopefully happen sometime this year.

**Comment by efficks** [comment]
Hi @kylebrandt 
Thank you for your answer. I'm more a C++ programmer and I've never touch Go. But if I could help just inform me.

**Comment by efficks** [comment]
@kylebrandt Any news on the refactoring? Is it planned this year?

**Comment by efficks** [comment]
@kylebrandt Any news on the refactoring?
