### ISSUE TITLE
virustotal.com result for scollector-windows-amd64.exe

### ISSUE THREAD

**Issue by R-Sommer** [bosun-monitor/bosun#1873]
Detection ratio: 1 / 55:
Jiangmin:  Trojan.Ebowla.q  

https://virustotal.com/de/file/ec1c0dbe954333ae0d5c4c8a0db9e7a41afa469d4e521dcbe1ad0c583158d9b7/analysis/

I'd assume this is a false positive?

**Comment by gbrayut** [comment]
Likely related to our use of Go 1.6 which is also flagged as containing Ebowla. See https://github.com/golang/go/issues/16292
