### ISSUE TITLE
Continuous external collectors do not get terminated with scollector

### ISSUE THREAD

**Issue by TrentScholl** [bosun-monitor/bosun#1876]
When using continuous external collectors (in the 0 directory), if scollector is restarted the associated external collector does not get terminated. When the new scollector instance starts up, it starts new instances of the continuous external collectors.

Not sure if this is specific to PowerShell, but it's what I'm using and have noticed the issue.

Example - scollector running with 2 external powershell collectors

```
Get-Process powershell

Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName
-------  ------    -----      ----- -----   ------     -- -----------
    198      14    52804      48584   540     0.41   3428 powershell
    204      14    53716      50128   541     0.48   4196 powershell
```

Restart scollector

```
Get-Process powershell

Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName
-------  ------    -----      ----- -----   ------     -- -----------
    200      14    53368      49164   540     0.44   3428 powershell
    201      14    52896      49156   540     0.47   3520 powershell
    206      14    55080      51688   541     0.63   4196 powershell
    198      14    52780      48488   540     0.47   6296 powershell
```

The existing external collectors are still running

**Comment by TrentScholl** [comment]
Here's a quick and dirty work-around for PowerShell external collectors

```
$ParentPid = (gwmi win32_process -Filter "processid='$pid'").ParentProcessId

$GrandParentProcessName = (gwmi win32_process -Filter "processid='$ParentPid'").ProcessName

If ($GrandParentProcessName -NotMatch 'scollector')
{
    Exit
}
```

**Comment by GenghisJan** [comment]
Hi, folks. Maybe this is specific to powershell? FWIW, the process tree for my lone cmd-driven external collector does die when the scollector service is stopped or restarted; not right away, but within ~10 seconds of the scollector proc itself exiting. I don't run a PS-driven collector to compare against. My external collector is invoked like this:

`
C:\Program Files\scollector\collectors\0>type smart-stats.cmd
@echo off
python "c:\Program Files\scollector\collectors\0\smart-stats.py"
`
