### ISSUE TITLE
InfluxQL parser is out of date

### ISSUE THREAD

**Issue by earwin** [bosun-monitor/bosun#1886]
I'm trying to use `moving_average` function in my `influx()` expression and getting a rather cryptic `invalid number of arguments for moving_average, expected 1, got 2` error message.
The very same expression run directly against influx works without any problem.
It then came to my attention that bosun parses influx queries before running them, using a copy of influx code embedded in your repository.
My guess is that parser is out of date?

**Comment by gbrayut** [comment]
I added a PR with the new vendor libraries, but it may take some time before I can do the required testing.

**Comment by gbrayut** [comment]
Thanks to krise3k `SELECT moving_average(usage_idle,6)` queries should now work on master, but moving_average with nested functions like `SELECT moving_average(min(usage_idle),6)` are still having issues with parsing/validation. See https://github.com/bosun-monitor/bosun/pull/1976#issuecomment-265023594 for more details. 

I will wait to close this this until nested functions are working.
