### ISSUE TITLE
escount band() function?

### ISSUE THREAD

**Issue by calh** [bosun-monitor/bosun#1891]
Hi,

I'm trying to construct an alert that compares the count of the past 1 hour of elasticsearch error messages against past messages.  Is there any way to use a band() function with escount()?

Thank you!

**Comment by kylebrandt** [comment]
This would be a new es function. Basically would need to make sure we hit the right indexes, and make multiple elastic Range Filters OR'd together. I had no considered this when I did the elastic functions, and also have some refactoring there in another branch.

I'll aim to get this into the 0.6.0 beta (aiming to release that near end of sept).

The other strategy would be to make N queries like we do with OpenTSDB, but my instinct would be that that would be the wrong choice for elastic.

**Comment by calh** [comment]
So far, this is how I've attempted to implement my own banding, but it doesn't seem to be working.  

```
$start_duration = "1h"
$bucket_duration = "1h"
    
$current = escount($index, "host", $query, $bucket_duration, $start_duration, "")

$hist_w1 = escount($index, "host", $query, $bucket_duration, "1w1h", "1w")
$hist_w2 = escount($index, "host", $query, $bucket_duration, "2w1h", "2w")
$hist_w3 = escount($index, "host", $query, $bucket_duration, "3w1h", "3w")
$hist_w4 = escount($index, "host", $query, $bucket_duration, "4w1h", "4w")

$hist_sum = sum($hist_w1) + sum($hist_w2) + sum($hist_w3) + sum($hist_w4)
$hist_avg = $hist_sum / 4

$sum_current = sum($current)
crit = $sum_current > $hist_avg
```
The check doesn't seem to return any results.  The JSON response looks like this:

```
{"Sets":[{"Critical":0,"Warning":0,"Normal":0,"Time":"2016/08/29-16:45:48"}],
```

Any suggestions on what I'm doing wrong there?  Thanks!

**Comment by kylebrandt** [comment]
I think it is probably the durations. They are passed to our opentsdb.ParseDuration which doesn't support that format I don't think (Will need to see why it is not erroring, it is a regex so need to mentally parse that).

Try changing them 1w1h etc to the duration in hours (i.e. 168h) and see if that fixes it. 

You can also hit Alt-p to bring up miniprofiler when you are on Bosun's expression page. You should be able to expand the box in the corner and get to the raw JSON of the elastic query that is sent if it still isn't working for you and maybe we can see what is going on from that.

**Comment by kylebrandt** [comment]
Or you can do something like `tod(d("1w") + d("1h"))`

**Comment by calh** [comment]
I've tried both of these formats, and received the same null results:
```
$hist_w2 = escount($index, "host", $query, $bucket_duration, "337h", "336h")
$hist_w2 = escount($index, "host", $query, $bucket_duration, tod(d("2w") + d("1h")), tod(d("2w")))
```

`Alt + p` on the Expression page doesn't seem to do anything for me?  However, I also tested my "1w1h" format and it returned the same results as the hour format.

I have a feeling the problem I'm seeing has something to do with adding the sum() functions together, and dividing by the scalar `4`.  Is there anything wrong with what I'm doing there?

**Comment by calh** [comment]
Wait... I feel dumb.  The index I'm using is a newer one, and I don't yet have 4 weeks of data.  :-/  If I average 3 weeks of data, my alert functions.

However, I'd still love to have a proper esband() function that is a little more efficient at performing this aggregation.  :-)

**Comment by kylebrandt** [comment]
alt-p should show miniprofilter, which looks like a box in the lower left corner:

![image](https://cloud.githubusercontent.com/assets/1692624/18060463/6bd1392e-6dec-11e6-8f49-91503e7271f5.png)

I just tried the following and it works okay for me:

```
$index = esls("logstash")
$keyField = "logsource"
$filter = esall()
$current = escount($index, $keyField, $filter, "1h", "1h", "")
$old = escount($index, $keyField, $filter, "4h", "3h", "")
sum($current) * sum($old) / 2
```

**Comment by kylebrandt** [comment]
Your response from Bosun is still unexpected, if you don't have indexes for one of the queries it should error ("no elastic indices available during...") . Do you have indexes with no documents in them or something?

**Comment by calh** [comment]
I'm not sure what I was fat fingering before... but I have the profiler working, very handy!

I should clarify, the index itself is not new, but it's a new app added to an existing index.  So, zero documents returned sounds like an acceptable response.
