### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by efficks** [bosun-monitor/bosun#1895]
I'm observing a memory leak on Bosun. I'm using it with the internal redis and get the data from graphite. 
Can the internal redis be the cause of the problem?
![image](https://cloud.githubusercontent.com/assets/8975620/18280313/a31f1ef6-7426-11e6-90ed-8b7bf340dbf9.png)

Is there a setting I'm missing to clear the memory?

**Comment by captncraig** [comment]
Does it drop again if you restart bosun? I believe the ledis store should be storing things on disk, and should not use unbounded memory.

**Comment by efficks** [comment]
@captncraig Yes it does. It return to it's original memory usage, 221 Mib.

**Comment by efficks** [comment]
I'm running Bosun on Ubuntu Server 12.04 LTS

**Comment by captncraig** [comment]
ok, we should get a heap dump from you after it has run for a while. I'll have instructions shortly.

**Comment by efficks** [comment]
@captncraig Thank you for your help.

**Comment by captncraig** [comment]
Lets try this. Hopefully you have go installed. 

Run `go tool pprof http://your-bousn-server/debug/pprof/heap`

You should see soemthing like:
```
Fetching profile from http://ny-bosun01.ds.stackexchange.com/debug/pprof/heap
Saved profile in /Users/yourname/pprof/pprof.ny-bosun01.ds.stackexchange.com.inuse_objects.inuse_space.002.pb.gz
```
grab that zip file and upload it somewhere we can get it.

**Comment by efficks** [comment]
@captncraig There it is. I runner bosun 20 hours and the memory gets from 259 MiB to 283 MiB
Not a so big value but in one week it gets huge.
If it can help you, I'm also using the API  and I don't acknowledge any alarm.
Finally, I've made this test with a real redis server. The leak continue to be present.

It's the only problem I get before pushing this nice system in production. I got the problem on two independent platforms running Ubuntu server 12.04 LTS.

Thank you for your help.
[pprof.10.133.63.22:8070.inuse_objects.inuse_space.001.pb.gz](https://github.com/bosun-monitor/bosun/files/459238/pprof.10.133.63.22.8070.inuse_objects.inuse_space.001.pb.gz)

**Comment by captncraig** [comment]
Hmmm, nothing is jumping out at me as abnormal there. In use only accounts for ~48MB. Would you mind re-running it with `go tool pprof -alloc_space http://10.133.63.22:8070/debug/pprof/heap` please? Are you reloading the config at runtime by chance? 

It may also be useful if you can show graphs of `bosun.collect.alloc`, `bosun.collect.gc.total_pause` and `bosun.collect.goroutines`. Sorry, kinda shooting in the dark here, but those are some of the first places we look.

**Comment by captncraig** [comment]
Would also like to see the graph of `bosun.collect.alloc` vs your collectd gathered view of the memory in case there is a discrepancy between what the os has allocated and what the go runtime is managing.

**Comment by efficks** [comment]
@captncraig I'm on it. I will try to do it tomorrow.

**Comment by efficks** [comment]
@captncraig I think I forgot to use the -alloc_space option for the last file.
I also made a graph comparing vm memory with resident (rss) memory. The memory seems to increase a little bit but it does not seems a lot.
Where do you take data like bosun.collect.alloc and bosun.collect.gc.total_pause?

[pprof.10.133.63.22:8070.alloc_objects.alloc_space.001.pb.gz](https://github.com/bosun-monitor/bosun/files/459821/pprof.10.133.63.22.8070.alloc_objects.alloc_space.001.pb.gz)

![memorybosun](https://cloud.githubusercontent.com/assets/8975620/18324887/bcc309da-750c-11e6-9de2-c33bb5038b76.png)

**Comment by efficks** [comment]
@captncraig I've runned bosun for 2 weeks.
There is the result : 
![2016-09-14 14_49_06-grafana - test](https://cloud.githubusercontent.com/assets/8975620/18525438/7d8611b2-7a8a-11e6-927c-ab5de8473cec.png)
