### ISSUE TITLE
TLS and HTTP Basic Auth support for tsdbrelay

### ISSUE THREAD

**Issue by bencarlton** [bosun-monitor/bosun#1898]
scollector supports TLS and HTTP Basic Auth, but tsdbrelay does not. This makes it difficult to secure an OpenTSDB cluster when leveraging tsdbrelay.

**Comment by captncraig** [comment]
what do you mean? like auth to opentsdb? Can't you put it in the urls: `https://name:pass@mytsdb03`? Or do you mean actually having tsdbrelay check the credentials. That is a bit of a harder problem.

**Comment by kylebrandt** [comment]
We are adding SSL to bosun as part of 0.6.0-beta due @ end of month. Maybe
@captcraig can advise if it would be trivial to add it here at the saem
time.

**Comment by bencarlton** [comment]
@captncraig I tried specifying encoding the credentials in the urls. This works for scollector, but tsdbrelay throws an error stating that there are too many colons in the address.

`http: proxy error: dial tcp: too many colons in address <username>:<password>@<hostname>:<port>`

You get the same error whether you specify the scheme or not.

**Comment by captncraig** [comment]
oh, that may be a result of how we internally translate urls. I can take a look.

**Comment by gbrayut** [comment]
Usually you would have multiple tsdbrelay instances behind a load balancer like haproxy, so terminating TLS at the LB and handling authentication/acls there is the best recommendation. A single instance of tsdbrelay isn't highly available and will cause metrics to be lost when you update or restart the service.

**Comment by bencarlton** [comment]
@gbrayut What about securing access to OpenTSDB (assuming the daemons are behind a load balancer)? Whitelist the IPs of all of the servers running tsdbrelay?

**Comment by gbrayut** [comment]
We have opentsdb behind the same load balancer, which spits /api/put write traffic and /api/query read traffic (See http://kbrandt.com/post/bosun_arch/) and applies IP based whitelist/blacklist to who can access /api/put. The tsdbrelay instances run directly on each write opentsdb node (best to have dedicated write and read nodes).

So a basic layout is  request -> haproxy -> a) send reads to opentsdb, b) send writes to tsdbrelay on write nodes -> tsdbrelay forwards to local opentsdb instance.

**Comment by gbrayut** [comment]
In general it is difficult to do auth in tsdbrelay, as it literally relays the request bytes to the target (with minimal changes to the request headers). Better to use a load balancer and/or standard networking firewall rules to control access to the targets.

**Comment by lmorfitt** [comment]
Hello,

Do you have a ETA for 0.6.0 please.

Thanks,
Luke
