### ISSUE TITLE
Alerting on yesterday's data

### ISSUE THREAD

**Issue by andycarlsonuk** [bosun-monitor/bosun#1911]
I suspect that my use case is a little out of the ordinary although probably not unique.

I’m experimenting with Bosun by feeding it with monitoring metrics from a production system but I don’t have permission to put it onto a machine where it can get metrics in near real time.

Instead I’m feeding it with semi-historical metrics that are extracted daily. Typically I will get the metrics at, say, 10AM. In most cases the metrics will be for midnight to midnight on the previous day.

I hope to be able to plug Bosun into near real time metrics in future but right now I need to work with the ‘batch’ extracts, learn Bosun, test some useful alerts and demonstrate its value to the customer.

I’ve come up with two approaches, both of which have drawbacks. Maybe there is another approach that I have not found.

Option 1 is to have the alerts work on a long time span – 36 hours will guarantee covering the whole of the previous working day on Tuesday to Friday. To pick up Friday’s data on a Monday morning needs an even bigger time span. The first snag here is that the alerts are very coarse grained in time. An issue that happens, say, late on a Tuesday will cause the alert to remain in a critical state for more than a day afterwards. Another requirement is to compare, say, the performance for 11-12AM yesterday with the norms established for the same day and hour in previous weeks. I don't know whether this is possible when using coarse time windows. If it is possible then it's certainly difficult to figure out. A final snag is that alerts like this will probably need to be thrown away when I do eventually move to near real time data.

Option 2 is to use the rule editor page and the /api/rule call. This allows the alerts to be much tighter time-wise because the API allows me to say exactly what start and end time I want to look at (option 1 always uses ‘now’ as the end time). Here I'm just using Bosun as a rules engine and skipping the alert acknowledgement workflow etc. The downside is that the API always seems to generate exactly one email… even if more than one host has an issue. It also generates an email when there are no issues at all.

I realise that option 2 is intended for testing and that's probably what I'm doing... but I'd like to keep running my alerts on new data for a period of time once I think that I've got the logic right. This often proves that the alerts are not quite right. Sometimes they also pick up real issues that were not noticed on the day.

So far I have not found a way that gives me both a tight time window for data relating to yesterday AND generates the correct number of email notifications.

**Comment by gbrayut** [comment]
If it was me I'd try to create all my alerts using q("...","36h","35h") so it is always looking at an hours worth of data 36 hours in the past (or something similar to get a 5min window offset by 36 hours). It means you may not get an alert until 36 hours after it occured, but your data is already delayed so there is no real way around that. That is better than having a long window of data, since looking at a full 36 hours means alerts don't go normal until the event is outside of the window.

**Comment by andycarlsonuk** [comment]
Thanks. I see what you're saying but having a guaranteed 36 hour delay seems like a bad place to be because it pretty much guarantees that you won't be notified of an issue even on the working day after it happened. These are genuine issues so there is a decent chance that Bosun can tell us stuff that we don't know even with the data being from yesterday.

If the alerting tool provides control of the time window (both the start and the end) that it's looking at then most of the things possible with real time data become possible on historical batch data - at least everything can be notified on the following working day which is the best that can be expected given the limitations of the data. Knowing when to run the alerts is not an issue - I know when the data arrives so it's easy enough to make an API call at the right time.

Seems to me that Bosun can do all of these things... but not all at the same time (unless I'm missing something).

At the moment my plan is to go with the /api/rule approach and write some stuff to extract the group tags and alert status from the JSON response. Then I'll at least be able to flag the issues to myself but the notifications won't have the context data that's available to Bosun templates or the ability to embed graphs... which is quite a loss.
