### ISSUE TITLE
feature request: InfluxDB band

### ISSUE THREAD

**Issue by andycarlsonuk** [bosun-monitor/bosun#1913]
As far as I can see there is no equivalent to the 'band' function for InfluxDB queries... which makes it difficult to implement anomaly style alerting.

I checked whether there is some magic possible in InfluxQL to avoid the need for this function but I don't think so.

**Comment by p3r7** [comment]
Yup, and even if we did manually one select per wanted band, there seems to be no practical way to concatenate them.
Indeed, merge would fail in this case as series would share similar tags.

**Comment by kylebrandt** [comment]
@p3r7 Correct, merge takes multiple sets (series), and combines the items into a single set.

A function that would do this would be something new (call it `concat`) for now. Concat would look for matching series between the sets, and then concatenate the values of matching series.

**Comment by p3r7** [comment]
Indeed, we could have a generic `concat` function an eventually in a second time an `influxBand` for syntactic sugar needs.
