### ISSUE TITLE
Does scollector support Event Tracing for Windows (ETW) on Windows?

### ISSUE THREAD

**Issue by pisees** [bosun-monitor/bosun#1917]

**Comment by gbrayut** [comment]
There isn't anything build into scollector for ETW. We use an OLE package to access some WMI counters, but even then it is specific counters that are hard coded.

You can always use [external collectors](http://bosun.org/scollector/external-collectors) to capture whatever metrics you want. There is a [sample PowerShell collector](http://stackoverflow.com/documentation/bosun/720/scollector-external-collectors/2426/sample-collector-written-in-powershell#t=201609271628183385752) that could be converted to gather data from ETW.
