### ISSUE TITLE
lookupSeries function doesn't work for notification lookup. 

### ISSUE THREAD

**Issue by digrich** [bosun-monitor/bosun#1921]
We are not able to use lookupSeries for the notification lookup. 

It gives the following configuration error

conf: Test Config:248:7: at <warnNotification = l...>: unknown notification lookupSeries(q("zimsum:

**Comment by gbrayut** [comment]
I think this is actually just a parse time error. May need to update the regex at https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/conf/rule/rule.go#L470 and the code for procNotification

**Comment by gbrayut** [comment]
Also it was reported that the lookup(...) function doesn't work for setting notifications if the alert uses log=true. I haven't tested this yet, but it may be another edge case in the code.

**Comment by digrich** [comment]
Any priority to fix this issue?

**Comment by kylebrandt** [comment]
lookup when used as the value of `warnNotification` or `critNotification` in an alert def is actually different the expression lookup function - it is different code paths even though it looks like the same call.

**Comment by kylebrandt** [comment]
Verified it cannot be used with log alerts. It throws:

```
$ go run main.go -c bosun.toml -w -r -skiplast
2017/03/16 15:18:52 fatal: main.go:118: couldn't read rules: conf: ./examples.conf:23:0: at <alert exampleTable {...>: log + warn specified, but no warnNotification
exit status 1
```

in rule.go

```
func (c *Conf) loadAlert(s *parse.SectionNode)
```

throws it.

**Comment by kylebrandt** [comment]
My assumption is that a.WarnNotification.Notifications is 0 when there are only notification lookups. In the case of non-log the this gets past the logic. Because we check if the length is not zero, then check if the corresponding expression is not nil.

But with log alerts, we only check if it is zero if the expression is not there.

```
	if a.Log {
		for _, n := range a.CritNotification.Notifications {
			if n.Next != nil {
				c.errorf("cannot use log with a chained notification")
			}
		}
		for _, n := range a.WarnNotification.Notifications {
			if n.Next != nil {
				c.errorf("cannot use log with a chained notification")
			}
		}
		if a.Crit != nil && len(a.CritNotification.Notifications) == 0 {
			c.errorf("log + crit specified, but no critNotification")
		}
		if a.Warn != nil && len(a.WarnNotification.Notifications) == 0 {
			c.errorf("log + warn specified, but no warnNotification")
		}
	}
	if len(a.WarnNotification.Notifications) != 0 {
		if a.Warn == nil {
			c.errorf("warnNotification specified, but no warn")
		}
		if a.Template == nil {
			c.errorf("warnNotification specified, but no template")
		}
	}
```

The current method to resolve lookups - Get, required a rule conf provider which is what we are creating at parse time. So these checks either need to be removed I think, or the resolution of notification lookups needs to be moved to the rule package. I could be missing something here though or mistaken, need to check with fresh eyes

**Comment by kylebrandt** [comment]
I can get the length via `len(a.CritNotification.Notifications) + len(a.CritNotification.Lookups)`

However, the checks don't make sense. I may want to have alerts with no notifications (i.e. so they only are on the dashboard).

Also, a may want to define some shared macros that have warn/crit contacts, but use them with alerts that have warn or crit only.

Therefore these checks just need to be removed that compare Warn statements with notifications.

**Comment by kylebrandt** [comment]
That PR should fix this. Also the explanation about lookup being different from the expr function is added to the sixDocs branch which will get merged.

**Comment by digrich** [comment]
Thanks @kylebrandt

**Comment by angadsingh** [comment]
@kylebrandt even after the above PR/fix, lookupSeries still doesn't work with notifications (i.e. critNotification). You fixed the log-alert problem, not the lookupSeries problem. Any workaround or fix planned for that?

**Comment by kylebrandt** [comment]
@angadsingh You should be using `lookup` regardless when defining notification lookups. I updated the documentation to mention this: http://bosun.org/definitions#lookup-tables

**Comment by angadsingh** [comment]
@kylebrandt how will lookup function work with graphite data? we use lookupSeries exactly because we need to use it with a graphite query. So does that choosing different notifications based on tags isn't possible with graphite?

**Comment by angadsingh** [comment]
@kylebrandt we just checked. lookup works with graphite now. earlier there was a bug where it didn't.
