### ISSUE TITLE
Alert stays active after data stops in stead of going unkown

### ISSUE THREAD

**Issue by IzakMarais** [bosun-monitor/bosun#1925]
An alert is stuck in _Critical_ _Active_ state even thought the time-series it evaluates stopped days ago. The alert was  _Critical_ _Active_ when the time series stopped. The expected behaviour is that is should go _Unknown_. We were unable to get rid of the alert though any user interface method. Restarting Bosun did not have an effect. After deleting the state file and restarting the alert is gone, as expected. 

The alert definition is a pretty basic threshold alert:

```
alert sds_CriticalAlarmCmChannelAlloc {
    template = sfeTemplate
    $alarms = max(q("sum:critical.alarm.active{alarmtype=channel-alloc-failure,host=*,resourcetype=*,systemtype=sds,servicetype=*,systemuid=*}", "5m", ""))
    macro = grafanaConfig
    $grafanaDash = $grafanaHost/dashboard/db/ssm-dashboard
    crit = $alarms > 0
}
```

I can add screenshots we took if that will help. 

We are on Bosun 0.4 [(9ef650b36b5d4abb6cf6fe4a4a57327045a97fa4) built 2015-09-18T14:39:03Z].

**Comment by kylebrandt** [comment]
Probably a fixed bug. I would upgrade to 0.5 which uses redis/ledis instead
(redis recommended for production).

Going from .4 to .6 when it is released won't upgrade your state file to
redis whereas .4 to .5 does. Although, maybe you don't care if you are
willing to delete your state file.

.5 is also a lot more performant. .5 would have issues for us where the
dashboard would take 30 seconds to load etc, that isn't the case anymore.

**Comment by pradeepbbl** [comment]
#1812 looks very similar
