### ISSUE TITLE
Need method for combining two series using empty tag set into one graph

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1927]
Right now the only way to generate a graph from multiple queries is using the merge(...) function. That function won't allow you to merge two series with the exact same tags, so you sometimes need to do something like merge($series1,rename($series2,"host=series2host")).

This doesn't work if both series tags are empty. I don't think we have any way to add a tag to a series, so I can't think of any way to currently graph two series using empty tags.

**Comment by kylebrandt** [comment]
If you look at docs in repo:

# Group Functions

Group functions modify the OpenTSDB groups.

## addtags(seriesSet, group string) seriesSet

Accepts a series and a set of tags to add in `Key1=NewK1,Key2=NewK2`
format. This is useful when you want to add series to set with merge and
have tag collisions.

Just haven't pushed the documentation, but that is in master and may solve
your problem?

**Comment by gbrayut** [comment]
Ah sweet... I'll try that and report back later. Thanks!
