### ISSUE TITLE
Bosun Dashboard should auto refresh

### ISSUE THREAD

**Issue by IzakMarais** [bosun-monitor/bosun#1961]
The use case is that we would like the Bosun dashboard up on a wallboard. It should auto-refresh to display the latest alerts after each Bosun evaluation run. 

I think this is a valid use-case for an alerting tool.

**Comment by kylebrandt** [comment]
The Grafana Bosun plugin app can do this with the incident panel. Doesn't resolve the issue, but sort of a "work around" to anyone else running into this issue.
