### ISSUE TITLE
unable to pass custom dev.conf to bosun docker image

### ISSUE THREAD

**Issue by srikhi** [bosun-monitor/bosun#1963]
Trying the latest bosun docker image (0.6.0-pre) with a dev.conf that has been working till 0.5.0
but now the contents of the file are not being honored. Below is the docker compose file that I have been using with previous rev (0.5.0 that is also tagged as latest on docker hub)
 

version: '2'
services:
  bosun:
    image: "stackexchange/bosun:0.6.0-pre"
    container_name: bosun
    ports:
      - "8071:8070"
    volumes:
      - "/containers/private/bosun/conf/dev.conf:/data/bosun.conf"

**Comment by gbrayut** [comment]
In the 0.6.0 docker image some of the files moved. bosun.conf isn't used anymore, and was split into bosun.toml for system settings, and bosunrules.conf for notifications/templates/macros/lookups/alerts. See https://github.com/bosun-monitor/bosun/tree/master/cmd/bosun/docker/run for examples of these files. Also you can now edit and save the rules file directly from the website.

The documentation is still in a staging branch right now, but you can see some more examples at https://github.com/bosun-monitor/bosun/tree/master/cmd/bosun
