### ISSUE TITLE
'depends' clause uses a different validator than crit/warn do

### ISSUE THREAD

**Issue by sysadmin1139** [bosun-monitor/bosun#1965]
Given an alert that looks like this:

```ruby
alert lacking_counted_thing_pd {
  # If we haven't seen a thing in a while, and we're busy enough to care, scream
  $oldsa = since(influx("graphite", "select last(value) from counters_service_a where service='worker_success_thing'", "30m", "0", ""))
  $oldsb = since(influx("graphite", "select last(value) from counters_service_b where service='worker_success_thing'", "30m", "0", ""))
  $numVertsSa = sum(influx("graphite", "select sum(value) from counters_service_a where service='worker_success_thing'", "30m", "0", ""))
  $numVertsSb = sum(influx("graphite", "select sum(value) from counters_service_b where service='worker_success_thing'", "30m", "0", ""))
  $depend_threshold = 75
  $alarm_threshold = 300
  depends = $numVertsSa < $depend_threshold && $numVertsSb < $depend_threshold
  crit = $oldsa > $alarm_threshold && $oldsb > $alarm_threshold
  ignoreUnknown = true
  template = pagerduty
  critNotification = pagerduty
}
```
I'm getting a validation error of `Depends and crit/warn must share at least one tag.`

This might be an Influx-specific thing, but the depends-test and the crit-test are using nearly identical queries and logic. And yet, the depends test is failing validation. That suggests a different validator is being used.

This is in the release version of 0.5.0

**Comment by IzakMarais** [comment]
Not sure how to read that influx query, but this might be related to https://github.com/bosun-monitor/bosun/issues/431#issuecomment-108936772. Would be great to get feedback from devs on current status of using depends without tagsets.
