### ISSUE TITLE
/api/egraph won't render graphs I can build in the expression tab

### ISSUE THREAD

**Issue by eswdd** [bosun-monitor/bosun#1966]
For example, I have an expression which we use to extrapolate when our tsdb write rate will exceed our threshold and render it nicely:
```
$recent_period = 16w
$extrapolate_period = 10y
$q = dropl(q("sum:1d-max:rate:tsd.rpc.received{type=put}","$recent_period",""), 0)
$line = linelr($q, "$extrapolate_period")
$offset_line = $line - first($line) + max($q)
$line_start = epoch() - d("$recent_period")
$threshold = series("line=threshold", $line_start, 100000, epoch() + d("$extrapolate_period"), 100000)
$m = merge($q, $offset_line, $threshold)
$m
```

This renders nicely on the expr tab when I click graph. However, attempts to render this in a template using the .Graph command, or embedding using the /api/egraph link result in the following error:

> expr: unexpected invalid character: $ in input

How do I render complex expressions for use in a template? I can't find any samples.

**Comment by kylebrandt** [comment]
Working on improving the template documentation, but for now you can see
examples at
http://stackoverflow.com/documentation/bosun/716/templates-graph-and-graphall#t=201611211550198275677

**Comment by eswdd** [comment]
Ah perfect, I don't suppose you can parameterise it to not render markers for the points to match the UI?

**Comment by eswdd** [comment]
Actually had a look at the code, I can see you can't. Thanks.
