### ISSUE TITLE
Forget action doesn't generate email notification with message

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1967]
If an alert goes unknown and you use the Forget button to clear it from the dashboard, it prompts you to enter a message. There is a checkbox on the action page to "Send Notification", which when checked will send the specified message to the notification assigned as crit or warn when you press the submit button. 

It doesn't seem to work for the Forget action, so my guess is that Forget is not setup to send any notifications. We probably want Forget to send notifications similar to the ones generated when you acknowledge alerts (so long as the send notification box is checked).

**Comment by kylebrandt** [comment]
@captncraig maybe related to some of the changes you are working on for HTTP notifications?
