### ISSUE TITLE
TSDB failed to start when running bosun from official docker image

### ISSUE THREAD

**Issue by sahil-sharma** [bosun-monitor/bosun#1973]
Greetings Bosun Team,

I faced this issue while spinning up a bosun container (using official docker image). TSDB failed to start. Don't know why? On checking the log files via getting into the container (tail -f /var/log/opentsdb/opentsdb.log) and found that file is empty.
I am attaching the screenshot of the problem I am facing. Kindly check and update me if I am missing out something.
Thanks.

![bosun tsdb](https://cloud.githubusercontent.com/assets/5774379/20751544/531bab42-b722-11e6-9829-99cb28af3849.png)

**Comment by gbrayut** [comment]
Which image did you try? The latest tag is still 0.5.0, but stackexchange/bosun:0.6.0-pre is a newer version with some fixes https://github.com/bosun-monitor/bosun/pull/1915#issuecomment-259295397

That image also has a fix to a timing issue in one of the scripts that caused issues with opentsdb starting
https://github.com/bosun-monitor/bosun/commit/b585c890132ed272a20cd4e9c2e2d176730d33b8

Basically the script ran before hbase was online, so none of the tables actually existed.

**Comment by sahil-sharma** [comment]
Thanks for the update. After using the stackexchange/bosun:0.6.0-pre TSDB works fine.
