### ISSUE TITLE
Remove previous container entries from Bosun which are not alive anymore

### ISSUE THREAD

**Issue by sahil-sharma** [bosun-monitor/bosun#1974]
Greetings Bosun Team,

Let's assume I have five container ID's in Bosun items (sending metrics via scollector). And, after some time my two containers were down and replaced by two new containers (obviously with new container ID's) and are appearing in Bosun items dashboard but the previous container ID's are still being visible in the dashboard. Isn't cumbersome when you have 100+ containers? How can we differentiate between the alive and dead containers?
Kindly do the needful or update me if there is any option.
Thanks in advance!

**Comment by gbrayut** [comment]
Lack of datapoints usually means the container isn't running. After a while the tags will stop showing up in the autocomplete drop down (See https://github.com/bosun-monitor/bosun/issues/1969 for some details) but we don't have any sort of data retention or removal policies.

Also the container monitoring in Bosun is pretty basic. We don't use them much here so there are probably some rough edges in that area.

**Comment by EricFortin** [comment]
While it helps on the UI side, the cache in Bosun keeps growing forever and backup to redis gets bigger and bigger with time. This is not so much an issue for size as it is for number of operations I think. Bosun memory consumption also expand with time as it internally copies the data before backing it up. Is there some way to age data ?

**Comment by bobais** [comment]
Hi, I have related requirement. Possibility to delete old data - lets say 2yo+ data are not interesting anymore and in order to have dataset as small as possible I would like to remove them. Is there any way how to do it? Is there some feature request I can vote for? Thanks in advance.

**Comment by kylebrandt** [comment]
This newish option in master takes care of the majority of memory growth

http://bosun.org/system_configuration#maxrenderedtemplateage
