### ISSUE TITLE
How to transfer TimeFormat

### ISSUE THREAD

**Issue by FAKERINHEART** [bosun-monitor/bosun#1988]
Two problems:
1. If I got value of a variable in time format like "2016-12-15 05:47:00 +0000 UTC" in an alert and its template, how can I transfer the value to Unix Seconds (TimeStamp)? **#Because my alert's calculation is related to timestamp.**

2. If I use escount(...) to request log aggregation from Elastic, is there any possible to get the specific contents of these logs, such as the serial number of each log?
        $index = esls("logstash-cpp_75")
        $filter = esregexp("category", "server.pay.yinshang_query_verify_consumer")
        $m_count = escount($index, "priority", $filter, "1m", "1h", "")

THX~

**Comment by gbrayut** [comment]
Not sure I follow exactly what you are asking. Might be easier if you provide an example. In templates there are a only [certain functions](http://bosun.org/configuration#functions-available-to-alert-templates) you can use, but one of them is the http://golang.org/pkg/time/#ParseDuration which can be used like:

```
    $notes = This alert exists to notify of us any SSL certs that will be expiring for hosts monitored by our httpunit test cases defined in the scollector configuration file.
    $expireEpoch = last(q("min:hu.cert.expires{host=ny-bosun01,url_host=*,ip=*}", "1h", ""))
    $secondsLeft = ($expireEpoch - epoch())
    $daysLeft = $secondsLeft / d("1d")

       #Template
       <tr>
            <td>Expiration Date</td>
            <td>{{.Last.Time.Add (parseDuration (.Eval .Alert.Vars.daysLeft | printf "%vs")) }}</td>
       </tr>
```

The following would show up to 200 messages from the last hour on that index, displaying the logsource and message values.
```
        {{ $index  := (.Eval .Alert.Vars.index)}}
        {{ $filter := (.Eval .Alert.Vars.filter)}}
        {{range $i, $x := .ESQueryAll $index $filter "60m" "" 200 }}
            <tr>
                <td style="text-align: right;">{{$x.logsource}}</td>
                <td>{{$x.message}}</td>
            </tr>
        {{end}}
```

**Comment by FAKERINHEART** [comment]
I have add a new Context's function in sched/template.go as below to solve the timestamp transform.
![image](https://cloud.githubusercontent.com/assets/13352188/21255058/8fd76b28-c3a4-11e6-85a4-86fa025f871d.png)

**Comment by FAKERINHEART** [comment]
I have add a new Context's function in sched/template.go as below to solve the timestamp transform.
![image](https://cloud.githubusercontent.com/assets/13352188/21255058/8fd76b28-c3a4-11e6-85a4-86fa025f871d.png)
