### ISSUE TITLE
Query aggregation using unique tag values

### ISSUE THREAD

**Issue by JamieCressey** [bosun-monitor/bosun#1990]
We have a number of API servers that are then split up into groups. If I wanted to create an alert that aggregates the CPU usage across all API servers in each group, would I need to create a rule for each group, e.g;

```
avg(q("avg:rate:os.cpu{purpose=api, group=group1}", "5m", "")) > 80
avg(q("avg:rate:os.cpu{purpose=api, group=group2}", "5m", "")) > 80
...
```

Or is there a more dynamic way of specifying the group tag to be unique without having to repeat the majority of config for each group?

I'm fairly sure it's not available natively in OpenTSDB, but wanted to check no Bosun magic has been worked on this too!

**Comment by gbrayut** [comment]
Not sure I understand... does purpose=api, group=* not work? You can also define a [macro](https://bosun.org/configuration#macro) if there are alerts that share common queries. The macro can also use variables that are defined in each of the alert definitions.
