### ISSUE TITLE
How to get the zero time in "Alert"?

### ISSUE THREAD

**Issue by FAKERINHEART** [bosun-monitor/bosun#1995]
I want to get the duration from the zero time of today to now. So I wanna get the zero time of today. Is there any function or way satisfying it?

**Comment by kylebrandt** [comment]
There is not, but if you want to make a PR, you could model it on the month function http://bosun.org/expressions#monthoffset-scalar-startend-string-scalar that does basically the same thing, but the "zero time" of the month.
