### ISSUE TITLE
"image" button not working for graph

### ISSUE THREAD

**Issue by PeterGrace** [bosun-monitor/bosun#1996]
When trying to generate an image from the graph page, I receive the following error when trying to make the image:

`opentsdb: {"start":"2h-ago","end":"","queries":[{"aggregator":"sum","metric":"os.net.tunnel.bytes","rate":true,"rateOptions":{"counter":true,"resetValue":1},"filters":[{"type":"auto","tagk":"direction","filter":"*","groupBy":true},{"type":"auto","tagk":"host","filter":"a-host","groupBy":true},{"type":"auto","tagk":"iname","filter":"some|interfaces","groupBy":true}]}]}: Unable to parse the given JSON`

**Comment by kylebrandt** [comment]
Closing because old, please reopen if this is still a problem.
