### ISSUE TITLE
'short link' button does not work for this query.

### ISSUE THREAD

**Issue by PeterGrace** [bosun-monitor/bosun#1997]
When I create a graph from the graph page that includes two queries, the short link button fails without telling the user why, it simply just clicks and doesn't indicate anything further.

[graph in question](http://bosun/graph?b64=eyJzdGFydCI6IjIwMTYvMTIvMjEtMTc6MzY6MTciLCJxdWVyaWVzIjpbeyJhZ2dyZWdhdG9yIjoic3VtIiwibWV0cmljIjoib3MubmV0LnZpcnR1YWwuYnl0ZXMiLCJkZXJpdmF0aXZlIjoiYXV0byIsImdiRmlsdGVycyI6eyJkaXJlY3Rpb24iOnsidHlwZSI6ImF1dG8iLCJ0YWdrIjoiZGlyZWN0aW9uIiwiZmlsdGVyIjoiKiIsImdyb3VwQnkiOnRydWV9LCJob3N0Ijp7InR5cGUiOiJhdXRvIiwidGFnayI6Imhvc3QiLCJmaWx0ZXIiOiJkZW4tZmdhdGUwMSIsImdyb3VwQnkiOnRydWV9LCJpZmFjZSI6eyJ0eXBlIjoiYXV0byIsInRhZ2siOiJpZmFjZSIsImZpbHRlciI6IiIsImdyb3VwQnkiOnRydWV9LCJpbmFtZSI6eyJ0eXBlIjoiYXV0byIsInRhZ2siOiJpbmFtZSIsImZpbHRlciI6IkRFTi1MRVZFTDMiLCJncm91cEJ5Ijp0cnVlfX0sIm5HYkZpbHRlcnMiOnsiZGlyZWN0aW9uIjp7InR5cGUiOiJhdXRvIiwidGFnayI6ImRpcmVjdGlvbiIsImZpbHRlciI6IiIsImdyb3VwQnkiOmZhbHNlfSwiaG9zdCI6eyJ0eXBlIjoiYXV0byIsInRhZ2siOiJob3N0IiwiZmlsdGVyIjoiIiwiZ3JvdXBCeSI6ZmFsc2V9LCJpZmFjZSI6eyJ0eXBlIjoiYXV0byIsInRhZ2siOiJpZmFjZSIsImZpbHRlciI6IiIsImdyb3VwQnkiOmZhbHNlfSwiaW5hbWUiOnsidHlwZSI6ImF1dG8iLCJ0YWdrIjoiaW5hbWUiLCJmaWx0ZXIiOiIiLCJncm91cEJ5IjpmYWxzZX19LCJmaWx0ZXJzIjpbeyJ0eXBlIjoiYXV0byIsInRhZ2siOiJkaXJlY3Rpb24iLCJmaWx0ZXIiOiIqIiwiZ3JvdXBCeSI6dHJ1ZX0seyJ0eXBlIjoiYXV0byIsInRhZ2siOiJob3N0IiwiZmlsdGVyIjoiZGVuLWZnYXRlMDEiLCJncm91cEJ5Ijp0cnVlfSx7InR5cGUiOiJhdXRvIiwidGFnayI6ImluYW1lIiwiZmlsdGVyIjoiREVOLUxFVkVMMyIsImdyb3VwQnkiOnRydWV9XX0seyJhZ2dyZWdhdG9yIjoic3VtIiwibWV0cmljIjoib3MubmV0LnR1bm5lbC5ieXRlcyIsImRlcml2YXRpdmUiOiJhdXRvIiwiZ2JGaWx0ZXJzIjp7ImRpcmVjdGlvbiI6eyJ0eXBlIjoiYXV0byIsInRhZ2siOiJkaXJlY3Rpb24iLCJmaWx0ZXIiOiIqIiwiZ3JvdXBCeSI6dHJ1ZX0sImhvc3QiOnsidHlwZSI6ImF1dG8iLCJ0YWdrIjoiaG9zdCIsImZpbHRlciI6ImRlbi1mZ2F0ZTAxIiwiZ3JvdXBCeSI6dHJ1ZX0sImlmYWNlIjp7InR5cGUiOiJhdXRvIiwidGFnayI6ImlmYWNlIiwiZmlsdGVyIjoiIiwiZ3JvdXBCeSI6dHJ1ZX0sImluYW1lIjp7InR5cGUiOiJhdXRvIiwidGFnayI6ImluYW1lIiwiZmlsdGVyIjoiREVOLU5ZQyIsImdyb3VwQnkiOnRydWV9fSwibkdiRmlsdGVycyI6eyJkaXJlY3Rpb24iOnsidHlwZSI6ImF1dG8iLCJ0YWdrIjoiZGlyZWN0aW9uIiwiZmlsdGVyIjoiIiwiZ3JvdXBCeSI6ZmFsc2V9LCJob3N0Ijp7InR5cGUiOiJhdXRvIiwidGFnayI6Imhvc3QiLCJmaWx0ZXIiOiIiLCJncm91cEJ5IjpmYWxzZX0sImlmYWNlIjp7InR5cGUiOiJhdXRvIiwidGFnayI6ImlmYWNlIiwiZmlsdGVyIjoiIiwiZ3JvdXBCeSI6ZmFsc2V9LCJpbmFtZSI6eyJ0eXBlIjoiYXV0byIsInRhZ2siOiJpbmFtZSIsImZpbHRlciI6IiIsImdyb3VwQnkiOmZhbHNlfX0sImZpbHRlcnMiOlt7InR5cGUiOiJhdXRvIiwidGFnayI6ImRpcmVjdGlvbiIsImZpbHRlciI6IioiLCJncm91cEJ5Ijp0cnVlfSx7InR5cGUiOiJhdXRvIiwidGFnayI6Imhvc3QiLCJmaWx0ZXIiOiJkZW4tZmdhdGUwMSIsImdyb3VwQnkiOnRydWV9LHsidHlwZSI6ImF1dG8iLCJ0YWdrIjoiaW5hbWUiLCJmaWx0ZXIiOiJERU4tTllDIiwiZ3JvdXBCeSI6dHJ1ZX1dfV0sImVuZCI6IjIwMTYvMTIvMjEtMTg6NDM6MzAifQ%3D%3D)

**Comment by kylebrandt** [comment]
I am guessing this happens when the metric name is the same for two graph tabs.

**Comment by kylebrandt** [comment]
Via inspector we are getting back the following from the shortner API:

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Value",
    "locationType": "parameter",
    "location": "resource.longUrl"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
 }
}
```
