### ISSUE TITLE
Bosun crashing with error: interface conversion: expr.Value is expr.Number, not expr.Series 

### ISSUE THREAD

**Issue by pradeepbbl** [bosun-monitor/bosun#2006]
Hi,

We are running bosun 0.6.0-pre for more than a month. Today we found bosun crashing with below error no major change to the alerts and template

2017/01/12 12:27:47 info: expr.go:133: interface conversion: expr.Value is expr.Number, not expr.Series: goroutine 30078 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/lib64/go/src/runtime/debug/stack.go:24 +0x80
bosun.org/cmd/bosun/expr.errRecover(0xc847bebe00)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:133 +0xbd
panic(0x121eb20, 0xc84372de00)
	/usr/lib64/go/src/runtime/panic.go:426 +0x4e9
bosun.org/cmd/bosun/expr.reduce.func1(0xc84492f380, 0xc84492f140, 0xc861897348, 0x1, 0x1, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:777 +0x24a
bosun.org/cmd/bosun/expr.match(0xc847beb2b0, 0xc84492ecf0, 0xc847beb328, 0x1, 0x1, 0x123f260, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:768 +0x45f
bosun.org/cmd/bosun/expr.reduce(0xc83de648f0, 0x7febc4215c38, 0xc832c71b00, 0xc84492ecf0, 0x16a1cb8, 0xc847beb328, 0x1, 0x1, 0xc832c71b00, 0x0, ...)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:785 +0x87
bosun.org/cmd/bosun/expr.Max(0xc83de648f0, 0x7febc4215c38, 0xc832c71b00, 0xc84492ecf0, 0x0, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:1085 +0x262
reflect.Value.call(0x11c4e60, 0x16a1b88, 0x13, 0x1436470, 0x4, 0xc8240b1620, 0x3, 0x4, 0x0, 0x0, ...)
	/usr/lib64/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x11c4e60, 0x16a1b88, 0x13, 0xc8240b1620, 0x3, 0x4, 0x0, 0x0, 0x0)
	/usr/lib64/go/src/reflect/value.go:303 +0xb1
bosun.org/cmd/bosun/expr.(*State).walkFunc.func1(0x7febc4215c38, 0xc832c71b00)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:742 +0x8ad
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc832c71b00, 0xc83a737050, 0x9, 0xc845d2d4a0)
	/opt/golang/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:195 +0x8c
bosun.org/cmd/bosun/expr.(*State).walkFunc(0xc83de648f0, 0xc821612090, 0x7febc4215c38, 0xc832c71b00, 0xc858fbc900)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:755 +0x125
bosun.org/cmd/bosun/expr.(*State).walk(0xc83de648f0, 0x7febca0af6b8, 0xc821612090, 0x7febc4215c38, 0xc832c71b00, 0xc8253de42f)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:477 +0x12b
bosun.org/cmd/bosun/expr.(*State).walkBinary(0xc83de648f0, 0xc8215ebf80, 0x7febc4215c38, 0xc832c71b00, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:497 +0x6e
bosun.org/cmd/bosun/expr.(*State).walk(0xc83de648f0, 0x7febca0af778, 0xc8215ebf80, 0x7febc4215c38, 0xc832c71b00, 0xc84749dd78)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:473 +0x208
bosun.org/cmd/bosun/expr.(*Expr).ExecuteState.func1(0x7febc4215c38, 0xc832c71b00)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:120 +0x65
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc832c71b00, 0x145c6b0, 0xc, 0xc845d2d480)
	/opt/golang/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:195 +0x8c
bosun.org/cmd/bosun/expr.(*Expr).ExecuteState(0xc820cce4f8, 0xc83de648f0, 0x7febc4215c38, 0xc832c71b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:121 +0x19c
bosun.org/cmd/bosun/expr.(*Expr).Execute(0xc820cce4f8, 0xc84286e5a0, 0xc836178ff0, 0x0, 0x0, 0xed0095ef1, 0x36f5e80c, 0x1d721e0, 0x0, 0x6741774343514700, ...)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:109 +0x160
bosun.org/cmd/bosun/sched.(*Schedule).executeExpr(0x1d7c7c0, 0x0, 0x0, 0xc82a663a80, 0xc8216689c0, 0xc820cce4f8, 0x0, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/sched/check.go:626 +0x24d
bosun.org/cmd/bosun/sched.(*Schedule).CheckExpr.func2(0x1d7c7c0, 0x0, 0x0, 0xc82a663a80, 0xc8216689c0, 0xc820cce4f8, 0xc8479bcfc0)
	/opt/golang/src/bosun.org/cmd/bosun/sched/check.go:649 +0x66
created by bosun.org/cmd/bosun/sched.(*Schedule).CheckExpr
	/opt/golang/src/bosun.org/cmd/bosun/sched/check.go:651 +0x170
panic: interface conversion: expr.Value is expr.Number, not expr.Series [recovered]
	panic: interface conversion: expr.Value is expr.Number, not expr.Series

goroutine 30078 [running]:
panic(0x121eb20, 0xc84372de00)
	/usr/lib64/go/src/runtime/panic.go:464 +0x3e6
bosun.org/cmd/bosun/expr.errRecover(0xc847bebe00)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:134 +0x203
panic(0x121eb20, 0xc84372de00)
	/usr/lib64/go/src/runtime/panic.go:426 +0x4e9
bosun.org/cmd/bosun/expr.reduce.func1(0xc84492f380, 0xc84492f140, 0xc861897348, 0x1, 0x1, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:777 +0x24a
bosun.org/cmd/bosun/expr.match(0xc847beb2b0, 0xc84492ecf0, 0xc847beb328, 0x1, 0x1, 0x123f260, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:768 +0x45f
bosun.org/cmd/bosun/expr.reduce(0xc83de648f0, 0x7febc4215c38, 0xc832c71b00, 0xc84492ecf0, 0x16a1cb8, 0xc847beb328, 0x1, 0x1, 0xc832c71b00, 0x0, ...)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:785 +0x87
bosun.org/cmd/bosun/expr.Max(0xc83de648f0, 0x7febc4215c38, 0xc832c71b00, 0xc84492ecf0, 0x0, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/funcs.go:1085 +0x262
reflect.Value.call(0x11c4e60, 0x16a1b88, 0x13, 0x1436470, 0x4, 0xc8240b1620, 0x3, 0x4, 0x0, 0x0, ...)
	/usr/lib64/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x11c4e60, 0x16a1b88, 0x13, 0xc8240b1620, 0x3, 0x4, 0x0, 0x0, 0x0)
	/usr/lib64/go/src/reflect/value.go:303 +0xb1
bosun.org/cmd/bosun/expr.(*State).walkFunc.func1(0x7febc4215c38, 0xc832c71b00)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:742 +0x8ad
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc832c71b00, 0xc83a737050, 0x9, 0xc845d2d4a0)
	/opt/golang/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:195 +0x8c
bosun.org/cmd/bosun/expr.(*State).walkFunc(0xc83de648f0, 0xc821612090, 0x7febc4215c38, 0xc832c71b00, 0xc858fbc900)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:755 +0x125
bosun.org/cmd/bosun/expr.(*State).walk(0xc83de648f0, 0x7febca0af6b8, 0xc821612090, 0x7febc4215c38, 0xc832c71b00, 0xc8253de42f)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:477 +0x12b
bosun.org/cmd/bosun/expr.(*State).walkBinary(0xc83de648f0, 0xc8215ebf80, 0x7febc4215c38, 0xc832c71b00, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:497 +0x6e
bosun.org/cmd/bosun/expr.(*State).walk(0xc83de648f0, 0x7febca0af778, 0xc8215ebf80, 0x7febc4215c38, 0xc832c71b00, 0xc84749dd78)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:473 +0x208
bosun.org/cmd/bosun/expr.(*Expr).ExecuteState.func1(0x7febc4215c38, 0xc832c71b00)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:120 +0x65
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc832c71b00, 0x145c6b0, 0xc, 0xc845d2d480)
	/opt/golang/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:195 +0x8c
bosun.org/cmd/bosun/expr.(*Expr).ExecuteState(0xc820cce4f8, 0xc83de648f0, 0x7febc4215c38, 0xc832c71b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:121 +0x19c
bosun.org/cmd/bosun/expr.(*Expr).Execute(0xc820cce4f8, 0xc84286e5a0, 0xc836178ff0, 0x0, 0x0, 0xed0095ef1, 0x36f5e80c, 0x1d721e0, 0x0, 0x6741774343514700, ...)
	/opt/golang/src/bosun.org/cmd/bosun/expr/expr.go:109 +0x160
bosun.org/cmd/bosun/sched.(*Schedule).executeExpr(0x1d7c7c0, 0x0, 0x0, 0xc82a663a80, 0xc8216689c0, 0xc820cce4f8, 0x0, 0x0, 0x0)
	/opt/golang/src/bosun.org/cmd/bosun/sched/check.go:626 +0x24d
bosun.org/cmd/bosun/sched.(*Schedule).CheckExpr.func2(0x1d7c7c0, 0x0, 0x0, 0xc82a663a80, 0xc8216689c0, 0xc820cce4f8, 0xc8479bcfc0)
	/opt/golang/src/bosun.org/cmd/bosun/sched/check.go:649 +0x66
created by bosun.org/cmd/bosun/sched.(*Schedule).CheckExpr
	/opt/golang/src/bosun.org/cmd/bosun/sched/check.go:651 +0x170

 Thanks,
Pradeep

**Comment by dgryski** [comment]
If there are no changes to the templates, is there maybe a difference in the data that's coming back from graphite?
