### ISSUE TITLE
Cursor moved to the end on every keystroke when editing host filters

### ISSUE THREAD

**Issue by clinta** [bosun-monitor/bosun#2012]
On the graph page when editing the host query the cursor is moved to the end of the field after every keystroke, making it incredibly frustrating to edit regex in that field.

**Comment by kylebrandt** [comment]
older version? should have been fixed in https://github.com/bosun-monitor/bosun/issues/1665

**Comment by clinta** [comment]
Yup, sorry. Should have tested on master first. I'm running 0.5.0.
