### ISSUE TITLE
enabling authentication causes some api commands to fail with 'unexpected EOF in input: F()'

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#2015]
When the new authentication feature is disabled the following command will return data:

    curl 'http://bosun/api/expr' --data 'q("sum:rate{counter,,1}:os.cpu{host=*}", "1h", "")'

Once you enable authentication it will start returning the following error:

    curl 'http://bosun/api/expr' --data 'q("sum:rate{counter,,1}:os.cpu{host=*}", "1h", "")' -H 'X-Access-Token: asdfasdfasdfa'

> expr: unexpected EOF in input: F()

However if you add a  Content-Type header it will start working. It doesn't actually care what the value is, but adding  `-H 'Content-Type: whatever'` will make the error go away

**Comment by captncraig** [comment]
Fixed in 7ac6783fb03fe764921bee22a993017cd0d351b4

**Comment by captncraig** [comment]
Semantically, we should be providing a Content-Type whenever we send a body. But it is certainly not the job of the auth library to enforce that. It now properly reads the query string only, and avoids methods that have any potential to read the body at all.
