### ISSUE TITLE
tsdbrelay: Rapid socket use results in trouble

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#2018]
tsdbrelay creates a new socket connection whenever it is chatting with bosun, and closes it immediately. This results in a large number of sockets stuck in TIME_WAIT. On our production systems, this often causes issues where the ports which hbase or opentsdb typically use are very frequently being consumed by ephemeral ports from sockets in TIME_WAITs, which causes issues on server startup.

Would be nice if tsdbrelay would set `SO_REUSEADDR` on socket creation so that it reuses some of those TIME_WAITs rather than eating up a new ephemeral port.

**Comment by alienth** [comment]
Main issue here is probably not socket creation, but lack of http connection reuse. This will be partially addressed in #2034.

**Comment by kylebrandt** [comment]
Assuming fixed enough by the issues unless we run into future problems.
