### ISSUE TITLE
False Unknowns

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#2019]
Here is the incident json of one

```
{
  "Id": 220966,
  "Start": "2017-02-14T21:40:23.042928549Z",
  "End": "2017-02-14T21:49:32.837879926Z",
  "AlertKey": "sites.readonly.mode{}",
  "Alert": "sites.readonly.mode",
  "Tags": "",
  "Value": 0,
  "Expr": "",
  "Events": [
    {
      "Crit": {
        "Value": 0,
        "Expr": "min(t(min(q(\"sum:web.readonly.redis{host=*,role=*}{host=iwildcard(ny-*)}\", \"2m\", \"\")), \"\")) > 0"
      },
      "Status": "unknown",
      "Time": "2017-02-14T21:40:23.010320884Z",
      "Unevaluated": false
    },
    {
      "Crit": {
        "Value": 0,
        "Expr": "min(t(min(q(\"sum:web.readonly.redis{host=*,role=*}{host=iwildcard(ny-*)}\", \"2m\", \"\")), \"\")) > 0"
      },
      "Status": "normal",
      "Time": "2017-02-14T21:40:23.010320884Z",
      "Unevaluated": false
    }
  ],
  "Actions": [
    {
      "User": "kbrandt",
      "Message": "false, from restart of bosun with migration",
      "Time": "2017-02-14T21:49:32.837879926Z",
      "Type": "Closed"
    }
  ],
  "Subject": "",
  "NeedAck": true,
  "Open": false,
  "Unevaluated": false,
  "CurrentStatus": "normal",
  "WorstStatus": "unknown",
  "LastAbnormalStatus": "unknown",
  "LastAbnormalTime": 1487108423
}
```

This one happened after the migration with a few others. Have also seen this when restarting our physical bosun host.

Somehow we are getting two events with the exact same time stamp. Trying to hunt this down.

**Comment by kylebrandt** [comment]
```
eb 14 21:38:08 ny-bosun01 bosun: Starting bosun: [  OK  ]
2017/02/14 21:38:08 enabling syslog
2017/02/14 21:38:08 info: migrate.go:79: checking migrations
2017/02/14 21:38:08 info: migrate.go:91: schema version not found in db
2017/02/14 21:38:08 info: migrate.go:36: Running rendered template migration. This can take several minutes.
2017/02/14 21:38:08 info: migrate.go:40: migrating 65440 incidents
2017/02/14 21:40:19 info: search.go:194: Loading last datapoints from redis
2017/02/14 21:40:23 info: search.go:201: Done
2017/02/14 21:40:23 info: check.go:529: check alert tsdb.slow.requests start
2017/02/14 21:40:23 info: check.go:529: check alert linux.tcp start
....
2017/02/14 21:40:23 info: web.go:224: tsdb host: localhost:80
2017/02/14 21:40:23 info: web.go:234: bosun web listening https on: :8081
2017/02/14 21:40:23 info: web.go:228: bosun web listening http on: :8080
...
2017/02/14 21:40:23 info: check.go:529: check alert sites.readonly.mode start
2017/02/14 21:40:23 info: check.go:577: check alert sites.readonly.mode done (28.134286ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2017/02/14 21:40:23 info: alertRunner.go:74: runHistory on sites.readonly.mode took 5.381976ms
2017/02/14 21:41:23 info: check.go:529: check alert sites.readonly.mode start
2017/02/14 21:41:23 info: check.go:577: check alert sites.readonly.mode done (3.380277ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2017/02/14 21:41:23 info: alertRunner.go:74: runHistory on sites.readonly.mode took 16.954446ms
2017/02/14 21:42:23 info: check.go:529: check alert sites.readonly.mode start
2017/02/14 21:42:23 info: check.go:577: check alert sites.readonly.mode done (11.496274ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2017/02/14 21:42:23 info: alertRunner.go:74: runHistory on sites.readonly.mode took 17.447495ms
2017/02/14 21:42:23 info: notify.go:80: post notification successful for alert sites.readonly.mode{}. Response code 200.
2017/02/14 21:42:23 info: notify.go:115: relayed alert sites.readonly.mode{} to [XXX] sucessfully. Subject: 39 bytes. Body: 151 bytes.
```

**Comment by kylebrandt** [comment]
Random ideas:
 * A run history events is  make(map[models.AlertKey]*models.Event). So in theory we should not be able to get two events. I only see one append call in runHistory which processes this. Make somehow we are concurrently accessing this map which causes us to iterate over the same alert key twice?
 * Don't know how to repo this, so this is going to be a tough one to find :-/ 
 * Working on branch grokSomeSched to add some comments to better understand this code

**Comment by kylebrandt** [comment]
Or maybe something gets left in redis, not cleaned up on restart, and picked up on next run? Basically some sort of alternate memory path?

**Comment by kylebrandt** [comment]
Maybe Races:

```
==================
WARNING: DATA RACE
Read at 0x000001a4d288 by goroutine 97:
  bosun.org/cmd/bosun/sched.(*Schedule).checkAlert()
      /Users/kbrandt/src/bosun.org/cmd/bosun/sched/alertRunner.go:68 +0x5f
  bosun.org/cmd/bosun/sched.(*Schedule).RunAlert()
      /Users/kbrandt/src/bosun.org/cmd/bosun/sched/alertRunner.go:55 +0x17e

Previous write at 0x000001a4d288 by goroutine 94:
  bosun.org/cmd/bosun/sched.(*Schedule).updateCheckContext()
      /Users/kbrandt/src/bosun.org/cmd/bosun/sched/alertRunner.go:32 +0x32d

Goroutine 97 (running) created at:
  bosun.org/cmd/bosun/sched.(*Schedule).Run()
      /Users/kbrandt/src/bosun.org/cmd/bosun/sched/alertRunner.go:21 +0x208
  bosun.org/cmd/bosun/sched.Run()
      /Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:493 +0x4a
  main.main.func5()
      /Users/kbrandt/src/bosun.org/cmd/bosun/main.go:230 +0x6c

Goroutine 94 (running) created at:
  bosun.org/cmd/bosun/sched.(*Schedule).Run()
      /Users/kbrandt/src/bosun.org/cmd/bosun/sched/alertRunner.go:19 +0x134
  bosun.org/cmd/bosun/sched.Run()
      /Users/kbrandt/src/bosun.org/cmd/bosun/sched/sched.go:493 +0x4a
  main.main.func5()
      /Users/kbrandt/src/bosun.org/cmd/bosun/main.go:230 +0x6c
==================
```

**Comment by captncraig** [comment]
Requirements for unknown event to occur:

1. An alert key has not been "touched" for two "check durations" from the checkTime.
2. Evaluation of the expression at checkTime yields no results for the alert key.

I would believe #1 could have bugs in how it is evaluated. Is #2 actually occurring for the alert keys this is happening to?

If there are results in tsdb at the check time, we likely have a bug in the checking code.

**Comment by kylebrandt** [comment]
Also, in the logs why does post happen so much later than the event timestamp?

**Comment by kylebrandt** [comment]
Current Hypothesis. Two checks run with the same timestamp due to the race condition between checkAlert fetching the schedule's check time and the frequency of the alert running.

In short, the alerts run roughly a minute apart, but two of the checks that ran a minute apart were passed the same check time. This is why we see two events.

I'm going to add logging of the checktime that is passed so we can see if this is the case next time it happens, and craig is going to think about how we might prevent that from happening.

**Comment by kylebrandt** [comment]
Also worth noting, that hypothesis still doesn't fully explain this to us.

**Comment by captncraig** [comment]
My hypothesis is that the data has occasional gaps where there are no datapoints in the last two minutes. These gaps never last two minutes themselves though (no datapoints in 4 minutes). So they only go unknown when a bosun restart coincides with such a gap.

**Comment by kylebrandt** [comment]
Cancelled checks on a shutdown also would not get "Touched" I don't think, since it is the run history that does that, and we return before runHistory if the check was cancelled due to a shutdown.

**Comment by kylebrandt** [comment]
Logging confirms that checks at one minute intervals are sometimes getting run with the same value now:

```
2017/02/17 17:43:44 info: check.go:529: check alert sites.readonly.mode start with now set to 2017-02-17 17:43:44.690531283
2017/02/17 17:44:44 info: check.go:529: check alert sites.readonly.mode start with now set to 2017-02-17 17:43:44.690531283
2017/02/17 17:45:44 info: check.go:529: check alert sites.readonly.mode start with now set to 2017-02-17 17:44:44.789880559
```

**Comment by kylebrandt** [comment]
Made the issue above (https://github.com/bosun-monitor/bosun/issues/2023) since it may not fix these unknowns and could just be a bug exacerbating the issue.

**Comment by kylebrandt** [comment]
Secondary TSDB feature (https://github.com/bosun-monitor/bosun/issues/2024) might help with unknowns as well.

**Comment by kylebrandt** [comment]
Also, as a workaround to control the noise that has been isolated to the more frequent alerts (but seen this on less frequent as well) would be to set a greater unknown time than the default on these alerts http://bosun.org/configuration#alert
