### ISSUE TITLE
Slack invite page broken

### ISSUE THREAD

**Issue by RubyTuesdayDONO** [bosun-monitor/bosun#2022]
The Slack Invite page an Bosun.org: https://bosun.org/slackInvite
… fails to process my invitation request, apparently due to a CORS issue:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.runhook.com/eaakslsvhhtcu3bvkcijmcvpju?email=redacted@example.com. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

Not sure if this is just something in my browser, but I tried three (Firefox, Chrome, Safari) to the same negative effect. 

Also not sure if this is the right place to report this, but couldn't find a more appropriate channel :)

**Comment by captncraig** [comment]
Oh yeah, the service I made to handle those shut down. I rewrote it to a [gomix](https://gomix.com) script, but didn't push that to the main site yet. Hold on a sec.

**Comment by captncraig** [comment]
Updated the inviter to run from gomix: https://gomix.com/#!/project/puny-hygienic

Should work now.

**Comment by gbrayut** [comment]
details on gomix project at https://support.gomix.com/t/auto-invite-system-for-public-slack-teams/1018
