### ISSUE TITLE
Allow for inlining graphs in email notifications

### ISSUE THREAD

**Issue by theblazehen** [bosun-monitor/bosun#2031]
Requires changing the Content-Disposition of the attachment from `attachment` to `inline`

**Comment by kylebrandt** [comment]
@theblazehen What would be the benefit of doing this?

**Comment by theblazehen** [comment]
@kylebrandt It would allow having images display inline in mail clients, as opposed to having it as a separate attachment which you would need to open. Some mail clients do still show it inline even with it set as attachment, but many do not.

**Comment by captncraig** [comment]
@theblazehen do you know if email clients would handle inline data-uri img tags? That may be easier than attachments anyway. By that I mean just doing `<img src="src="data:image/png;base64,ASADASDASD...">`
