### ISSUE TITLE
Duplicate Notifications After Reload

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#2056]
Need to investigate. Think it only happens after reload.

Perhaps in the rulevars changed notifications are getting loaded twice the way I pass it - going to check that first.

**Comment by kylebrandt** [comment]
Double logged as well.

```
Apr 06 09:02:09 ny-bosun01.ds.stackexchange.com bosun[9543]: 2017/04/06 09:02:09 info: notify.go:84: post notification successful for alert exceptions{}. Response code 200.
Apr 06 09:02:09 ny-bosun01.ds.stackexchange.com bosun[9543]: 2017/04/06 09:02:09 info: notify.go:84: post notification successful for alert exceptions{}. Response code 200.
```

**Comment by kylebrandt** [comment]
When I `println` in `NewConf` and then reload the notifications gets appended to each time (still need to figure out why):

```
$ go run main.go -c bosun.toml -w -skiplast -q -n -dev
2017/04/06 08:40:59 map[sre-chat:0xc4203e6000]
2017/04/06 08:40:59 info: migrate.go:79: checking migrations
2017/04/06 08:40:59 info: web.go:82: using local web assets
2017/04/06 08:40:59 info: web.go:210: tsdb host: localhost:4242
2017/04/06 08:40:59 info: web.go:214: bosun web listening http on: :8080
2017/04/06 08:40:59 info: main.go:329: watching *.go in .
2017/04/06 08:40:59 info: main.go:329: watching *.html in web/static/templates
2017/04/06 08:40:59 info: main.go:329: watching *.ts in web/static/js
2017/04/06 08:41:24 map[sre-chat:0xc420ce32c0]
2017/04/06 08:41:24 map[sre-chat:0xc420ce3680]
2017/04/06 08:41:24 info: main.go:234: schedule shutdown, loading new schedule
2017/04/06 08:41:24 info: main.go:247: config reload complete
2017/04/06 08:41:24 info: main.go:242: running new schedule
2017/04/06 08:41:40 map[sre-chat:0xc4203e63c0]
2017/04/06 08:41:52 map[sre-chat:0xc4201462d0]
2017/04/06 08:41:52 map[sre-chat:0xc4201463c0]
2017/04/06 08:41:52 info: main.go:234: schedule shutdown, loading new schedule
2017/04/06 08:41:52 info: main.go:247: config reload complete
2017/04/06 08:41:52 info: main.go:242: running new schedule
```

**Comment by kylebrandt** [comment]
Actually the above observation may be incorrect. There is an extra call from validate so that accounts for one of them. I can't reliably get it to keep continuing. Not seeing anything running with the race detector.

**Comment by kylebrandt** [comment]
In the prod logs where the dup notifications are, there are *not* duplicate checkalert or runHistory

**Comment by kylebrandt** [comment]
Actually with that prod alert there are 2 post notifications, so there should be two entries. I checked a double post with an alert that only has a single post notification, and there is only one entry in the log.

**Comment by kylebrandt** [comment]
sigh, we have another instance running. Not a valid bug.

**Comment by egor4eg** [comment]
@kylebrandt . It's reproducing for me. If I call reload api and there are not acknowledged chained notifications, they will be duplicated. If I do reload several times, they duplicate several times.

This doesn't reproduce if I simply restart the process instead of reload api call. 

I tested that on the 0.6.0-pre version downloaded inside this container - https://hub.docker.com/r/stackexchange/bosun/. After that I compiled the latest version and replaced the binary inside the same container - still reproduced

**Comment by ms300** [comment]
> @kylebrandt . It's reproducing for me. If I call reload api and there are chained notifications which are not acknowledged yet, they will be duplicated. If I call reload api several times, they duplicate several times.
> 
> This doesn't reproduce if I simply restart the process instead of reload api call.
> 
> I tested that on the 0.6.0-pre version downloaded inside this container - https://hub.docker.com/r/stackexchange/bosun/. After that I compiled the latest version and replaced the binary inside the same container - still reproduced

https://github.com/bosun-monitor/bosun/pull/2445 has fixed this issue.
