### ISSUE TITLE
Unable to get non-numeric field by "esstat"

### ISSUE THREAD

**Issue by avijitcgit** [bosun-monitor/bosun#2078]
I see in docs that "esstat" only accepts field that must be numeric, but I need to read a field that is not numeric and have comma separated values (strings).

$q = esstat(esls("metrics-xxx"), "host,role", esquery("metric", "mem"), "used_percent", "avg", "1m", "7m", "")

Above query working fine since "used_percent" is numeric field. How can I do the same for non-numeric field.

**Comment by kylebrandt** [comment]
You case don't this in the expression language. Esstat generates server side aggregations (meaning it is done on Elastic), and Elastic only supports these operations on numeric fields.

If this is for displaying in the notifications, you can look at ESQuery and ESQueryAll template funcs at http://bosun.org/definitions#esqueryindexroot-expresindexer-filter-expresquery-sduration-eduration-string-size-int-interface
