### ISSUE TITLE
Bosun sending multiple alerts for comma separated keyString

### ISSUE THREAD

**Issue by avijitchat1** [bosun-monitor/bosun#2079]
In below query, if any of the keyString has comma separated multiple values, then bosun sending these many alert for each value, 

Example:
In this case, `role="csp,up,mmp,admin"`

bosun alert definition is, 

`alert high.mem.usage {
        template = highusage
         $warn_threshold = 75
       $crit_threshold = 90
        $q = esstat(esls("metrics-xxxx"), "host,role", esquery("metric", "mem"), "used_percent", "avg", "1m", "7m", "")
     warn = $val >= $warn_threshold
     warnNotification = slackChannel
    crit = $val >= $crit_threshold
     critNotification = slackChannel`

When condition meets, bosun is sending 4 alerts for all `role` values. 
How can we send single alert since those are for same host and single issue.

**Comment by kylebrandt** [comment]
Since the second argument is "host,role" the tags keys will be host and role (with possible alerts for each host,role value combination that exists. So in this case you would leave out role from that argument. 

Elastic in Bosun is really meant more for log data than it is metrics. You might be able to make it work but since there is no predefined schema for storing time series data in elastic it depends on what you have.

**Comment by AvijitCGit** [comment]
Thanks for your reply..
In this case, is there any other way I can read the "role" field, then I can remove "role" from tag keys happily. My primary ambition is to read "role" field values and send it as part of notification to make more meaningful. 

I read the doc and understand that "esstat" only works on filed that has numeric value, so it doesn't make sense to write another "esstat" statement to read "role" field.

Any suggestion ?

**Comment by kylebrandt** [comment]
Might be able to get what you want with t()
http://stackoverflow.com/documentation/bosun/7213/alerts-advanced-scoping#t=201705120127356089298

**Comment by kylebrandt** [comment]
Also you can run expressions from the template that were not necessarily
used in warn/crit. So you alert on host. But in the template use eval or
evalall to execute the query that includes host and role.

**Comment by AvijitCGit** [comment]
Excellent, that worked, but little modification required, 
As you stated, now I am getting limited alert as per host after transpose by host, but I lost role values in key tags. I only have host in key tags now and I cannot display role in alert subject any more. 

alert high.usage {
  template = highusage
  $warn_threshold = 75
  $crit_threshold = 90
    $q = esstat(esls("xxxx"), "host,role", esand(esquery("metric", "disk"),esquery("path", "/.**/")), "used_percent", "avg", "1m", "15m", "")
  $val1 = avg($q)
  $val = avg(t($val1, "host"))
  warn = $val >= $warn_threshold
  crit = $val >= $crit_threshold
  warnNotification = slackChannel
  critNotification = slackChannel
}

Is there any way I can store {{.Group.tags}} in a variable before transpose it.

**Comment by AvijitCGit** [comment]
My template is like that:

template highusage {
  subject = {{.Last.Status}}: {{.Alert.Name}} in LOCALOI, Value: {{printf "%.2f" (.Eval .Alert.Vars.val)}} [Warn:{{.Alert.Vars.warn_threshold}};Crit:{{.Alert.Vars.crit_threshold}}], tags: [{{.Group}}]

**Comment by AvijitCGit** [comment]
I tried put "alert" in this way where "$q1" is not used for alert.

alert high.usage {
template = highusage
$warn_threshold = 75
$crit_threshold = 90
$q1 = escount(esls("xxxx"), "host,role", esquery("metric", "disk"), "1m", "7m", "")
$q = esstat(esls("xxxx"), "host,role", esand(esquery("metric", "disk"),esquery("path", "/.**/")), "used_percent", "avg", "1m", "15m", "")
$val1 = avg($q)
$val = avg(t($val1, "host"))
warn = $val >= $warn_threshold
crit = $val >= $crit_threshold
warnNotification = slackChannel
critNotification = slackChannel
}

template highusage {
subject = {{.Last.Status}}: {{.Alert.Name}}, Value: {{printf "%.2f" (.Eval .Alert.Vars.val)}} [Warn:{{.Alert.Vars.warn_threshold}};Crit:{{.Alert.Vars.crit_threshold}}], tags: [{{.Group}}]

Could you please help me how can I use eval/evalall in template to display host and role ?
