### ISSUE TITLE
RuleEditor link in Incident page breaks the testing function

### ISSUE THREAD

**Issue by ayashjorden** [bosun-monitor/bosun#2088]
Hi,
In the incident page, when I click on `Rule Editor` link, it result in: `http://BOSUN_HOST:8070/config?alert=ALERT_NAME&fromDate=49364-06-15&fromTime=19:30`

As can be seen the _year_ part of the `fromDate` parameter is wrongly generated.

Bosun version: `bosun version 0.6.0-pre-dev last modified 2016-12-06T18:52:15Z`

Reproduce:
1. open the incident page: bosun.host.com/incident?id=INCIDENT_ID
2. Hover/Click the `Rule Editor` to see that the `fromDate` parameter is wrongly calculated.

Please advise,
Yarden

**Comment by kylebrandt** [comment]
Comment via slack: "looks like incorrect convertion from `millisconds since
epoch` to a human readable date format"

**Comment by ayashjorden** [comment]
Read that, but what is the source timestamp that gets converted?
This is a bug in the link generation....
