### ISSUE TITLE
Bosun Graphs throw Unable to Parse JSON error when host is specified

### ISSUE THREAD

**Issue by cedw93** [bosun-monitor/bosun#2099]
**Edit**: This seems to only be happening when a `host` is specified for the query.

Ive recently updated to 0.6 beta, and originally everything worked OK, graphs and metrics worked as expected.

However, I was updating some of the rules in the rule editor (using the save from the UI feature) and now every single metric (clicking on the metric name from the list of metrics in the items tab) shows the following when trying to view the graph:

```
opentsdb: {"start":"1h-ago","queries":[{"aggregator":"sum","metric":"bosun.check.duration","rateOptions":{},"filters":[{"type":"literal_or","tagk":"host","filter":"ip-10-10-1-74","groupBy":true}]}]}: Unable to parse the given JSON
```

Screenshot

![screen shot 2017-06-05 at 14 12 19](https://cloud.githubusercontent.com/assets/5663935/26785215/2fe6b81e-49f9-11e7-8bdb-c4edb4ea4122.png)

I thought it might be an issue with the rules I was defining so I cleared my rules and saved an empty set of rules and restated Bosun.

However this issue still persists. I've not made any changed to OpenTSDB or how the metrics are sent, this worked fine literally hours ago, and I'm not entirely sure how to debug the issue.

My config is pretty much the default one with a few minor tweaks. The graphs have been working with this config, they have just recently broken.

**Edit**: The graphs do load if I navigate to 'Graph' tab and type a metric and hit enter. However, using the same method if I specify any kind of host I get the same error as above.

**Edit 2**: The metrics exist and are viewable from the opentsb UI.

**Edit 3**: Is no host is specified or a metric the graphs seem to load. However specifying a host causes the above error.

**Comment by kylebrandt** [comment]
@cedw93  What version of OpenTSDB are you using? I'm wonder if maybe you are configured to use OpenTSDB 2.2 but are using opentsdb 2.1?

That error is coming from OpenTSDB. I don't get a parse error on something like that, just that the tag doesn't exist:

```
opentsdb: {"start":"1h-ago","queries":[{"aggregator":"sum","metric":"bosun.check.duration","rateOptions":{},"filters":[{"type":"literal_or","tagk":"host","filter":"ip-10-10-1-74","groupBy":true}]}]}: No such name for 'tagv': 'ip-10-10-1-74'
```
