### ISSUE TITLE
how to “moving average trend forecasting" alert with bosun expression

### ISSUE THREAD

**Issue by ourdark** [bosun-monitor/bosun#2100]
I'd like to define a trending alert with “moving average trend forecasting" algorithm:
_a_t=2m_t^{(1)}-m_2^{(2)}
b_t=\frac{2}{n-1}(m_2^{(1)}-m_t^{(2)})_

I can get data from query  function(band/window), so what's the next?
@jsoriano @Dieterbe @mjibson @vitorboschi @biswanaths

**Comment by kylebrandt** [comment]
Bosun doesn't having a moving average function so this would need to be a PR with a new function in the expression language.
