### ISSUE TITLE
how to filer out the response message of bosun /api/alter

### ISSUE THREAD

**Issue by tymfr** [bosun-monitor/bosun#2101]
Dear all:
       I encounter some problems when I use bosun api of alter to filter out the alters I wanted.
       In the bosun api documents, I can only see this description lines below:
       /api/alerts?[filter=filter]
       Returns a list of alert summaries matching the given filter (defaults to all).
        But I do not know how the filter expression should be composed.
        I tried this express  /api/alters?filter=Active:true but I can only see nothing.
        So dear friend, can you please give me an examples on how can I filter out the alters.
        Thank you all.

**Comment by kylebrandt** [comment]
It uses the incident filters as documented in http://bosun.org/usage#incident-filters , this should be referenced from the API documentation so I added "Needs Documentation" Label.

Example

```$ curl 'https://bosun.ds.stackexchange.com/api/alerts?filter=!notify:*patcher*%20AND%20!notify:*it*'```
