### ISSUE TITLE
How to enable bosun log?

### ISSUE THREAD

**Issue by ourdark** [bosun-monitor/bosun#2103]
nohup ./bosun-linux-amd64 -c bosun.toml &` 
only show info log, how can I enable debug log including restapi logs? 
`

**Comment by kylebrandt** [comment]
Bosun doesn't have a debug log level. This probably isn't something we are going to make time for any time soon, workaround for now is to just build bosun yourself adding log lines where you think they are needed when troubleshooting an issue I'm afraid.
