### ISSUE TITLE
Send better response code for invalid routes

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#2105]
Right now if you send a request to an invalid route you get a 200 response code. Example:

```
$ curl -v https://bosun/metadataasdf/putasdf
* About to connect() to bosun port 443 (#0)
> GET /metadataasdf/putasdf HTTP/1.1
> User-Agent: curl/7.29.0
> Host: bosun
> Accept: */*
>
< HTTP/1.1 200 OK
< Vary: Accept-Encoding
< Date: Thu, 15 Jun 2017 17:03:14 GMT
< Content-Type: text/html; charset=utf-8
< Connection: close
< Transfer-Encoding: chunked
<
<!DOCTYPE html>
<html ng-app="bosunApp">
        <head>
                <title ng-bind="'Bosun &mdash; ' + title"></title>
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

This should generate a 404 or other error message. Responding with a 200 can hide issues like https://github.com/bosun-monitor/bosun/commit/a5be1340ee9cfbb0930a6abf834505f236a74dd9

**Comment by kylebrandt** [comment]
One tricky part is that we probably still want the topbar with a 404, so people can click correct links. I guess sufficient could just be a link on the 404 to the index home page.

**Comment by gbrayut** [comment]
The content of the page doesn't matter as much. It could still be the same content sent today, although an actual 404 error page would be better. But sending a 200 response code for an invalid route can cause a lot of problems especially when there are proxies/relays involved.
