### ISSUE TITLE
Alert lookup based on metric name

### ISSUE THREAD

**Issue by mxk1235** [bosun-monitor/bosun#2109]
Apologies if this has been asked and answered.  The lookups work great with tags.  however, in our setting we moved our environment string into the metric name.  now, i am trying to do a lookup based on the metric, which appears to break in a confusing way.  it is complaining that "metric" has become a tag.

> conf: Test Config:579:4: at <warn = avg($q) < loo...>: expr: parse: incompatible tags (tag and metric) in avg(q("min:dev.metric.minutes{tag=*}", "15m", "")) < lookup("metric", "warnMins")

```
lookup metric {
    entry metric=dev.* {
        main_contact = cloud-alerts-slack
        warnMins = 0
    }
    entry metric=prod.* {
        main_contact = cloud-alerts-slack
        warnMins = 15
    }
}
macro metric_based {
    warnNotification = lookup("metric", "main_contact")
    $filter = tag=*
    $time = 15m
    $q = q("min:$metric{$filter}", "$time", "")
}
alert test.dev {
    $metric = dev.metric.minutes
    macro = metric_based
    warn = avg($q) < lookup("metric", "warnMins")
}
alert test.prod {
    $metric = prod.metric.minutes
    macro = metric_based
    warn = avg($q) < lookup("metric", "warnMins")
}
```

It is worth noting that I can get a workaround of this issue by adding, but that seems... inelegant.

```
    $q1 = addtags($q, "metric=$metric")
```

thanks in advance for looking at this.

**Comment by kylebrandt** [comment]
I'm afraid that workaround is what you will have to use (very clever by the way). 

When Bosun gets a response from a time series provider the response object does not hold the metric name. So there is no way to add this functionality that I can see without a significant to change to Bosun which I don't see happening anytime soon. So going to close this.

**Comment by kylebrandt** [comment]
Oh, you could also try sending the environment as Bosun metadata and adding the tag that way once I get around to finishing up this PR https://github.com/bosun-monitor/bosun/pull/2094 . You will be exploring new territory there.

**Comment by TaylorMonacelli** [comment]
Thank you!
Spark by Readdle

**Comment by mxk1235** [comment]
thanks, the limitation makes sense now.

**Comment by mxk1235** [comment]
just so i understand, the $metric here is an arbitrary alert variable.  so when the time series provider comes back with a response object, and its set of tags, in theory it should be sufficient to be the subset of the tags and variables from the other side of the equation, rather than equal to the other set of tags.  i understand that's not the binaryoperator interface you have implemented, but i was wondering if i have the right understanding of your design.  can you comment a bit further?

**Comment by kylebrandt** [comment]
I'm not sure I fully understand what you are asking. Can you expand on what you are asking and maybe ask some more specific questions?

**Comment by mxk1235** [comment]
the error is thrown here https://github.com/bosun-monitor/bosun/blob/95be5d945aee72ae3558e57b00e1185e89570356/cmd/bosun/expr/parse/node.go#L387

the subset equality condition from the if condition is trivially violated if one side has null tags (like an expression or number node) while the other does not (a series).  however, that case is allowed.  but it is not allowed for BinaryNode to have both children Nodes with tags.  perhaps equality makes sense for something like a + operator on two series, but i'm having trouble seeing why the < operator needs it.  

does this example make sense?
