### ISSUE TITLE
scollector fails to collect data from haproxy 1.7

### ISSUE THREAD

**Issue by amgorb** [bosun-monitor/bosun#2112]
New haproxy version has more metrics and scollector fails with checks and fails to to gather them at all.

    error: interval.go:64: haproxy-4-http://127.0.0.1:22004/stats;csv: expected 63 lines. got: 84

https://github.com/bosun-monitor/bosun/pull/2113

**Comment by kylebrandt** [comment]
Believe this has been fixed via https://github.com/bosun-monitor/bosun/pull/2113
