### ISSUE TITLE
Looping over empty slice dps

### ISSUE THREAD

**Issue by yxx8** [bosun-monitor/bosun#2115]
# Actual behaviour
On line 311 of [cmd/tsdbrelay/main.go](https://github.com/bosun-monitor/bosun/blob/master/cmd/tsdbrelay/main.go#L311) we create an empty slice `dps`:
`dps := []*opentsdb.DataPoint{}` and we then proceed to loop over it:
```
for _, dp := range dps {
			...
		}
```

# Expected behaviour
Not looping over an empty slice.

**Comment by captncraig** [comment]
Unless I'm mistaken, we populate that slice by decoding json into it on the line after we create it: https://github.com/bosun-monitor/bosun/blob/master/cmd/tsdbrelay/main.go#L312

Am I missing something?

**Comment by yxx8** [comment]
Thou art correct.

This is me not understanding Go code.
