### ISSUE TITLE
Having trouble using scollector to monitor hbase-master and hbase-regionserver

### ISSUE THREAD

**Issue by atticusmiles** [bosun-monitor/bosun#2116]
I checked that we do have hbase collectors in the code, but I'm having trouble activating the hbase collector, can anybody offer some help as to how to config the hbase collector, since there are no document about it...

**Comment by longhua** [comment]
Would you please try to use external collectors? You can try the following scripts.
https://github.com/OpenTSDB/tcollector/tree/master/collectors/0
