### ISSUE TITLE
Unable to run without docker

### ISSUE THREAD

**Issue by ray1888** [bosun-monitor/bosun#2118]
system environment :Ubuntu 16.04.2(Server), I have already installed go hbase opentsdb and tcollector ,when i try to run the binary file download from Bosun.org. It comes error like this [ERROR:fatal: main.go:111: couldn't read system configuration: open bosun.toml: no such file or directory
],so what cause this problem? and how can i fix this

**Comment by ray1888** [comment]
after a create a bosun.toml file like below:
Hostname = "bosun"
HTTPListen = ":8070"
CheckFrequency = "1m"
DefaultRunEvery = 5
RuleFilePath = "/data/bosun.rules.conf"
TimeAndDate = [ 202, 75, 179, 136 ]
ShortURLKey = "aKey"
MinGroupSize = 5
UnknownThreshold = 5
Ping = true
PingDuration = "24h"
SearchSince = "72h"

[OpenTSDBConf]
    Host = "localhost:4242"
    Version = 2.2
    ResponseLimit = 25000000

it come errors like this:
fatal: main.go:111: couldn't read system configuration: Near line 1 (last key parsed 'tsdbHost'): Expected value but found 'l' instead.

**Comment by langerma** [comment]
how did you try to start bosun?

**Comment by HwiLu** [comment]
> after a create a bosun.toml file like below:
> Hostname = "bosun"
> HTTPListen = ":8070"
> CheckFrequency = "1m"
> DefaultRunEvery = 5
> RuleFilePath = "/data/bosun.rules.conf"
> TimeAndDate = [ 202, 75, 179, 136 ]
> ShortURLKey = "aKey"
> MinGroupSize = 5
> UnknownThreshold = 5
> Ping = true
> PingDuration = "24h"
> SearchSince = "72h"
> 
> [OpenTSDBConf]
> Host = "localhost:4242"
> Version = 2.2
> ResponseLimit = 25000000
> 
> it come errors like this:
> fatal: main.go:111: couldn't read system configuration: Near line 1 (last key parsed 'tsdbHost'): Expected value but found 'l' instead.

Have you run bosun normally at last?
