### ISSUE TITLE
BUG: Linux process monitoring ID assignment broken after a process quits

### ISSUE THREAD

**Issue by bharrisau** [bosun-monitor/bosun#2128]
See - https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/processes_linux.go#L355

After the first monitored process quits, the ID assigned to it is added to the list `free`. When the next process starts it is assigned the smallest ID from `free` but that ID is not removed, so all future processes receive the same ID.

**Comment by captncraig** [comment]
I believe this is why we have a high number of datapoints in the process metrics with duplicate tag sets. Thanks for catching it.

**Comment by LexTalionisGeli** [comment]
I'm running into this bug as well.  Would be nice if the patch could be merged, I don't know go so I'm more or less stuck with this weird behavior till then!

**Comment by LexTalionisGeli** [comment]
I don't have a build environment set up for go either 😞
