### ISSUE TITLE
cmd/scollector/collectors/processes_linux.go - thread and swap tracking

### ISSUE THREAD

**Issue by Liudvikas** [bosun-monitor/bosun#2133]
Hello,

I suggest to add a thread and swap tracking capability for the scollector. This will allow to gather metrics on count of threads and swapped memory by the monitored process. Please let me know what do you think. Thanks!

Pull request: https://github.com/bosun-monitor/bosun/pull/2132

Regards,
Liudvikas

**Comment by kylebrandt** [comment]
Closing this since there is a PR, so don't need this issue to track this.
