### ISSUE TITLE
How to filter out results based on tags? Unable to find OpenTSDB query or bosun function

### ISSUE THREAD

**Issue by rohit01** [bosun-monitor/bosun#2134]
Existing query example:

```
q("max:metric.example.value{group=*,host=*}", "7m", "2m")
```

Tag `group` has multiple values. We dont want alert for a particular value of group tag, viz. `test`.

I was expecting something like this to work. But it gives syntax error:

```
q("max:metric.example.value{group!=test,group=*,endpoint=*,host=*}", "7m", "2m")
```

**Comment by johnewing1** [comment]
q("max:metric.example.value{group=*,endpoint=*,host=*}{group= not_literal_or(test)}", "7m", "2m")

Assuming you are using opentsdb 2.2 or later
http://opentsdb.net/docs/build/html/user_guide/query/filters.html

**Comment by rohit01** [comment]
Hi @johnewing1,

Thanks for the reply. I tried your solution. Query:

```
q("max:metric.example.value{group=*,endpoint=*,host=*}{group=not_literal_or(functional-tests)}", "7m", "2m")
```

It gives the following error in bosun:

```
opentsdb: bad query format: max:metric.example.value{group=*,endpoint=*,host=*}{group=not_literal_or(functional-tests)}
```

Tried few other combinations as well, did not work. I am using bosun version: 0.5.0

```
# /usr/local/bin/bosun -version
bosun version 0.5.0 (00772aee8c27482893f885bbdbb10e26f75d7fd0) built 2016-06-21T18:18:45Z
```

**Comment by johnewing1** [comment]
Do you have tsdbVersion=2.3 set in the config ?

**Comment by rohit01** [comment]
@johnewing1: No, it was not set. I just added the configuration and it worked perfectly.

Thanks a lot.

**Comment by loggerhead** [comment]
Is there a way to filter multiple tags with 'AND' logic? something like:

```
if group != test AND host != test:
    q("max:metric.example.value{group=*,endpoint=*,host=*}", "7m", "2m")
```

**Comment by hyzgh** [comment]
@loggerhead Have you find a solution for this?

**Comment by loggerhead** [comment]
> @loggerhead Have you found a solution for this?

If you can use `lookup` table (see https://bosun.org/examples for details), then it can resolve your problem. Others, I found no way to achieve it.
