### ISSUE TITLE
undecoded fields in system configuration when using elasticsearch

### ISSUE THREAD

**Issue by bobmshannon** [bosun-monitor/bosun#2138]
When starting bosun on `0.6.0-beta` with the following Elasticsearch system configuration:

```
[ElasticConf]
    [ElasticConf.default]
        Hosts = ["http://ny-lselastic01.example.com:9200", "http://ny-lselastic02.example.com:9200"]
        SimpleClient = false
```

It fails with the following error in the logs:

```
2017/08/08 23:41:14 fatal: main.go:111: couldn't read system configuration: undecoded fields in system configuration: [ElasticConf.default ElasticConf.default.Hosts ElasticConf.default.SimpleClient]
```

Is this potentially a bug, or potentially a misconfiguration / documentation problem?

**Comment by bobmshannon** [comment]
Update: It looks like one needs to pull the latest changes from `master` to work around this for now until 0.6.0 stable is released.

**Comment by vennekilde** [comment]
Same with 0.6.0-beta1
`[ElasticConf]
   [ElasticConf.default]
        Hosts = ["http://localhost:9200"]
        SimpleClient = false`

`fatal: main.go:111: couldn't read system configuration: undecoded fields in system configuration: [Scheme ElasticConf.default ElasticConf.default.Hosts ElasticConf.default.SimpleClient]`
