### ISSUE TITLE
Global notification group for high error rates/etc

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#215]
Also need a bosunNotification global config value for when the error rate of a check is >50%. If so, don't trigger notifications, trigger the global notification. For use when OpenTSDB is down or network down, etc.

**Comment by kylebrandt** [comment]
We do this with Unknowns now, which I think is enough. If there is a large amount of alerts when an event occurs, it probably means that your alerts are not scoped correctly. There are exceptions to this, but I have found it to be infrequent. 

I wouldn't be against a global rate limiting, but don't feel it is important enough to keep the issue open.
