### ISSUE TITLE
maxLogFrequency unknown unit issue.

### ISSUE THREAD

**Issue by PerRommetveit** [bosun-monitor/bosun#2166]
Dear bosun community,

within an alert definition I have:

    log = true
    maxLogFrequency = 5m  

When starting bosun the logs displays this error:
<maxLogFrequency = 5m>: time: unknown unit m  in duration 5m

Notice there is a space between 'm' and 'in'. 

It seems like that you cannot have a space behind 5m. 

Whitespace should be stripped from the value here.

**Comment by captncraig** [comment]
Interesting find. Bosun takes everything until the end of the line and treats that string as the value of each pair. The code for that is [here](https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/conf/rule/parse/parse.go#L218). I would be ok applying `strings.TrimSpace` to the final value there. 

If you make a pr for it, I'll merge it.

**Comment by PerRommetveit** [comment]
Thanks for the response, never did any go coding or a pr (pull request) for that matter. But it is an interesting opportunity to learn. Will do my best to make a pr as soon as I have the time.
