### ISSUE TITLE
Reporting CNMP metrics with scollector on windows

### ISSUE THREAD

**Issue by georgeduckett** [bosun-monitor/bosun#2169]
I'm trying to add in reporting cnmp metrics with a config file for scollector on windows. I've tried using both 0.6.0-beta1 and 0.5.0. I added the following to the config file:

    [[SNMP]]
      Community = "xxxxx"
      Host = "123.123.123.123"

When I try starting up scollector it complains about an unknown MIB cisco. I understand I can specify specific MIBs, however I'm not sure what I should be putting in there exactly (should I reference something I specify in `[[MIBs]]`? How should I reference the built in ones?). I've found where in the code the error message is generated from, but I don't know enough about go to figure out where the MIBs should be loaded from. As far as I can tell they're hard-coded in files like `snmp_cisco.go` but I can't work out what I've done wrong in the config. I've also tried putting an MIB file in the same directory as scollector and referencing it by name: `MIBs = ["MIB-FILE"]`

How can I add report on an cnmp compatible device using scollector on windows?

**Comment by georgeduckett** [comment]
I've managed to figure it out; I found the code that defines the built in names:

	"ifaces":   SNMPIfaces,
	"ios":      SNMPCiscoIOS,
	"asa":      SNMPCiscoASA,
	"nxos":     SNMPCiscoNXOS,
	"bridge":   SNMPBridge,
	"ips":      SNMPIPAddresses,
	"ciscobgp": SNMPCiscoBGP,
	"sys":      SNMPSys,
	"fortinet": SNMPFortinet,
	"lag":      SNMPLag,

Looks like the config default of "cisco" isn't valid, presumably because it was broken into multiple builtins at some point, but the default value wasn't updated.

Maybe it's worth updating the default value and documentation somewhere? Happy to have a go at a pull request if it helps.

**Comment by kylebrandt** [comment]
This correct, we broke them out because we discovered that SNMP can be pretty different between Cisco's various operating systems. So we broke this up per operating system that is created by Cisco.

In truth, there ends up being exceptions in the code per certain devices IIRC... Cisco monitoring is a mess.

A documentation update via PR would be welcome.
