### ISSUE TITLE
HAProxy collector should tag the sid (server ID)

### ISSUE THREAD

**Issue by adeverteuil** [bosun-monitor/bosun#2170]
It's possible to have multiple server lines with the same name, provided they have a different id.

```
backend foo
  server a 10.1.1.1 id 1
  server a 10.1.1.1 id 2
```

One possible use-case is to connect to backend servers from a pool of source IP addresses to overcome ephemeral port exhaustion.

https://alohalb.wordpress.com/2012/12/12/haproxy-high-mysql-request-rate-and-tcp-source-port-exhaustion/

HAProxy reports the id in the sid column in the statistics in CSV format.

http://cbonte.github.io/haproxy-dconv/1.7/management.html#9.1

However, since no tag is created by scollector for the sid, this creates duplicate datapoints which are resolved by keeping only the last value. For example, I would see this in the output of scollector -p:

```
2017/10/05 18:04:22 info: queue.go:102: {"metric":"haproxy.server.stot","timestamp":1507226661,"value":6,"tags":{"cluster":"test","host":"lb04","pxname":"80_http","svname":"web1","tier":"4"}}
2017/10/05 18:04:22 info: queue.go:102: {"metric":"haproxy.server.stot","timestamp":1507226661,"value":6,"tags":{"cluster":"test","host":"lb04","pxname":"80_http","svname":"web1","tier":"4"}}
2017/10/05 18:04:22 info: queue.go:102: {"metric":"haproxy.server.stot","timestamp":1507226661,"value":5,"tags":{"cluster":"test","host":"lb04","pxname":"80_http","svname":"web1","tier":"4"}}
2017/10/05 18:04:22 info: queue.go:102: {"metric":"haproxy.server.stot","timestamp":1507226661,"value":5,"tags":{"cluster":"test","host":"lb04","pxname":"80_http","svname":"web1","tier":"4"}}
```

To resolve this, I suggest adding the tag sid or id to create multiple time series when multiple server lines with the same name exist.

**Comment by kylebrandt** [comment]
Main difficulty here is the number of tags on haproxy metrics. Since a lot of metrics are collected, adding additional tags is going to cost a lot in space and query performance (at least, with OpenTSDB). 

We probably would want this behind an option flag, even though in the case of sids this collector is technically incorrect as spelled out in the issue.
