### ISSUE TITLE
Inconsistent metadata between different sources for the os.net... metric

### ISSUE THREAD

**Issue by georgeduckett** [bosun-monitor/bosun#2172]
I'm running scollector on several windows servers and collecting the metric `os.net.errs` (and several others starting `os.net.`). I'm also using SNMP to query other hardware using the built in `ifaces` MIB. This also adds `os.net.errs` metrics for the monitored hardware.

There is inconsistent naming of the unit of the metric between `snmp_ifaces.go` and `network_windows.go`, meaning the output of scollector is cluttered with constant metadata renaming notifications as the units get switched back and forth.

I'm not sure which way the unit name should go, but could the metadata for this (and more generally, all) metrics be given consistent units.

**Comment by kylebrandt** [comment]
I'm not entirely clear on what you mean by:

>  meaning the output of scollector is cluttered with constant metadata renaming notifications as the units get switched back and forth.

Can you expand on that?

**Comment by georgeduckett** [comment]
![image](https://user-images.githubusercontent.com/325039/31343712-50d9d4d0-ad08-11e7-90ea-5c2cf0399b8f.png)

**Comment by kylebrandt** [comment]
Marked as bug. The purpose of the `os.` namespace is to be a normalized metric. So Metadata should be consistent.
