### ISSUE TITLE
bosun master (pre 0.7) w/ opentsdb 2.1.3 = Unable to parse the given JSON

### ISSUE THREAD

**Issue by dustyketchum** [bosun-monitor/bosun#2182]
hi,

running the master branch of bosun with opentsdb 2.1.3 we see lots of errors like the following in bosun.log.  We've confirmed that we've set Version = 2.1 in [OpenTSDBConf]
`2017/10/17 22:37:45 error: tsdb.go:97: Error on tsdb query 2: opentsdb: {"start":1508276265,"end":1508279865,"queries":[{"aggregator":"avg","metric":"jvm.memory.heap.usage","rateOptions":{},"downsample":"1h-avg","filters":[{"type":"literal_or","tagk":"env","filter":"production","groupBy":true},{"type":"iwildcard","tagk":"host","filter":"*app-name*","groupBy":true}]}]}: Unable to parse the given JSON`
`2017/10/17 22:37:45 error: check.go:653: opentsdb: {"start":1508276265,"end":1508279865,"queries":[{"aggregator":"avg","metric":"jvm.memory.heap.usage","rateOptions":{},"downsample":"1h-avg","filters":[{"type":"literal_or","tagk":"env","filter":"production","groupBy":true},{"type":"iwildcard","tagk":"host","filter":"*app-name*","groupBy":true}]}]}: Unable to parse the given JSON`
`2017/10/17 22:37:45 error: check.go:570: Error checking alert heapSpace: opentsdb: {"start":1508276265,"end":1508279865,"queries":[{"aggregator":"avg","metric":"jvm.memory.heap.usage","rateOptions":{},"downsample":"1h-avg","filters":[{"type":"literal_or","tagk":"env","filter":"production","groupBy":true},{"type":"iwildcard","tagk":"host","filter":"*app-name*","groupBy":true}]}]}: Unable to parse the given JSON`

**Comment by kylebrandt** [comment]
@dustyketchum do you still get this error if you comment out the Version line with OpenTSDBConf in the system config (toml)?

**Comment by dustyketchum** [comment]
hi, if I remove the OpenTSDBConf Version I get different opentsdb errors:
`2017/10/19 21:21:47 error: tsdb.go:97: Error on tsdb query 2: opentsdb: {"start":1508447806,"end":1508448106,"queries":[{"aggregator":"sum","metric":"kafka.lag","rateOptions":{},"tags":{"group":"app","partition":"*","topic":"app-topic"}}]}: No such name for 'tagv': 'app'`
`2017/10/19 21:21:47 error: notify.go:48: sending http: bad response on notification POST: 400`
`2017/10/19 21:21:47 error: check.go:653: opentsdb: "start":1508447806,"end":1508448106,"queries":[{"aggregator":"sum","metric":"kafka.lag","rateOptions":{},"tags":{"group":"app","partition":"*","topic":"app-topic"}}]}: No such name for 'tagv': 'app'`
`2017/10/19 21:21:47 error: check.go:570: Error checking alert appConsumeRate: opentsdb: {"start":1508447806,"end":1508448106,"queries":[{"aggregator":"sum","metric":"kafka.lag","rateOptions":{},"tags":{"group":"app","partition":"*","topic":"app-topic"}}]}: No such name for 'tagv': 'app'`

**Comment by kylebrandt** [comment]
Ah okay, so that is actually "working" now I believe. The problem is that
2.1 is being treated as 2.2 with the earlier messages.

These more recent error messages are OpenTSDB errors being returned to
Bosun because you are querying for tags that are not in the TSDB yet
(probably hitting a test instance I assume). So you should be good for now
with commenting out that line as a workaround.
