### ISSUE TITLE
Can I specify the check frequency for every alert

### ISSUE THREAD

**Issue by waxdsf** [bosun-monitor/bosun#2184]
Hi, guys. When I use bosun for monitoring data in opentsdb, I need know the avg number for 1 day ago, 1 hour ago and 5m ago, so I need specify the check frequency for every alert, but I cannot find how to do it in document. So can someone help me? Thanks!

**Comment by pradeepbbl** [comment]
@waxdsf  use runEvery in your alert configuration https://bosun.org/definitions#runevery

**Comment by waxdsf** [comment]
@pradeepbbl, I think runEvery means run how many times for once check, and I try to assign runEvery 5m, a format error ouccer. So if my understanding was wrong, can you give me an example? Thanks!

**Comment by pradeepbbl** [comment]
@waxdsf please use integer as value to runEvery as it multiple with CheckFrequency, so for example if you set CheckFrequency="1m" (in system config) and use runEvery=5(in alert config) the alert will schedule to run every 5m
Thanks,

**Comment by waxdsf** [comment]
@pradeepbbl that worked, thank you very much!
