### ISSUE TITLE
bosun master (pre 0.7) won't send notifications to slack, gets http 400 errors instead

### ISSUE THREAD

**Issue by dustyketchum** [bosun-monitor/bosun#2186]
Hi, I'm testing master branch and having issues getting notifications to Slack.
Also please note that another Bosun user has confirmed they see the same problem sending Bosun notifications to Slack on the your support slack channel.
We are getting notifications to Pagerduty successfully, though I also seen an error regarding email in the logs.
In my logs I see lots of these errors, which I assume are related to Slack.
`2017/10/24 13:46:19 info: notify.go:179: Batching and sending unknown notifications`
`2017/10/24 13:46:19 info: notify.go:219: Done sending unknown notifications`
`2017/10/24 13:46:19 error: notify.go:192: failed to send alert  to [] Must specify at least one From address and one To address`
`2017/10/24 13:46:19 error: notify.go:42: sending email: Must specify at least one From address and one To address`
`2017/10/24 13:46:19 error: notify.go:48: sending http: bad response on notification POST: 400`
`2017/10/24 13:46:19 info: notify.go:196: relayed email  to [bosun-alerts@fqdn.com] sucessfully. Subject: 47 bytes. Body: 192 bytes.`
`2017/10/24 13:46:19 info: notify.go:196: relayed email  to [bosun-staging@fqdn.pagerduty.com] sucessfully. Subject: 47 bytes.` `Body: 193 bytes.`

Unfortunately slack is ssl so tcpdump isn't going to get me very far.

Here's the smtpconf from system.conf:
`[SMTPConf]`
`        EmailFrom = "errors@fqdn.com"`
`       Host = "email-smtp.us-east-1.amazonaws.com:25"`
`       Username = "user"`
`       Password = "pass"`
        
Here's the slack config from rules.conf:
`{% raw %}`
`template slack {`
`    body = `{`
`    "text": "{{.Subject}} <{{.Incident}}|view in bosun>",`
`  }`
`}`
`{% endraw %}`
``
`notification slack_test {`
`  post = https://hooks.slack.com/services/stuff/stuff/stuff`
`  bodyTemplate = body`
`}`
``
`lookup pageable_notifications {`
`  entry env=experiment {`
`    warnNotification = email,experiment_slack`
`    critNotification = email,experiment_slack`
`  }`
`}`

**Comment by kylebrandt** [comment]
Documentation needs to be updated, here is part of an internal example, maybe this will help. This constructs an object so you don't have to worry about sending malformed json because of quoting. 

```
template it.anomalous.docs.slack.alt {
    slackBody = `
        {{- /* If the Eval piped to q errors and doesn't return a number the template
        will not error, it will just disply %!(MISSING) */ -}}
        
        {{- $qValue := .Eval .Alert.Vars.q | printf "%.0f" -}}
        {{- $qField := makeMap "title" "Value" "value" $qValue "short" true -}}
        
        {{- $pastAvgValue := .Eval .Alert.Vars.past_avg | printf "%.0f" -}}
        {{- $pastAvgField := makeMap "title" "Past Average" "value" $qValue "short" true -}}
        
        {{- $pastDevValue := .Eval .Alert.Vars.past_dev | printf "%.0f" -}}
        {{- $pastDevField := makeMap "title" "Standard Deviation" "value" $pastDevValue "short" true -}}
        
        {{- $fields := makeSlice $qField $pastAvgField $pastDevField -}}
        
        {{- $author := printf "Bosun: %s" .AlertKey -}}
        
        {{- $attachmentOne := makeMap "fallback" "Bosun alert" "color" "warning" "author_name" $author "title" .Subject "title_link" .Incident "fields" $fields -}}
        
        {{- $attachments := makeSlice $attachmentOne -}}
        
        {{- makeMap "attachments" $attachments | json }}
    `
}

notification it-slack-chat {
    post = ${sys.CHAT_IT_SLACK}
    bodyTemplate = slackBody
    contentType = application/json
}


```

**Comment by dustyketchum** [comment]
hi, I've copied and pasted your example into my rules.conf but slack still isn't working, I still get 
`2017/10/25 23:30:10 error: notify.go:48: sending http: bad response on notification POST: 400`

here's my rules.conf:
`
template slack {
        body = `
        {{- /* If the Eval piped to q errors and doesn't return a number the template
        will not error, it will just disply %!(MISSING) */ -}}

        {{- $qValue := .Eval .Alert.Vars.q | printf "%.0f" -}}
        {{- $qField := makeMap "title" "Value" "value" $qValue "short" true -}}

        {{- $pastAvgValue := .Eval .Alert.Vars.past_avg | printf "%.0f" -}}
        {{- $pastAvgField := makeMap "title" "Past Average" "value" $qValue "short" true -}}

        {{- $pastDevValue := .Eval .Alert.Vars.past_dev | printf "%.0f" -}}
        {{- $pastDevField := makeMap "title" "Standard Deviation" "value" $pastDevValue "short" true -}}

        {{- $fields := makeSlice $qField $pastAvgField $pastDevField -}}

        {{- $author := printf "Bosun: %s" .AlertKey -}}

        {{- $attachmentOne := makeMap "fallback" "Bosun alert" "color" "warning" "author_name" $author "title" .Subject "title_link" .Incident "fields" $fields -}}

        {{- $attachments := makeSlice $attachmentOne -}}

        {{- makeMap "attachments" $attachments | json }}
    `
}

notification slack {
  post = https://hooks.slack.com/services/url
  bodyTemplate = body
  contentType = application/json
}
`

**Comment by dustyketchum** [comment]
I should point out I've also tried a one word subject and body for a slack message, and that didn't work any better.

**Comment by earwin** [comment]
@dustyketchum 
> Unfortunately slack is ssl so tcpdump isn't going to get me very far.
Well, you could temporarily edit notification `post` field to point at something else than slack.
Say, your own http server, or netcat.
See what you get, and `curl` to Slack manually, if you so desire.

**Comment by dustyketchum** [comment]
we solved this ourselves eventually.
