### ISSUE TITLE
Bosun Connecting to Redis Cluster gives CROSSLOT error

### ISSUE THREAD

**Issue by ert56** [bosun-monitor/bosun#2187]
Hello,

We have a redis cluster with master/slave architecture setup in our PRODUCTION environment.
When we connect to redis from bosun, we get the below error.

_state_data.go:291: ERR CROSSSLOT Keys in request don't hash to the same slot (command='HDEL', key='openIncidents') within 'MULTI'._

Can somebody please help on this as this is very urgent?

**Comment by captncraig** [comment]
What version of bosun specifically are you running?

**Comment by captncraig** [comment]
We have never tested or run bosun on a redis cluster setup. I think you have just discovered it does not work. That code is doing fairly involved cleanup in a transactional way, and it seems the cluster can't handle that unless every key is on the same shard.

I don't know what to tell you other than sorry. My initial indication is that adding support for redis cluster is a non-trivial task that will take significant resources.

**Comment by captncraig** [comment]
See #2190
