### ISSUE TITLE
Bosun support for Redis Cluster

### ISSUE THREAD

**Issue by ert56** [bosun-monitor/bosun#2190]
Hello,

We have figured out that bosun does not support the redis Cluster. 

Are there any plans for providing the support for the same?

**Comment by captncraig** [comment]
We have no plans to implement it in the near future on our end, as we do not use redis in cluster mode ourselves. I am not exactly sure what things we are doing currently that prevent it from working fully. 

We would surely welcome any further information about what we can do to support it, and would welcome a contribution to add it.
