### ISSUE TITLE
On JSON notification issues

### ISSUE THREAD

**Issue by mvuets** [bosun-monitor/bosun#2197]
Hi. I've been asked to look into an issue of making JSON notifications (for instance to POST JSON to PD on an incident ack, etc.). My understanding is that composing JSON using a text template engine is inherently incorrect: it is clumsy and error-prone.

From this pull request #2135 and [@kylebrandt's comment](https://github.com/bosun-monitor/bosun/pull/2135#issuecomment-327512356) I see that there is an effort to improve the situation. There are three helpers `makeSlice`, `makeMap` and `| json` that could be used to assemble and serialise a data structure and avoid dealing with JSON encoding issues. Yet they don't seem to quite cut it.

One issue in particular is related to a complex data structure provided to, say, `actionBodyAck` and limited capabilites of Go's _text/template_ package: how to traverse multi-dimensional data? `.States` is an array, so I presume multiple accidents may be acknowledged at once. Here is where I fail to come up with an appropriate way to get IDs across all `.States` items. 

I can think of two potential enhancements.

1. Keep composing JSON by hand as text, but provide with a JSON escaping helper that would be a middle ground between built-in `js` and Bosun's `json`. It would encode given values (both scalar and structures) in such a way that it can be always safely used in place of an object field value:
```
jsonBody = `{
  "key": {{ V "$key" | json_val }},
  "accident_nr": {{ len .States | json_val }},
  "accident_ids": [ {{ range .States }}{{ .Id }},{{ end }} ],
  "summary": {{ .Subject | json_val }}
}
`
```

2. Provide templates with another helper that could help querying data, return it in a structured way which then can be serialised with `json`. Something alike [jq](https://stedolan.github.io/jq/). For example:
```
jsonBody = `
  {{- $accident_nr := len .States -}}
  {{- makeMap "key" (V "$key") "accident_nr" $accident_nr "summary" .Subject "accident_ids" (jq "[.States[].Id]") | json -}}
`
```

I would be glad to hear what's your vision on improving support for JSON notifications? Thanks.

**Comment by kylebrandt** [comment]
I played with this a little bit last week:

- Idea: Add an `append` like command to the template language. Problem - the template language doesn't allow access to to modifying variables in the outside scope within the inner scope
 - Other idea: Make a new type slice that has methods attached to it. And append and and a method that returns something you can range over (iterator). Might work but awkward

We might just need to make sure there are some different arrangements of the state data attached to the context for the general use cases.

**Comment by mvuets** [comment]
I tried to imitate a proposed `append` command too and stumbled upon the same variable scope issue:
```
{{ $ids := "" }}
{{ range .States }}
  {{ $ids := printf "%s %s" $ids .Id }}
{{ end }}
```

Here is a yet another idea that can help to leverage existing _text/template_ syntax and apply it to the described case. Write a helper that can evaluate a template and capture its output into a variable (alike described here https://stackoverflow.com/questions/40164896/capture-or-assign-golang-template-output-to-variable). For example:
```
{{ define "list-ids" }}
  {{ range .States }}{{ .Id }}{{ end }}
{{ end }}
{{ $ids := template "list-ids" }}
```
However this also does not seem to help when one wants to have structured data, say a JSON array of ids, because how does one iterate over `.States` and passes its `.Id` to `makeSlice`, right?
