### ISSUE TITLE
How to install Bosun to windows ?

### ISSUE THREAD

**Issue by l2999019** [bosun-monitor/bosun#2206]
I downloaded "bosun-windows-amd64.exe", but I don't know how to install it..

**Comment by MetSystem** [comment]
直接运行

**Comment by l2999019** [comment]
直接运行就没反映了 ..进程里面也没有

**Comment by MetSystem** [comment]
没配置文件bosun.conf？

**Comment by pkunze** [comment]
I would also be interested in installing to windows. Any Docs/Blog entries someone can recommened?

**Comment by muffix** [comment]
I don't have a Windows machine handy at the moment, but it should just be a single binary. There's nothing to install.

**Comment by pkunze** [comment]
So there is no need for a separate openTSDB or sth.?

**Comment by langerma** [comment]
you need a tsdb, influx, elasticsearch or prometheus as source for your time series data you want to check.

**Comment by pkunze** [comment]
alright, will check tomorrow. Thanks!

**Comment by pkunze** [comment]
worked. thanks a lot!
