### ISSUE TITLE
No setting for redis database

### ISSUE THREAD

**Issue by efficks** [bosun-monitor/bosun#2219]
In previous version it was possible to set the redis db with the setting "redisDb".
In 0.0.6, it seems the the setting is migging. Is it a documentation mistake?

**Comment by PeterGrace** [comment]
Have a look at https://bosun.org/system_configuration -- specifically the "DBConf" section of the file.  The bosun config file is now toml format, and you specify the redis host via the toml config file, specifically the DBConf section.

**Comment by efficks** [comment]
Yes, I've seen this informations.
You can specify, the host and port and the password. But you can't set the Database index (0, 1, 2, etc.)
In the previous version, the setting redisDb was available to indicate which index to use.

**Comment by PeterGrace** [comment]
https://github.com/bosun-monitor/bosun/blob/29af0ede01999e0d434117a20c4fdca98206d00a/cmd/bosun/conf/system.go#L150-L158

It appears that "RedisDB" should work for that setting, but I agree that the documentation is ambiguous about that setting.

**Comment by PeterGrace** [comment]
Issued PR to update docs: https://github.com/bosun-monitor/bosun/pull/2220

**Comment by efficks** [comment]
@PeterGrace Thank you
