### ISSUE TITLE
Post from Bosun is successful but still no alert on slack

### ISSUE THREAD

**Issue by bonisintu** [bosun-monitor/bosun#2226]
We are using Bosun 0.5 and running it as a container service. Trying to send the message to slack using a incoming-webhook. Bosun Log is saying post is successful but still no alert on slack whereas able to post a sample message to slack using cURL from the container.

![bosun-log](https://user-images.githubusercontent.com/33446174/36888745-e22efb42-1e1c-11e8-9e20-38850d72d26e.JPG)

The config file I am using is as below -
===================================================================== 
tsdbHost = localhost:4242
tsdbVersion = 2.2
ledisDir = /data/ledis_data
ledisBindAddr = 0.0.0.0:9565

checkFrequency = 3m
template test {
    subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
    body = `<p>Name: {{.Alert.Name}}
    <p>Tags:
    <table>
        {{range $k, $v := .Group}}
            <tr><td>{{$k}}</td><td>{{$v}}</td></tr>
        {{end}}
    </table>`
}
notification slack {
contentType = application/json
post =  #https://hooks.slack.com/services/key
body ={"text": "Bosun-Slack connectivity Testing!"}
next = slack
timeout = 1m
}
alert test1 {
    template = test
    critNotification = slack
    runEvery = 1
    crit = avg(q("sum:linux.disk.fs.space_free{host=literal_or(95dc27cd3f70)}", "1h", "")) > 0
}

Checked with slack support team as well. Got following response - "_**looks like there is a need to check your code to see why it's occasionally sending empty payloads. We're definitely getting some empty requests from your side. The fact that cURL requests are coming through is further indicator that there's something going awry with your script.**_"

Can you please guide me on this? Thanks

**Comment by rickynils** [comment]
I have this behavior too. The first email/HTTP post is correct, but when the next notification is executed the body is empty (for both email and HTTP POST)

Also @zhenghouzz has seen this behavior: https://github.com/bosun-monitor/bosun/issues/1583#issuecomment-182533332

cc @captncraig
