### ISSUE TITLE
Support Elasticsearch 6.x as a Datasource

### ISSUE THREAD

**Issue by ghost** [bosun-monitor/bosun#2240]
I see that there is an open issue and work in progress for supporting ES 5.x as a data source https://github.com/bosun-monitor/bosun/issues/1982
I would like to vote to also have support for 6.x as that is the current release version of ES.

**Comment by langerma** [comment]
as far as i have testet the esv5 option it also works for esv6

**Comment by jbrann** [comment]
I am unable to run current master branch vs ElasticSearch due to config problem.  See issue 2138.  Cannot ingest config
