### ISSUE TITLE
cmd/Bosun Items page data question

### ISSUE THREAD

**Issue by KozzyKoder** [bosun-monitor/bosun#2263]
Hello,

I have a question about Items page in cmd/Bosun application. Is it so that it shows data only for openTSDB datasource?

Depending on setup it might be completely empty and confuse users who doesn't set up an openTSDB environment. Mine suggestion is to disable this menu point and show tooltip that describes in which case this menu point might be available. What do you think about that?

Thanks!

**Comment by mvuets** [comment]
I see the PR got merged. Can this issue be closed too?
