### ISSUE TITLE
Notification variables in templates question

### ISSUE THREAD

**Issue by KozzyKoder** [bosun-monitor/bosun#2272]
Hello, we have an issue with templates. Currently we have a lot of copy-paste in templates because we need to include a special authorisation key(service_key) in template body for pagerduty. Pagerduty does not provide another way to pass that key. It will be great to have a way to store key outside of template in variable. These variables most reasonably to store in notification, not in alert, because alert might have several notifications and each notification might have its own value for variable with same name.

Thus, it will be good to have a functionality of rendering notification variables in templates. Otherwise we will need to copy templates over and over again with very small amount of changes. Is it any way to implement this functionality?

**Comment by kylebrandt** [comment]
Perhaps the `V` template function and RuleVars will do what you need? See http://bosun.org/system_configuration#rulevars

**Comment by KozzyKoder** [comment]
It does not solve our problem, because for each such global variable we need to have a separate set of templates (each variable need appear in templates)

**Comment by kylebrandt** [comment]
Might need a sort of example showing the repetition to understand. This is what a prototype notification for pduty including the routing key ended up looking like https://github.com/bosun-monitor/bosun/pull/2135#issuecomment-329511507

**Comment by KozzyKoder** [comment]
Please see an example:

      template service1_notifications {  
        
          pdService1Body = `{  
             "service_key": "83b6bd9f-d020-41f2-9a86-753197c0778e",  
             <<bunch of fields>>  
          }`  
        
          pdService1ActionAck = `{  
            "service_key": "83b6bd9f-d020-41f2-9a86-753197c0778e",  
            <<bunch of fields>>  
          }`  
        
          pdService1ActionClose = `{  
            "service_key": "83b6bd9f-d020-41f2-9a86-753197c0778e",  
            <<bunch of fields>>  
          }`  
            
          pdService1UnknownBody = `{  
             "service_key": "83b6bd9f-d020-41f2-9a86-753197c0778e",  
             <<bunch of fields>>  
          }`  
      }  
        
      template service1_template {  
          body = `body`  
          subject = `subject`  
          inherit = service1_notifications  
      }  
        
      notification service1_pagerduty {  
          post         = <<post address>>  
          contentType  = application/json  
          bodyTemplate = pdService1Body  
          runOnActions = Ack,Close  
          actionBodyAck = pdService1ActionAck  
          actionBodyClose = pdService1ActionClose  
          unknownBody = pdService1UnknownBody  
      }  
        
      alert service1_alert {  
          template = service1_template  
        
          crit = <<some conditions>>  
          critNotification = service1_pagerduty  
      }

here if we want to define another alert for service2 with another service_key we need to carefully copy
template service1_notifications and change service_key there. All other fields remains the same. We already have a lot such templates for different services which all have different service_key.

How can we make a generic templates in such case?

**Comment by kylebrandt** [comment]
If you look at the example I linked to, the "details" field body in the
body changes whereas the rest is the same.

pduty = `{{ .Set "details" (makeMap "host" .Group.host) }}{{ template
"baseFakePDuty" . }}`


This is done with ineherit, .Get and .Set. I believe you do the same with
the service key?

**Comment by kylebrandt** [comment]
I think I need to understand the better role of "services" in this example
/ your environment. For example, do you have X teams in the company, and
each team has a collection of services? Or is each product a service?

**Comment by KozzyKoder** [comment]
We have lots of teams, each team can look after one or many different systems, each system will have one or many alerts defined for it. Systems might be very different - DB's, messaging queues, websites. Teams want to add new notifications on their own. Bosun is a shared resource for teams.

Each team would usually have one ‘Service’ in PagerDuty with one or multiple integrations key that are called ‘service_keys’ (https://support.pagerduty.com/docs/services-and-integrations). IOW dozens of our teams are integrating with PagerDuty via their several own ‘service_keys’, we do not have one single global ‘service_key’.


We want to simplify bosun-pagerduty integration for our teams. 

Here’s what we can get with global variables: https://gist.github.com/KozzyKoder/c88bbfb6c70758f28790c1b39da47eb8

Here’s an example how we dream to have it work: https://gist.github.com/KozzyKoder/4f1012efbf3d8b1f146eedaade57bb54

If you compare these examples you’ll notice that overall config length for each system shrunk by ~2 times, and IMHO also looks simpler.

**Comment by kylebrandt** [comment]
I think I am starting to understand much better now. In terms of Teams having more than one integration key (service_key), will there be cases where a single team has multiple keys that will be used with Bosun. So, for example, Team A has 3 services keys, might 2 of them be used with Bosun, or would it always be one for the Bosun integration for that team and other service keys are for other stuff?

**Comment by KozzyKoder** [comment]
Yes, it is often situation for teams to have several PD service_key in Bosun.

**Comment by kylebrandt** [comment]
@KozzyKoder So Bosun `notification` objects basically end up as a combination of team+service_keys. So a team might have a handful of bosun notification objects?

**Comment by KozzyKoder** [comment]
Yes, team also might have several notifications.

**Comment by KozzyKoder** [comment]
@kylebrandt could you please share any ideas/thoughts how to approach this issue? Thanks
