### ISSUE TITLE
ElasticSearch 5 support, bug in results / grouping

### ISSUE THREAD

**Issue by phoinixgrr** [bosun-monitor/bosun#2285]
Have discovered a potential bug when using bosun compiled with 'go build -tags="esv5" ' 
Is related to elasticsearch - escount() function results, when using tagkeys. 

The following simple Expression is being used to reproduce the issue: 

>   $index = esdaily("@timestamp", "*" , "2006-01-02")
>   $minute = 1
>   $bucketSize = "${minute}m"
>   $keyField = "zone"
>   $es_search_time_duration = "5m" 
>   $filter = esall()
>   ["legacy"]escount($index , $keyField, $filter, $bucketSize, $es_search_time_duration , "")_ 

  
field string named "zone"($keyField) is being used to group the ElasticSearch results under the same tag key. 
There are a total of 33 different "zone" keyfields in all indices of the ElasticSearch service that is being queried. 

Bosun compiled **without** "esv5" tag produces complete results, and returns results for all 33 different "zone" keyfields. 

<img width="779" alt="screen shot 2018-07-26 at 18 15 11" src="https://user-images.githubusercontent.com/36594156/43272082-c817ecf2-9101-11e8-8a9f-51db5643d566.png">
<img width="752" alt="screen shot 2018-07-26 at 18 15 22" src="https://user-images.githubusercontent.com/36594156/43272089-ca6fe798-9101-11e8-8e18-ba0fe6798a70.png">

Bosun compiled with "esv5" tag produces incomplete results, and returns results only for the first 10 "zone" keyfields, and ignores testing against the remaining 23 groups. 
<img width="754" alt="screen shot 2018-07-26 at 18 05 29" src="https://user-images.githubusercontent.com/36594156/43272104-d36d8c06-9101-11e8-8a7b-97efd553dde5.png">

This produces incomplete ES results to test against, and makes elasticsearch 5.0 support unusable. 

Bosun build used is compiled from master , Bosun_0.7.0_git_master_77a972c
2 builds used, one compiled with go build -tags="esv5" , and one without the esv5 tag. 

Able to reproduce the issue, every time, also confirmed using different ElasticSearch servers.

**Comment by phoinixgrr** [comment]
Something to mention, that could be significant: 

When using the following expression, to sum all the documents produced in the last 5 minutes, and compare the non esv5 build with the esv5 build: 

> $index = esdaily("@timestamp", "*" , "2006-01-02")
> $minute = 1
> $bucketSize = "${minute}m"
> $keyField = ""
> $es_search_time_duration = "5m"
> $filter = esall()
> sum(["legacy"]escount($index , $keyField, $filter, $bucketSize, $es_search_time_duration , ""))

_

Bosun compiled without "esv5" tag:
<img width="795" alt="screen shot 2018-07-26 at 18 49 36" src="https://user-images.githubusercontent.com/36594156/43273296-c4dc27d0-9104-11e8-8a0d-2b7ccedc16e1.png">

Bosun compiled with "esv5" tag:
<img width="707" alt="screen shot 2018-07-26 at 18 49 30" src="https://user-images.githubusercontent.com/36594156/43273298-c6ae885a-9104-11e8-9eba-34d6635cd766.png">


Documents count is the same (slight difference is because of 2-3 seconds ahead in the count of the documents between the 2 builds - new documents being pushed in ES).  
Therefore the complete document count is available in both  "non esv5 build", and the "esv5 build". 

Something seems to be broken, in the "grouping"/"tag key" functionality of the esv5 build.

**Comment by phoinixgrr** [comment]
Further testing, with 2 KeyFields (2 groups) : 
_
> $index = esdaily("@timestamp", "*" , "2006-01-02")
> $minute = 1
> $bucketSize = "${minute}m"
> $keyField = "zone,rack"
> $es_search_time_duration = "5m"
> $filter = esall()
> ["legacy"]escount($index , $keyField, $filter, $bucketSize, $es_search_time_duration , "")
_

Bosun compiled without "esv5" tag returns all 68 groups. 
Bosun compiled with "esv5" tag returns 23 groups. 

Multiple group tags(2), change the groups returned from 10 to 23 for the esv5 enabled build. 

Let me know if I can help with further debugging this.

**Comment by liujin1993** [comment]
I send a agg request to esv5 directly without "size" in "agg",and it returns only 10 groups. So I feel this is limited by esv5.
