### ISSUE TITLE
Memory Leak on Windows Server 2016

### ISSUE THREAD

**Issue by Raynor59** [bosun-monitor/bosun#2289]
Hello,

We faced some memory leak issues with scollector on Windows Server 2016.
Don't know exactly how to analyze the issue.
I have tried to WinDBG the Dump File of the process but I have not been able to extract usefull information.

Someone already faced the same problem ?

Regards.

**Comment by bobais** [comment]
We are facing similar issue when scollector slowly consumes huge amount of memory starting with 12 MB and after some time windows reports like 800 MB.
