### ISSUE TITLE
OpenTSDB write rate

### ISSUE THREAD

**Issue by mancubus77** [bosun-monitor/bosun#2307]
Hi Crew,
I use "batch" option, which chops metrics stream, but scollector sends batches over established connection and do not make pauses between transmissions. This makes HBase regional server suffer with high rate of incoming metrics.
I'm curious if scollector could write messages to OpenTSDB with **configurable rate** or change OpenTSDB host with every new batch for equal data distribution across OpenTSDB cluster.
Cheers

**Comment by kylebrandt** [comment]
I'm curious if you have been able to observe this behavior a little more carefully in terms what is going on when it gets the high rate of incoming metrics?

In particular, scollector will *queue* up metrics to a point when it can't send them, and then start sending them when it can. I've believe I have noticed some problems in my environment when this happens (a bunch of scollector queues drain). MaxQueueLen (or something like this) in the scollector config sets how large the queue can get.

**Comment by mancubus77** [comment]
On high rate I get following error message:
```
put: HBase error: Call queue is full on /0.0.0.0:16020, too many items queued ?
Caused by RPC: PutRequest(table="tsdb", key=[2, 0, 0, -114, 91, 62, 22, 80, 0, 0, 16, 0, 56, 100, 0, 0, 21, 0, 14, 107, 0, 0, 22, 0, 39, -6], family="t", qualifiers=[[0, 0]], values=["\x04"], timestamp=9223372036854775807, lockid=-1, durable=true, bufferable=false, attempt=2, region=RegionInfo(table="tsdb", region_name="tsdb,\x02\x00\x00\x81Z\xF4\xC0\xE0\x00\x00\x0F\x00'\xF8\x00\x00\x10\x00\\n\x00\x00\x11\x00\x01,1528689496201.587ecbcd990f938ec6c92b2b92b9b349.", stop_key=[3, 0, 0, -122, 90, -3, 26, 96, 0, 0, 15, 0, 39, -8, 0, 0, 16, 0, 66, 17]))
put: HBase error: Call queue is full on /0.0.0.0:16020, too many items queued ?
Caused by RPC: PutRequest(table="tsdb", key=[2, 0, 0, -114, 91, 62, 22, 80, 0, 0, 16, 0, 56, 107, 0, 0, 21, 0, 122, 60, 0, 0, 22, 0, 39, -6], family="t", qualifiers=[[0, 0]], values=["\x00"], timestamp=9223372036854775807, lockid=-1, durable=true, bufferable=false, attempt=2, region=RegionInfo(table="tsdb", region_name="tsdb,\x02\x00\x00\x81Z\xF4\xC0\xE0\x00\x00\x0F\x00'\xF8\x00\x00\x10\x00\\n\x00\x00\x11\x00\x01,1528689496201.587ecbcd990f938ec6c92b2b92b9b349.", stop_key=[3, 0, 0, -122, 90, -3, 26, 96, 0, 0, 15, 0, 39, -8, 0, 0, 16, 0, 66, 17]))
put: HBase error: Call queue is full on /0.0.0.0:16020, too many items queued ?
Caused by RPC: PutRequest(table="tsdb", key=[2, 0, 0, -114, 91, 62, 22, 80, 0, 0, 16, 0, 56, 110, 0, 0, 21, 0, 122, 61, 0, 0, 22, 0, 39, -6], family="t", qualifiers=[[0, 0]], values=["\x00"], timestamp=9223372036854775807, lockid=-1, durable=true, bufferable=false, attempt=2, region=RegionInfo(table="tsdb", region_name="tsdb,\x02\x00\x00\x81Z\xF4\xC0\xE0\x00\x00\x0F\x00'\xF8\x00\x00\x10\x00\\n\x00\x00\x11\x00\x01,1528689496201.587ecbcd990f938ec6c92b2b92b9b349.", stop_key=[3, 0, 0, -122, 90, -3, 26, 96, 0, 0, 15, 0, 39, -8, 0, 0, 16, 0, 66, 17]))
```
I have 7 regional servers and 190 regions and have no a hotspots because of HAProxy on front of OpenTSDB Cluster. 
Presumably a cause of issue is related to burst of metrics produced by custom collectors:
![image](https://user-images.githubusercontent.com/16170560/45468038-09935d80-b766-11e8-864a-3c6379443efd.png)

I've implemented rate function and backend rotation (surprisingly I haven't found it in OpenTSDB, therefore in most cases traffic hits one regional server) functions and testing them now. My goal is get flat write rate to OpenTSDB, and I believe it will resolve issues with error messages and puts less stress to OpenTSDB. 

I have another cluster with Redis+Tcollector, which performs much better:
![image](https://user-images.githubusercontent.com/16170560/45468275-211f1600-b767-11e8-8064-5bfc644a66de.png)

**Comment by johnewing1** [comment]
Do you have salting enabled in opentsdb ?

**Comment by mancubus77** [comment]
Sure
```
# Enable salting
tsd.storage.salt.width = 1
tsd.storage.salt.buckets = 20
```

**Comment by mancubus77** [comment]
Well, I've implemented rate limiting, it's better now and doesn't have spikes anymore.

**Comment by kylebrandt** [comment]
@mancubus77 can you share anything about what you did to get the rate
limiting in place?

**Comment by mancubus77** [comment]
@kylebrandt 
Sure mate
I made simple patch (this is a snippet only):
```
+++ b/collect/queue.go
@@ -78,13 +78,19 @@ func send() {
                        sending := queue[:i]
                        queue = queue[i:]
                        if Debug {
-                               slog.Infof("sending: %d, remaining: %d", i, len(queue))
+                               slog.Infof("sending: %d, remaining: %d, delay between transmissions: ", i, len(queue))
                        }
                        qlock.Unlock()
                        if DisableDefaultCollectors == false {
                                Sample("collect.post.batchsize", Tags, float64(len(sending)))
                        }
                        sendBatch(sending)
+                       if BatchSize == 1 {
+                               time.Sleep(time.Second / time.Duration(Rate))
+                               if Debug {
+                                       slog.Infof("Sleeping between transmissions for safe streaming")
+                               }
+                       }
```
This is not very efficient solution, because scollector uses HTML PUT mode, therefore it has an overhead. Nevertheless with this, streaming is smooth. Also I've added rotation parameter, which reset HTML session to hit next OpenTSDB server. I hope it will help someone in fighting with OpenTSDB.
