### ISSUE TITLE
It's been a long time sinece last beta release

### ISSUE THREAD

**Issue by seanlook** [bosun-monitor/bosun#2324]
Last release version 0.6.0-beta1 has been made in 2017-04-01. bosun has change a lot since that, like this that I met too: #2138 

I think the documentation is always updated, so I have encounted too much error when following the docs steps, like `bodyTemplate` is an unknow key in bosun_rule.conf.

Go build myself, but what about go version?

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/releases/tag/0.8.0-preview

Go version would be 1.11
