### ISSUE TITLE
Can't use ledis with 0.8-preview because of migrations

### ISSUE THREAD

**Issue by johnseekins** [bosun-monitor/bosun#2335]
Every time I restart bosun using the new 0.8 preview and a ledis backend (since we're just testing), Bosun refuses to start until I've deleted the `ledis_data` folder.

```
2018/10/18 18:47:19 info: main.go:297: Interrupt: closing down...
2018/10/18 18:47:19 info: alertRunner.go:85: Stopping alert routine for zfsarcstats
2018/10/18 18:47:19 info: alertRunner.go:85: Stopping alert routine for load
2018/10/18 18:47:19 info: main.go:299: done
root@use1-hadoop-5:~/bosun# ./bosun 
2018/10/18 18:47:27 enabling syslog
2018/10/18 18:47:27 info: migrate.go:137: checking migrations
2018/10/18 18:47:28 info: migrate.go:85: Adding fields for previous incidents and next incident on all incidents in order to link incidents together. This is a one time operation that can take several minutes.
2018/10/18 18:47:28 info: migrate.go:88: migrating 0 incidents
2018/10/18 18:47:28 fatal: main.go:153: state_data.go:287:  command not found
root@use1-hadoop-5:~/bosun# rm -rf ledis_data/
root@use1-hadoop-5:~/bosun# ./bosun 
2018/10/18 18:47:34 enabling syslog
2018/10/18 18:47:34 info: migrate.go:137: checking migrations
2018/10/18 18:47:34 info: migrate.go:149: schema version not found in db
2018/10/18 18:47:34 info: migrate.go:151: assuming new installation because allIncidents key not found
2018/10/18 18:47:34 info: migrate.go:152: writing current schema version
2018/10/18 18:47:34 info: search.go:194: Loading last datapoints from redis
2018/10/18 18:47:34 error: search.go:197: search_data.go:189: redigo: nil returned
2018/10/18 18:47:34 info: search.go:201: Done
```

**Comment by seanlook** [comment]
#2324 

I encounter the same issue when I build bosun myself and not resolved yet

**Comment by kylebrandt** [comment]
@johnseekins To be clear, does it only happen until you delete previous data from a previous version of Bosun. Or does it happen when you start with a fresh db, and then restart again?

**Comment by kylebrandt** [comment]
I think there are two levels of issues:
 1. Pretty sure I screwed up and should have incremented `SchemaVersion` https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/database/database.go#L22 need to think through the implications of this mess up.
 2. in the migrations we use a call (`getAllIncidentIdsByKeys`) uses the Redis `KEYS` command which isn't supported in redis. It would be better to use `SCAN` for redis anyways but the ledis implementation of this is different ( https://github.com/siddontang/ledisdb/issues/67 ) so need to make sure that is done right.

**Comment by johnseekins** [comment]
Sorry, yeah.

Startup #1 works and creates a ledis folder.

Startup #2+ fails until I delete the ledis folder.

**Comment by kylebrandt** [comment]
@johnseekins Yes that makes sense to me now. master branch has a fix for second start issue, however you still can't do migration with ledis. So upgrading a version with ledis still won't work correctly. However, if you clear the data it no longer will fail on the second startup

**Comment by johnseekins** [comment]
Works for me! I think your documentation even made it clear migrations would be dicey at best.

**Comment by kylebrandt** [comment]
updated docs in https://github.com/bosun-monitor/bosun/commit/ad59c1221712e2ff3cab4e7d8cbe9fa5220109cb
