### ISSUE TITLE
APM metrics possible?

### ISSUE THREAD

**Issue by VoidMonk** [bosun-monitor/bosun#2349]
Hi, I've spent a few hours playing with bosun and Grafana, and it's an awesome combo, so kudos to the bosun devs & community!

Now, I was wondering if it's possible for `scollector` to already or potentially collect APM-style metrics, like:

* .NET process CPU usage
* .NET process memory usage
* .NET process IO (disk read/write) usage
* IIS AppDomain response time
* IIS AppDomain throughput (requests per second)
* .NET exceptions (via CLR Profiling API or Windows Event Log, and Linux error log)

Please share an existing metric if any of this possible, or kindly suggest a suitable approach.

Thanks!

**Comment by voidmonk** [comment]
Regarding .NET exceptions, looks like it's possible to make an API call (on something like a global Application_Error event), but which [API](https://bosun.org/api) call is most suited if I want to collect this data each time:

* an error code (short string)
* an error description (long string)

And then be able to aggregate by error code (i.e. number of errors per hour with same code).

Any suggestions are appreciated!
