### ISSUE TITLE
Add exponential backoff for openTSDB

### ISSUE THREAD

**Issue by VartulAgrawal** [bosun-monitor/bosun#2355]
- Currently in case an openTSDB query fails it retries 3 times without any backoff. 
- **Impact of no backoff:** Since there is no backoff in case of issues with opentsdb this multiplies the traffic by 3, increasing the query volume significantly causing more issues due to overloading and making it harder for the service to recover.
- I am working on a PR to implement ExponentialBackoff with Jitter instead of the default 3 retries. I initially planned to use this library https://github.com/cenkalti/backoff to add backoff but the current implementation doesn't use jitters. Due to this I am planning to write a function myself that does so and can be potentially used at other places in the code as well. 
- Does that sound reasonable and would you be happy to merge a PR for this? Or do you recommend using some other library that already does this?

**Comment by neilfordyce** [comment]
Noticed that a random backoff was added recently https://github.com/huayl/bosun/pull/44/files
