### ISSUE TITLE
Is it possible to use some math facilities in Bosun expression?

### ISSUE THREAD

**Issue by psjay** [bosun-monitor/bosun#2356]
Eg: `PI`, `e`(natural constant) or trigonometric functions.

**Comment by captncraig** [comment]
Not currently, no. Do you have a real-world use case for such things?

**Comment by psjay** [comment]
> Not currently, no. Do you have a real-world use case for such things?

I recently tried to add some alters against my service, which methods are distinguished by tag in OpenTSDB. 

Different method has different QPS, alerts threshold of QPS change rate of higher QPS methods should be smaller than lower QPS methods, so I need trigonometric functions to write some algebra to solve this.
