### ISSUE TITLE
scollector: unmarshaling error with Varnish 

### ISSUE THREAD

**Issue by peterfroehlich** [bosun-monitor/bosun#2357]
After an Varnish update from 4.1 to 6.0.2 (new LTS version), the following is being reported from scollector: 
Dec 13 08:45:05 varnish04 scollector[3116]: error: varnish_unix.go:42: varnish parser error: VBE.boot.backend_prod.happy json: cannot unmarshal number 18446744073709551615 into Go struct field varnishStat.value of type int64
It seems that this is not due to the new version as the error popped up before (as a bit of digging has produced). But the error happen now multiple times a minute up from a few times per hour.

**Comment by johnewing1** [comment]
Are you still experiencing this issue ?

**Comment by peterfroehlich** [comment]
Yes. From right now:  
Feb 14 12:06:12 varnish04 scollector[84685]: error: varnish_unix.go:42: varnish parser error: VBE.reload_20200210_152216_109063.app_intern.happy json: cannot unmarshal number 18446744073709551615 into Go struct field varnishStat.value of type int64
