### ISSUE TITLE
can bosun support cluster?

### ISSUE THREAD

**Issue by MyZhang0826** [bosun-monitor/bosun#2360]
when bosun down, another bosun will replace it

**Comment by MyZhang0826** [comment]
why bosun rule need config in conf?, in some db is not ok?so we can use db cluster

**Comment by svagner** [comment]
There is exists pull request - https://github.com/bosun-monitor/bosun/pull/2345 But unfortunately it isn't merged yet:(

**Comment by johnewing1** [comment]
Duplicate of #2443
