### ISSUE TITLE
Split rules in multiple files

### ISSUE THREAD

**Issue by cindoum** [bosun-monitor/bosun#2364]
Hi,

I just want to propose a suggestion. When many rules are used, it quickly become hard to maintain the unique rules file (multiple alerts, multiple notifications, multiple templates etc...).

That would be awesome if we could give a folder which contains multiple rules files or just an array of files.

Thanks

**Comment by johnewing1** [comment]
Thanks for the feedback. We're looking at how to add this functionality.
