### ISSUE TITLE
Bosun version information missing

### ISSUE THREAD

**Issue by Zteve** [bosun-monitor/bosun#2372]
From the Bosun dashboard, there appears to be no means of obtaining a version number.  When reporting issues it would be nice to be able to reference the version being run.

I installed this to run on a local docker instance using: stackexchange/bosun:latest, and therefore have no idea what version I'm running.

Additionally, it would be good to be able to display the versions of the collectors being used by this instance of Bosun, but that may be harder to achieve.

**Comment by johnewing1** [comment]
You can get the version number by going to /api/version

**Comment by johnewing1** [comment]
Closing assuming above information was sufficient. If you need further help please re-open
