### ISSUE TITLE
several days ago, i receive the alert, and now it's normal, but it still send mail to me

### ISSUE THREAD

**Issue by BigFishhhh** [bosun-monitor/bosun#2379]
![image](https://user-images.githubusercontent.com/16998719/51449201-f6bd1500-1d65-11e9-815d-dbe31a0315e5.png)
![image](https://user-images.githubusercontent.com/16998719/51449214-089eb800-1d66-11e9-8030-ebbceb3d73be.png)

**Comment by jiangppp** [comment]
next关键词？
