### ISSUE TITLE
Emailing not working, how to debug?

### ISSUE THREAD

**Issue by tomaustin700** [bosun-monitor/bosun#2380]
Hi,
I have Bosun setup however I can't seem to get emailing to work, where can I look to get some logs showing the issue? My smtp server is office365 and this requires ssl to send however I'm not sure how to set this in the config file so I'm pretty sure that is my problem.

Thanks

**Comment by johnewing1** [comment]
Which version of bosun are you running ?

**Comment by tomaustin700** [comment]
@johnewing1 I am using 0.6 inside a docker container. Thanks.

**Comment by johnewing1** [comment]
If you got to the `Rule Editor` tab, select an alert which would send an email. Enter your email into the form and click the Test button it will trigger the handler to send the email.

In the logs for the docker container you will see an entry like this if there is an error


```

**Comment by tomaustin700** [comment]
@johnewing1 Where can I find the logs in the container? Sorry!

**Comment by johnewing1** [comment]
The logs are written to stdout and not to the container filesystem.  
If I run the container like this
`docker run -p8070:8070  stackexchange/bosun:0.6.0-pre`
I get the logs on the console.

If you've been running it as a daemonised service you can follow the logs by
`docker logs -f <containerid>`

**Comment by tomaustin700** [comment]
@johnewing1  Thanks. This is the error I get and it looks like it is what I suspected and office365 requires ssl. Is there anyway to use ssl emailing with Bosun?

2019/01/31 13:38:27 error: notify.go:116: failed to send alert uptime.allhosts{host=117c1473c187} to [tom.austin@****.com] 504 5.7.4 Unrecognized authentication type [LO2P123CA0003.GBRP123.PROD.OUTLOOK.COM]

**Comment by johnewing1** [comment]
I'm not 100% sure, would need to defer to the devs.
From a quick look at the smtp code it tries initially to connect using TLS, and sends a username and password if you've filled those in. If the remote server doesn't support TLS it then falls back to unauthenticated  smtp .

https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/conf/notify.go#L348

From  a brief google, it looks like office 365 does support TLS, but I'm not sure what you'd need to configure on the 365 end to give your bosun instance permission to send.
