### ISSUE TITLE
elasticsearch 7.X support

### ISSUE THREAD

**Issue by langerma** [bosun-monitor/bosun#2402]
not a bug but a feature request. i guess this would be a bigger change.

i tried to use es7 with esv6 configuration (as i used version 6 with the es5 switch back then)
but i receive **json: cannot unmarshal object into Go struct field SearchHits.total of type int64**

also annotation backend is not working with es 7 

i tried to add it and it seems to work #2403

**Comment by johnewing1** [comment]
Elastic 7 support was added via https://github.com/bosun-monitor/bosun/pull/2440 and is now in master
