### ISSUE TITLE
Remote trigger an alert?

### ISSUE THREAD

**Issue by kevallakhani** [bosun-monitor/bosun#2412]
Hi,

I have a use case where I would like to do analysis of my own with some statistics that I query from TSDB and then trigger a bosun alert based on the results. For example: say I have an anomaly detected on latency for a production page using time-series data from opentsdb, can I then use the bosun notification framework to notify and send an email in that case?

If not, is there a way we can automatically monitor a ton of metrics (lets say these metrics have the same name pattern) at the same time without having to create a config in the config file for each of these metrics?

Thanks.

**Comment by johnewing1** [comment]
Hi, could you give an example of the pattern the metrics would follow, in particular what the tags and metric name would look like. Thanks
