### ISSUE TITLE
release.sh on failure

### ISSUE THREAD

**Issue by zhifei92** [bosun-monitor/bosun#2420]
I want to pull requests, but ci is failed,I tried many times.  When i don't make any changes, still so.
errors:
2019/07/09 10:15:05 info: web.go:220: bosun web listening http on: :8070
validate.sh: line 79: kill: SIGTERM: invalid signal specification
2019/07/09 10:15:35 info: main.go:296: Interrupt: closing down...
2019/07/09 10:15:35 info: main.go:298: done
Failed to signal bosun to stop cleanly. Likely crashed before signal sent.
Failed to stop bosun cleanly. Exit code 124 (124=60s test timeout reached)

**Comment by KeepCaim** [comment]
@AlekSi Can you help me. I want to apply for a pr that is #2424

**Comment by captncraig** [comment]
The failure looks like the test that starts up bosun and shuts it down. My
guess is something you did in the close routine stopped bosun from cleanly
exiting on time.

**Comment by captncraig** [comment]
You can leave your pr open. We are behind on reviews at the moment, but
will take a look when we can.

**Comment by KeepCaim** [comment]
Thank you. We've used it in production environments, that is ok. But I'm not sure that's what you want.
