### ISSUE TITLE
crash while query /api/status

### ISSUE THREAD

**Issue by svagner** [bosun-monitor/bosun#2421]
Example of query:
GET /api/status?ak=some_alert%7Bsome_tag=tag%7D
`2019/07/09 13:06:15 http: panic serving 127.0.0.1:50093: runtime error: invalid memory address or nil pointer dereference
                                                              goroutine 53679 [running]:
                                                              net/http.(*conn).serve.func1(0xc00e3545a0)
                                                                      /usr/lib64/go/src/net/http/server.go:1769 +0x139
                                                              panic(0x122a760, 0x23055a0)
                                                                      /usr/lib64/go/src/runtime/panic.go:522 +0x1b5
                                                              bosun.org/cmd/bosun/web.Status(0x180ede0, 0xc012e607e0, 0x1801e80, 0xc00c592260, 0xc00c62a500, 0x40d509, 0xc00bbc3410, 0x30, 0x30)
                                                                      /builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/web/web.go:694 +0x397
                                                              bosun.org/cmd/bosun/web.JSON.func1(0x1801e80, 0xc00c592260, 0xc00c62a500)
                                                                      /builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/web/web.go:391 +0x90
                                                              net/http.HandlerFunc.ServeHTTP(0xc009c6b480, 0x1801e80, 0xc00c592260, 0xc00c62a500)
                                                                      /usr/lib64/go/src/net/http/server.go:1995 +0x44
                                                              bosun.org/vendor/github.com/captncraig/easyauth.(*authManager).Wrap.func1(0x1801e80, 0xc00c592260, 0xc00c62a500)
                                                                      /builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/vendor/github.com/captncraig/easyauth/auth.go:197 +0x2f8
                                                              net/http.HandlerFunc.ServeHTTP(0xc00b2fda40, 0x1801e80, 0xc00c592260, 0xc00c883e00)
                                                                      /usr/lib64/go/src/net/http/server.go:1995 +0x44
                                                              bosun.org/vendor/github.com/NYTimes/gziphandler.GzipHandler.func1(0x1801b40, 0xc012764540, 0xc00c883e00)
                                                                      /builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/vendor/github.com/NYTimes/gziphandler/gzip.go:71 +0x379
                                                              net/http.HandlerFunc.ServeHTTP(0xc009bfb560, 0x1801b40, 0xc012764540, 0xc00c883e00)
                                                                      /usr/lib64/go/src/net/http/server.go:1995 +0x44
                                                              bosun.org/cmd/bosun/web.glob..func2.1(0x1801b40, 0xc012764540, 0xc00c883e00)
                                                                      /builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/web/middlewares.go:42 +0x1f6
                                                              net/http.HandlerFunc.ServeHTTP(0xc009bfb5c0, 0x1801b40, 0xc012764540, 0xc00c883e00)
                                                                      /usr/lib64/go/src/net/http/server.go:1995 +0x44
                                                              bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.ContextHandler.ServeHTTP(0xc009bfb5e0, 0x1801b40, 0xc012764540, 0xc00c883d00)
                                                                      /builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/context.go:34 +0x19d
                                                              bosun.org/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00032afa0, 0x1801b40, 0xc012764540, 0xc00c883d00)
                                                                      /builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/vendor/github.com/gorilla/mux/mux.go:114 +0xdb
                                                              net/http.serverHandler.ServeHTTP(0xc0021c45b0, 0x1801b40, 0xc012764540, 0xc00c883200)
                                                                      /usr/lib64/go/src/net/http/server.go:2774 +0xa8
                                                              net/http.(*conn).serve(0xc00e3545a0, 0x1808a40, 0xc00c981ac0)
                                                                      /usr/lib64/go/src/net/http/server.go:1878 +0x851
                                                              created by net/http.(*Server).Serve
                                                                      /usr/lib64/go/src/net/http/server.go:2884 +0x2f4`

**Comment by muffix** [comment]
Fixed in #2422
