### ISSUE TITLE
ES 7.x support and go modules introduction

### ISSUE THREAD

**Issue by harudark** [bosun-monitor/bosun#2425]
I'd like to add ElasticSearch 7.x support in Bosun. However, ES v7 client(https://github.com/olivere/elastic) requires to use go modules.

I tried to use govendor to add ES v7 client but that would change files used by ES v6 client.
I also tried to use go modules and it works. But it looks like a big change for the project and I'm not sure about how upstream or other people think about it.

Do you have any suggestion about this? Thank you.

**Comment by johnewing1** [comment]
We've reworked the build to move to modules but we had to make a few other changes to the build steps so ended up doing so in our own PR. Would you mind rebasing #2427 from master so that it just represents the elastic changes. Thanks.

**Comment by harudark** [comment]
@johnewing1, thanks for taking care of Bosun. 👍 
I'll rebase and let you know when I've finished.

**Comment by johnewing1** [comment]
merged. Thanks for the contribution
