### ISSUE TITLE
Feature request: Clustering support

### ISSUE THREAD

**Issue by svagner** [bosun-monitor/bosun#2443]
# Short description
Currently, bosun doesn't support any ha and load distribution. We should provide something that will allow us to provide bosun as a high available and scalable service 

# How this feature will help you/your organisation
- Automatic failover then server with bosun became unavailable
- Avoid split-brain problem
- Distribute check execution between multiple servers 

# Possible solution or implementation details
One of working implementation - https://github.com/bosun-monitor/bosun/pull/2441

I offer to use raft clustering implementation from hashicorp.
Possible roundmap:
- [x] Create cluster for improving availability. Have a simple master-slave configuration. We can use silence/nochecks flags to make node as standby. This step without ant snapshots etc. Just simple standby.
- [ ] Add support for snapshot cluster state, rotate snapshots, recover the cluster state
- [ ] Host leader can distribute tasks for checks (by check name as instance) between nodes using consistent hashing distribution. In that step we can stop to use flags as the main instrument for manage nodes within the cluster

**Comment by svagner** [comment]
Related issues: https://github.com/bosun-monitor/bosun/issues/2360

**Comment by johnewing1** [comment]
Hi, thanks for this contribution 👍 
What's the minimum number of nodes needed for an HA solution ?
In the description you talk about a master slave solution, but my understanding was it would require at least 3 nodes for raft to tolerate the loss of a node and elect a new master.

**Comment by svagner** [comment]
Yes this is correct. We need at least 3 nodes. It will allow us in feature spread check load between the nodes. In that case leader will response to set the task to servers (I'm thinking about consistent hashing based on alarm name definition)

**Comment by johnewing1** [comment]
I've been thinking about this approach, and one thing that would need resolved is how updates to the alert definitions are handled.

Currently editing the rule definitions via the ui or api  and saving them to the local disk is supported. Without further work this would lead to the definitions being inconsistent in a multi node setup.

**Comment by svagner** [comment]
Yes. It definitely is. Currently, we are syncing configs while deployment. But I think I will add sync config over the cluster internally

**Comment by svagner** [comment]
> I've been thinking about this approach, and one thing that would need resolved is how updates to the alert definitions are handled.
> 
> Currently editing the rule definitions via the ui or api and saving them to the local disk is supported. Without further work this would lead to the definitions being inconsistent in a multi node setup.

I've created a new pull request with rule sync support and some improvement. We are using clustering from https://github.com/bosun-monitor/bosun/pull/2472 on production now and didn't notice any issue.

**Comment by langerma** [comment]
So no progress on this?

**Comment by svagner** [comment]
Looks like the community didn't want to support this cluster implementation and I stopped using bosun. Probably someone else will pick up care of clustering for bosun but not me anymore. Sorry
