### ISSUE TITLE
Bug: Unable to get data from Graphite

### ISSUE THREAD

**Issue by yoshi314** [bosun-monitor/bosun#2454]
# Expected behaviour

I expect to see graphite metrics in bosun web ui.

# Current behaviour

I see no metrics.

## Steps to reproduce

I started 0.6.0-pre on my docker installation, extracted the toml file, added graphitehost entries, and created new container with updated config.

## Context

```
docker run -d -p 4242:4242 -p 8070:8070  -v /home/mkowalski/docker_cfg/bosun/data/bosun.toml:/data/bosun.toml stackexchange/bosun:0.6.0-pre
```
There are no attempts from bosun to connect to graphite at all. Nothing in the logs on either end.

This is the toml file used : https://gist.github.com/yoshi314/cb48ce2114135004ca9fa8f693b91bab

**Comment by muffix** [comment]
Hi @yoshi314, this is running a very old version of Bosun (`v0.6.0-pre`). We're looking into publishing a newer version to DockerHub, but in the meantime, can you try to see if this issue still happens with the latest version?

**Comment by yoshi314** [comment]
The docs are pretty scarce as to how i build a new docker image. Any hints?

**Comment by muffix** [comment]
To test it out locally, you should be able to just use the existing Dockerfile: https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/docker/run/Dockerfile

**Comment by yoshi314** [comment]
Right now it breaks with 

```
curl: (6) Could not resolve host: central.maven.org
```

which seems to be down universally.

**Comment by muffix** [comment]
Yeah, Maven now requires HTTPS and changed the host. It's now at https://repo1.maven.org.

Presumably that's hard-coded somewhere, possibly in the old OpenTSDB build script.

**Comment by yoshi314** [comment]
I've fixed it and managed to build a working docker image, but there is no change with graphite. I'll do some more testing.

**Comment by johnewing1** [comment]
Can I clarify what the issue you are experiencing is ?
` I expect to see graphite metrics in bosun web ui.`
Are you running a query against graphite from the expression editor ?
If so do you get any error message when doing this ?

**Comment by yoshi314** [comment]
i expected to see graphite objects in the Items tab, but there is nothing there. That is how it used to work some time ago.

When i just use internal tsdb, it gets populated with bosun's stats.

**Comment by johnewing1** [comment]
My recollection is that the items tab only works for opentsdb metrics, and only with the setup where you stream the metrics through bosun's /api/put endpoint

This issue seems to support that
https://github.com/bosun-monitor/bosun/issues/2263
