### ISSUE TITLE
Clarify release status

### ISSUE THREAD

**Issue by ryantm** [bosun-monitor/bosun#2498]
We package this for NixOS, and we like to use the latest stable release from upstream.

https://github.com/bosun-monitor/bosun/releases/tag/0.8.0-preview is listed as the latest release on GitHub. Is it a stable release or should it be marked pre-release? I ask because it has the "-preview" suffix attached to it, making me think it is an unstable release.

**Comment by langerma** [comment]
for my freebsd port i am using the 0.9.0-preview and it is running stable in production for ages.

**Comment by breml** [comment]
It is really a shame, that this is no longer maintained and the maintenance status is completely unclear.

**Comment by amgorb** [comment]
yep, very nice project.

**Comment by ryantm** [comment]
Still an issue

**Comment by ryantm** [comment]
Still an issue.
