### ISSUE TITLE
ack links broken when weird chars are in them

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#256]
Ex: `http://ny-bosun01.ds.stackexchange.com/action?key=it.ping.packetloss{destination=ny-intbuild01,host=nyhq-intmon01}&type=ack` breaks after "destination", so on the `=`.

**Comment by kylebrandt** [comment]
I think we have this now, reopen if I am mistaken.

**Comment by azhurbilo** [comment]
we use  `[<{{.Ack}}|Acknowledge alert>]` in template 'subject'
and in notification block:

         body = payload={"username": "bosun", "text": {{.|json}}}

in result we get broken links in slack without encodings symbols

actual result:  

      http://mtrc01l1.root.company.com:8070/action?key=rabbitmq.errors{host=rbng01l1.root.company.com}&type=ack

expected result: 

      http://mtrc01l1.root.company.com:8070//action?type=ack&key=rabbitmq.errors%7Bhost%3Drbng01l1.company.root.com%7D
