### ISSUE TITLE
Add ability to reference numbers in templates as numbers

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#325]
For example, if in my template I have something like:

`$threshold = lookup("host_tresholds", "threshold)`

I would like to be able to access `.Alert.Vars.threshold` in the template in such a way that I can a comparison against it. (i.e. `gt $r.Value (.Eval $threshold)` or something like this.  This allows me to conditionally display things if they exceed the threshold.

**Comment by Dieterbe** [comment]
+1 this would be neat.

**Comment by melhesedek** [comment]
+1! Also it would allow one to get more informative notifications, for example: "Critical! Free space on Myhost: 2.17%" instead of "Critical! Free space on Myhost < 10%".

**Comment by kylebrandt** [comment]
I believe this is already fixed now - can do things like `{{x := .Eval .Alert.Vars.threshold}}` and X will be a float in master.

**Comment by melhesedek** [comment]
My bad, missed that part of the docs. `.Eval` works great, thanx.
Are there any reasons to keep this issue open?

**Comment by kylebrandt** [comment]
Not now thanks to your verification!
