### ISSUE TITLE
Auto refresh skips and stutters and is weird

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#366]
Something wrong with auto refresh.

**Comment by gbrayut** [comment]
I just noticed auto refresh appears to have stopped working all together. I tried chrome and IE and neither are updating the graph after checking the Auto Refresh box and running the query.

**Comment by tdinucci** [comment]
This doesn't work at all (Chrome).  Perhaps just remove the feature or fix and allow user to specify refresh rate, with default being 1m to avoid unnecessary server load
