### ISSUE TITLE
Make emailable reports in addition to alerts

### ISSUE THREAD

**Issue by PeterGrace** [bosun-monitor/bosun#372]
For some of my statistics, I would like to be able to make reports based on them.  In these situations it is tough to create an "alert" out of it because I simply want the data, it is not that I need to particularly action on any of it.

**Comment by kylebrandt** [comment]
These could be scheduled Alerts:

It would be useful to be able to specify alerts to run on a certain schedule outside of the normal schedule. Essentially this would enable Bosun to also act as a reporting system.

These could still be conditionally triggered such that it only send the "daily report" if something has been wrong. This would help reduce alert noise for things that naturally group and/or require notification - but not urgent notification.

Using the Go implementation of Cron might be useful considering it is something many system administrators are already familiar with.

**Comment by kylebrandt** [comment]
Additional implementation information:
 * I don't think these should be on the dashboard
 * You should still be able to work with them on the dashboard
 * An alert can't be both a normal alert *and* a scheduled alert. If you want this, just put the majority of an alert in a macro and define two alerts

**Comment by vaibhav376** [comment]
+1

**Comment by tdinucci** [comment]
Closing as this can be achieved by different means
