### ISSUE TITLE
Add Function to Sort Template Results

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#390]
i.e.

```
<table>
    	<tr><th>Redis Instance<th><th>Value</th></tr>
       {{ range $r := .EvalAll .Alert.Vars.by_port | SortGroup "port"}}
         <tr>
          <td>{{$r.Group.port}}</td>
       	  <td>{{$r.Value}}</td>
         </tr>
      {{ end }}
</table>
```

Or perhaps sort should change the order of the result set itself (like sort normally does in Go), i.e. a call to `{{$r.Sort "port"}}` multiple values could be "port,host" as the argument

**Comment by Dieterbe** [comment]
I don't really understand how `{{$r.Sort "port"}}` would work, but on @kylebrandt 's request a status update:
we now have the DescByValue function which sorts the actual resultslice in place:
`{{(.EvalAll .Alert.Vars.importance).DescByValue}}`. this still needs docs though..
so this is about sorting result arrays (slices), for sorting `[][]Result` (i.e. after LeftJoin) see #753
