### ISSUE TITLE
regression: desc metadata is appearing in the host metadata tab again

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#397]
The per metric desc metadata was removed earlier today, but now it is back in the host metadata tab. It was much cleaner without them.

**Comment by gbrayut** [comment]
I'm seeing desc metadata for hosts again... Mostly the client timing stuff, but there are others too. Example http://bosun.ds.stackexchange.com/host?host=ny-web05&time=1d-ago&tab=metadata

**Comment by kylebrandt** [comment]
Doesn't seem to be a problem anymore.
