### ISSUE TITLE
Store HBase data outside of docker

### ISSUE THREAD

**Issue by nornagon** [bosun-monitor/bosun#407]
The `stackexchange/bosun` docker image stores its hbase data inside the docker container. I'm collecting metrics which I'd like to keep forever -- is it possible to mount a docker volume and keep the hbase data outside of docker?

**Comment by kylebrandt** [comment]
Our docker image is really just for testing. Happy to accept contributions to improve it but don't want to track issues for it that are outside of the scope of testing.

**Comment by shauryaHSC** [comment]
Hi I am facing this issue right now, when i kill the docker container, and restart it. The data is lost. Even though I have mounted the data to the host file system.

Command I am using is : "docker run -d -v /hbase_final:/data/hbase -p 4242:4242 petergrace/opentsdb-docker"

please help
