### ISSUE TITLE
Bosun Web UI Fails Trying /api/query on 127.0.0.1:80

### ISSUE THREAD

**Issue by nickman** [bosun-monitor/bosun#416]
Installed bosun binary download on Linux Mint 15 Olivia (x86_64).
I already have OpenTSDB (2.0) and HBase (0.96.2) installed and working.
dev.conf is very simply:
```
tsdbHost=127.0.0.1
```
(Defaults to 4242, I assume...) When I bring up the web UI on http://localhost:8070, I can list the items without issue, but when I attempt to run a query, I get this message appended to the bottom of the UI:

```
opentsdb: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /api/query was not found on this server.</p> <hr> <address>Apache/2.2.22 (Ubuntu) Server at 127.0.0.1 Port 80</address> </body></html>
```

Can't figure out why it's trying to hit port 80. Docs don't indicate this is a default port, and so far as I can tell, I should be able to run with only the tsdbHost configured.

The bosun console output repeats this output every few seconds:

```
2014/11/24 06:24:11 info: queue.go:117: restored 250, sleeping 5s
2014/11/24 06:24:16 error: queue.go:97: 404 Not Found
2014/11/24 06:24:16 error: queue.go:103: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/put was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at localhost Port 8070</address>
</body></html>
2014/11/24 06:24:16 info: queue.go:117: restored 250, sleeping 5s
```

Looking for any suggestions on what might be the issue here.

Thanks.

**Comment by kylebrandt** [comment]
gzip got merged in

**Comment by vijayp1986** [comment]
I am facing same kind of issue, graph is not working for bosun's metrics. I created metrics and added data point in OpenTSDB using CLI (telnet). Graph for this metrics open's with datapoints, but if submit datapoint using bosun, then these data point does not appear in the graph.
I have installed standalone Bosun and OpenTSDB. I am stuck with the issue and not able to move ahead.
