### ISSUE TITLE
Metric Name Wildcards

### ISSUE THREAD

**Issue by bretcope** [bosun-monitor/bosun#419]
Talked about this with Jibson today...

Some metrics are really measuring the same thing, but with a different aggregator. The best example I can think of at Stack Exchange is the way we record response timings from HAProxy. We record `_95`, `_min`, `_max`, `_avg`, and `_median`. I quite often want to see max, avg, and 95th percentile on the same graph. I can currently do that, of course, by using the `+` button and adding more queries, but this is annoying because it's not just the metric name I have to type twice, it's all of the tag values I care about. Then, on the same graph, if I decide I want to look at those metrics, but with different tags, I have to go edit all of my 3-4 queries. It's _possible_, but tedious, error prone, and not enjoyable.

I'm working on a new Bosun [BosunReporter.NET](https://github.com/bretcope/BosunReporter.NET) library which, among many other things, will make it very easy to create gauges with multiple aggregators like that. My initial thought was that I could record the aggregator type as a tag so it would be easier to view on the graph page. I understood this meant if you didn't specify the aggregator tag for the graph then the data would be nonsensical, but Jibson won me over that it's a bad enough idea to not do. So I'll use suffixes instead.

However, this leaves me with the same problem as before - cumbersome to graph. We brainstormed a little bit about possible solutions, and it seemed like the best solution would be to support wildcard metric names (like wildcard tags) on the graph page. Behind the scenes, this would just be expanded into multiple queries.

We might also consider some restraints on this. At the very least, if it expands to more than x metrics, say it's invalid. Perhaps metadata has to be provided on all of the metrics which match the wildcard, and their type has to be the same, for the sake of sanity. Or provide some explicit way of defining metrics which are linked. These would just be ways to help people from misinterpreting data.

I'm open to other solutions which don't involve copy/paste. This just seemed the most reasonable to us at the time.

**Comment by kylebrandt** [comment]
Closing this as outside of Bosun's graphing scope. Likely integrating Grafana into bosun eventually and then we can bring this up again.
