### ISSUE TITLE
Config management

### ISSUE THREAD

**Issue by nornagon** [bosun-monitor/bosun#420]
I want to deploy bosun as a dashboard & alerting system within my organization, but I feel like having config management being completely external to bosun is a major drawback. It would be super fantastic if it were possible to, entirely through the web interface, define, test, and commit a new alert, or to update an existing alert to tweak the parameters.

Is anything like this in the works? How do you manage this in your existing deployments?

**Comment by Dieterbe** [comment]
what if we store all alerts and templates in a file for each? that way the rule editor's alert and template editors could literally correspond to files on disk, transmitted via the api, and stored in git. 1 file for each alert or template also seems a bit more manageable to me, although that's personal taste.

**Comment by kylebrandt** [comment]
I think we should treat multiple files and config management independtly. Multiple files might make it somewhat easier, but then people are forced into that pattern, and I don't think it would help that much. We could track file + line number when reading in the config to create diffs that you could edit and commit.

**Comment by captncraig** [comment]
I'm envisioning a pluggable system with a common interface to implement. The current state would be a flat file that is essentially read only. Another implementation could store it in a git repo in one or multiple files or whatever, and another could put it in boltdb or hbase or whatever.

**Comment by kylebrandt** [comment]
Step 1 is to make it so we can merge changes in the alert rule page into the config. Next would be how to save and manage changes on that - it might be better to leave that to the user. But the workflow from Rule Page -> Config test is the worst pain of this - so that needs to be priority 1

**Comment by marco-hoyer** [comment]
I like the idea of @captncraig to have a pluggable solution. Tried bosun the first time and think of it has a really new solution for the underestimated problem of alarming configuration. But the manual file management stuff really prevents adopting it. Ease of use as a key design goal should also be considered for this aspect.

**Comment by vitorboschi** [comment]
@marco-hoyer we have kinda worker around this problem in our deployment by using git. The config file resides in a repository, and there are server side hooks in place that:

1. Reject pushes containing any invalid config file
2. Deploys the config and restarts Bosun.

This way, it's really easy to change rules and at the same time keep a history of the rule changes and perform ACL

**Comment by jregovic** [comment]
I would like to be able to config via a web UI, that way I can have users without direct access to git or the server to make config updates. It also abstracts the format from the end goal of creating an alert. It also seems like having the entire configuration in a single file complicates the issue. In an enterprise setting, users won't necessarily have a lot of VCS knowledge, but may want to configure alerts.

I'd rather not have to restart the entire application to add an alert, that seems like behavior necessary only when changing a system level parameter, such as the TSDB config, mail server, or something like that.

**Comment by marco-hoyer** [comment]
I agree with @jregovic. A user friendly configuration system is what nearly all monitoring solution struggle with. I really like bosun for the idea of having a workflow from exploring data to alerting on them. This is awesome but stops at the middle with having to manually write a single config file. We have round about 200 people writing monitoring configuration. Doing this with a single file would fit our needs. I would really prefer to have a persistency layer like mysql or equal to store the monitoring configuration. This would help with a lot of concurrency issues. You could implement it in a copy-on-write way, where every configuration change creates a new configuration entity and bosun always uses the last one (with a cleanup job preserving the last 10 or so).

**Comment by mxk1235** [comment]
do you guys have a plan for this?  it's rather common to use sqlite3 as a persistent store in go applications for this sort of thing.  seems that if the app was able to load the db from config file, and then export current db contents to config file, it wouldn't be terrible for users.

**Comment by rickynils** [comment]
Whatever is decided here, I strongly hope the current declarative approach remains as an option. It's a perfect fit for configuration management, where I can simply generate alerts from my configuration model, instead of manually populating an sqlite database.

**Comment by krutaw** [comment]
From an automation and auditing perspective, I sincerely hope that maintaining a separate configuration management process remains an option.  I, personally, don't want a lot of people being able to apply changes to alerting without peer approval and that's something that I'm already designing into my Puppet workflow to manage Bosun.

If it does end up being "our way or the highway", then I sincerely hope that peer review and auditing of changes is built into the system.

**Comment by kylebrandt** [comment]
Not something I plan on us ever doing. Different companies use different config management workflows and I don't think this should be Bosun's job. 

I do hope one day we evolve the config and rules to be an interface in the code, so people could implement different ways to store their configuration, but that is different than having bosun take on config management.

We will be doing config reloading though (already have a branch that seems to work).
