### ISSUE TITLE
Error When Bosun Can't Index a Metric into Search Data

### ISSUE THREAD

**Issue by nickman** [bosun-monitor/bosun#421]
Version: bosun version 20141120204702 (bc4a2fce2d2bdb601b201df819571120907a0dd3)
Platform: Linux Mint x86_64
OpenTSDB 2.0.1 patched for GZipped Post Content Support
HBase: hbase-0.96.2

--------------------------------
I am using a custom data submitter which implements the OpenTSDB HTTP /api/put protocol. It is a groovy script I use for testing. It collects data using Sigar and posts formatted JSON. The script is submitting 329 metrics every 5 seconds, directly to Bosun port 8070. The script is available here:  https://gist.github.com/nickman/5d17b3efa16a068486f9. Depends on AsyncHTTPClient, org.json and HeliosSigar (I will post the JAR if it is useful).

All of the submitted metrics are ingested by OpenTSDB (and visible in OpenTSDB's UI) so the relaying is working correctly, but some number of metrics never appear in Bosun's UI.

Example of metrics that do **not** appear in Bosun:

```
{
 "metric": "sys.cpu",
 "tags": {
  "cpu": 0,
  "type": "combined"
 },
 "timestamp": 1416911037,
 "value": 4.25531914893617
},
{
 "metric": "sys.cpu",
 "tags": {
  "cpu": 0,
  "type": "idle"
 },
 "timestamp": 1416911037,
 "value": 95.74468085106383
},
{
 "metric": "sys.cpu",
 "tags": {
  "cpu": 0,
  "type": "irq"
 },
 "timestamp": 1416911037,
 "value": 0
}
```

Examples of metrics that **do** appear in Bosun:

```
{
 "metric": "sys.fs.queue",
 "tags": {
  "name": "/boot",
  "type": "ext2"
 },
 "timestamp": 1416912036,
 "value": 1.961757960524923
},
{
 "metric": "sys.fs.files",
 "tags": {
  "name": "/boot",
  "type": "ext2"
 },
 "timestamp": 1416912036,
 "value": 124496
},
{
 "metric": "sys.fs.free",
 "tags": {
  "name": "/boot",
  "type": "ext2"
 },
 "timestamp": 1416912036,
 "value": 156487
}

```

I don't think there are any unique attributes to the missing metrics, although it seems as though the same metrics are missing regardless of how many times I run the test.

One aspect that I noted in earlier tests was that for large-ish HTTP posts, OpenTSDB was throwing errors until I enabled http chunking and set a maximum chunk size of 81920:

tsd.http.request.enable_chunked = true
tsd.http.request.max_chunk = 81920

but after that, I had no issues and was able to verify 100% receipt of Bosun submitted metrics in the OpenTSDB instance.

OpenTSDB UI for **sys.cpu** metrics:

![image](https://cloud.githubusercontent.com/assets/597608/5181727/3809f3b8-7467-11e4-8738-81496418c786.png)

Bosun UI Items:  (note, no **sys.cpu**)

![image](https://cloud.githubusercontent.com/assets/597608/5181740/5ebd723c-7467-11e4-8559-6cca5e095e11.png)

I don't think there are any naming convention issues with the missing metrics, but is it safe to assume that any metric structure supported by OpenTSDB should be expected to be supported by Bosun ?

Thanks.
//Nicholas

**Comment by kylebrandt** [comment]
Closing this unless someone confirms this is still an issue since search indexing has been largely refactored with the move to redis
