### ISSUE TITLE
Short Link does not update if you've already clicked it once and then re-submitted changes to the page

### ISSUE THREAD

**Issue by PeterGrace** [bosun-monitor/bosun#436]
Reproduce:

- Click "Short Link" on an expression, rule, graph.
- Change said expression, rule, graph.
- Short Link will not update, nor will it revert to a clickable button.  One must refresh the page to get a new short link.

**Comment by kylebrandt** [comment]
It seems the link is cleared if I run another query, so this must have been fixed at some point.
