### ISSUE TITLE
Windows should log to its own log instead of Application

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#568]
<a href="https://github.com/mjibson"><img src="https://avatars.githubusercontent.com/u/41181?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjibson](https://github.com/mjibson)**
_Monday May 19, 2014 at 21:26 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/16_

---

The `Windows Logs / Application` part of the event viewer is filled with scollector info. scollector should have its own place in the `Applications and Services Logs` tree. I've tried changing service_windows.go to use:

```
eventlog.Install(name, "%SystemRoot%\\System32\\Winevt\\Logs\\Scollector.evtx", eventlog.Error|eventlog.Warning|eventlog.Info)
```

and also `"C:\\scollector.exe"` as the second argument, but neither created a new log file as hoped. The service was stopped, removed, installed, and started for these, while an admin. Settings changed in the registry. Not sure why it didn't make the file.

**Comment by tdinucci** [comment]
If people are still bothered by this we can reopen, Windows server share is diminishing across industry
