### ISSUE TITLE
Auto deduplication

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#569]
<a href="https://github.com/mjibson"><img src="https://avatars.githubusercontent.com/u/41181?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjibson](https://github.com/mjibson)**
_Friday Jul 18, 2014 at 18:20 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/43_

----

**Comment by kylebrandt** [comment]
Actually don't want this feature. This is because a duplicate observation is still an observation, and reduplicating means we might lose information we want.
