### ISSUE TITLE
collect should support metadata

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#570]
<a href="https://github.com/kylebrandt"><img src="https://avatars.githubusercontent.com/u/1692624?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kylebrandt](https://github.com/kylebrandt)**
_Saturday Jul 19, 2014 at 16:11 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/47_

----

Add, Set, and Put should support metadata arguments

**Comment by kylebrandt** [comment]
Instead of doing this we just use the metadata library instead. This is better because we can just declare constants at the top.
