### ISSUE TITLE
vSphere collection requests: old snapshots, host time sync

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#571]
<a href="https://github.com/shanemadden"><img src="https://avatars.githubusercontent.com/u/3057436?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shanemadden](https://github.com/shanemadden)**
_Tuesday Aug 05, 2014 at 15:42 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/57_

----

Add metrics for a couple of items within vSphere that can be problematic when in a bad state and ignored:

VM snapshots

Monitor the snapshot status of VMs in inventory.  Not sure what this looks like in the API, but ideally, a metric for snapshot count and a metric for age of oldest snapshot if there is one.

Host time sync

Monitor the status of VM host time synchronization.  Ideally monitoring service state (stopped or running) and the number of seconds the host time differs from the time of the host running scollector.

**Comment by kylebrandt** [comment]
not going to work on this anytime soon
