### ISSUE TITLE
collect needs functionality to support programs that don't run continuously 

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#572]
<a href="https://github.com/kylebrandt"><img src="https://avatars.githubusercontent.com/u/1692624?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kylebrandt](https://github.com/kylebrandt)**
_Thursday Aug 07, 2014 at 12:28 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/58_

---

I have a program that is run by cron every half over. I believe collect is currently designed to only support programs that are continuously running. 

What I'd like to be able to do is have some sort of flush/send functionality that will allow sending before exit (or perhaps a wait).

**Comment by tdinucci** [comment]
Closing as other ways to do this
