### ISSUE TITLE
Ability to add metadata to external collectors

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#573]
<a href="https://github.com/PeterGrace"><img src="https://avatars.githubusercontent.com/u/967365?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PeterGrace](https://github.com/PeterGrace)**
_Tuesday Sep 16, 2014 at 13:15 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/61_

----

I would really like to be able to specify metadata for some of my external checks.  Can some sort of interface be added which would allow me to set metadata for custom metrics?

**Comment by gbrayut** [comment]
I've had this come up as an issue a few times in the past week so I wanted to bump it to give it some better visibility. Especially now that we show metadata on the graph page, external collectors should be able to submit metadata just like regular collectors.

**Comment by kylebrandt** [comment]
done http://bosun.org/scollector/external-collectors
