### ISSUE TITLE
Http check

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#574]
<a href="https://github.com/kylebrandt"><img src="https://avatars.githubusercontent.com/u/1692624?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kylebrandt](https://github.com/kylebrandt)**
_Monday Oct 06, 2014 at 16:24 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/pull/68_

----

----

_**[kylebrandt](https://github.com/kylebrandt)** included the following code: https://github.com/bosun-monitor/scollector/pull/68/commits_

**Comment by kylebrandt** [comment]
So old it would just be time to start from scratch.
