### ISSUE TITLE
os.* meta labels not created for MacOS X

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#576]
<a href="https://github.com/tlimoncelli"><img src="https://avatars.githubusercontent.com/u/6293917?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tlimoncelli](https://github.com/tlimoncelli)**
_Monday Oct 13, 2014 at 16:01 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/77_

----

Sad Mac Face

**Comment by kylebrandt** [comment]
Don't care enough to track this.
