### ISSUE TITLE
linux.disk.fs.* skips file systems with whitespace in their mountpoint name

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#577]
<a href="https://github.com/tlimoncelli"><img src="https://avatars.githubusercontent.com/u/6293917?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tlimoncelli](https://github.com/tlimoncelli)**
_Monday Oct 13, 2014 at 21:10 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/78_

----

Because Dennis Ritchie didn't own a Mac.

**Comment by kylebrandt** [comment]
Closing until someone else cares
