### ISSUE TITLE
vsphere monitoring fail

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#578]
<a href="https://github.com/PeterGrace"><img src="https://avatars.githubusercontent.com/u/967365?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PeterGrace](https://github.com/PeterGrace)**
_Wednesday Oct 15, 2014 at 13:20 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/81_

----

interval.go:53: vsphere-lon-vm01.ds.stackexchange.com: vsphere: no UUID during connect

**Comment by jkcouch** [comment]
Matt - Yes,this is still happening. Tried with known good passwords, and known bad passwords. Both return the same error. I have tried on ESXi 5.5 u2 and ESXi 5.0 u3. 

c:\scollector>scollector-windows-amd64.exe -v root:#####@xxxxx.xxx.com
2015/03/05 10:17:05 info: main.go:236: OpenTSDB host: http://xxxxx:4242
2015/03/05 10:17:05 error: interval.go:53: vsphere-xxxxx.xxx.com: vsphere: no UUID
during connect

c:\scollector>scollector-windows-amd64.exe -version
scollector version 20150220180110 (1b01fb0a96425d225a00f8a741c8b7911f3ad953)

**Comment by bizhao** [comment]
Met same issue with ESXi 5.5.

./scollector-linux-amd64 -f vsphere -p
...
2015/11/13 07:52:33 error: interval.go:62: vsphere-10.111.90.38: vsphere: no UUID during connect

**Comment by pvitty** [comment]
Old issue, but has there been any movement on this?

**Comment by simnv** [comment]
@pvitty I think it is resolved in #1611 and is in RC1 already.

You can also check #1644, it is a enhanced performance counters support for ESX and VMs.

**Comment by pvitty** [comment]
@simnv You are correct. I was using it wrong. I had it configured to point directly to an ESXi hypervisor rather than a vCenter instance. Perhaps an update to the documentation would be useful?
