### ISSUE TITLE
scollector should prevent running multiple versions on the same system

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#584]
<a href="https://github.com/gbrayut"><img src="https://avatars.githubusercontent.com/u/304401?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gbrayut](https://github.com/gbrayut)**
_Tuesday Nov 11, 2014 at 20:10 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/120_

----

A few times now I have run multiple instances of scollector.exe on the same system at the same time. This causes issues as it reports the data twice. 

Scollector should check to see if another version of the process is already running and if so it should exit with an error message.

**Comment by kylebrandt** [comment]
Running multiple instances should be valid at least in the case of sending to different hosts.

**Comment by kylebrandt** [comment]
Closing - don't agree. People should be able to run multiple instances if they want to, and this other parts of the OS provide this (i.e. systemd)
