### ISSUE TITLE
linux: scollector doesn't show keepalived IP addresses

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#585]
<a href="https://github.com/NickCraver"><img src="https://avatars.githubusercontent.com/u/454813?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NickCraver](https://github.com/NickCraver)**
_Wednesday Nov 12, 2014 at 00:04 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/122_

----

Currently scollector uses `ifconfig` to pull IPs but doesn't include things like keepalived IP addresses. For example on or-lb01 it's showing 1 IP address when it owns over 30. I am unsure if this applies to DHCP interfaces as well.

**Comment by kylebrandt** [comment]
Not sure when this was fixed but the IPs are there now.
