### ISSUE TITLE
Windows scollector Client Panics

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#587]
<a href="https://github.com/dalehhirt"><img src="https://avatars.githubusercontent.com/u/2246127?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dalehhirt](https://github.com/dalehhirt)**
_Wednesday Nov 12, 2014 at 20:06 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/125_

----

I'm having a hard time understanding what the stack trace is saying here.  Any help is appreciated.  This is running on Windows 8.1:

C:\Users\dalehirt\Documents\GitHub\scollector\tmp>scollector-windows-amd64.exe -h=http://192.168.59.103:8070/
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x79bf20, 0x9ff10f)
        c:/go/src/pkg/runtime/panic.c:279 +0x11f
code.google.com/p/winsvc/svc.IsAnInteractiveSession(0x7e0700, 0x0, 0x0)
        C:/Users/dalehirt/.go/src/code.google.com/p/winsvc/svc/security.go:82 +0x3a1
main.win_service_main()
        C:/Users/dalehirt/Documents/GitHub/scollector/service_windows.go:35 +0xaa
main.main()
        C:/Users/dalehirt/Documents/GitHub/scollector/main.go:122 +0x1cb

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        c:/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        c:/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        c:/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
        c:/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init┬╖1
        c:/go/src/pkg/os/signal/signal_unix.go:27 +0x39

goroutine 21 [runnable]:
github.com/mjibson/snmp.func┬╖003()
        C:/Users/dalehirt/.go/src/github.com/mjibson/snmp/snmp.go:417
created by github.com/mjibson/snmp.init┬╖1
        C:/Users/dalehirt/.go/src/github.com/mjibson/snmp/snmp.go:421 +0x6f

goroutine 22 [runnable]:
github.com/bosun-monitor/scollector/collectors.func┬╖001()
        C:/Users/dalehirt/.go/src/github.com/bosun-monitor/scollector/collectors/collectors.go:62
created by github.com/bosun-monitor/scollector/collectors.init┬╖1
        C:/Users/dalehirt/.go/src/github.com/bosun-monitor/scollector/collectors/collectors.go:68 +0x29

**Comment by kylebrandt** [comment]
Old, assuming no longer an issue for now
