### ISSUE TITLE
linux interface collector needs better metadata

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#589]
<a href="https://github.com/mjibson"><img src="https://avatars.githubusercontent.com/u/41181?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjibson](https://github.com/mjibson)**
_Wednesday Nov 12, 2014 at 23:58 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/127_

----

**Comment by kylebrandt** [comment]
Too Vauge
