### ISSUE TITLE
Set hostname explicitly

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#594]
<a href="https://github.com/lukaspustina"><img src="https://avatars.githubusercontent.com/u/398967?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lukaspustina](https://github.com/lukaspustina)**
_Wednesday Nov 26, 2014 at 13:30 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/152_

----

As far as I understand scollector, the hostname is set by asking the OS for the hostname. I would appreciate a parameter to explicitly set the hostname in order to control the host and domain part.

For example, while the hostname might be `host1.at.my.subdomina.my.organization.internal` it seems more useful to set the scollector host tag to something like `host1.at.my.subdomain` only.

**Comment by lukaspustina** [comment]
I compiled scollector from source yesterday and I'm using `-hostname` to set the hostname. This works for all metrics, but `scollector.*` metrics which still seem to transmit just the /etc/hostname.
Any ideas?

**Comment by mjibson** [comment]
That sounds like a bug.

**Comment by kylebrandt** [comment]
scollector.* metrics which still seem to transmit just the /etc/hostname - related is that the filters `-f` don't apply to these either.

**Comment by gbrayut** [comment]
self metrics have a different flag to disable:

-m=false: Disable sending of metadata.
-n=false: Disable sending of scollector self metrics.

**Comment by captncraig** [comment]
I agree, I don't think there is a significant advantage to filtering scollector metrics beyond on/off

**Comment by kylebrandt** [comment]
Agreed. Hostname still needs to be set the same for both though.

**Comment by kylebrandt** [comment]
Fixed in #594
