### ISSUE TITLE
scollector metrics from the collect package do not get added tags

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#597]
<a href="https://github.com/kylebrandt"><img src="https://avatars.githubusercontent.com/u/1692624?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kylebrandt](https://github.com/kylebrandt)**
_Tuesday Dec 02, 2014 at 14:08 GMT_
_Originally opened as https://github.com/bosun-monitor/scollector/issues/159_

---

When adding tags from the command line or conf, the collect metrics don't get the tags:

```
2014/12/02 09:07:28 info: queue.go:66: {"metric":"scollector.collect.goroutines","timestamp":1417529247,"value":64,"tags":{"host":"grove"}}
2014/12/02 09:07:28 info: queue.go:66: {"metric":"darwin.disk.fs.total","timestamp":1417529247,"value":487712924,"tags":{"cat":"meow","host":"grove","mount":"/"}}
2014/12/02 09:07:28 info: queue.go:66: {"metric":"darwin.disk.fs.used","timestamp":1417529247,"value":208095692,"tags":{"cat":"meow","host":"grove","mount":"/"}}
```

**Comment by tdinucci** [comment]
This no longer appears to be an issue
