### ISSUE TITLE
Silence Didn't Work

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#607]
The following alert triggered: 

http://goo.gl/r8HDgZ

![image](https://cloud.githubusercontent.com/assets/1692624/5396951/1e511fae-8124-11e4-86bd-6837c59dcef8.png)

Even though there was an active silence for this:

![image](https://cloud.githubusercontent.com/assets/1692624/5396963/3531b04e-8124-11e4-8af9-8e8d68468e16.png)

**Comment by lukaspustina** [comment]
@kylebrandt We're running a self compiled Bosun -- pulled this morning 451c58823c9b9ffa22f3dec63f1b36c0d1803a6a.

I'm seeing emails notifications being generated for already acknowledged alerts. That might be related. I'm happy to send you more information, if helpful.

**Comment by kylebrandt** [comment]
@lukaspustina: You should get another email for acknowledge alert if there is a state increase ( http://bosun.org/documentation.html#severity-states ).

And can you look at the history for one of the alerts that is doing this, you get to history via a dashboard panel:

![image](https://cloud.githubusercontent.com/assets/1692624/6148800/449a7c3a-b1d2-11e4-8f7c-721addde93d4.png)

And it will look something like this:
![image](https://cloud.githubusercontent.com/assets/1692624/6148809/535000b0-b1d2-11e4-9a59-b2f75b577ec8.png)

**Comment by lukaspustina** [comment]
No, neither severity nor state changed -- see history screenshot.
![screen shot 2015-02-11 at 15 56 27](https://cloud.githubusercontent.com/assets/398967/6149106/b5a87092-b206-11e4-93c5-baf14365749b.png)
![screen shot 2015-02-11 at 15 56 45](https://cloud.githubusercontent.com/assets/398967/6149107/b5c9a500-b206-11e4-9d58-e0e4a45e5330.png)

**Comment by kylebrandt** [comment]
@lukaspustina : Do you have any notification chains set up?

**Comment by lukaspustina** [comment]
Yes, a tiny one:

```
notification default {
  email = hidden@secrect.net
  next = default
  timeout = 6h
}
```

**Comment by kylebrandt** [comment]
Did you do any restarts of bosun during this 6 hour period?

**Comment by lukaspustina** [comment]
Unfortunately, no.

**Comment by kylebrandt** [comment]
@lukaspustina Can't repro, I tested with a short timeout and kept getting emails until I ack'd the alert. Have you been using Bosun for a while? If you have I wonder if deleting your state file will fix this.

**Comment by lukaspustina** [comment]
@kylebrandt So I deleted the state file and had no luck. Still the same behavior. So I tried to silence the alarms at least which also had no effect. Alarm notification emails keep coming.
Any ideas?

**Comment by lukaspustina** [comment]
@kylebrandt I restarted all of bosun components including OpenTSDB etc. and that seemed to have fixed the problem.

**Comment by kylebrandt** [comment]
Oh good to know, sorry for forgetting to respond to your last comment

**Comment by kylebrandt** [comment]
Assuming silence bug isn't real - haven't noticed any issues in a long time.
