### ISSUE TITLE
Ability to filter items included in graphs without grouping them

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#612]
This is something both Tom and I have run into so far, where sometimes you want to limit which hosts (or other tags) are included but still aggregate the data to a single result. Right now you can use host=ny-lb03|ny-lb04 to view metrics (linux.net.conntrack.count for example) for just those systems, but the graph will still break down the result between the two servers. Since they are a cluster, we sometimes don't don't care about the individual break down, but instead just want to see the total for those two servers. This is similar to why tsql supports both a 'where' statement (pre aggregate filtering) and a 'having' statement (post aggregate filtering) when doing a group by.

Not sure how easy this is to create, but from a UI perspective you could reuse the current tag boxes and just change the syntax a bit. For example:

host=filter(ny-lb03|ny-lb04) would return data only for just those two hosts but still aggregate them to one line on the graph

host=filter(ny-web*) would also be one graph of all the ny-web servers as an aggregate

This could also be used on other tags ( svcname or application for example) when you only care about a few of the available options. I can even see a use for something like filter(...),* which does a pre-aggregate filter (aka only these two tags) then displays individual results:

metric: exceptional.exceptions.count
application: filter(Core|APIv2),* //Meaning filter to just core and api, but then break out individual stats
machine: filter(ny-web10,ny-web11) //only dev tier servers

as it stand right now you can probably do this with an expression, but having the ability to filter the results would make the graph page more powerful

**Comment by gbrayut** [comment]
This is added in opentdsb 2.2 by setting groupBy to false. See https://github.com/OpenTSDB/opentsdb/issues/546

Support for this in bosun is currently under development at https://github.com/bosun-monitor/bosun/tree/OpenTSDB_2_2 which would allow an expression like

q("sum:rate:os.cpu{}{host=wildcard(ny-web*)}", "1h", "")

The first {} is groupby, the second {} is a non-groupby filter. See http://opentsdb.net/docs/build/html/user_guide/query/filters.html for the new filters in 2.2

**Comment by kylebrandt** [comment]
implemented in bosun now using opentsdb's filters
