### ISSUE TITLE
items in *normal* state classified as unknown and needing acknowledgement

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#622]
right after starting, all these checks become normal, yet they show up as normal and needing ack.
why? looks like a bug?

![normal-ack](https://cloud.githubusercontent.com/assets/20774/5511422/59be0642-879b-11e4-9bfd-361ebd81974e.png)

**Comment by kylebrandt** [comment]
@Dieterbe Can you let me know if this is still an issue?

**Comment by Dieterbe** [comment]
i have no idea. someone will need to reopen if so.
