### ISSUE TITLE
We wish add user auth system.

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#624]
:)

**Comment by elementai** [comment]
@wkshare Bosun is easily composable, for web access one can use any proxy with http basic auth support plus optional SSL. As for managing configuration - just use, for example, Gitlab repo and post-commit hook to update bosun.cfg and restart daemon.

**Comment by wkshare** [comment]
@elementai we used cas.

**Comment by tdinucci** [comment]
Closing as no detail and we will be covering in separate ticket
