### ISSUE TITLE
Could the Docker container for bosun have a text editor in it?

### ISSUE THREAD

**Issue by cwhittl** [bosun-monitor/bosun#625]
I cannot find out how to get any kind of editor to install in my bosun container.  I am trying to follow the Quick Start but without an editor I can't edit the bosun.conf file.

I'm new to docker and trying to figure it out but so far I can't. 

I tried >> to the file the changes but when I restarted the container it failed and I had to revert to the backup I made.

**Comment by moubry** [comment]
This should be in the Quick Start documentation.

**Comment by gbrayut** [comment]
I plan creating a new docker page at some point and will make sure these details get in there
