### ISSUE TITLE
"Eval: expected string or expression" error to vague

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#634]
in a template,
```
{{.Eval .Alert.Vars.some_var_that_does_not_exist}}
```
results in:
```

template: generic:1:93: executing "generic" at <.Eval>: error calling Eval: expected string or expression, got <nil> (<nil>)
```

would be nice if it mentioned that the variable name is `some_var_that_does_not_exist`

**Comment by kylebrandt** [comment]
Closing because I think it is "clear enough" for the current laundry list - will wait for someone to reopen the same issue.

**Comment by rahul8590** [comment]
I intermittently face this issue with bosun with following message 
`<.Eval>: error calling Eval: no results returned` 
It ll be convenient to have specific errors.

**Comment by efficks** [comment]
Same problem here. I need to find this issue to correctly understand what's going on.
