### ISSUE TITLE
Variable expansion can be misleading, so should auto-add parens

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#639]
Consider:

```
$a = $b / $c
$d = $a > 1
```

This actually does `$b / ($c > 1)` due to operator precedence rules, but that's not obvious from the variable replacement.

Proposal: for variables that are valid expressions and binary nodes (i.e., two arguments and an operator), bosun should auto-add parens around them.

**Comment by Dieterbe** [comment]
dup of #635? :)

**Comment by kylebrandt** [comment]
Dupe of #635
