### ISSUE TITLE
usb_fiq error on ARM

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#647]
`<179>Jan  9 20:49:15 localhost /opt/scollector/scollector[2433] error: interval.go:53: bosun.org/cmd/scollector/collectors.c_procstats_linux: interrupts: unexpected value: usb_fiq,interval.go:53: bosun.org/cmd/scollector/collectors.c_procstats_linux: interrupts: unexpected value: usb_fiq`

**Comment by PeterGrace** [comment]
/proc/interrupts from a raspberry pi

$ cat /proc/interrupts
           CPU0       
  3:     119269   ARMCTRL  BCM2708 Timer Tick
 16:          0   ARMCTRL  bcm2708_fb dma
 32:     132561   ARMCTRL  dwc_otg, dwc_otg_pcd, dwc_otg_hcd:usb1
 52:          0   ARMCTRL  BCM2708 GPIO catchall handler
 65:        337   ARMCTRL  ARM Mailbox IRQ
 66:          1   ARMCTRL  VCHIQ doorbell
 75:          1   ARMCTRL
 77:      22825   ARMCTRL  bcm2708_sdhci (dma)
 79:          0   ARMCTRL  bcm2708_i2c.1
 80:          0   ARMCTRL  bcm2708_spi.0
 83:          6   ARMCTRL
 84:      31039   ARMCTRL  mmc0
FIQ:              usb_fiq
Err:          0
