### ISSUE TITLE
Results/Template/Timeline should be marked as stale while new test is running

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#653]
1) on rule page, run a test
2) results/template/timelines appear
3) change the rule/template/date-range/etc and hit test button again.

=> stale results stay visible.  would be nice if the background could be made gray or something, so you can keep looking at results but it's more obvious they are out of date.

**Comment by kylebrandt** [comment]
There is a "running..." bar and a the Bosun logo will be animated when a request is running. Given the general level of the UI, considering this to be a strong enough signal.  Would accept a PR that does something more though if someone wants to submit one.
