### ISSUE TITLE
Bosun should have a default unknown Template

### ISSUE THREAD

**Issue by ryan1234** [bosun-monitor/bosun#655]
I'm not sure where to look to help debug the issue, but from time to time I get "phantom" email notifications. The subject is empty and the body is empty. 

I currently have only one alert setup. See my config below. 

The interesting note is that they seem to be spaced by about one hour. One at 5:46AM, 6:38AM, 7:36AM, 8:38AM. Then again maybe not so interesting as that is my alert interval. =)

```
tsdbHost = localhost:4242
smtpHost = <removed>
smtpUsername = <removed>
smtpPassword = <removed>
emailFrom = <removed>

template test {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Alert: {{.Alert.Name}} triggered on {{.Group.host}}
	<hr>
	<p><strong>Computation</strong>
	<table>
		{{range .Computations}}
			<tr><td><a href="{{$.Expr .Text}}">{{.Text}}</a></td><td>{{.Value}}</td></tr>
		{{end}}
	</table>
	<hr>
	{{ .Graph .Alert.Vars.metric }}
	<hr>
	<p><strong>Relevant Tags</strong>
	<table>
		{{range $k, $v := .Group}}
			<tr><td>{{$k}}</td><td>{{$v}}</td></tr>
		{{end}}
	</table>`
}

notification default {
	email = <removed>
	next = default
	timeout = 1h
}

alert api.high.bandwidth {
	template = test
	critNotification = default	
	warnNotification = default		
	$metric = q("sum:rate{counter,,1}:os.net.bytes{host=saddleback-api-*}", "1h", "")
	$max = max($metric)
	crit = $max > 5000000
	warn = $max > 2000000
}
```

**Comment by mjibson** [comment]
What version of bosun are you using? You are getting emails each hour perhaps because of the `timeout = 1h` which will continue to send an email until the given alert is acknowledged. The template is blank probably because there's some error during template computation. Using the newest docker image should email you a template with details about the template processing error. If that's not the case, then I'm not sure. Is it possible it's a problem with your email provider? Use the rule page, where you can enter in a email address, to test if things are correct.

**Comment by ryan1234** [comment]
Thanks for the notes. 

Not sure what version.

```
root@7d6daaca7a8d:/bosun# ./bosun --version
bosun version 0 ()
root@7d6daaca7a8d:/bosun#
```

I do have unacknowledged alerts, so maybe that's what it is. I checked the bosun-stderr file and didn't see any errors. 

Let me try the latest Docker image. The email provider is Gmail, so I'm guessing no problem there. =)

**Comment by ryan1234** [comment]
So far now more empty emails. Related to my config above though ... I keep getting email notifications marked as "normal". Sorry if this is explained somewhere, but where do those come from? I specified critical and warning, but not normal? 

The computations shown in the email show that the alert should not have fired. The bottom line has a 0 instead of a 1. 

Does the timing matter? In other words, at one point in time the alert is valid and then a few seconds later the email template is computed and by then the alert has subsided?

**Comment by mjibson** [comment]
The email chain you set up is causing those to appear normal. The templates get re run every notification, and the alert is now normal, so that's what it's showing. We are already planning on changing that so the templates are run wrt the time of the alert, not now. Alert chains is not something we've tested much ourselves, so there could be a bug there. I don't have a lot of other things to say other than to just ack the alert, and the email should go away until it happens again.

**Comment by ryan1234** [comment]
Got it. The empty emails seem to be from "unknown" alerts. Any idea what causes the status to be unknown as opposed to normal/critical/warning? 

I've been ack'ing the alerts and that makes things manageable. =)

**Comment by kylebrandt** [comment]
See http://bosun.org/documentation.html#severity-states and let us know if that clarifies unknown.

**Comment by ryan1234** [comment]
Makes sense. From doing some work the API today, I think I'm starting to understand the expressions better. My understanding is that when a wildcard for a host is evaluated then the list of qualifying hosts is explicitly enumerated and saved.

Is that what causes the issue? For example, at one time, the wildcard might find 5 hosts and then later the same wildcard would yield 4 hosts. Since the expression is saved, and a host has disappeared, then we see unknown alerts.

If that's right, I'm trying to think I would ignore hosts that have vanished. I'm trying to monitor machines in Azure that come and go from time to time. So it's common for one of them to disappear - and that's fine. 

Any way to send unknown statuses in an alert definition to a no op?

**Comment by kylebrandt** [comment]
This is mostly correct. The difference is that the the possible hosts (or other tags) are not learned at query time, but rather that information is collected as data is relayed through bosun. Once you define an alert with a resulting tagset i.e. alert foo { q(...{host=*} } bosun tracks those possible tags for that alert and reports if that alert can't find data for one of those tag sets. 

The alert name + tags produces the alert key, i.e. foo{host=ab01} which identifies possible alerts.

You can set the ignoreUnknown flag on alerts as per the documentation and unknowns will not be generated for that alert: http://bosun.org/configuration.html#alert . I don't think that is a global option at this time, but you could define a base macro like the following and have alerts reference that macro:

``` 
macro iunknown {
   ignoreUnknown = true
}

alert foo {
   macro = iunknown
}
```

**Comment by ryan1234** [comment]
Perfect, thanks.

**Comment by mjibson** [comment]
Reopening so I remember to have some default unknown template so this doesn't happen again.

**Comment by ryan1234** [comment]
Since we've reopened, I would suggest maybe a link in the unknown default template to the documentation about the ignoreUnknown flag? =)

**Comment by kylebrandt** [comment]
Default unknown template should be built into Bosun so you don't have to specify one I think. Then can be overridden.
