### ISSUE TITLE
Feature Request: Provide HTTP Passthrough to OpenTSDB

### ISSUE THREAD

**Issue by nickman** [bosun-monitor/bosun#671]
In some cases, I would like to be able to call other URIs to call oepntsdb directly, such as submitting annotations, getting the server version and updating/querying metric meta-data. It would be convenient if all OpenTSDB api endpoints were exposed by bosun in some generic fassion such as **/api/tsdb/[open-tsdb-api]**

**Comment by mjibson** [comment]
You can use the undocumented `relayListen` setting in your conf file. It will listen on the given address (i.e., set to `:4242`) and will pass through all `/api/X` calls to your OpenTSDB server.

**Comment by kylebrandt** [comment]
Needs Documentation.
