### ISSUE TITLE
Silent Rule Error:  json: unsupported value: NaN

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#672]
When running the following rule http://goo.gl/5lHXKY the web interface returns immediately with no error displayed. When the rule is run the following is logged: `json: unsupported value: NaN`. If I remove either side of the `||` operator (And the operator of itself) from `($error_count > 10) || ($timeout_rate > 2)` it works.

**Comment by kylebrandt** [comment]
Oh, it is becuase the groups don't join, the following works: `warn = ungroup($error_count > 10) || ungroup($timeout_rate > 2)`. Still should throw and error in the web interface though

**Comment by Dieterbe** [comment]
same sympton, potentially different cause:

```
alert requests_by_country {
    template = requests_by_country
    $r = "transformNull(sum(stats.dfvimeopweb*.request.web),0)"
    $r_duration = "30m"
    $r_period = "7d"
    $r_hist = graphiteBand($r, $r_duration,$r_period, "",1)
    $r_now = graphite($r, $r_duration, "", "")
    $r_hist_med = median($r_hist)
    $r_now_med = median($r_now)

    $rbc = "aliasByNode(transformNull(stats._sum_dfvimeopweb.request_by_country.*,0),3)"
    $duration = "10m"
    $period = "1h"
    $lookback = 1
    $rbc_hist = graphiteBand($rbc, $duration,$period, "country",$lookback)
    $rbc_now = graphite($rbc, $duration, "", "country")
    $rbc_hist_med = median($rbc_hist)
    $rbc_hist_dev= dev($rbc_hist)
    $rbc_now_med = median($rbc_now)
    $rbc_now_dev = dev($rbc_now)

    $rbc_med_diff = ($rbc_now_med - $rbc_hist_med)/$rbc_hist_dev
    $rbc_med_bad = $rbc_med_diff < -4
    $rbc_dev_units = $rbc_now_dev/$rbc_hist_dev
    $rbc_dev_bad = $rbc_dev_units > 3

    $r_strength = $r_now_med/$r_hist_med
    $rbc_med_issues = sum(t($rbc_med_bad,""))
    $rbc_dev_issues = sum(t($rbc_dev_bad,""))
    warn = $rbc_med_issues > 0 || $rbc_dev_issues > 0
    crit = ($rbc_med_issues > 10 || $rbc_dev_issues > 10) || ($r_strength < 0.7)

}
```

the $r graphite expression returns a single series, $rbc returns multiple series with each a tagset, but all the rbc stuff gets transposed down. so everything in warn and crit has no associated groups.
also because of the transformNull's in the graphite queries, we don't have nulls in the graphite output. yet i also get `json: unsupported value: NaN` and sometimes `json: unsupported value: +Inf`

I tried
```
warn = $rbc_med_issues > 0
crit = $rbc_med_issues > 10
```
but i still get the same issue
