### ISSUE TITLE
Why use UTC, rather than a Local？

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#680]
We in China, the bosun's time zone display is not correct。

example：
moment.utc() and time.Now().UTC()

Can remove the UTC? or Add timezone to dev.conf ?

**Comment by kylebrandt** [comment]
Non UTC support isn't of any use to use at Stack - so we won't be working on this any time soon. However if there is a well tested pull request for this feature I think we would be happy to accept it.

**Comment by wkshare** [comment]
thks，i know。

We try to modify。

change time.Parse() to time.ParseInLocation in *.go（funcs.go, expr.go, web.go, tsdb.go ... ...)
change moment.utc to moment.local in bosun.js
and TZ=Asia/shanghai ./bosun

After the success, wish to join configuration in dev.conf。

What you suggest?

We have 3000+ machines。2W+ qps moniting data.
We'd like to try to use the bosun：）

**Comment by kylebrandt** [comment]
We would want the all js to use whatever timezone is in the config for now
(and maybe eventually users can configure it). That way the interface can
be in UTC still (or the local time).

Also be aware that we use typescript to (all the tsc files) to generate .js
and don't edit the js directly.

**Comment by Dieterbe** [comment]
just linking to whshare's PR from here: #685 
big +1 from me, I would like this feature a lot :)

**Comment by kylebrandt** [comment]
One this I will want to make sure is that this settable my people (or at least a whole instance). I don't want to view things in localtime, rather see them in UTC. So I don't want the web interface restricted to localtime of the client machine.

**Comment by wkshare** [comment]
@kylebrandt   The web page, use the best Localtime，I 'm sure :)

**Comment by gbrayut** [comment]
We have servers and employees in many different time zones and want everything displayed in UTC. If you have a pull request to allow local time on bosun that is fine, but we still want to be able to configure UTC for all our users.

**Comment by nickman** [comment]
UTC is fine, considering the requirement, but it would be nice if it was labeled as UTC. Otherwise (in other time-zones) it just looks wrong.
![tz](https://cloud.githubusercontent.com/assets/597608/6416037/0e4cf6f2-be71-11e4-9080-72c47c7ae874.png)

**Comment by wkshare** [comment]
@nickman i got it

**Comment by Dieterbe** [comment]
closed, why? i think some good points were brought up here :?

**Comment by kylebrandt** [comment]
Want to get to a more manageable length of issues. Supporting local time is
a pretty big project with no contenders to do the work any time soon.
