### ISSUE TITLE
Alerts close, 400 Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#683]
800+ alerts, close.

![image](https://cloud.githubusercontent.com/assets/2918384/6016794/26615f38-abc2-11e4-9760-01f951db40d2.png)

![image](https://cloud.githubusercontent.com/assets/2918384/6016757/8b6cf640-abc1-11e4-94f3-d484bc3976d2.png)

**Comment by wkshare** [comment]
I setting nginx configure: large_client_header_buffers
fix this issues.

**Comment by mjibson** [comment]
nginx? Are you using it as a reverse proxy?

**Comment by wkshare** [comment]
@mjibson Yes. 
Nginx -> Haproxy(HTTP) -> Bosun(count:3) -> TSDB(count:3) -> Hbase Cluster(CHD4)

**Comment by kylebrandt** [comment]
This isn't related to your specific issue, but you said you currently have
3 bosun instances. Bosun builds the tags it has seen by data passing
through it. That data is not shared between instances. So using multiple
bosun instances behind HAProxy currently is something that may not work
correctly.

**Comment by wkshare** [comment]
thks, @kylebrandt 

3 Bosun Instances。
1、Only Receive Data
2、Only Receive Data
3、not receive，Alert and Web Search

I'm still testing, currently used properly.

**Comment by wkshare** [comment]
@kylebrandt thks again.
multiple bosun，stat is wrong。i know。
