### ISSUE TITLE
time: invalid duration

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#684]
Select: Graph -> SwitchTime(1h-ago change to time format) -> Query, and click Expression, and then。。。
![image](https://cloud.githubusercontent.com/assets/2918384/6018253/52ee0f02-abd0-11e4-901f-2810c2bbe43e.png)

**Comment by kylebrandt** [comment]
Expression link from graph page should always switch back to relative time

**Comment by tdinucci** [comment]
The query on the expression page did not specify a start time, e.g. 

`q("sum:linux_loadavg_1min", "1h", "")`
