### ISSUE TITLE
more flexible/powerful body templating for http post action

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#689]
```
[ re http post actions for alerting rules]
@mjibson but when overriding body with a template in the config, dot is the subject,
so there's really not much that can be put in there.
like in my hipchat message i'ld like to put some links, a little graph, maybe a little table, etc.
how about in the template, in addition to body and subject, we can optionally
write a postBody template variable,
and similar to how the email action uses body and subject,
the http post handler would use postBody when available (with fallback to subject)

mjibson
agreed. that should be changed so both body and subject are available.
```

**Comment by kylebrandt** [comment]
So we have options:
 - Specify what to use in the notification
 - Specify what to use in the alert
 - Add an optional additional field to templates that will be used for http posts (otherwise it defaults to subject)

I haven't thought about this a lot, but it needs more thought to get closer to implementation.

**Comment by gbrayut** [comment]
For our exceptions alert we would want a detail email and brief summary posted to chat. It should have access to all the variables defined in the alert. My vote would be the option of an httpbody in the template that when present would be used for the http post notification.

The ability to have different content for different notifications (we likely will have multiple http post notifications, one for each room) would be nice, but a simple httpbody would suffice for now

**Comment by Dieterbe** [comment]
> My vote would be the option of an httpbody in the template that when present would be used for the http post notification.

+1

if the user wants to reuse the email subject for http post message, they can probably just put something like `render subject` as content for the http post template (not sure what the actual go template syntax for this is)

**Comment by nhproject** [comment]
+10

For now, In HTTP POST we can only use {{. | json}} and it takes the subject of the template.
It will be great for a lot of us to be able to use specific values like we do in the template. For example - {{.Group.host}}.

**Comment by angadsingh** [comment]
+100 for this one

**Comment by kylebrandt** [comment]
will be fixed in https://github.com/bosun-monitor/bosun/pull/2135
