### ISSUE TITLE
Scheduled Alerts (Reports)

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#692]
It would be useful to be able to specify alerts to run on a certain schedule outside of the normal schedule. Essentially this would enable Bosun to also act as a reporting system. 

These could still be conditionally triggered such that it only send the "daily report" if something has been wrong. This would help reduce alert noise for things that naturally group and/or require notification - but not urgent notification.

Using the Go implementation of Cron might be useful considering it is something many system administrators are already familiar with.

**Comment by acesaro** [comment]
+1

**Comment by Dieterbe** [comment]
what ever happened to this?

**Comment by kylebrandt** [comment]
Just not a priority right now. We are mostly focused on stability and performance for the next month or two. Parallel checks are nearing completion, next we will be working on relaxing the state file with something more robust and efficient.
