### ISSUE TITLE
scollector BatchSize too low

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#693]
BatchSize = 250   too low.

2015/02/05 15:43:54 info: queue.go:52: sending: 250, remaining: 741
2015/02/05 15:43:58 info: queue.go:133: sent 250
2015/02/05 15:43:58 info: queue.go:52: sending: 250, remaining: 491
2015/02/05 15:44:02 info: queue.go:133: sent 250
2015/02/05 15:44:02 info: queue.go:52: sending: 250, remaining: 241

2015/02/05 15:44:11 info: queue.go:133: sent 250
2015/02/05 15:44:11 info: queue.go:52: sending: 250, remaining: 997
2015/02/05 15:44:15 info: queue.go:133: sent 250
2015/02/05 15:44:15 info: queue.go:52: sending: 250, remaining: 747
2015/02/05 15:44:19 info: queue.go:133: sent 250
2015/02/05 15:44:19 info: queue.go:52: sending: 250, remaining: 497

2015/02/05 15:57:56 info: queue.go:133: sent 250
2015/02/05 15:57:56 info: queue.go:52: sending: 250, remaining: 3118
2015/02/05 15:58:00 info: queue.go:133: sent 250
2015/02/05 15:58:00 info: queue.go:52: sending: 250, remaining: 2868

remaining too many!!!

**Comment by wkshare** [comment]
![image](https://cloud.githubusercontent.com/assets/2918384/6057945/a9d61b46-ad5d-11e4-8733-b96cbc79fd4c.png)
too many data delayed!!!

**Comment by mjibson** [comment]
This looks like a problem with OpenTSDB not being able to write data fast enough, or your network being too slow to handle these requests, not a problem with the batch size. If the batch size were increased, the problem would likely remain.

However, let's test my claim with some data. You can run scollector with `-b` to specify a higher batch size: `scollector -b 1000`. Try that and see if it improves anything. If not, then it's not a problem scollector can fix.

**Comment by wkshare** [comment]
thks:-P

**Comment by wkshare** [comment]
closed
