### ISSUE TITLE
No way to set hostname for SNMP polling

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#698]
It is often the case with network equipment one might need to poll an IP other than the hostname - we should find a way to support this in our snmp config string

**Comment by captncraig** [comment]
snmp currently accepts `community@host,community@host` type connection strings. Are you implying that a host might expose an snmp interface for an entirely separate host? Is the problem that data points in such a scenario would be mistagged? Perhaps then `community@host(realhost)` would be an acceptable syntax?

**Comment by kylebrandt** [comment]
Not important right now
