### ISSUE TITLE
variable value not consistent within 1 rule execution

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#700]
my `g_dev_units` variable's value is not consistent within execution of a rule, on the rule page.
it appears in the subject and in the body, and has different values

```
{{if gt (.Eval .Alert.Vars.g_max_erratic_warn) -1.0}}
   <h2>Erraticness of {{.Alert.Vars.tpl_unit}}, Global</h2>
Erraticness - increased deviation - could be indicative of a spike or drop.
Low values up to {{.Eval .Alert.Vars.g_max_erratic_warn}} are ok. {{.Eval .Alert.Vars.g_max_erratic_crit}} are critical
       <br>
        {{if gt (.Eval .Alert.Vars.g_dev_units) (.Eval .Alert.Vars.g_max_erratic_crit)}}
            <span style="color:red;">
        {{else if lt (.Eval .Alert.Vars.g_dev_units) (.Eval .Alert.Vars.g_max_erratic_warn)}}
            <span style="color:green;">
        {{else}}
            <span>
        {{end}}
            {{.Eval .Alert.Vars.g_dev_units}}</span>  <-----------
       <div style="height: 450px">
         {{.Graph .Alert.Vars.g_reqs }}
       </div>
        {{end}}
```
in subject:
```
    subject =`
    {{.Last.Status}}: {{.Alert.Name}} :

    Global {{.Alert.Vars.tpl_unit}} {{.Eval .Alert.Vars.g_strength | printf "%.3f"}}

   {{if gt (.Eval .Alert.Vars.g_max_erratic_warn) -1.0}}
       - erraticness {{.Eval .Alert.Vars.g_dev_units | printf "%.3f"}}<-----------
   {{end}}

 | {{.Eval .Alert.Vars.s_med_issues | printf "%.0f"}} {{.Alert.Vars.tpl_s_tag_plural}} with dropped median:
        {{range $r :=.EvalAll .Alert.Vars.s_med_bad}}
        {{ if gt $r.Value 0.0}}
             {{ index $r.Group $.Alert.Vars.tpl_s_tag }}
         {{end}}
    {{end}}`
```

![bosun-wtf](https://cloud.githubusercontent.com/assets/20774/6088847/c569b7f2-ae28-11e4-94cf-f347879d850f.png)

**Comment by Dieterbe** [comment]
note, most of the time it works fine. like right now i'm seeing:
```
normal: requests_by_country : Global Web requests 0.883 - erraticness 9.186 | 0 countries with dropped median: 
....
Erraticness - increased deviation - could be indicative of a spike or drop. Low values up to 2 are ok. 3 are critical
9.18607582825225
```

**Comment by kylebrandt** [comment]
A Theory:

When the notifications are sent, we re-evaluate the expressions with the
time set to the same time the alert triggered. Since the data is not passed
directly, there could be some discrepancies if the data in graphite has
changed (for the same time period - think backfilled or aggregated) between
trigger and notification time.

Does that sound possible?

**Comment by Dieterbe** [comment]
another way you can tell the discrepancy (i think): 
```
$g_max_erratic_warn = 2
    warn = $s_med_issues > 0 || ($g_max_erratic_warn != -1 && $g_dev_units > $g_max_erratic_warn)
```
note in my previous post how g_dev_units is 9.1 and yet the alert claims "normal", it should be warning.

@kylebrandt that might in theory be possible, but does it apply here? alert emails are not involved here, i see the inconsistency within 1 single rule test execution on the rule page

**Comment by Dieterbe** [comment]
#715 should address this, along with Matt's work to compute the templates in the alerting run

**Comment by Dieterbe** [comment]
this should be fixed now since #715 is merged. will close this

**Comment by mjibson** [comment]
Reopen if still present.

**Comment by mjibson** [comment]
orly? Screenshot?

**Comment by kylebrandt** [comment]
wrong bug... know which one was for the notification not matching the the trigger? Body and subject match, but shouldn't have triggered:

![image](https://cloud.githubusercontent.com/assets/1692624/6567756/54c70ce6-c6a3-11e4-9bbb-022726ee5ac8.png)

**Comment by kylebrandt** [comment]
Or rather I should say based on the notification it shouldn't have triggered - probably was in a state to trigger, but notification didn't match trigger condition.

**Comment by mjibson** [comment]
Did this come after building a new prod bosun? There were 39 changes there. Could have been because of one of them?

**Comment by kylebrandt** [comment]
Yes. this was after the build, was 3ish EDT, and confirmed that bosun did restart at that time on the server. Can verify this is bosun as well:

![image](https://cloud.githubusercontent.com/assets/1692624/6567836/987c4a86-c6a4-11e4-9d61-d5b4b0100042.png)
