### ISSUE TITLE
Unable to fetch metrics:

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#706]
If the long time does not operate a page, will appear the following error:
Refresh the page, recovery.
![image](https://cloud.githubusercontent.com/assets/2918384/6123546/efbfbea2-b13e-11e4-88d4-82252ed570fa.png)

**Comment by Dieterbe** [comment]
look at the standard out and standard error of the bosun program, it probably tells you more details

**Comment by wkshare** [comment]
@Dieterbe 

error like this:

2015/02/11 03:30:38 http: proxy error: EOF
2015/02/11 03:38:30 http: proxy error: unexpected EOF
2015/02/11 03:42:09 http: proxy error: unexpected EOF
2015/02/11 03:43:24 http: proxy error: unexpected EOF
2015/02/11 03:47:27 http: proxy error: read tcp 192.168.33.200:64595: connection reset by peer
2015/02/11 03:48:44 http: proxy error: EOF

**Comment by tdinucci** [comment]
Seems like a connection timeout.  Not enough info in ticket to attempt to reproduce and it's also very old so closing.
