### ISSUE TITLE
"now" resets to current time after 1 test run

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#714]
confirmed with graphite.
not sure if also visible with opentsdb
but if i have an alert that queries from 3d ago to now, and on the rule page i set "from" to 2015-02-12 10:00 (UTC, so 5 EST). (today is 2015-02-12 15:54 EST)

the first run : 
```
~ ❯❯❯ date -d @1423476000 # from
Mon Feb  9 05:00:00 EST 2015
~ ❯❯❯ date -d @1423735200 #to
Thu Feb 12 05:00:00 EST 2015
```
this is good, but if i don't change anything, and hit the test button again, it's:
```
~ ❯❯❯ date -d @1423515284 # from
Mon Feb  9 15:54:44 EST 2015
~ ❯❯❯ date -d @1423774484 #to
Thu Feb 12 15:54:44 EST 2015
```

**Comment by mjibson** [comment]
I can't repro this. `from` in the request is the same each time I hit test (on the Rule page).

**Comment by Dieterbe** [comment]
hmm i can't repro this anymore either. in both master and fix-template-now-divergence it works fine now :? i guess let's close this and keep an eye out?
