### ISSUE TITLE
i think we need flap detection / notification supressing

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#726]
i believe we should support different alerting styles, on a per notification setting (because it depends on the alert and the recipient)
for simplicity, i'm mostly ignoring the effect of acknowledging for now.

ordered by alert volume:

1. keep sending alerts every x minutes until resolved or acked.  i had a colleague ask for this, but i never heard anyone else ask for this. (anyone else?) i hear this can be done now by setting a timeout on the notification, and set next to itself.
2. trigger notification every time status becomes warn/crit. we currently do this.  some people really just want this.  i think this is mostly useful if you don't easily have access to a proper historical overview of the alert, so that you can see in your mailbox all the times where it fired.  for high-volume notifications people will typically route to lowprio email inbox and then glance over their many messages.  not a great approach but some people want this.  another reason for this is external logging/event handling system that want every single hit
3. same as above, but back off if alert flaps between states. surpress alerts to a destination if we already sent an alert to the given endpoint in the last X minutes/hours and tthe status has not become worse
4. extension of the above: timeframe becomes infinity.  only alert if there's anything new to share.  pretty risky because text/email/.. don't have guaranteed delivery. but kyle likes this
5. no notifications (d'uh)

**Comment by Dieterbe** [comment]
i think we can currently do all of these except 3 and 4.
i would like 3, but 4 would be acceptable as well. note that 4 can be implemented as a special case of 3

**Comment by kylebrandt** [comment]
I'm not fond of supporting multiple notification styles unless we really find we need it - it increases complexity.

The reason I am adverse to the time component is that it makes it pretty hard to understand why or why not you got a notification. I also just don't think it is necessary.

My idea is:
 1. Once an alert is instantiated (i.e. the first non-normal status) throughout it's lifetime (until it is closed by a human) alerts are only sent when there is a state increase throughout it's entire lifetime (currently to crit or unknown). This means there will be no flapping because we don't alert when the state decreases.
2. If a person wants repeated emails for an issue, the can have the notification handle that with next and timeout
3. Acking alerts stops any notification chains from repeating.
4. Closing an alert resets everything.

**Comment by Dieterbe** [comment]
the only argument pro-3 against 4 that i can come up with is reliability of notification delivery. if your delivery doesn't work well, at least with flap surpression you'll get an alert, but it might be hours late.  with option 4 you might never get an alert.  anyway this is a crappy argument.  one should just make sure emailing/sms works, i've actually never had an issue with receiving business email or alert text messages.

I think I like your suggestion

**Comment by Dieterbe** [comment]
wait so with your suggestion, what happens in the following state transition?

1. normal
2. crit
3. warn
4. crit

an alert only at 2 or also at 4?

how about
1. normal
2. warn
3. normal
4. warn

?

**Comment by kylebrandt** [comment]
Question 1) Yes, only 2
Question 2) Only 2 again

Another Scenario:

1. normal
2. warn
3. normal
4. warn
5. normal
6. crit

We would get notified on 2 and 6

**Comment by Dieterbe** [comment]
ok perfect, that covers my needs

**Comment by Dieterbe** [comment]
@kylebrandt is this ticket still valid?

* the bosun bugs that caused multiple notifications even though state didn't go above what already was reported, have been fixed, right?
* if the above is yes, then flapping is not a thing and there's no need for flap detection. 
* the current system is number 4, but number 1 and 5 are easy.
* i personally don't need 3 (or 4), i think sometimes people want 3 because they might ignore or just delete an individual email and not realize the consequences (not getting alerted again while the state is still non-normal), people do this when they get a lot email (perhaps non bosun).  but i'm fine with not worrying about this case and forcing people to have better email habits, and teach them how bosun works.

so i think we can close this, if those alerting bugs are fixed.

**Comment by Dieterbe** [comment]
@captncraig ^^
