### ISSUE TITLE
Kill scollector if the handle count exceed given threshold

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#727]
Today we had an issue where scollector exhausted the UDP ports on the local server. It looks like the handle count for the process was over 16,000 by the time we found the root cause, where as normally it operates in the 500 range.

![image](https://cloud.githubusercontent.com/assets/304401/6234584/33c8eb96-b699-11e4-9b9a-874d73ea624b.png)

We should add a kill switch to scollector if it ever goes above 5,000 or 10,000 similar to the [memory usage panic](https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/main.go#L260)

**Comment by gbrayut** [comment]
On Windows, the handle count is already monitored via win.proc.handle_count
On Linux, linux.proc.num_fds is similar to the handle count but may need a different threshold
On Mac ?

**Comment by kylebrandt** [comment]
Something to keep in mind with this is that if we tie this into the
collector code, people can disable those collectors and probably wouldn't
realize that they no longer get threshold protection. So I think these
maybe all needs to go into kill_windows.go and kill_linux.go etc or
something to be independent.
