### ISSUE TITLE
Provide a method to prevent accidental data being pushed to Bosun

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#730]
Frequently at SE dev data accidentally gets written to our prod instance. The vast majority of this could be fixed by an IP access list for our put routes.

Long term eventually we will want to thing about auth for the API, but I think this is a pretty easy feature with at least big win at SE.

**Comment by gbrayut** [comment]
+1. We also need to consider ways of cleaning up the data. We are past the days of waiting for the state file to be reset.

**Comment by mjibson** [comment]
@kyle please change the title to state the problem, not the solution
