### ISSUE TITLE
Porting scollector to influxdb

### ISSUE THREAD

**Issue by fire** [bosun-monitor/bosun#734]
Prerequisites to scollector influxdb support

* Tag support in influxdb
* Unhard code opentsdb

**Comment by internetjanitor** [comment]
tags are now supported plus [More Unicorns](http://influxdb.com/blog/2015/02/24/influxdb-v0_9_0-rc4_released_now_with_tags_and_more_unicorns.html)

**Comment by kylebrandt** [comment]
Closing, there is a branch for this and an open influx issue. Won't get merged until we have some dedicated influx users though. https://github.com/bosun-monitor/bosun/issues/618

**Comment by pdf** [comment]
FYI for anyone playing at home - InfluxDB 0.9 already has a tsdb input, so scollector should not need any modifications to support InfluxDB as a backend (unless there's a specific desire for native protocol support - performance might be a valid reason).

**Comment by mjibson** [comment]
Scollector doesn't support the kind of TSDB input that InfluxDB supports, so sadly that isn't true. (Scollector outputs JSON, InfluxDB wants the old "telnet" style.)

**Comment by captncraig** [comment]
That being the case, I wonder if it would be more valuable to submit a more complete opentsdb compatibility layer to influx.

**Comment by pdf** [comment]
InfluxDB supports both telnet and HTTP style inputs.

**Comment by mjibson** [comment]
Oh it does! I remember reading some documentation a while back that only listed the telnet protocol. But looking at the current code they support gzipped JSON arrays of points, which is exactly what scollector sends. Fantastic.

**Comment by fire** [comment]
I'm not sure how exactly how to use scollector with bosun / influxdb. Do I just tell scollector to directly send to influxdb?

**Comment by captncraig** [comment]
`./scollector -h=myInfluxHost` should do it if influx really does support it.

**Comment by mjibson** [comment]
You may also want to add on `-m` to disable scollector metadata sending, which is a bosun-specific thing.

**Comment by fire** [comment]
Noting I was able to use scollector with Influxdb. 

Sidenote: I don't see any username login possibilities.
