### ISSUE TITLE
Use metrics directly put into OpenTSDB, e.g., from logstash

### ISSUE THREAD

**Issue by lukaspustina** [bosun-monitor/bosun#739]
I configured *logstash* to write certain metrics directly to *OpenTSDB* via the corresponding output module.

Unfortunately, I cannot figure out how to access these metrics in Bosun since they do not show up in the items list. Obviously, there is a connection between Bosun and these metrics missing.

Could you give me hand and show me how to do this?

**Comment by nickman** [comment]
You need to send the metrics to bosun which then forwards them to tsdb.

**Comment by lukaspustina** [comment]
Does Bosun offer a OpenTSDB compatible interface and if so, how do I access it?

**Comment by nickman** [comment]
Yes. It supplies the same submission interface as tsdb's /api/put endpoint.

**Comment by lukaspustina** [comment]
Thanks. As far as I see, logstash uses the Telnet API and thus, cannot pass metrics to Bosun at the moment.

**Comment by nickman** [comment]
Ew. Perhaps you might open a ticket with bosun requesting implementation of
the telnet put service. Should be simple enough.

**Comment by lukaspustina** [comment]
Do you have an idea why the metric data needs to be sent to Bosun? When I look as the source code, it seems to me that all access to /api/put it just passed through to OpenTSDB using `net/http/httputil.ReverseProxy`.

I might be wrong though as I don't speak Go.

**Comment by kylebrandt** [comment]
At least two things happen there:

 - We populate the search data. The search data allows for autocompletion of relevant tags and their values. It also allows us to support globs like host:ny-web* which OpenTSDB doesn't support.
 - IP ACLs to allow who can put (new as of yesterday)

I understand the advantage of precomputing time series for logs. However, it seems like adding rest support to the logstash opentsdb plugin would be a better path. You can directly query an elastic instance that is populated by logstash. See the `lscount()` and `lsstat()` functions.

**Comment by lukaspustina** [comment]
I agree, this should be the task of the plugin; not bosun's. I just wanted to understand what happens behind the scenes.

lscount and lsstat are nice, but they don't allow for all the functions you can use on opentsdb metrics.

**Comment by kylebrandt** [comment]
Which functions in particular are you looking to utilize?
