### ISSUE TITLE
Scollector fails to start on Windows within 30 second timeout

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#741]
We have seen a number of issues where scollector fails to start on Windows (usually after reboot, but also can occur if the service is restarted due to failure or manual action). In the Event Log we see Event ID 7009 `A timeout was reached (30000 milliseconds) while waiting for the scollector service to connect.`

To try and correct the issue we have already set the service to delayed-start so it is not fighting other services for cpu/memory resources. We have also set the service to automatically restart if it crashes, which results in Event ID 7031 `The scollector service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service.`

This has helped but we still occasionally get a notice that the service failed to start. It shows the 7009 error in the event log, followed by Event 7000 `The scollector service failed to start due to the following error: The service did not respond to the start or control request in a timely fashion.`

Scollector uses the [winsvc library](https://code.google.com/p/winsvc/), which I assume handles the control requests, but we may need a delay or something in the code on start up to make sure it can respond to the control requests before the 30 second timeout.

Also it would be great if the service registered itself using the delayed-start setting instead of automatic and set the failure action to restart up to two times in a 24 hour period. Currently these are set via Powershell/DSC and are not included in the default -winsvc="install" settings.

**Comment by kylebrandt** [comment]
Is there maybe a standard windows service that scollector should logically start after? Maybe networking or something?

**Comment by gbrayut** [comment]
All services were already up in this case, as it crashed and was restarted by Windows. There weren't any errors in the event log from Windows, so my guess is the winsvc code isn't able to respond due to some other thread/task consuming cpu during scollector startup.

**Comment by gbrayut** [comment]
Looks like there was a previous issue with deadlocks in the code, but says it was fixed already: https://code.google.com/p/winsvc/issues/detail?id=4&can=1

**Comment by kylebrandt** [comment]
Might just need to refresh the vendoring on that package

**Comment by JoshKeegan** [comment]
Hi All,
Was this ever fixed?
We appear to be having the same problem now.

**Comment by michael-holzheimer** [comment]
We have been having the same problem on our Win 2008r2 and Win 2012r2 servers. Seems to start consistently on our Win 2016 servers.
