### ISSUE TITLE
scollector with invalid -f flag throws exceptions on Windows

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#746]
If you use -f to filter collectors but use a name that does not exist there are execptions thrown on windows

> ./scollector.exe -h 'http://ny-gbraylx01.ds.stackexchange.com:8070' -f asfd
> 2015/02/25 16:16:00 info: main.go:230: OpenTSDB host: http://ny-gbraylx01.ds.stackexchange.com:8070
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_iis_webservice: Exception occurred.
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_iis_apppool: Exception occurred.
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_network_team_windows: Exception occurred.
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_mssql: Exception occurred.
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_mssql_replica_resources: Exception occurred.
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_mssql_replica_db: Exception occurred.
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_mssql_replica_server: Exception occurred.
> 2015/02/25 16:16:14 error: interval.go:53: bosun.org/cmd/scollector/collectors.c_mssql_replica_votes: Exception occurred.

**Comment by captncraig** [comment]
Problem is filter search returns a null set if nothing matches: https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/collectors.go#L95

and the run command runs *everything* if the set is null: https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/collectors.go#L110

Fix would probably be to exit with an error if filter matches nothing.

**Comment by gbrayut** [comment]
Ah and the init methods probably weren't run, which is why they throw exceptions! I'll take a look at the pr and make sure it works as expected, but sounds good to me.
