### ISSUE TITLE
Allow for selection of plain or SSL HTTP for ElasticSearch server configuration 

### ISSUE THREAD

**Issue by lukaspustina** [bosun-monitor/bosun#747]
I'd be nice, if we could select whether to use plain HTTP or SSL when accessing ElasticSearch.

**Comment by lukaspustina** [comment]
@kylebrandt: Doesn't seem to work for me.

I adapted the configuration:
`http://10.102.2.231:9200`

But I get 'no Elasticsearch node available' whenever I try to make an ES query. It's the same ES server as I used before.

Any idea?

**Comment by kylebrandt** [comment]
ES Version?

**Comment by lukaspustina** [comment]
1.4.4

**Comment by kylebrandt** [comment]
I'm on 1.4.0 and it can repro this , will check with https://github.com/olivere/elastic/issues/48 ...

**Comment by kylebrandt** [comment]
@lukaspustina Sorry about the delay, I'm going to try to dig into this weekend...

**Comment by kylebrandt** [comment]
Nope... still getting nodes unavailable

**Comment by kylebrandt** [comment]
Working now... maybe it just takes a min to learn about the connections... Next thing is to monitor its pool I guess...

**Comment by lukaspustina** [comment]
Sorry to come back to you so late, but ES works for me fine now. Thanks for your support!
