### ISSUE TITLE
Can't see any metrics but bosun's from TSDB

### ISSUE THREAD

**Issue by kebarcla** [bosun-monitor/bosun#750]
I installed go from go1.4.2.linux-amd64.tar.gz and opentsdb-2.1.0RC1 on Centos 6.4 (x86_64.)

I have bosun running on the same server as TSDB, and put its hostname in dev.conf as

tsdbHost = prdslsldsafht30.myfamilysouth.com:4242

There are a lot of metrics coming in to TSDB from scollector and tcollector, all of which are viewable in the TSDB UI and metrilyx.

The bosun UI works fine except it only shows us bosun.* metrics and no others.

I tried debug mode on scollector but I didn't glean from its copious output what the problem might be.

The only errors I've seen are ones in /var/log/messages like

Feb 26 23:38:14 prdslsldsafht30 /opt/bosun/src/bosun.org/cmd/scollector/scollector[31026]: error: metadata.go:210: bad metadata return: 400 Bad Request

Looking for suggestions on how to debug this.

Thanks
Ken

**Comment by kylebrandt** [comment]
Currently OpenTSDB data needs to be relayed through Bosun (You send it to Bosun, Bosun sends it to OpenTSDB). We did this so we could have structures that show related metrics and tags, support globs like `host: ny-web*`, and know when a tagset disappears (goes into unknown status).
