### ISSUE TITLE
Remove RunHistory from Poll and CheckUnknown

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#756]

**Comment by Dieterbe** [comment]
i'll do this once LRU cache is merged

**Comment by Dieterbe** [comment]
will do this after LRU gets merged. on further inspection, it looks like ` (s *Schedule) CheckUnknown()` does use its RH though (but no caching). :?

**Comment by Dieterbe** [comment]
fixed in LRU PR.
