### ISSUE TITLE
Bosun/scollector Metrics don't jive with PerfMon

### ISSUE THREAD

**Issue by nickman** [bosun-monitor/bosun#758]
We're looking at using scollector/bosun to monitor a cluster of calc servers. After running a sanity test, we were comparing stats collected via perfmon with stats viewed in bosun. In most cases, after compensating for sampling periods etc., most of the stats aligned acceptably. However, in some cases,  there's just no correlating the data. I am assuming we're just not comparing apples-to-apples, but I could really use a pointer on how to validate these outliers. The simplest example is Processor Queue Length. The following is our rendering of data collected via perfmon and bosun/scollectors on the same host at the same time. Again, I would totally expect some variances on account of collection periods and aggregation, but this one seems inexplicable to me)

PerfMon Collected Data
![image](https://cloud.githubusercontent.com/assets/597608/6489927/57f71578-c270-11e4-9ac6-2d1800c0fe4a.png)

Bosun Collected Data
(via ./tsdb query 1h-ago avg win.system.cpu_queue)
![image](https://cloud.githubusercontent.com/assets/597608/6489959/a5771668-c270-11e4-9efd-6ec28e86e4d3.png)

I am not too familiar with the internals of the Windows, but as I was looking at the data, it almost seemed like the counter might be a reset-on-read, so the perfmon monitor was getting some of the data and scollector was getting the rest. Is that possible ?

Thanks for any insight you can give me.

//Nicholas

**Comment by kylebrandt** [comment]
This particular metric is a gauge. That means we get a "snapshot" from scollector every 15 seconds. Unless they Perfmon and Scollector were running at the *exact* same frequency, and are *Exactly* in sync you will not get the same results. 

So I would say this is expected. If this is not a good enough explanation you need to set scollector to a default freq of every second (I'd filter so you are only getting this particular collector), perfmon to every second, and things still look very different we dig deeper. If not I'll just close this.

**Comment by kylebrandt** [comment]
Also worth mentioning. Whenever it sensible not use a gauge, we go into the raw performance counters to get the data so we don't have that "missing" information. Think that go up and down generally don't work as a counter though, such as disk space or a queue. That is because every increment and decrement would need to be captured, and that isn't sane.

**Comment by nickman** [comment]
Got it. So I was looking at the code to figure out how to change the frequency. Do I need to rebuild ?  'Cause there's no command line option for frequency......

**Comment by kylebrandt** [comment]
```
scollector -h
....
-freq="15": Set the default frequency in seconds for most collectors.
...
```

Most collectors because some are hardcoded. But those are things we know we don't want to check very often. For example the one that runs yum to look for updates since yum locks, and takes a long time to run. This one probably uses the default freq

**Comment by kylebrandt** [comment]
Oh wait, sorry the binary on our website might not have that feature yet...
So you may need to pull from github and build it. Is that hard for you? I
can looking into pushing scollector binaries today if it is.

On Wed, Mar 4, 2015 at 2:34 PM, Nicholas Whitehead <notifications@github.com

**Comment by nickman** [comment]
I got it. Thanks Kyle !

**Comment by gbrayut** [comment]
The [win.system.cpu_queue](https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/system_windows.go#L26) data currently comes from the [Win32_PerfRawData_PerfOS_System](https://msdn.microsoft.com/en-us/library/aa394318(v=vs.85).aspx) WMI class, but as Kyle said it is a Gauge that changes very quickly so is difficult to match when you have different sample frequencies.

I tested in powershell using the below command and it seems to follow what permon.exe shows for Processor Queue Length, so the differences you see are most likely do to sampling and/or the fact that Gauge changes VERY quickly.

```
while($true){gwmi Win32_PerfRawData_PerfOS_System | select -ExpandProperty ProcessorQueueLength;sleep -Milliseconds 500}
```

**Comment by nickman** [comment]
Thanks for the info @gbrayut.
I think we're all set, so closing this issue.
Thanks all.
