### ISSUE TITLE
tunable config knobs for the LRU cache

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#760]
need to be able to tune size of both the alert-run and "forever cache web UI queries"

current suggestion (kyle):
I'm guessing less than 10% of users will know what LRU means - I would call alertCache and interfaceCache - or something that makes more sense from a user perspective.

**Comment by mjibson** [comment]
I think the schedule cache should stay infinite until that's a problem. The web cache could be configurable. Or, we could just copy the schedule cache to the web cache each schedule run. This would prevent the stale cache data mini-problem we have, and allow the web interface to benefit from the schedule queries.

**Comment by Dieterbe** [comment]
> I think the schedule cache should stay infinite until that's a problem

right, we basically _have_ to do this to guarantee consistency in query results within a run!

> we could just copy the schedule cache to the web cache each schedule run

that seems very annoying: your web UI cache getting invalidated as you're working on a rule every time a schedule run completes. I thought I saw some value in merging cache results from scheduled runs to the webUI cache, which would be very cheap as the cached value is just a pointer, but once the schedule cache expires it becomes expensive because the data can't be freed. there's a small chance you'll reuse the data, but the data is more likely to be not up to date yet, whereas it would be if you run a fresh query on the (now older) timeframe from the web UI. so -1 on this.
