### ISSUE TITLE
Metrics for .NET CLR Memory

### ISSUE THREAD

**Issue by skhprabu** [bosun-monitor/bosun#764]
I'm starting to use scollector in windows server. I was looking at all the metric data submitted by scolletor for windows. I could not find metric for .NET CLR Memory. I'm looking for data submitted by perfmon counters like
1. #Gen 0 Collections,  #Gen 1 Collections,  #Gen 2 Collections
2. Gen 0 Heap Size, Gen 1 Heap Size, Gen 1 Heap Size
3. % Time in GC
4. # Induced GC etc.,
Is there anything similar to this available for scollector

**Comment by kylebrandt** [comment]
Assigned, we have another donnet collector in PR, so you will likely get this soon.

**Comment by skhprabu** [comment]
Thanks Kyle for the response. How soon can I expect that ? I've a greater need for it since my app is very much memory intensive

**Comment by kylebrandt** [comment]
From Greg: "once I finish the .NET CLR Loading stuff I have the CLR Memory queued up in another commit. I'll work on the current PR today and should be able to get both done this afternoon".

Note the word "should", but a conservative estimate should be within the week - but maybe sooner.

**Comment by gbrayut** [comment]
This is implemented in https://github.com/bosun-monitor/bosun/pull/745 and should be merged in early next week.
