### ISSUE TITLE
Getting errors on Windows Loading WMI values into uint32s

### ISSUE THREAD

**Issue by nickman** [bosun-monitor/bosun#778]
This is on my own build from current.
Windows 7, 64.

Example:
```2015/03/10 17:25:25 error: network_windows.go:66: wmi: cannot load field "InterfaceIndex" into a "uint32": unsupported type (int32)```

It seems like this is occurring for all WMI calls. e.g.

* system_windows
* windows_processes
* cpu_info

Sketchy build or something else ?

**Comment by gbrayut** [comment]
This was caused by one of the recent party commits, but should now be fixed. Pull latest and try building again.

**Comment by nickman** [comment]
Cool and thanks.
