### ISSUE TITLE
scollector Feature Request

### ISSUE THREAD

**Issue by nickman** [bosun-monitor/bosun#799]
Plural actually. 

1.  Easy one. scollector errors out when I use a "#" for comments. It seems comments are not supported, and it would be great if they were.

2. Reach request:  Report scollector instance meta-data (version, arch and config) in the Bosun console.

3. Super reach request:  Allow real time editing of the scollector properties in the Bosun console and have the changes take effect when changes are commited.

**Comment by kylebrandt** [comment]
We have thought about 3 but I don't think that is something we will be working on any time soon. Can you separate 1 and 2 into different issues?

**Comment by kylebrandt** [comment]
For 1 we switched to toml so should be fixed. For 2 it is now a metric called scollector.version which shows OS and scollector version.

I don't think 3 is something we are going to do, rather it is expected your configuration management will do this (i.e. puppet, chef, whatever)
