### ISSUE TITLE
Existing OpenTDSB

### ISSUE THREAD

**Issue by mike-a-davis** [bosun-monitor/bosun#800]
Is there a way to stack this on top of OpenTSDB?  Running OpenTSDB 2.0 with 40k metrics a second.  Would love to see bosun on top of that.

**Comment by kylebrandt** [comment]
What do you mean exactly? We have 25k DP/s going through bosun then to opentsdb...

**Comment by mike-a-davis** [comment]
I have an existing infrastructure collecting data and feeding opentsdb directly.  I didn't see a way I  could create alerts for datapoints/hosts that already exist.  It would be great if I could just plug this on top of prod wouthout having to redirect all my data.  Stand up some dedicated read tsd's and go. :)

**Comment by mjibson** [comment]
You can do exactly that. But the following things won't work:

1. tag value glob matching: `avg:metric.name{tag=something-*}`
2. the items page
3. the graph page's tag list

**Comment by mike-a-davis** [comment]
Awesome, i'll try setting it up.  I made assumption I could only use metrics on items page.  Thanks!
