### ISSUE TITLE
Invite to slack room

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#805]
Hey guys, may I get an invite to the development room on Slack? My email is my username at gmail.com
Thanks in advance

**Comment by kylebrandt** [comment]
Invite sent, reopen if you don't get it.

**Comment by gilesw** [comment]
Hi Kyle,

Could I have an invite? My email is giles dot westwood at gmail...

**Comment by kylebrandt** [comment]
@gilesw invite sent.
