### ISSUE TITLE
bosun (docker container) cannot post to /api/query (tsdb) on port 4242

### ISSUE THREAD

**Issue by jayb904** [bosun-monitor/bosun#807]
Freshly created docker container cannot post to 127.0.0.1:4242/api/query with error connection refused.

I'm under the impression no additional configuration of OpenTSDB is required when using the docker container.

**Comment by vitorboschi** [comment]
You should use port 8070 to access your container. OpenTSDB indeed is running inside your docker container, but port 4242 isn't exported by default, just port 8070

**Comment by jayb904** [comment]
Bosun is running on 8070, but tsdbHost is set to localhost:4242 by default.

**Comment by mjibson** [comment]
You need to expose the port when you invoke docker. Add `-p 4242:4242` to your docker command.

**Comment by jayb904** [comment]
That did it.

The Quick Start guide should be updated as the instructions read:
"$ docker run -d -p 8070:8070 stackexchange/bosun"
rather than
$ docker run -d -p 8070:8070 -p 4242:4242 stackexchange/bosun
