### ISSUE TITLE
Can't close alerts that are fixed; Add timer to close

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#808]
Problem: There is an active alert on the dashboard. You're confident you fixed the issue, but can't close the alert because it is still active. If the time series span is on the longer side, you might be able to close it for quite a while. By then people have moved on and forget so alerts don't get closed. If alerts don't get closed they won't trigger again when people expect them too, therefore important events could be missed.

Possible Solution: Add the ability to close active alerts with a "delayed close". A Delayed close waits for the alert to go back to Normal during the specified duration, when it goes to normal, the alert is closed. Once that happens the timer is cleared so it will alert again if the severity escalates. Alerts will also still trigger if severity escalates during the close window. If never gets to normal and we reach the end of the alert the alert is still closed. That will make it re-trigger on the next run.

The desired result of this behavior is that people can close active alerts in a reasonable way when the  fix a problem that they believe corresponds to the alert.

**Comment by Dieterbe** [comment]
+1 would be very useful.
