### ISSUE TITLE
Can No longer close Unknown "Errors"

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#810]
When we get an error the following generally happens:
 * The alert goes into an err state (and we don't get a notification, https://github.com/bosun-monitor/bosun/issues/766 )
 * The alert then goes unknown. That unknown is for the empty tagset of the alert (I don't know why we do this, have to ask Matt). Errors maybe shouldn't have a notion of Groups and just cover the whole alert? Not sure if we can have errors on only one tagset.
 * Once it goes unknown, you can Forget it.

Now when we forget it, the unknown that was error just comes back on the next run and re-notifies.

**Comment by kylebrandt** [comment]
@captncraig Guess this was introduced with the dependencies merge

**Comment by kylebrandt** [comment]
This is going to be a lot of fun to troubleshoot. After closing it a couple times it finally went away. Then when I tried to the view history of it "os.low.memory{}" that particular one came back on the dashboard.

**Comment by captncraig** [comment]
My thought here is to:

1. Remove the Error -> Unknown transition. Simply don't generate unknown events if the current state is error.
2. At the end of CheckAlert, if no errors occur _and_ an error state is present for alertName{}, generate a normal event for alertName{}

**Comment by captncraig** [comment]
#836 addresses this.
