### ISSUE TITLE
graphite requests - static http

### ISSUE THREAD

**Issue by michnmi** [bosun-monitor/bosun#812]
Hi gentlemen, 
We are going for a ProofOfConcept here on this and I've started working on bosun. 
Since I want to utilize graphite as a backend here, I 've started reading the graphite.go code. 
I see the following : 
1)Uses explicitly http - need to change this in https
2)The GET request on graphite seems to include at times the hostname instead of using it (only) in the header. 
Also, in here:
http://bosun.org/quickstart.html#graphite
you mention : 
>In your config, set
>graphiteHost = http://localhost
Which is wrong because as we said in (1) , you explicitly set http, so it will go and do a GET http://http://localhost

The gist is I want to work on this and start fixing things as I go ahead implementing where I work. Normal pull requerts? I noticed that 20 days ago the chat channel went off. Do I send a join request to you @kylebrandt ? 

Many Thanks
MM

**Comment by kylebrandt** [comment]
@michnmi I just need your email somehow

**Comment by michnmi** [comment]
Hey Kyle,
Thanks for the quick reply
my email is michalis.michaloliakos@gmail.com

If you want my corporate email it's the same @oracle.com - depending on how
you want to
label people in your channel

MM

2015-03-20 15:22 GMT+00:00 Kyle Brandt <notifications@github.com>:

**Comment by kylebrandt** [comment]
Invite sent.

**Comment by kylebrandt** [comment]
@Dieterbe Can you speak to his graphite questions?

**Comment by Dieterbe** [comment]
aha yes we should make the `http://` or `https://` part of the `graphiteHost` config value. yes, please go ahead and submit a PR. thank you.

**Comment by michnmi** [comment]
@Dieterbe  quick change pushed here : https://github.com/bosun-monitor/bosun/pull/824
CC: @kylebrandt
