### ISSUE TITLE
Slow Alerts

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#820]
Our os.diskspace alert runs quite slowly. This doesn't seem to be due to OpenTSDB, but rather time spent in bosun:

![image](https://cloud.githubusercontent.com/assets/1692624/6771648/92de0be4-d0ba-11e4-9939-e68270f06b16.png)

I can't seem to capture where that time is going with miniprofiler. The kprof branch has the instrumentation that you see in the above image.

I also took several heap snapshots of the expression running while no scheduled checks were running. When looking at allocations, I saw reflect.Value.Call growing, it got to about 4 GB:

First Snapshot:
![image](https://cloud.githubusercontent.com/assets/1692624/6771689/3af64034-d0bc-11e4-9250-c9ae75dde1b0.png)

Second Snapshot (Note the change in total as well):
![image](https://cloud.githubusercontent.com/assets/1692624/6771690/4726930e-d0bc-11e4-8b87-08185578c4e7.png)

**Comment by kylebrandt** [comment]
![image](https://cloud.githubusercontent.com/assets/1692624/6791623/cc5f07ac-d186-11e4-85b8-5fe7b067583a.png)

**Comment by captncraig** [comment]
Improved somewhat by #841.
