### ISSUE TITLE
Need Style and Conventions Doc

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#825]
We should have an md for committing. Would have things like:

 * PRs must be squashed before commit
 * Must be go fmt'd
 * Provide a description, unit, and type for all new metrics. Descriptions should not be in the Add line, but in another data structure or a constant (See keepalive collectors for the constants, and the memcached for a datastructure version.
 * Run esc when changing any html or js files
 * JS needs to be compiled from typescript.
 * Everything gets a code review before going into master 

The reason for this is not waste anyone's time. Without this we waste our own time by having to keep telling people about these things, and we waste the time of the commiter by making them jump through unknown hoops.

**Comment by Dieterbe** [comment]
note: i have the habit of running `find . -name '*.go' | xargs gofmt -w` regularly, and often it updates web/static.go like so:
```
diff --git a/cmd/bosun/web/static.go b/cmd/bosun/web/static.go
index da21097..47f6262 100644
--- a/cmd/bosun/web/static.go
+++ b/cmd/bosun/web/static.go
@@ -1802,8 +1802,8 @@ var _esc_data = map[string]*_esc_file{
        },
 
        "/js/.editorconfig": {
-               local: "web/static/js/.editorconfig",
-               size:  55,
+               local:      "web/static/js/.editorconfig",
+               size:       55,
                compressed: "\x1f\x8b\b\x00\x00\tn\x88\x00\xff\x8a֊\xe5\xca\xccKI\xcd+\x89/.\xa9\xccIU\xb0U(IL\xe2*)\xca̍/)J\xcc\xcc\xc9\xccK\x8f
        },
```
this is cumbersome. i presume esc generates this go file, would be nice if it did so in a way that go fmt agrees with.

**Comment by elementai** [comment]
* @mjibson 's `party` tool must be used for adding 3rd party dependencies, details at http://godoc.org/github.com/mjibson/party . That also means all external source files are put into `project_root/_third_party` directory and included into PR.

**Comment by mjibson** [comment]
@Dieterbe that's a bug in `esc` which should be fixed

**Comment by mjibson** [comment]
@Dieterbe esc has been fixed. `go get -u github.com/mjibson/esc` for the new one.

**Comment by mjibson** [comment]
I've made a PR for this: https://github.com/bosun-monitor/bosun/pull/828
