### ISSUE TITLE
Notifications on the Rule Page Are not Loaded when in Lookup Table

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#834]
![image](https://cloud.githubusercontent.com/assets/1692624/6792610/27574062-d190-11e4-85bc-10eceaf576fe.png)

**Comment by Dieterbe** [comment]
very related, possibly same as #749

**Comment by captncraig** [comment]
#868 should make progress towards solving all problems of this nature. New config/rule page in one. Always tests based on the entire config rather than a handpicked subset of the entire config.
