### ISSUE TITLE
Can't get alerts to fire

### ISSUE THREAD

**Issue by kebarcla** [bosun-monitor/bosun#837]
Hello,

Just getting started with writing alerts, and can't get any of them to fire.

We'd like to know if any of our RegionServers go down for example, so I wrote this one:

alert prd_rs {
        template = prd_rs
        $q = min(q("min:hbase.master.server.numRegionServers{host=prdslsldsafht25}", "1m", ""))
        crit = $q < 64
}

so we get an alert any time the number of RS drops below the maximum. It doesn't matter what number we put in for the comparison: we always get 

0 crits, 0 warns

whenever this alert is checked.

Is this the right way to do this kind of test BTW? We want to make sure all the master process for the Hadoop cluster are running and subsequently for the Spark, Elasticsearch,, and other clusters we have also.

Thanks
Ken

**Comment by kylebrandt** [comment]
What shows up when you input `min(q("min:hbase.master.server.numRegionServers{host=prdslsldsafht25}", "1m", ""))` to the expression page?

**Comment by kebarcla** [comment]
It creates the link, which when clicked on correctly shows the number of RS (54) at the bottom, however the graph is blank. The start and end times are one minute apart:

end=2015/03/25-15:10:09&m=min:hbase.master.server.numRegionServers{host=prdslsldsafht25}&start=2015/03/25-15:09:09

and if I add a few minutes to the end time in the Graph tab I see the plot for that time range with the correct value. I changed the time interval to 5m in the alert but still get 0 crits. I'm restarting bosun after each edit of the conf file and the alert does show up correctly in the Rule tab.

**Comment by kylebrandt** [comment]
There should be results on the expression page. What of you increase the
time there?

**Comment by kebarcla** [comment]
If I use 5m for the time interval in the Expression page, I immediately see a graph of the value 54 over the specified interval.

**Comment by kebarcla** [comment]
I noticed that in the Rule window, if I set the start time back 1 day and hit 'Test', it finally does show the alert as critical. So it is retrieving the value and doing the calculation successfully. The only question is why the bosun server doesn't calculate it is as critical when it's running. I have the checkFrequency set to 1m.

![bosun-rule-window-showing-critical-status](https://cloud.githubusercontent.com/assets/8218875/6836874/991ed416-d303-11e4-9a8a-94aa35f7039a.png)

**Comment by kylebrandt** [comment]
Sounds like maybe a timezone issue. Is the bosun host and the opentsdb host set to UTC? Also keeping in mind that you will need a critNotificaiton to get an actual email. (Assuming you are using the dashboard currently to see if it fires).

**Comment by kebarcla** [comment]
I'm just tailing the bosun log and looking for the output:

2015/03/25 21:46:38 check alert prd_rs start
2015/03/25 21:46:38 check alert prd_rs done (3.092ms): 0 crits, 0 warns

and plan to set critNotification & so on when it's working.

Our servers are set for MDT: can you point me to where I'd look up the timeAndDate integers in that case?

Thanks Kyle

**Comment by kebarcla** [comment]
I found if I use "7h", "" for the time intervals, the alert fires. So you're right about the TZ.
Just need to find what timeAndDate should be for MDT and we'll be good to go....

**Comment by kylebrandt** [comment]
Are you using this repo's head or the latest binary from bosun.org ?

**Comment by kebarcla** [comment]
I pulled the binary from bosun.org on 2/21/15 using 'go get.'
Should I update?

**Comment by kylebrandt** [comment]
Yes, very much so. Zillions of issues have been fixed since then (and
others introduced :-P ). Bosun is in UTC time (regardless of system time).
OpenTSDB uses localtime. Someone added a change to switch the queries to
Unix time which might fix it. IF that doesn't work you need to tell
OpenTSDB to use UTC.

**Comment by kebarcla** [comment]
Updated to latest and set timezone on bosun server to UTC (which is where TSDB runs also.)
Alerts are working fine: now working on getting emails to send.
