### ISSUE TITLE
put directly to opentsdb

### ISSUE THREAD

**Issue by Joongho** [bosun-monitor/bosun#838]
I am trying to use bosun in our alerting system.

I'd like to put message to openTSDB directly.
because we have lots of tsd node and make it simple.

and want to use bosun as read-only node.

I tested on my laptop but I am not sure this is supported.

Sorry to ask here.
But I can't find where to ask about setting up bosun.

Thanks.

**Comment by kylebrandt** [comment]
Documented how that works, see the above commit (or the backends section on the configuration page of http://bosun.org )

**Comment by Joongho** [comment]
Hi, 

Thanks for your information.

I noticed that there is already description.

Thanks for your great works.
