### ISSUE TITLE
scollector Windows CPU usage measurement

### ISSUE THREAD

**Issue by skhprabu** [bosun-monitor/bosun#844]
I'm seeing a strange problem in one of my windows server where i'm running scollector. The data for CPU metrics "os.cpu", "win.cpu" is collected incorrectly

For a given Duration, In this example 7:52 AM, Perfmon is reporting the CPU usage(%Priveleged Time , %User Time %Interrupt Time ) of <10% where as when the same data is collected by scollector "os.cpu", win.cpu type=user,  win.cpu type=priveleged, win.cpu type=interrupt
 it is shown as > 80% and it doesn't sync with perfmon information.

I see this issue in only one of my servers, scollector metrics sync's with perfmon's CPU Usage in other servers.

![image](https://cloud.githubusercontent.com/assets/11336922/6846051/4f1f6d24-d391-11e4-9b1b-0cd8549da2c3.png)

![image](https://cloud.githubusercontent.com/assets/11336922/6846225/bd29a252-d392-11e4-92bf-22006cee8437.png)

**Comment by gbrayut** [comment]
First make sure you are using a recent version of scollector (check with -version flag) as there were some issues with some of the older releases. 

Also note that os.cpu is total CPU usage (0-100%) where as win.cpu is per core usage (0-100% per core). Also the raw metric values are [counters](https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/cpu_windows.go#L30) so the "info: queue" lines you see will never match the 0-100% results you should see on the graph or expression pages. Counters make it easier to compute change at multiple points and have higher fidelity/precision than gauges, but you need two data points to compute the metric value (ex [v2-v1]/[t2-t1] ). Opentsdb/bosun will convert counters to their real values when you use the counter series type.

**Comment by skhprabu** [comment]
I seem to be using the latest version of scollector. This is my version

scollector version 20150311224711 (7dc91ad5902bb9316c75321d07268221f64ce3b3) .

Coming to your point, I assume bosun/opentsdb convert counters to real values. Shouldn't the outcome from bosun/tsdb atleast be closer to the outcome of perfmon though they don't match exactly?

The below data is taken from the same server for the same time interval. Only difference is source (tsdb vs perfmon) I see a huge deviation ? If it is a volatile metric like cpu queue length, i can understand.. But, I don't find an explanation for this.. any insight would be helpful ? Is my below assumption right on comparing the CPU counter

Assumption 
\Processor(_Total)\% Processor Time --> os.cpu


As Taken from Perfmon
![image](https://cloud.githubusercontent.com/assets/11336922/6853180/e8269154-d3bf-11e4-911c-bf6baccc2603.png)

As Taken from Grafana/Opentsdb
![image](https://cloud.githubusercontent.com/assets/11336922/6853486/dee2f518-d3c1-11e4-9fa8-0fdd6a810131.png)

**Comment by gbrayut** [comment]
hmm... this may be due to how opentsdb handles [aggregation and down sampling](https://github.com/OpenTSDB/opentsdb/issues/462). How many cores/CPUs are in the server that has issues? Also if you just look at one instance do they match better (\Processor(n)\% * Time should match win.cpu{cpu=n,host=...,type=*} for all cores). 

Also can you try using bosun to generate a graph like this (note the avg aggregator used for win.cpu instead of the default Sum):

![image](https://cloud.githubusercontent.com/assets/304401/6854763/d128f19c-d3b8-11e4-80e7-2b0732259c98.png)

For our Server 2012 and Server 2012 R2 systems this matches very closely with what Perfmon displays

I will also look at adding the \Processor(_total)\% * Time instance to scollector so you have access to the pre-aggregated data using something like win.cpu_total.

**Comment by skhprabu** [comment]
This server has 2 Processor and 12 Cores in total. This is the server model. http://ark.intel.com/products/81900/Intel-Xeon-Processor-E5-2643-v3-20M-Cache-3_40-GHz

Bosun Graph for the same duration.. Still shows about 80% busy
![image](https://cloud.githubusercontent.com/assets/11336922/6855175/680a0c96-d3cc-11e4-8423-903d31c2c8a4.png)

I have about 20 odd windows Servers in my lab, each with multiple cores and this is the only server giving me odd information. Everyother server matches more or less closely with Perfmon for CPU info

I tried instance specific data, but it is not much different as well. Here is for your view
For CPU Instance 5, This is what i find

As in Bosun
![image](https://cloud.githubusercontent.com/assets/11336922/6855345/9f379afc-d3cd-11e4-9968-6c3732ab8c9f.png)

As in Perfmon
![image](https://cloud.githubusercontent.com/assets/11336922/6855350/ae647a4a-d3cd-11e4-89c0-1c68a53a794b.png)

**Comment by gbrayut** [comment]
I merged changes to add the win.cpu_total metric which uses the pre-aggregated values for  "\Processor(_total)\% * Time" via the Win32_PerfRawData_PerfOS_Processor WMI class. You can use a build after e3768ced8ae8ec6174c117aa88738b8a36b20473 to see if the pre-aggregated match what you are seeing in permon.

**Comment by skhprabu** [comment]
I used the win.cpu_total metric after downloading yesterday's build. The Total CPU is almost matching the data i see in perfmon.

**Comment by gbrayut** [comment]
A small amount of variance is to be expected due to sample intervals or the volatility of the data. We still haven't seen any issues with the win.cpu data but will keep an eye out. Glad to hear the cpu_total is working better.
