### ISSUE TITLE
Bosun should support OpenTSDB annotations API

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#852]
Since Bosun is made in a way to sit between collectors and OpenTSDB, it should support the metadata API, as described in http://opentsdb.net/docs/build/html/api_http/annotation/index.html
Without this feature, It's not possible to point applications using this interface to Bosun, instead of openTSDB

**Comment by kylebrandt** [comment]
I think we should just document the passthrough route to opentsdb for this stuff. We don't want to use opentsdb's metadata / annotation system so we can more backend agnostic (plus I found it to be pretty slow)

**Comment by nickman** [comment]
+1

**Comment by captncraig** [comment]
Perhaps the relay could blindly proxy and calls it doesn't recognize?

**Comment by vitorboschi** [comment]
I think it's a good solution

**Comment by kylebrandt** [comment]
bosun has its own annotation system, not going to worry about supporting opentsdb's.
