### ISSUE TITLE
External collector metrics trigger 'unknown' alerts even though data is received

### ISSUE THREAD

**Issue by lukaspustina** [bosun-monitor/bosun#853]
Maybe I have a misconception of unknown alerts, but since running bosun built from source today -- like 1 hour ago -- I see the following unknowns which I can't interpret:
![screen shot 2015-03-30 at 18 07 07](https://cloud.githubusercontent.com/assets/398967/6900590/d4ff2f82-d707-11e4-9dc2-e3741c309ec6.png)

The corresponding scollectors and their external metrics do send data though. Any ideas?

**Comment by captncraig** [comment]
I Believe this was introduced by me with #836 and should be fixed by #842. Sorry about that.

**Comment by lukaspustina** [comment]
Terrific. Thanks for letting me know. Let's build a new version :)

**Comment by lukaspustina** [comment]
Looking good. Thanks again. I'll close the ticket.

**Comment by lukaspustina** [comment]
Sorry, I was to quick on that. Just received the notification E-Mail agains.

**Comment by captncraig** [comment]
Can you try forgetting those alerts and see if they reappear?

**Comment by lukaspustina** [comment]
Which alerts? I don't now about any alerts ... yes, I 'forgot' them all.

**Comment by gbrayut** [comment]
On the dashboard when you select the active alerts there is a forget button at the top. See http://bosun.org/documentation.html#actions

**Comment by lukaspustina** [comment]
@gbrayut I know. I was trying to make a joke :)
I did select to forget the alerts any until now no more "unknown" warning has been fired. Closing this issue again.
