### ISSUE TITLE
The check config option should print errors

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#854]
When using `bosun -c config`, it would be nice if the config errors were printed instead of only just getting a bad exit code.

**Comment by captncraig** [comment]
The only issue I have is that syslog enables itself and suppresses console output. Once I disable that it works as expected:

`./bosun -t -disable-syslog -c="prod.conf"
2015/04/01 08:23:16 conf: prod.conf: parse: prod.conf:1686: unexpected "=" in section declaration
`

**Comment by captncraig** [comment]
Perhaps a patch to make `-t` activate `-disable-syslog` as well could help this.
