### ISSUE TITLE
Include timestamp in the .Alert.Vars object

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#855]
I wanted to include a timestamp in the HTTP Post notification, and was not sure the best way to do that. After playing around for a bit I settled on `at {{.State.Touched.Format "15:04:05UTC"}}` which generates the correct timestamp in my case (a log alert) but am pretty sure the Touched value could be modified and represent something other than the alert timestamp.

Is there a better way to create a timestamp in the alert template? If not can we add .Alert.Vars.Time like is exposed in the Unknown alert template.

**Comment by kylebrandt** [comment]
What exactly should this timestamp represent? I think this needs to be better defined.

**Comment by kylebrandt** [comment]
For example of could be the timestamp of when the alert first triggered (since being closed). It could be the time of the last severity increase....

**Comment by gbrayut** [comment]
There already is some "history" exposed by the .State.History and .State.Actions objects. I believe Touched represents the last time the state was updated. Not sure how valuable a "first triggered" would be unless it is reset after an alert is closed. The only only one I currently wanted was time.Now().UTC() from when the alert was triggered.

**Comment by kylebrandt** [comment]
Can you define what you mean exactly by triggered?

**Comment by kylebrandt** [comment]
Or actually, what is the problem you trying to solve?

**Comment by gbrayut** [comment]
"I wanted to include a timestamp in the HTTP Post notification"

**Comment by kylebrandt** [comment]
Right, we can include all sorts timestamps. I could make one that just returns this constant string everytime "Tue Mar 31 16:20:38 UTC 2015" which would be obviously useless. What I'm try to get from you is what exactly is being stamped. What is the event you would like the timestamp to represent?

**Comment by gbrayut** [comment]
Assuming I was posting to something that forwarded via SMS text message (which can have a large delay), some indicator of what time the event actually occurred. Even on our chat system I can see that the Touched timestamp is more than 10s older than when the post was created in chat.
