### ISSUE TITLE
Emails not being received  - how to debug?

### ISSUE THREAD

**Issue by kebarcla** [bosun-monitor/bosun#856]
We're running bosun on Centos 6.4
I can use mailx to send emails from the bosun host, but bosun isn't sending any emails when configured as below:

smtpHost = mail.ancestry.com:25
emailFrom = kbarclay@ancestry.com

notification email {
        email = kbarclay@ancestry.com
        next = email
}

I can telnet to the SMTP host and port above: seems to be OK
Alerts are definitely being created 
I don't see any errors in /var/log/messages

Any suggestions how to track down where the problem lies?
Thanks
Ken

**Comment by mjibson** [comment]
You'd need to post a more full configuration file. Are alerts showing up on the dashboard? Also try adding `print = true` to the notification, which will print something to the log.

**Comment by kebarcla** [comment]
We are currently getting two alerts on the dashboard that are critical, prd_rs and sbx_rs.
We're getting warnings from cpu.too.high, defined below.

In the log file I see

Mar 31 15:33:11 prdslsldsafht30 bosun[10139]: 2015/03/31 21:33:11 check alert sbx_rs start
Mar 31 15:33:12 prdslsldsafht30 bosun[10139]: 2015/03/31 21:33:12 check alert sbx_rs done (44.081285ms): 1 crits, 0 warns, 0 unevaluated, 0 unknown
Mar 31 15:33:12 prdslsldsafht30 bosun[10139]: 2015/03/31 21:33:12 check alert prd_rs start
Mar 31 15:33:12 prdslsldsafht30 bosun[10139]: 2015/03/31 21:33:12 check alert prd_rs done (14.244546ms): 1 crits, 0 warns, 0 unevaluated, 0 unknown
...
Mar 31 15:33:29 prdslsldsafht30 bosun[10139]: 2015/03/31 21:33:29 wrote notifications: 48.00B

and I added 'print = true' to the notification but it seems not have changed anything.

This is the conf file (most templates removed):

smtpHost = mail.ancestry.com:25
emailFrom = kbarclay@ancestry.com
httpListen = :8070
timeAndDate = 202,75,179,136
stateFile = ../bosun.state
checkFrequency = 1m

notification email {
        email = kbarclay@ancestry.com
        next = email
        print = true
}

template sbx_rs {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Name: {{.Alert.Name}}
	<p>Tags:
	<table>
		{{range $k, $v := .Group}}
			<tr><td>{{$k}}</td><td>{{$v}}</td></tr>
		{{end}}
	</table>`
}

alert sbx_rs {
	template = sbx_rs
	crit = min(q("avg:hbase.master.server.numRegionServers{host=prdslsldsafht30}", "5m", "")) < 10
}

alert prd_rs {
	template = prd_rs
	$q = min(q("min:hbase.master.server.numRegionServers{host=prdslsldsafht25}", "5m", ""))
        crit = $q < 64
}

alert cpu.too.high {
        template = test
        $metric = q("avg:rate{counter,,1}:os.cpu{host=*}", "1h", "")
        $avgcpu = avg($metric)
        crit = $avgcpu > 80
        warn = $avgcpu > 60
}

**Comment by mjibson** [comment]
See `critNotification` in http://bosun.org/configuration.html#alert

**Comment by captncraig** [comment]
Specifically, you didn't link the alert to any notifications.

`critNotification = email` in your alert should do the trick.

You should only do `next = email` in the notification if you want to be nagged until the alert is acknowledged. If you only want it to send once you don't need to set up the notification chain that way.

**Comment by kebarcla** [comment]
Got it working: in addition to leaving out the critNotification from the alert, our SMTP server config would only work if we used the IP address & not the hostname.

We may also have a bit of what was mentioned in Issue #655 going on but I think from that thread I understand what to do about it.

Thanks ya'll.
