### ISSUE TITLE
cmd/bosun: aggregation endpoint (statsd-like)

### ISSUE THREAD

**Issue by elementai** [bosun-monitor/bosun#858]
In many cases one wants to monitor, for example, web server log data that can generate a lot of events. Usually there's statsd or similar event aggregating part put in-between.

It's probably rather easy to implement that part in Bosun via like `/api/aggregate` endpoint to calculate percentiles, mean, etc metrics just like statsd does.

**Comment by kylebrandt** [comment]
I'm not sure if this should be bosun's job. Bosun works with time series and not events. Generally the more efficient place to turn events into aggregated buckets closer to where they are being generated. So for example if you want to count log events have your log processor (i.e. logstash, flume?, those things) do it, and when instrumenting an application have the library do that.

**Comment by Dieterbe** [comment]
+1 on what kyle said.

**Comment by elementai** [comment]
Makes much more sense to me now. I just want to make things simple(r). It's much easier to just spew events _somewhere_ not thinking about aggregation and stuff. Considering data locality, if not Bosun, maybe scollector listening locally then? Or even another `cmd/saggregator-whatever` accepting OpenTSDB protocol? That way one can reuse scollector configuration including Bosun URL and host tags. More to that its one less protocol(statsd) to worry about.

**Comment by gbrayut** [comment]
Scollector currently does limited processing of data before sending it to bosun. If you are looking at doing bulk processing or aggregation of data similar to statsd then that should probably be a separate program. You might want to look at using https://github.com/reddit/tallier which a go based replacement for statsd used by reddit.

**Comment by elementai** [comment]
Ok, thanks you for responses. I'll open another issue/PR when I have a better plan on how to write a separate program.
