### ISSUE TITLE
Scollector: Unique tagset for each SNMP host. 

### ISSUE THREAD

**Issue by jemilsson** [bosun-monitor/bosun#861]
It would be great if each SNMP host polled could have a unique set of tags. Perhaps something along the line of:

-s=""
    SNMP host to poll of the format: "community@host&tag1=value1&tag2=value2...[,community@host&tag1=value1&tag2=value2...]".

Using this syntax you could also allow overwriting the hostname.

Ideas?

**Comment by mjibson** [comment]
The problem this creates is that similar collectors (vsphere, aws, ping) could reasonably also want this feature. I recommend instead running multiple copies of scollector with their own `-t` flag. You'd also need `-m`, `-n`, and `-f` to cause scollector to only report metrics for the SNMP host you are on.

**Comment by jemilsson** [comment]
I suppose it would be a nice feature for the other collectors polling remote hosts. 

In my use case running multiple instances of scollector has me worried about performance. We will be doing SNMP polling of a large number of devices. Around 30 000 hosts according to our last estimate, and there will be many different tagset. Running an instance per tagset would cause a lot of overhead i imagine. Perhaps using Scollector is the wrong choice, but it seems like an attractive choice given that we are planning on using Bosun and OpenTSDB for alerting and storage of the data.

**Comment by mjibson** [comment]
You have 30,000 SNMP routers/switches? That's pretty much the only thing SNMP mode is useful for. If you have 30,000 hosts/machines, then you should install scollector on each. SNMP mode only collects a tiny subset of information, it does not collect all SNMP info available.

**Comment by jemilsson** [comment]
Yes, 30 000 modems/switches so they are not able to run Scollector on their own unfortunetly.
We will be having around 750 unique tagsets so i guess it would be possible to have a different instance of Scollector per tagset. But i still think that it is logical to support having different tagsets per host when doing data gathering of remote hosts.

**Comment by kylebrandt** [comment]
What is your intended polling frequency? This is kind of a tangent, just trying to understand your plans

**Comment by jemilsson** [comment]
We plan on polling each device every 5 minutes.

**Comment by mjibson** [comment]
We talked about this and decided that we would be willing to merge this feature, but we don't have resources to devote to writing it ourselves currently. We would be happy to discuss how this should work (maybe in our [slack room](https://bosun.slack.com/)).
