### ISSUE TITLE
error: metadata.go:216: Post http://localhost:8070/api/metadata/put: dial tcp 127.0.0.1:8070: connection refused

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#864]
i get the error in the subject upon startup.

my config is

```
smtpHost = ...:25
graphiteHost = ..
emailFrom = foo@example.com
httpListen = :8070
timeAndDate = 202,75,179,136
stateFile = ./bosun.state
checkFrequency = 1m
(...)
```

since i don't use any of the opentsdb stuff, perhaps this is caused by the new instrumenting alerts feature?

**Comment by mjibson** [comment]
Metadata doesn't have anything to do with OpenTSDB (it is all stored in bosun). Will research.

**Comment by mjibson** [comment]
I can't repro this. Network configuration issue? This is one of the few places where bosun is connecting to itself via localhost.

**Comment by Dieterbe** [comment]
maybe it's since https://github.com/bosun-monitor/bosun/commit/cc7b0ec ?

**Comment by captncraig** [comment]
That is certainly not the first time we were doing `collect.Put` from bosun stuff.
