### ISSUE TITLE
Move the OpenTSDB Relay into a independent Process

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#866]
The relays job is to is to collect tag information. It extends OpenTSDB's tag capability in two ways:
 
 1. In allows for globbing of tags, for example `ny-foo*`
 2. It lets use keep a relational structure of tag information: This metric has these tags, and that metric tag combination has these values etc...

A couple of features depend on this working:

 1. The Items Page
 2. The graphing Page 
 3. Others...?

This results in a few different issues:

 * Other backends are not as well supported. They could be if bosun used an API to get this information. Our Relay process could fulfill that API, and people could make other stuff to fulfill the api for other backends.
 * When Bosun crashes, so does our relaying of data. We have been dancing around this problem by adding delays to bosun's check cycle. 
 * People with existing OpenTSDB installations have to relay through bosun, and that might cause availability and scaling issues. We already see the reliability issues.

If we make tag and relational tag information available via an API from a separate process this gives us:
* more options
* better reliability (there is the assumption here that we won't have more outages due to the complexity, but I don't think this change is •that* complex, in particular the first iteration.
* It will help with Geographic scaling because we could have some method of combining the information from multiple sources to a single bosun instance (raft from the relays, or bosun does the aggregation, something like this).
* Make having independent development instances better because they can get the tag information from prod in a read only mode.

Big change, but I think an important one in the long term. Although not as simple to deploy, I think we can automate most of this and have a more reliable and scalable design. We could also have a standalone mode where bosun manages a single relay process itself to make it mostly transparent for small or testing installations.

**Comment by captncraig** [comment]
How will we communicate between the relay and the web-app? On-demand queries? Periodic file dumps of the search data? A persistent tcp connection?

What about clustering for scalability? Can I run 4 relays on different hosts and aggregate their search metadata back to bosun? 

If such a thing is available, perhaps the pings could be moved into scollector, who can query the relay for hosts to ping.

Just a few thoughts.

**Comment by gbrayut** [comment]
Having never looked at this part of bosun, I'm curious why a relay is required. Does OpenTSDB not have API methods we can call to gather the data we need? Is there a way of having OpenTSDB (or a simple http mirror process) forward a copy of the OpenTSDB traffic to bosun so we can create the metadata we need but are not a point of failure in getting data into the system? I'm sure these options were looked at before but for us newbies it would be nice to know why bosun HAS to be in between the client and back end server.

**Comment by Dieterbe** [comment]
related projects that do this for graphite https://github.com/vimeo/carbon-tagger and graph-explorer's structured-metrics (https://github.com/vimeo/graph-explorer/wiki/Structured-Metrics). not super relevant here perhaps, except for the fact that they use an elasticsearch index to maintain the tags metadata, which has proven to be very fast or all kinds of queries i've thrown at it (even regex).

currently none of this is currently leveraged in bosun (you define your "tag interpretation" at query time for graphite queries), but it could be more feasible if we do a similar approach for openTSDB.

**Comment by kylebrandt** [comment]
Re @gbrayut OpenTSDB has both of these things but not the globbing. It can both emit datapoints and and collect metadata information about tags. They also have a search API you can hook into. 

Also this stuff makes OpenTSDB something like 10x slower and less reliable last time we tried it. We could try it again. I'm not totally sold on a specific implementation, but I think having Bosun itself be the relay has resulted in the problems I stated.

**Comment by kylebrandt** [comment]
How will we communicate between the relay and the web-app? On-demand queries? Periodic file dumps of the search data? A persistent tcp connection?

Some sort API. SE has some devs to figure this stuff out ;-)

"What about clustering for scalability? Can I run 4 relays on different hosts and aggregate their search metadata back to bosun?"

Yes this would be what we are after. I don't know if they should just send their information and let bosun handle the aggregation, or if the relays would handle this (if relays are even the right way to go as greg suggests). Sounds simpler to have bosun do that.

"If such a thing is available, perhaps the pings could be moved into scollector, who can query the relay for hosts to ping."

I'm also keen on exploring elastic, but I don't think elastic is that great at geo distributed clusters. @NickCraver  would know more about that than I.

**Comment by gbrayut** [comment]
Can we source the data required to support globbing in bosun without being in between the client and backend? If we were to poll their api regarding tags could we get what we need? I assume detecting unknown would be more difficult with that approach, but using a mirror of the stream would be another approach that doesn't require us being a point of failure. If OpenTSDB can forward a raw stream to bosun (similar to how we setup our network gear to point to omni) that seems like a more stable approach than our current system or even your proposed changes (although those still would offer additional benefits)

And re Elastic... I'd rather not introduce a new external dependency if possible.

**Comment by kylebrandt** [comment]
@captncraig  Oh, and scollector can already do the same ping information. currently it only gets it from the command line. So I was thinking "I will just change scollector to get the information from bosun and do it instead." But then I realized that would only help so much since the relay would be down too. I could send directly to OpenTSDB but....

**Comment by kylebrandt** [comment]
@gbrayut Ya globbing isn't the hard problem once we have the data I don't think. OpenTSDB emitting the data points slows it down a lot, and doesn't provide a common interface other backends could use. 

Unknown won't be an issue. We don't use the relay search data for that, we use tags bosun has learned about for various alerts ( alertname+tagset) forms the identifier.

I'm not keen on external dependencies either. But I worry we may dogmatic in that concept in a way that could hurt us - using lesser technology.

**Comment by kylebrandt** [comment]
@mjibson is going to explore some of opentsdb's apis and plugins to see if we can avoid the relay entirely
