### ISSUE TITLE
"Global" rate limiter for all alert notifications generated during a check run

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#867]
I chatted with Kyle about how to prevent our new NTP alert from blowing up if there were issues with the NTP servers. In the end we settled on using the new dependency feature, but we also identified the need for a "global" rate limiter when a large number of alerts are generated during a check run. We currently have a rate limiter for unknown alerts that prevents sending a large number of emails for unknown alerts, but Kyle agreed that having a "never send more than x00 or x0 notifications during a single check run" sounded like a good idea.

**Comment by Dieterbe** [comment]
so if a collague gets his 100 alerts because all his checks are failing, i will not get the alert i need for an alert i set up due to the global rate limit?

I don't see how this makes sense in bosun, where you have an arbitrary amount of people maintaining their arbitrary amount of alerts, none of them needs to care about, or should be affected by each others stuff.  limits that are per-email address or per notification sounds better to me.

**Comment by gbrayut** [comment]
This would be optional/configurable, but our goal is to never get 100 emails in a single check run. Instead we should have dependencies in place so we get notified about the root cause or a bulk "this service is out on these 100 systems" email. If bosun tries to send 100 alert emails, usually something is wrong or we need to redefine the alert at a different level (cluster vs host for example)

**Comment by Dieterbe** [comment]
so wait, you're saying this limit is scoped within the execution of an alerting rule?
not sure what you mean with "check run", you mean the run of 1 particular alerting rule? in that case, this sounds good to me.

**Comment by gbrayut** [comment]
"check run" is when all the alert rules are checked. Occurs every 5 minutes usually. At the end of that bosun will send out notifications for for active alerts. If that count is > some number we would bulk them like we currently due for unknowns instead of sending individual emails.

Having it be per email address or per notification would be another options. Right now we have a lot of cases where something goes wrong and we get a bunch of emails we dont really want.
