### ISSUE TITLE
dashboard notification "Loading..." is so long

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#869]
![image](https://cloud.githubusercontent.com/assets/2918384/6978440/78b1a646-da05-11e4-934d-6887d07baf43.png)

**Comment by Dieterbe** [comment]
+1 also seeing this a lot

**Comment by gbrayut** [comment]
This should be fixed now that the history doesn't contain the computations. Please create a new issue if you see it happening again on the latest build.
