### ISSUE TITLE
[Question] How to query logstash

### ISSUE THREAD

**Issue by txchen** [bosun-monitor/bosun#871]
I tried to follow the document but failed to figure out how to query the ELK's elasticsearch.

The query I am using: lscount("logstash-2015.04.04", "*", "", "10m", "3d", "")

And I got nothing.

Can someone share some information about how to use LS in bosun, thanks in advance!

**Comment by kylebrandt** [comment]
Just "logstash" as the first argument. We generate the date portion of the
index names for you based on the query time range. Second field can just be
blank if you are going to use star. But you might have something like
"logsource" if you want the results grouped by logsource.

**Comment by txchen** [comment]
@kylebrandt thanks! I changed to `lscount("logstash", "", "response_code:200", "5m", "2d", "")` now I can get some data.
I will continue to try it. It would be nice if in the document, some simple examples are provided.

Thanks again!
