### ISSUE TITLE
`application/x-www-form-urlencoded` is hardcoded

### ISSUE THREAD

**Issue by ayashjorden** [bosun-monitor/bosun#873]
HTTP POST/PUT can handle different 'Content-Type'-s, the above is hard-coded in [several places](https://github.com/bosun-monitor/bosun/search?utf8=%E2%9C%93&q=x-www-form-urlencoded).

**Comment by captncraig** [comment]
Will add a `contentType` configuration option you can include in a notification like so:

    # post to a slack.com chatroom 
    notification slack{
	  post = https://company.slack.com/services/hooks/incoming-webhook?token=TOKEN
	  body = payload={"username": "bosun", "text": {{.|json}}, "icon_url": "http://stackexchange.github.io/bosun/public/bosun-logo-mark.svg"} 
      contentType = application/json
    }
