### ISSUE TITLE
Configuration parsing message inaccurate

### ISSUE THREAD

**Issue by captncraig** [bosun-monitor/bosun#882]
Sometimes parse messages are a bit off. Particularly, when adding jibberish like so:

![screen shot 2015-04-09 at 3 26 32 pm](https://cloud.githubusercontent.com/assets/192540/7077312/f8c0c774-decc-11e4-9e53-db3cc237ee1b.png)

I would expect a "unexpectd sdfsdf" on line 502 message instead of the one I got.

**Comment by mjibson** [comment]
I think the error message is pretty ok. If you have a proposal I'd review it.
