### ISSUE TITLE
Documentation indicates web assets are bundled with bosun binary, does not appear to be the case

### ISSUE THREAD

**Issue by PeterGrace** [bosun-monitor/bosun#896]
When attempting a bosun install from binaries available on busn.org/downloads.html, an error occurs due to web assets not found:

> 2015/04/13 20:33:50 RestoreState
> 2015/04/13 20:33:50 metric unknown bucket: bindata
> 2015/04/13 20:33:50 tagk unknown bucket: bindata
> 2015/04/13 20:33:50 tagv unknown bucket: bindata
> 2015/04/13 20:33:50 metrictags unknown bucket: bindata
> 2015/04/13 20:33:50 notifications unknown bucket: bindata
> 2015/04/13 20:33:50 silence unknown bucket: bindata
> 2015/04/13 20:33:50 status unknown bucket: bindata
> 2015/04/13 20:33:50 metadata unknown bucket: bindata
> 2015/04/13 20:33:50 RestoreState done in 346.002µs
> 2015/04/13 20:33:50 starting check
> 2015/04/13 20:33:50 using local web assets
> 2015/04/13 20:33:50 open web/static/templates/index.html: no such file or directory

Steps to reproduce:

```bash
wget https://github.com/bosun-monitor/bosun/releases/download/20150409220449/bosun-linux-amd64
mkdir -p /opt/bosun/data
mv bosun-linux-amd64 /opt/bosun/bosun
chmod +x /opt/bosun/bosun
cd /opt/bosun
echo dHNkYkhvc3QgPSBsb2NhbGhvc3Q6NDI0MgpzdGF0ZUZpbGUgPSAvb3B0L2Jvc3VuL2RhdGEvYm9zdW4uc3RhdGUK | base64 -d > /opt/bosun/reprod.conf
/opt/bosun/bosun -c="reprod.conf" -dev=true
```

**Comment by mjibson** [comment]
```
% bosun --help
Usage of bosun:
[...]
  -dev=false: enable dev mode: use local resources
[...]
```
