### ISSUE TITLE
Separate relay process

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#904]
Problem: if for any reason bosun is down, the data relay breaks for OpenTSDB. When bosun is back up, many alerts go unknown before the data can be restored. It is also not scalable, since all OpenTSDB data must go through a single host. The sole purpose of the relay is to index the metric and tag data for tag search.

Proposed solution:

Have a completely separate process that handles the relay to OpenTSDB and collects all needed data for tag search. Bosun gets a new API that is exposed to the web for pushing tag search data. The relay writes the tag search data to this API at some interval. This will allow the relay to continue while bosun is restarting or crashed, and still maintain the search database.

The existing relay code in bosun can be kept for those who do not want to run a separate relay process. This relay will be changed to write to the new search API listed above.

**Comment by captncraig** [comment]
How will we support multiple relays? I assume the push apis will aggregate data as it comes in?

**Comment by mjibson** [comment]
Each relay can push tag search data to the API on its own. The API is in charge of aggregation, not the relays.

**Comment by mjibson** [comment]
While implementing this I ran into some problems. Currently our search service records the most recent 2 data points for each metric+tag combination, for use with opserver (http://bosun.org/api.html#apihost). Relays make this pretty complicated. I'm thinking about instead using a model where the relay has no idea about the data, it just listens on a port and sends data to as many locations as specified.
