### ISSUE TITLE
How can bosun check if metrics does not exist?

### ISSUE THREAD

**Issue by Joongho** [bosun-monitor/bosun#907]
I am trying to check simple sum like below.
sum(q("sum:metrics.count", "20m", ""))

But if metrics does not exist,  ( due to agent down ) 
how can it evaluate ?

thanks.

**Comment by kylebrandt** [comment]
When you have an alert defined on a metric or set of metrics, and data is
no longer available a  group that was present before (aka tag set), the
alert will go into unknown status for that group. See the usage
documentation for more info in this state
