### ISSUE TITLE
The page at <url> says: <blank> dialog

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#915]
On our Bosun dashboard some of the alerts take a while to render the template. After the rendering times-out and you then try to expand another alert it will sometimes display the following message:

![pasted-image-png](https://cloud.githubusercontent.com/assets/304401/7284371/4938e7fe-e8fa-11e4-92ed-d58d66924e9c.png)

This can sometimes be reproduced in Chrome by expanding the "critical - haproxy.server.downtime" alert on our dashboard and then try expanding other alerts.

The loading issue is probably related to issue #869

**Comment by mjibson** [comment]
I think this got fixed by the computation removal. If you see it again repost.
