### ISSUE TITLE
alerts with nothing in them and since/touched 00s ago

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#917]
i often get stuff like this on the dashboard:
![weird](https://cloud.githubusercontent.com/assets/20774/7284492/160b45b8-e90c-11e4-8241-0fb614a68333.png)

interesting remarks:
* subject rendered fine, but not body
* status is empty 
* since and touched 00s ago
* expr is empty

looking at js console in chromium -> no errors
network tab:

* /api/status?ak=requests_by_country%7B%7D
-> 200 OK with 9.5MB of data txferred,  though chromium says "failed to load response data"

* /mini-profiler-resources/results
200 OK
```
{"Id":"49246820296ae271","Name":"bosun.org/cmd/bosun/web.func·015","Started":1429734332000,"MachineName":"graphite1","Root":{"Id":"4871be7dd0744567","Name":"GET http://bosun.vimeows.com/api/status?ak=requests_by_country%7B%7D","DurationMilliseconds":17468.56982,"StartMilliseconds":0,"Children":null,"CustomTimings":null},"ClientTimings":null,"DurationMilliseconds":17468.56982,"CustomLinks":{}}
```

**Comment by kylebrandt** [comment]
We see this as well. Greg was going to file an issue today actually..

**Comment by Dieterbe** [comment]
FIRST!

**Comment by gbrayut** [comment]
The issue I filed was regarding a specific empty dialog I saw. See #915 although they both may be related to the loading issue #869

**Comment by kylebrandt** [comment]
Assuming this is fixed since the two referenced issues are fixed, please reopen if you still see this.
