### ISSUE TITLE
Queries to /server-info

### ISSUE THREAD

**Issue by k-bx** [bosun-monitor/bosun#920]
After I've installed bosun in a docker-container and some scollectors on my web application worker servers, they started logging these entries:

```
No handler found: /server-info User-Agent: Go 1.1 package http
```

So it seems that bosun is trying to ping `/server-info` endpoint on 80 port, but since web apps are running on those servers, they log it as "no handler found".

Can this be fixed somehow? I'm not sure on the purpose of doing these requests. Thanks!

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/pull/892 - Maybe image needs to be updated?

**Comment by k-bx** [comment]
Yes, I think I did the setup last Wednesday, so maybe image-update needs to be done.

**Comment by k-bx** [comment]
@kylebrandt just tried fresh image (`docker pull` showed something that seemed like a new content downloaded), it still sends those queries

**Comment by gbrayut** [comment]
You will need to update the scollector agent binary on your web servers using the latest version at http://bosun.org/scollector/

You can see what version they are currently running using scollector.exe -version

**Comment by k-bx** [comment]
@gbrayut seems like it helped, thanks!

**Comment by k-bx** [comment]
@gbrayut oops, it seems issue is still present after updating scollector.

```
deploy@builder:~$ ssh app1 scollector --version
scollector version 20150428222252 (8e4440108b9154fa20f485469a31f0c19e7607d2)
```

**Comment by gbrayut** [comment]
The requests you are seeing are from the scollector [c_apache_mod_info](https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/apache_mod_info_linux.go#L25) collector trying to detect if Apache is running on your app1 server. The local scollector agent will make a request every 5 minutes to http://127.0.0.1/server-info and check for the string "Apache Server Information". If that url is not valid or the string is not found, it will disable the collector until the next time it checks for new services (~ every 5 minutes)

Scollector is designed to automatically detect services and start sending metrics, so if these requests are causing issues your options are:

1. Ignore the messages in your application logs, or find a way to block scollector from reaching that url

2. Use the [-f flag](http://godoc.org/bosun.org/cmd/scollector) to tell scollector to only run specific collectors. If you just wanted disk and process stats you could use `scollector -f "c_iostat,c_dfstat,c_procstats"`. The list of collectors can also be included in the scollector.conf file using the filter directive like so: `filter=c_system,c_windows_,c_simple_mem_windows`. Use scollector -l to get a list of available collectors.

We don't currently have the ability to exclude just an individual or specific list of collectors, but I will look at adding that.

**Comment by k-bx** [comment]
@gbrayut thanks for a detailed explanation! Now I see what's going on. I won't log url-not-found info for this url.

**Comment by gbrayut** [comment]
FYI... scollector now allows you to exclude individual collectors, so you can disable the /server-info requests by adding the following to the scollector toml file:

```
Filter = ["*","-c_apache_mod_info"]
```
