### ISSUE TITLE
Recovery Conditions / Asymmetrical rules

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#922]
Currently there is no direct way to have an alert go back to normal other than the warn/crit/... expressions are no longer true. So basically !(warn || crit). What I would like to have is an expression that must be True as an additional requirement to returning to normal.

The problem I have is that icmp pings are a reasonable dependency for hosts, but hardware in particular might respond to pings for a long time before scollector is up.

I can try to invert the logic and make an additional part of the crit expression which may sort of do this, but it is really confusing, and I'm not sure I even have it correct:

```
alert host.down {
    template = generic
    macro = host.based.contacts
    $unit_string = Bosun ping timeout
    $last_two = rename(q("sum:bosun.ping.timeout{dst_host=*,host=*}", "2m", ""), "host=source,dst_host=host")
    $previous_four = rename(q("sum:bosun.ping.timeout{dst_host=*,host=*}", "5m", "1m"), "host=source,dst_host=host")
    $five_to_seven = rename(q("sum:bosun.ping.timeout{dst_host=*,host=*}", "7m", "5m"), "host=source,dst_host=host")
    crit = min($last_two) || (min($five_to_seven) && max($previous_four))
}
```

In this case the additional crit condition should still be "crit" because of the OR as the host comes backup. But that is assuming a five minute run interval, and the logic is all inverted. Better would be `recovery = max($last_five)` since that is a more natural way to think than trying to add an OR condition that says "still crit/warn". The recovery expression only needs to be evaluated if we are already in crit or warn and the crit/warn expressions are no longer true (so the recovery condition is ANDed to the !(crit || warn), else it might start flapping. I don't think this needs to apply to unknowns.

**Comment by mjibson** [comment]
I don't see how dependencies don't meet this requirement already. Can you put this other condition into the dependency check as well?

**Comment by kylebrandt** [comment]
@mjibson  I don't follow, example?

**Comment by kylebrandt** [comment]
To do this feature right we think we need another state. Until we have more uses for recovery conditions this won't be a priority since the work/reward isn't sensible right now.

**Comment by captncraig** [comment]
One thing that might help would be a function:

`ensureRecovery($realCrit, $recoveryExpr)` that will automatically look at the history (via opentsdb or otherwise) and only elaluate the recoveryExpr if the previous state was failed AND the current critExpr is normal.

**Comment by captncraig** [comment]
That takes the route of making it easier to do this in raw expressions.

**Comment by kylebrandt** [comment]
I like that idea. Only concern is adding stuff that makes the timeline test less useful. Maybe we look at this once we have a runhistory for that page...?

**Comment by kylebrandt** [comment]
Closing as archived since we are not going to work on this anytime soon.
