### ISSUE TITLE
Add a section for recently closed alerts to the Dashboard

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#931]
While talking with Kyle about the upcoming alert ids and the ability to create links to individual incidents, we started talking about links to the dashboard and how they might become stale when an alert is closed. This lead to the idea of adding a section that shows a list of recently closed alerts (example last 24 hours worth or last 50 closed alerts). This could be in a collapsed section (or semi-collapsed if we wanted to still display a small number) or even on a separate tab.

Full discussion in Stack Exchange Company Chat at http://chat.meta.stackexchange.com/transcript/message/3387941#3387941

**Comment by captncraig** [comment]
The incident search api I am working on should easily facilitate this.
