### ISSUE TITLE
Bosun Rule Editor: Ability to quickly switch between template and alert definitions

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#964]
I end up switching between the template and alert definitions a lot when working on alerts. Previously they were in separate editors, so it was easy, but now it is harder due to having to locate it in the drop down. Two approaches to making this easier:

1. Add a second instance of the editor to the rule page (or potentially more than 2 as needed)
2. Add a toggle button in the "jump to" row that lets you switch between the template and the alert definitions with a single click.

Option 2 shouldn't be that hard, since we already track the "active alert" that will be used when pressing the Test button. Getting the template information should be a simple regex and the toggle button can then let you bounce between the two.

**Comment by kylebrandt** [comment]
Nice idea with swap button
