### ISSUE TITLE
Feature request: Add units to alert graphs

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#968]
When looking at a graph, it can sometimes not be immediately clear what the Y axis unit is. For example:

![image](https://cloud.githubusercontent.com/assets/218431/7640141/dc9f3f72-fa2d-11e4-98cb-bfebca84fb07.png)

Would be nice to have the unit info included so that it is immediately obvious.

**Comment by vitorboschi** [comment]
While on that, it'd be good to have the option to set the min/max values for the Y axis.

**Comment by mjibson** [comment]
@kyle since expressions don't map directly with units, I think these options would have to be specified in the `{{.Graph}}` command. Are you ok with something like: `{{.Graph .Alert.Vars.q "bytes"}}`?

**Comment by kylebrandt** [comment]
A common pattern I think would be to get the metadat and pass that as the
argument. That might not look very nice nested in templates. Any ideas on
making that better?

**Comment by gbrayut** [comment]
This is now available using Graph(expression, y_label) in a template which can be used like `{{.Graph .Alert.Vars.q "bytes"}}`. There is an equivalent version of the GraphAll function.
