### ISSUE TITLE
Allow to configure a concrete indexRoot to lscount/lsstat

### ISSUE THREAD

**Issue by ayashjorden** [bosun-monitor/bosun#974]
Hi,
Sometimes, one would like (the great) Bosun to query the same Elasticsearch (ES) index for an alert.
Current implementation force the user to use 'prefix-yyyy.MM.dd' index naming convention.

Suggested is to allow the user to configure an indexRoot that will be used as the index name, without Bosun need to suffix it with something or any other changes.

Example use-case is ES indices with a small size of a couple of MB per day. ES indices are an expansive unit in matter of RAM and CPU to maintain it.

Currently I solved this by creating a single index 'my_index-global' and funneling all the relevant logs into it. the I crontab-ed an alias creation  command to add aliases matching Bosun requirements.

Thanks,
Yarden

**Comment by kylebrandt** [comment]
Best idea I have thought of is to have the prefix argument take a special
character at the end that is not allowed in index names....

**Comment by gbrayut** [comment]
Or you could use a verbose postfix. logstashWITHOUT-A-DATE works just as well as logstash@ or whatever obscure character with unknown meaning we can come up with

**Comment by ayashjorden** [comment]
Verbose postfix may create noise in configuration code, and we cant use the
$(regex end of line and bosun var prefix)
Can we do #,<,@       ?

**Comment by gbrayut** [comment]
I think https://github.com/elastic/elasticsearch/issues/9059 talks about the valid characters for index names.

* must be lowercase
* must NOT start with an underscore, a + or a -
* index names starting with '.' are reserved
* . and .. are forbidden, though they can occur in the name
* `\`, `/`, `*`, `?`, `"`, `<`,` >`, `|`,` `,`,` are forbidden

**Comment by kylebrandt** [comment]
I don't have any particular preference, which character if single
character, or if verbose

**Comment by gbrayut** [comment]
I'd say * and ? should be avoided since we may want to support globs on metrics at some point. So any of the other forbidden index characters would work.

**Comment by ayashjorden** [comment]
Is pipe a reserved char in Go Template or somewhere in Bosun?

**Comment by ayashjorden** [comment]
@kylebrandt suggested to short-circut GenIndex function after initializing ES client:
```GO
	if len(r.IndexRoot) > 0 {
		if r.IndexRoot[len(r.IndexRoot)-1] == '/' {
			return r.IndexRoot[:len(r.IndexRoot)-1], nil
		}
	}
```

Tested on my dev-env and it works great!
Can you please add it to next release?

Thanks,
Yarden
