### ISSUE TITLE
We received an air themed email

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#979]
Has anyone encountered a similar situation?
No subject, no content

**Comment by mjibson** [comment]
What version of bosun are you using?

**Comment by Dieterbe** [comment]
yes

**Comment by wkshare** [comment]
Self compiled, the last commit:
commit bedabb504344b762f6a90f57bfca038fcfdbcdd9
Merge: c8af246 6f7dca9
Author: Matt Jibson <matt.jibson@gmail.com>
Date:   Mon May 18 18:29:13 2015 -0400

    Merge pull request #973 from bosun-monitor/expr-short-circuit
    
    Short circuit || and &&

**Comment by wkshare** [comment]
T_T why,  How to debug

**Comment by tdinucci** [comment]
Closing as very old and not enough info to attempt to reproduce
