### ISSUE TITLE
Release Versioning

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#983]
Bosun and scollector need to have better versioning. Users should know when there are breaking changes, new features, or fixes.

Proposal: Both scollector and bosun will get a version string starting at "0.1.0". The middle number will be updated on breaking changes or major feature additions. The last number will be updated on bug fixes. The first number will be updated at our discretion. Bosun and scollector need not share the same number: they can be updated independently.

I don't think we should update the last number on each commit. So perhaps this isn't a great solution. One other is to just use two numbers: "0.1".

One other option is to just bump the second number each time we publish a release on the releases page. Thus, no bug fix versions, just "0.1", "0.2", etc, every once in a while.

In any case, we need to maintain the git commit string. The implementation should be changed, however, to use `go build -X` instead of the existing build script. It's much simpler.

However we do the version numbers, our releases page should reflect them, and we should list changes in the release notes instead of the current nothing.

Other questions: should we have a release schedule? Currently I publish a release every week or two. Are we happy with this?

**Comment by jayb904** [comment]
I'd suggest using SemVer: http://semver.org/ for versioning

**Comment by mjibson** [comment]
Done.
