### ISSUE TITLE
Overlay plot

### ISSUE THREAD

**Issue by pmonestie** [bosun-monitor/bosun#985]
Hi there,
I was wondering if there is a way to do an overlay plot with Bosun? Like a week on week plot of say request per seconds
Thanks in advance and keep up the good stuff with bosun :)

**Comment by elementai** [comment]
Hello.

I've did a little bit of research on that topic. There's actually a lot of feature requests for it not only for Bosun, but for Grafana etc. Best effort solution for now is to use Grafana dashboards with "Time Shift" feature https://i.imgur.com/dMq8clP.png so you'll have 2 dashboards (one for current period, one with shifted one). Per-metric time shift on one graph is not currently implemented. That shouldn't be very hard to code though. Grafana is probably better suited for such functionality.

**Comment by pmonestie** [comment]
Hi Dmitry,
I finally did try grafana with openTSDB - The problem though is as you said
grafana does not allow a different timeshift for every metrics, so as you
said it has to be done on 2 dashboard - Much less convenient - I would
think a lot of people would want that, I'll ask the grafana people.
On the flip side setting up an alert based on Week on Week computation with
Bosun was very easy :)
pierre

**Comment by kylebrandt** [comment]
Yes I built a Grafana dashboards like this and that isn't as useful as a
week over week style graph....

Working in bar / histogram charts currently, maybe this can be next for
visualization in bosun

**Comment by pmonestie** [comment]
I would vote for it :)
At my previous company (LinkedIn) all graph we used had WoW overlay: It's
such an easy way to detect something wrong in a system to compare with last
week or last 24h data. Bosun does the job as the alerting system supports
comparing WoW, though having it in graph would be awesome.
Anyway maybe I'll try to 'hack' grafana or Bosun to get this...
