### ISSUE TITLE
Feature: monitor services automatically

### ISSUE THREAD

**Issue by dimamedvedev** [bosun-monitor/bosun#987]
Current implementation can be improved as it's a bit difficult to debug regexes given that processes may have long argument list.

What I propose here is:
1. Detect init system (sysv, runit, upstart, systemd) and currently running services via specific init-commands (e.g. `sv status /etc/sv` for runit).
2. Find all processes belonging to service based on 
3. Assign an id to process based on process start time (i.e. service nginx will have id '1' assigned for master process and subsequent ids for workers).
4. Gather and store process start timestamp in addition to metrics in `process_linux` collector. That way user can understand whether process was restarted or not if scollector dies.

**Comment by elementai** [comment]
There can be rather large amount of code, I'm thinking about coding a library for it first, or even contribute to something like https://github.com/shirou/gopsutil .

**Comment by kylebrandt** [comment]
Regarding the first five items:
 Item 3: Isn't this what we already do?
 Item 4: Rather do the number of elapsed seconds since that is what we already do with the windows process collector. This is likely very easy

Items 1 and 2: How do you select which processes to monitor in this model? Why is this model better?

**Comment by elementai** [comment]
Item 3: I don't think so, there're no `os.Stat` calls in `process_linux` and no sorting based on any timestamps
Item 4: Agreed

Items 1 and 2: First and foremost, it's (hopefully) will be automatic, in `processes_windows` collector there's already a hardcoded regex https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/processes_windows.go#L27

Second, there's an option to monitor services (up/down/etc) too.

Although it all can be rather spammy, we can write a simple whitelist/blacklist filter in scollector.

**Comment by tdinucci** [comment]
Closing - see linked PR
