### ISSUE TITLE
Add a window function

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#995]
It is like band, except it takes an additional argument that is the name of a reduction function. Each series returned is run through the reduction function. The data is timestamped by the first data point in each interval.

**Comment by Dieterbe** [comment]
i think 'window' doesn't convey well the intent you describe. it sounds more like "band-and-map"

**Comment by mjibson** [comment]
You're totally correct, but, sadly, too late: http://bosun.org/expressions.html#windowquery-string-duration-string-period-string-num-scalar-funcname-string-seriesset
