### ISSUE TITLE
Bosun Filter ,Sort, and Limit functions need documentation

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#997]
These were added in https://github.com/bosun-monitor/bosun/pull/925

**Comment by gbrayut** [comment]
Example from SRE chat room:
```
template limit.sort.filter {
    subject = Test
    body = `
    {{.Graph .Alert.Vars.plot}}
    `
}

alert limit.sort.filter {
    template = limit.sort.filter
    $q = q("avg:rate:os.cpu{host=*}", "5m", "")
    $plot = filter($q, limit(sort(avg($q), "desc"), 5))
    crit = 0
}
```

**Comment by gbrayut** [comment]
Also, can I use these in a template or only in the alert expressions?

**Comment by kylebrandt** [comment]
Also `limit` needs to be documented. These are expression functions.

**Comment by gbrayut** [comment]
It would be nice if there were equivalent functions on the template side. Right now I had to do this to this:

```
$source = change("sum:rate{counter,,1}:exceptional.exceptions.count{source=*}", "5m", "")
...
{{$sources := (.EvalAll .Alert.Vars.source).DescByValue}}
{{$top_source := index $sources 0}}
```
to match what this expression would return:

`limit(sort(change("sum:rate{counter,,1}:exceptional.exceptions.count{source=*}", "5m", ""), "desc"), 1)`

**Comment by kylebrandt** [comment]
To match you can just `$top = limit(sort($source, "desc"), 1)` ... and then `{{ index (.EvalAll .Alert.Vars.top) 0 }}`. Not as nice but not that bad either. I have found in most instances I am using a different expression anyways because I want an expanded time window to give the alert context.
